Repository UK-Export-Finance/exip, pull requests merged in 2022-12, with the labels that each got.

#170 chore(EMS-585): bump govuk-frontend
  e2e-tests/cypress/e2e/journeys/insurance/header.spec.js
  e2e-tests/cypress/e2e/journeys/page-not-found.spec.js
  e2e-tests/cypress/e2e/journeys/quote/header.spec.js
  e2e-tests/cypress/e2e/partials/header.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/scripts/govuk-frontend.js
  src/ui/templates/partials/header.njk
Labels: tech, dependencies

#165 feat(docker-build): Orchestrated containers for DB, API and UI
  .env.sample
  .github/workflows/pr_tests.yml
  .gitignore
  database/exip.sql
  docker-compose.yml
  e2e-tests/constants/routes/insurance.js
  package-lock.json
  package.json
  src/api/.dockerignore
  src/api/.env.sample
  src/api/.gitignore
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/README.md
  src/api/custom-schema.ts
  src/api/init.sh
  src/api/keystone.test.ts
  src/api/keystone.ts
  src/api/package-lock.json
  src/ui/.dockerignore
  src/ui/.gitignore
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/cookies.js
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/main.js
  src/ui/server/api.ts
  src/ui/server/graphql/apollo.ts
  src/ui/server/helpers/task-list/README.md
  src/ui/styles/task-list.scss
  src/ui/templates/components/keystone/document/README.md
Labels: enhancement, feature, tech, dependencies

#173 chore: High vulnerability - `jpeg-js` updated from `0.4.3` to `0.4.4`
  package-lock.json
Labels: dependencies

#174 chore(deps): bump all deps
  package-lock.json
  package.json
Labels: tech, security, dependencies

#171 fix(EMS-618): Heading href link
  e2e-tests/constants/routes/quote.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/apply-offline-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/cannot-apply-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/check-if-eligible.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/eligible-to-apply-online.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/letter-of-credit/letter-of-credit.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/need-to-start-again.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/speak-to-ukef-efm.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/header.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/start.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-page.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/need-to-start-again.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  src/ui/server/constants/routes/quote.ts
  src/ui/server/controllers/insurance/eligibility/need-to-start-again/index.test.ts
  src/ui/server/controllers/insurance/eligibility/need-to-start-again/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/controllers/root/cookies/index.test.ts
  src/ui/server/controllers/root/cookies/index.ts
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/server/helpers/page-variables/core/insurance/index.test.ts
  src/ui/server/helpers/page-variables/core/insurance/index.ts
  src/ui/server/helpers/page-variables/core/quote/index.test.ts
  src/ui/server/helpers/page-variables/core/quote/index.ts
  src/ui/server/helpers/page-variables/single-input/index.test.ts
  src/ui/server/helpers/page-variables/single-input/index.ts
  src/ui/server/helpers/page-variables/single-input/insurance/index.test.ts
  src/ui/server/helpers/page-variables/single-input/insurance/index.ts
  src/ui/server/helpers/page-variables/single-input/quote/index.test.ts
  src/ui/server/helpers/page-variables/single-input/quote/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/required-data-provided/quote/index.test.ts
  src/ui/server/middleware/required-data-provided/quote/index.ts
  src/ui/templates/partials/header.njk
  src/ui/types/page-variables.d.ts
  src/ui/types/pages/tell-us-about-your-policy.d.ts
Labels: bug

#177 fix(EMS-623): Insurance need to start route
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/need-to-start-again.spec.js
  src/ui/server/controllers/insurance/eligibility/need-to-start-again/index.test.ts
  src/ui/server/controllers/insurance/eligibility/need-to-start-again/index.ts
Labels: bug

#178 chore: Dependency vulnerability removal
  .gitignore
  package-lock.json
Labels: dependencies

#180 chore(EMS-662): update README.md
  README.md
Labels: documentation

#176 feat(EMS-503): Policy and export - Type of policy 'save and go back' functionality
  e2e-tests/constants/routes/policy-and-export.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js
  src/ui/README.md
  src/ui/server/constants/routes/insurance/policy-and-export.ts
  src/ui/server/controllers/insurance/policy-and-export/save-data/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/save-data/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.ts
  src/ui/server/helpers/get-application/index.test.ts
  src/ui/server/helpers/get-application/index.ts
  src/ui/server/helpers/get-valid-fields/index.test.ts
  src/ui/server/helpers/get-valid-fields/index.ts
  src/ui/server/helpers/has-form-data/index.test.ts
  src/ui/server/helpers/has-form-data/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/policy-and-exports/type-of-policy.njk
Labels: feature

#187 chore(EMS-653): Add documentation to helper functions specific to main-application
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/get-application/index.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/server/helpers/page-variables/core/insurance/index.ts
  src/ui/server/helpers/page-variables/core/quote/index.ts
  src/ui/server/helpers/page-variables/single-input/index.ts
  src/ui/server/helpers/page-variables/single-input/insurance/index.ts
  src/ui/server/helpers/page-variables/single-input/quote/index.ts
  src/ui/server/helpers/update-submitted-data/insurance/index.ts
Labels: documentation, tech

#185 feat(EMS-501): Policy and export - Single contract policy page
  e2e-tests/constants/field-ids.js
  e2e-tests/constants/field-ids/index.js
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/constants/field-ids/shared-eligibility/index.js
  e2e-tests/constants/field-ids/shared/index.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/constants/routes/insurance/policy-and-export.js
  e2e-tests/constants/routes/policy-and-export.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/content-strings/fields/insurance/index.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/pages/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-house-search.spec.js
  e2e-tests/cypress/e2e/pages/insurance/index.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/index.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/singleContractPolicy.js
  src/ui/server/constants/field-ids.ts
  src/ui/server/constants/field-ids/index.ts
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/constants/field-ids/shared-eligibility/index.ts
  src/ui/server/constants/field-ids/shared/index.ts
  src/ui/server/constants/routes/insurance/policy-and-export.ts
  src/ui/server/constants/templates/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/pages/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-currencies.ts
  src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
Labels: feature, tech

#182 feat(EMS-637): Company details - trading name
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-submit.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-house-search.spec.js
  e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js
  package-lock.json
  src/api/package-lock.json
  src/ui/package-lock.json
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/pages/insurance/your-business/exporter-business/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/your-business/company-details.njk
Labels: feature

#190 feat(EMS-659): Insurance page not found, get-application middleware
  e2e-tests/constants/routes/exporter-business.js
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/content-strings/pages/insurance/exporter-business/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/page-not-found.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-submit.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-house-search.spec.js
  e2e-tests/cypress/e2e/journeys/page-not-found.spec.js
  e2e-tests/cypress/e2e/pages/pageNotFound.js
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/index.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/page-not-found/index.test.ts
  src/ui/server/controllers/insurance/page-not-found/index.ts
  src/ui/server/controllers/insurance/policy-and-export/save-data/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/save-data/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.ts
  src/ui/server/helpers/get-application/index.test.ts
  src/ui/server/helpers/get-application/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/insurance/get-application/index.test.ts
  src/ui/server/middleware/insurance/get-application/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/page-not-found.njk
  src/ui/templates/page-not-found.njk
  src/ui/types/express/index.d.ts
  src/ui/types/index.d.ts
Labels: enhancement, feature, tech

#189 feat(EM-718): Updated pipeline linting and tests
  .github/workflows/pr_tests.yml
  .gitignore
  package-lock.json
  package.json
  src/api/.eslintrc.js
  src/api/Dockerfile
  src/api/keystone.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/schema.ts
  src/api/types.ts
  src/ui/.eslintrc.js
  src/ui/Dockerfile
Labels: enhancement, feature, tech, dependencies

#191 feat(EMS-746): Company details page submit validation
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-submit.spec.js
  e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js
  src/ui/server/controllers/insurance/business/company-details/helpers/companies-house-search.helper.test.ts
  src/ui/server/controllers/insurance/business/company-details/helpers/companies-house-search.helper.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.ts
  src/ui/templates/insurance/your-business/company-details.njk
Labels: feature

#197 Update README.md
  README.md
Labels: documentation

#198 feat(EMS-621): No companies house number redirect
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-no-companies-house-link.spec.js
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/your-business/company-details.njk
Labels: feature

#196 feat(EMS-508): Single contract policy - add total value of contract field and improve form sanitisation functions
  database/exip.sql
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-total-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/singleContractPolicy.js
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/total-contract-value.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/total-contract-value.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/has-form-data/index.test.ts
  src/ui/server/helpers/has-form-data/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/strip-empty-form-fields/index.test.ts
  src/ui/server/helpers/strip-empty-form-fields/index.ts
  src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
  src/ui/types/application.ts
Labels: enhancement, tech

#203 feat(EMS-470): Development deployment
  .github/workflows/deploy.sh
  .github/workflows/development.yml
  .github/workflows/infrastructure.yml
  .github/workflows/production.yml
  .github/workflows/test.yml
  database/exip.sql
Labels: documentation, enhancement, feature, tech, dependencies

#208 fix(docker): MySQL configuration fix
  .github/workflows/test.yml
  database/exip.sql
  docker-compose.yml
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  src/ui/README.md
Labels: bug, dependencies

#199 fix(EMS-654): Generic combine validation rules function
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house-response/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house-response/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house-response/rules/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house/rules/companiesHouseNumber.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.ts
  src/ui/server/controllers/quote/policy-type/validation/index.test.ts
  src/ui/server/controllers/quote/policy-type/validation/index.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/currency.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/index.ts
  src/ui/server/helpers/combine-validation-rules/index.test.ts
  src/ui/server/helpers/combine-validation-rules/index.ts
  src/ui/server/helpers/validation/index.ts
Labels: tech

#201 feat(EMS-507): Single contract policy - add contract completion date
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-credit-period-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-total-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/singleContractPolicy.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/README.md
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
  src/ui/types/application.ts
Labels: enhancement, tech

#204 feat(EMS-504): About goods or services - initial page/form setup
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/pages/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/aboutGoodsOrServices.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/complete-and-submit-single-contract-policy-form.js
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/constants/routes/insurance/policy-and-export.ts
  src/ui/server/constants/templates/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/pages/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/policy-and-exports/about-goods-or-services.njk
Labels: feature, tech

#205 chore(EMS-696): Update all controllers to have the same template/export pattern
  src/ui/server/controllers/insurance/apply-offline/index.test.ts
  src/ui/server/controllers/insurance/apply-offline/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/insurance/eligibility/cannot-apply/index.test.ts
  src/ui/server/controllers/insurance/eligibility/cannot-apply/index.ts
  src/ui/server/controllers/insurance/eligibility/check-if-eligible/index.test.ts
  src/ui/server/controllers/insurance/eligibility/check-if-eligible/index.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-number/index.test.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-number/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
  src/ui/server/controllers/insurance/eligibility/exporter-location/index.test.ts
  src/ui/server/controllers/insurance/eligibility/exporter-location/index.ts
  src/ui/server/controllers/insurance/eligibility/insured-amount/index.test.ts
  src/ui/server/controllers/insurance/eligibility/insured-amount/index.ts
  src/ui/server/controllers/insurance/eligibility/insured-period/index.test.ts
  src/ui/server/controllers/insurance/eligibility/insured-period/index.ts
  src/ui/server/controllers/insurance/eligibility/letter-of-credit/index.test.ts
  src/ui/server/controllers/insurance/eligibility/letter-of-credit/index.ts
  src/ui/server/controllers/insurance/eligibility/other-parties/index.test.ts
  src/ui/server/controllers/insurance/eligibility/other-parties/index.ts
  src/ui/server/controllers/insurance/eligibility/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/eligibility/pre-credit-period/index.ts
  src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.ts
  src/ui/server/controllers/insurance/speak-to-ukef-efm/index.test.ts
  src/ui/server/controllers/insurance/speak-to-ukef-efm/index.ts
  src/ui/server/controllers/insurance/start/index.test.ts
  src/ui/server/controllers/insurance/start/index.ts
  src/ui/server/controllers/quote/buyer-body/index.test.ts
  src/ui/server/controllers/quote/buyer-body/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/controllers/quote/cannot-apply/index.test.ts
  src/ui/server/controllers/quote/cannot-apply/index.ts
  src/ui/server/controllers/quote/check-your-answers/index.test.ts
  src/ui/server/controllers/quote/check-your-answers/index.ts
  src/ui/server/controllers/quote/exporter-location/index.test.ts
  src/ui/server/controllers/quote/exporter-location/index.ts
  src/ui/server/controllers/quote/get-a-quote-by-email/index.test.ts
  src/ui/server/controllers/quote/get-a-quote-by-email/index.ts
  src/ui/server/controllers/quote/policy-type/index.test.ts
  src/ui/server/controllers/quote/policy-type/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/controllers/quote/uk-goods-or-services/index.test.ts
  src/ui/server/controllers/quote/uk-goods-or-services/index.ts
  src/ui/server/controllers/quote/your-quote/index.test.ts
  src/ui/server/controllers/quote/your-quote/index.ts
  src/ui/server/controllers/root/cookies/index.test.ts
  src/ui/server/controllers/root/cookies/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/routes/quote/index.test.ts
  src/ui/server/routes/quote/index.ts
Labels: tech
