Repository UK-Export-Finance/exip, pull requests merged in 2022-09, with the labels that each got.

#97 fix(EMS-248): update external guidance/application links. Fix accessibility issues
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages.js
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages.ts
  src/ui/templates/index.njk
  src/ui/templates/partials/phase-banner.njk
  src/ui/templates/quote/check-your-answers.njk
Labels: enhancement

#99 build(IaC): Exips production IaC
  .github/workflows/infrastructure.yml
  .github/workflows/production.yml
  .github/workflows/scan_codacy_analysis.yml
  .github/workflows/scan_codeql_analysis.yml
Labels: enhancement, tech

#100 fix/EMS-299 - Before you start link
  e2e-tests/content-strings/links.js
  src/ui/README.md
  src/ui/server/content-strings/links.ts
Labels: bug

#102 fix/EMS-300 - update before you start and full application links
  e2e-tests/content-strings/links.js
  src/ui/server/content-strings/links.ts
Labels: enhancement

#103 feat/EMS-301 - default multi policy length, remove change links
  e2e-tests/constants/field-values.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-policy-type-multiple-times-via-back-button.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/cypress/e2e/pages/quote/index.js
  e2e-tests/cypress/e2e/pages/quote/policyType.js
  e2e-tests/cypress/support/quote/forms.js
  src/ui/README.md
  src/ui/server/constants/field-values.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields.ts
  src/ui/server/controllers/quote/policy-type/index.test.ts
  src/ui/server/controllers/quote/policy-type/index.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-length.test.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-length.ts
  src/ui/server/helpers/data-content-mappings/map-policy-length.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.test.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.ts
  src/ui/server/helpers/update-submitted-data.test.ts
  src/ui/server/helpers/update-submitted-data.ts
  src/ui/server/middleware/required-data-provided.test.ts
  src/ui/server/middleware/required-data-provided.ts
  src/ui/templates/quote/policy-type.njk
  src/ui/types/summary-list.d.ts
Labels: enhancement

#107 feat/EMS-302: update pricing grid. Do not use policy length in multi policy calculation
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-high-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-standard-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-very-high-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/index.test.ts
  src/ui/server/generate-quote/index.test.ts
  src/ui/server/generate-quote/index.ts
  src/ui/server/generate-quote/pricing-grid.json
Labels: enhancement

#109 feat(EMS-314): nunjuck components to render keystone document data
  src/ui/templates/components/keystone/document/README.md
  src/ui/templates/components/keystone/document/blockquote.njk
  src/ui/templates/components/keystone/document/index.njk
  src/ui/templates/components/keystone/document/list-item.njk
  src/ui/templates/components/keystone/document/list.njk
  src/ui/templates/components/keystone/document/paragraph.njk
Labels: feature

#110 feat/EMS-316 - API setup
  package-lock.json
  package.json
  src/api/.env.sample
  src/api/.eslintignore
  src/api/.eslintrc.js
  src/api/.gitignore
  src/api/.prettierignore
  src/api/README.md
  src/api/auth.ts
  src/api/keystone.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/prettierrc.json
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/tsconfig.eslint.json
  src/api/tsconfig.json
Labels: feature, tech

#111 feat(EMS-330): UI apollo client, graphQL queries config
  src/ui/.env.sample
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/api.ts
  src/ui/server/graphql/apollo.ts
  src/ui/server/graphql/queries/page.ts
  src/ui/types/apollo/index.d.ts
  src/ui/types/index.d.ts
Labels: feature, tech

#114 fix(EMS-379): fix issue with buyer country form when JS is disabled
  e2e-tests/content-strings/footer.js
  e2e-tests/content-strings/links.js
  src/ui/server/content-strings/footer.ts
  src/ui/server/content-strings/links.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/templates/partials/footer.njk
Labels: bug

#116 feat(EMS-380): filter out invalid country names from CIS API
  src/ui/server/constants/api.ts
  src/ui/server/constants/invalid-CIS-countries.ts
  src/ui/server/helpers/mappings/map-countries.test.ts
  src/ui/server/helpers/mappings/map-countries.ts
Labels: enhancement
