Repository UK-Export-Finance/exip, pull requests merged in 2023-05, with the labels that each got.

#455 feat(EMS-1497): Account sign in - Enter code - additional input class
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code.spec.js
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/public/js/cookies.js
  src/ui/public/js/cookies.js.map
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/main.js
  src/ui/public/js/mojFrontend.js
  src/ui/templates/insurance/account/sign-in/enter-code.njk
Labels: enhancement

#453 fix(EMS-1515): Cookies - Change wording of message
  e2e-tests/content-strings/cookies-consent.js
  src/ui/server/content-strings/cookies-consent.ts
  src/ui/server/controllers/root/cookies/index.ts
  src/ui/server/middleware/cookies-consent/index.ts
  src/ui/templates/components/personal-details-input.njk
Labels: bug

#458 fix(EMS-1514-1339-1374-1516): Cookies - added Secure-optionalCookies to cookies check
  src/ui/server/constants/index.ts
  src/ui/server/controllers/root/cookies/index.ts
  src/ui/server/middleware/cookies-consent/index.test.ts
  src/ui/server/middleware/cookies-consent/index.ts
Labels: bug

#456 fix(EMS-1347): Account sign in - OTP form submission without completing eligibility
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code-without-completing-eligibility.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-enter-code-account-form.js
  e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-dashboard.js
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
Labels: bug

#461 fix(EMS-1186): Contact us page - Authenticated header
  src/ui/server/controllers/root/contact-us/index.test.ts
  src/ui/server/controllers/root/contact-us/index.ts
  src/ui/server/test-mocks/mock-buyer.ts
Labels: bug

#463 fix(EMS-1254): Application submission - fix incorrect flag used for sending emails
  src/api/.keystone/config.js
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/helpers/get-application-submitted-email-template-ids/index.test.ts
  src/api/helpers/get-application-submitted-email-template-ids/index.ts
  src/api/test-mocks/mock-buyer.ts
Labels: bug

#464 fix(EMS-1522-1555): Application submitted page authenticated header and start new application redirect
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/need-to-start-new-application/need-to-start-new-application-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/need-to-start-new-application/need-to-start-new-application-start-new-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/no-access-application-submitted.spec.js
  src/ui/server/controllers/insurance/check-your-answers/start-new-application/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/start-new-application/index.ts
  src/ui/server/controllers/insurance/no-access-application-submitted/index.test.ts
  src/ui/server/controllers/insurance/no-access-application-submitted/index.ts
Labels: bug

#459 feat(EMS-1348): Application status - disallow access to "check answers" pages if previous sections are incomplete
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/pages/insurance/complete-other-sections/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/cannot-skip-flow/check-your-answers/navigate-to-check-your-answers-pages-without-completing-previous-sections.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/complete-other-sections.spec.js
  e2e-tests/cypress/e2e/pages/insurance/complete-other-sections.js
  e2e-tests/cypress/e2e/pages/insurance/index.js
  e2e-tests/cypress/support/assert-url.js
  e2e-tests/cypress/support/commands.js
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/index.ts
  src/ui/server/content-strings/pages/insurance/complete-other-sections/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/complete-other-sections/index.test.ts
  src/ui/server/controllers/insurance/complete-other-sections/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/helpers/application-is-complete/index.ts
  src/ui/server/helpers/can-access-check-your-answers-routes/index.test.ts
  src/ui/server/helpers/can-access-check-your-answers-routes/index.ts
  src/ui/server/helpers/required-fields/index.test.ts
  src/ui/server/helpers/required-fields/index.ts
  src/ui/server/helpers/required-fields/section-review/index.test.ts
  src/ui/server/helpers/required-fields/section-review/index.ts
  src/ui/server/middleware/insurance/application-status/index.test.ts
  src/ui/server/middleware/insurance/application-status/index.ts
  src/ui/server/middleware/insurance/application-status/is-check-your-answers-route/index.test.ts
  src/ui/server/middleware/insurance/application-status/is-check-your-answers-route/index.ts
  src/ui/server/middleware/insurance/get-application/index.test.ts
  src/ui/server/middleware/insurance/get-application/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/complete-other-sections.njk
  src/ui/templates/insurance/feedback-confirmation.njk
Labels: feature, tech

#462 feat(EMS-1348): Application status - disallow access to "declarations" pages if previous sections are incomplete
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-incomplete-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/cannot-skip-flow/declarations/navigate-to-declarations-pages-without-completing-previous-sections.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/complete-prepare-application-tasks.spec.js
  src/ui/server/helpers/application-is-complete/index.ts
  src/ui/server/helpers/can-access-submit-your-application-routes/index.test.ts
  src/ui/server/helpers/can-access-submit-your-application-routes/index.ts
  src/ui/server/helpers/required-fields/check-your-answers/index.test.ts
  src/ui/server/helpers/required-fields/check-your-answers/index.ts
  src/ui/server/helpers/required-fields/index.test.ts
  src/ui/server/helpers/required-fields/index.ts
  src/ui/server/helpers/required-fields/prepare-application/index.test.ts
  src/ui/server/helpers/required-fields/prepare-application/index.ts
  src/ui/server/middleware/insurance/application-status/index.ts
  src/ui/server/middleware/insurance/application-status/is-submit-your-application-route/index.test.ts
  src/ui/server/middleware/insurance/application-status/is-submit-your-application-route/index.ts
Labels: enhancement, feature, tech

#460 feat(APIM): mdm apim migration
  .env.sample
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  docker-compose.yml
  package-lock.json
  package.json
  src/api/.env.sample
  src/api/constants/index.ts
  src/api/integrations/industry-sector/index.ts
  src/api/package-lock.json
  src/api/package.json
  src/ui/.env.sample
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/cookies.js
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/main.js
  src/ui/public/js/main.js.map
  src/ui/public/js/mojFrontend.js
  src/ui/server/api/external/index.ts
  src/ui/server/constants/api.ts
  src/ui/server/helpers/mappings/map-cis-countries.test.ts
  src/ui/server/helpers/mappings/map-cis-countries.ts
  src/ui/server/test-mocks/mock-cis-countries.ts
  src/ui/types/cis-country.d.ts
Labels: feature

#467 fix(CVE-2023-30533): updated node-xlsx to 0.4.0
  generate-exip-pricing-grid/package-lock.json
  generate-exip-pricing-grid/package.json
Labels: security, fix

#465 fix(CVE-2023-2142): dependencies bumps
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/webpack.common.config.js
Labels: tech, security, dependencies

#474 fix(EMS-1588): Feedback referralUrl
  database/exip.sql
  src/api/schema.ts
Labels: bug

#475 feat(EMS-1087): Account sign in - Reset verification expiry if account is unverified
  e2e-tests/cypress/e2e/journeys/insurance/account/manage/account-manage.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-and-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code-without-completing-eligibility.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/request-new-code/account-sign-in-request-new-code.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/validation/account-sign-in-validation-unverified-account.spec.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-sign-in-account-form.js
  e2e-tests/cypress/support/insurance/account/complete-insurance-eligibility-sign-in-and-go-to-dashboard.js
  e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-dashboard.js
  e2e-tests/cypress/support/insurance/account/sign-in-and-go-to-url.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-sign-in.test.ts
  src/api/custom-resolvers/mutations/account-sign-in.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address.test.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address.ts
  src/api/custom-schema/type-defs.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/helpers/send-email-confirm-email-address/index.test.ts
  src/api/helpers/send-email-confirm-email-address/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/index.ts
  src/api/types.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/graphql/mutations/account/sign-in.ts
Labels: enhancement, feature, tech

#477 fix(EMS-1577-1590): Feedback - Refactor and additional email variables
  database/exip.sql
  src/api/.keystone/config.js
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/create-feedback.test.ts
  src/api/custom-resolvers/mutations/create-feedback.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/api/keystone/feedback/index.ts
  src/ui/server/api/keystone/index.ts
  src/ui/server/api/keystone/send-feedback-emails/index.ts
  src/ui/server/constants/field-ids/index.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/index.test.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/index.ts
  src/ui/server/graphql/mutations/create-insurance-feedback.ts
  src/ui/server/graphql/mutations/send-insurance-feedback-email.ts
  src/ui/server/test-mocks/mock-feedback.ts
  src/ui/types/feedback.d.ts
Labels: bug, enhancement

#476 feat(infrastructure): IaC
  .github/workflows/README.md
  .github/workflows/deploy.sh
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/.env.sample
  src/api/Dockerfile
  src/api/package-lock.json
  src/api/package.json
  src/ui/.env.sample
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/package.json
Labels: enhancement, tech

#479 feat(EMS-1579-1580: Check your answers - Improve policy and exports flow
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/checkYourAnswers.js
  e2e-tests/cypress/support/insurance/check-policy-and-exports-summary-list.js
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
Labels: enhancement, tech

#481 fix(EMS-1615): Account verification - resend "confirm email address" email
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email-go-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/validation/account-sign-in-validation-unverified-account.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/confirmEmail.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-sign-in.test.ts
  src/api/custom-resolvers/mutations/account-sign-in.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/types.ts
  src/ui/server/api/keystone/account/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/create/confirm-email-resent/index.test.ts
  src/ui/server/controllers/insurance/account/create/confirm-email-resent/index.ts
  src/ui/server/controllers/insurance/account/create/resend-confirm-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/resend-confirm-email/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/graphql/mutations/account/sign-in.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/types/express/index.d.ts
Labels: bug, tech

#482 feat(EMS-1513): Your business - Contact - Save
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/contact/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/contact/your-contact-page.spec.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/insurance/complete-and-submit-your-contact-form.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code.ts
  src/api/custom-schema/type-defs.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/api/keystone/feedback/index.ts
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/business/contact/index.test.ts
  src/ui/server/controllers/insurance/business/contact/index.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/graphql/mutations/account/verify-sign-in-code.ts
  src/ui/server/graphql/mutations/create-insurance-feedback.ts
  src/ui/server/graphql/mutations/update-application/business-contact.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/get-values-from-user-session-or-application/index.test.ts
  src/ui/server/helpers/get-values-from-user-session-or-application/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-business-contact.ts
  src/ui/templates/components/personal-details-input.njk
  src/ui/templates/insurance/your-business/contact.njk
  src/ui/types/application.ts
  src/ui/types/express/index.d.ts
Labels: feature

#483 feat(EMS-628): Eligibility - Save all buyer country answers in the session
  e2e-tests/cypress/e2e/journeys/insurance/apply-offline-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country-country-only-apply-offline.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/cannot-apply-page.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country-country-only-get-a-quote-by-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/cypress/e2e/pages/quote/buyerCountry.js
  e2e-tests/cypress/e2e/pages/shared/buyerCountry.js
  e2e-tests/cypress/fixtures/countries.js
  e2e-tests/cypress/support/check-buyer-country-form.js
  e2e-tests/cypress/support/forms.js
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/controllers/insurance/account/create/confirm-email-resent/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/helpers/mappings/map-submitted-eligibility-country/index.test.ts
  src/ui/server/helpers/mappings/map-submitted-eligibility-country/index.ts
  src/ui/server/middleware/required-data-provided/helpers/index.test.ts
  src/ui/server/middleware/required-data-provided/helpers/index.ts
  src/ui/server/test-mocks/mock-session.ts
Labels: enhancement, feature, tech

#485 feat(EMS-1534-1532): Application Submitted - links
  e2e-tests/content-strings/links.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/application-submitted.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-contact.spec.js
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/insurance/application-submitted/index.ts
  src/ui/server/helpers/get-field-by-id/index.ts
Labels: feature

#486 feat(EMS-1209-1550-1549): Companies house eligibility text change and create account details privacy notice
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/yourDetails.js
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/feedback.njk
Labels: feature

#487 fix(EMS-1568-1632-1633): Feedback - Max characters, no satisfaction and email variables
  database/exip.sql
  e2e-tests/cypress/e2e/journeys/insurance/feedback/submit-feedback.spec.js
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/helpers/map-feedback-satisfaction/index.test.ts
  src/api/helpers/map-feedback-satisfaction/index.ts
  src/api/schema.prisma
  src/api/schema.ts
Labels: bug

#488 feat(EMS-1638): Account - Password reset - block account after a certain amount of requests in a period of time
  database/exip.sql
  e2e-tests/constants/account.js
  e2e-tests/constants/index.js
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-and-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-retry/account-password-reset-retry-maximum-retries.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/link-sent/account-password-reset-link-sent.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/account-password-reset-new-password.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/validation/account-password-reset-new-password-valdation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/success/account-password-reset-success.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/account-suspended.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/suspended/index.js
  e2e-tests/cypress/support/api/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-password-reset-form-maximum-retries.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-password-reset-form.js
  e2e-tests/cypress/support/insurance/account/delete-account.js
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/delete-an-account.test.ts
  src/api/custom-resolvers/mutations/delete-an-account.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/create-authentication-retry-entry/index.test.ts
  src/api/helpers/create-authentication-retry-entry/index.ts
  src/api/helpers/should-block-account/index.test.ts
  src/api/helpers/should-block-account/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/password-reset/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/index.ts
  src/ui/server/controllers/insurance/account/suspended/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/index.ts
  src/ui/server/graphql/mutations/account/send-email-password-reset-link.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/suspended.njk
Labels: enhancement, feature, tech, security

#490 fix(EMS-1628): Your business - Contact - Incorrect error message
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/contact/validation/your-contact-validation.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/email-address.test.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/email-address.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/first-name.test.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/first-name.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/last-name.test.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/last-name.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/position.test.ts
  src/ui/server/controllers/insurance/business/contact/validation/rules/position.ts
Labels: bug

#491 feat(EMS-1537): Account - Password reset - reject passwords that have been used before
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-and-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/account-password-reset-new-password.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/validation/account-password-reset-new-password-valdation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/success/account-password-reset-success.spec.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-new-password-account-form.js
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/custom-resolvers/mutations/account-password-reset.test.ts
  src/api/custom-resolvers/mutations/account-password-reset.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.ts
  src/api/custom-resolvers/queries/get-account-password-reset-token.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/account-has-used-password-before/index.test.ts
  src/api/helpers/account-has-used-password-before/index.ts
  src/api/helpers/create-authentication-entry/index.test.ts
  src/api/helpers/create-authentication-entry/index.ts
  src/api/helpers/get-password-hash/index.test.ts
  src/api/helpers/get-password-hash/index.ts
  src/api/helpers/is-valid-account-password/index.ts
  src/api/helpers/should-block-account/index.test.ts
  src/api/helpers/should-block-account/index.ts
  src/api/schema.graphql
  src/api/types.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/validation/cannot-use-new-password/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/validation/cannot-use-new-password/index.ts
  src/ui/server/graphql/mutations/account/password-reset.ts
Labels: enhancement, feature, tech, security

#496 feat(timezone): added TZ support
  .env.sample
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  docker-compose.yml
  e2e-tests/.env.sample
  src/api/.env.sample
  src/ui/.env.sample
Labels: tech

#489 fix(EMS-1648): Privacy policy - Incorrect link
  e2e-tests/content-strings/footer.js
  e2e-tests/content-strings/links.js
  e2e-tests/cypress/e2e/journeys/footer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/account-password-reset-new-password.spec.js
  src/ui/server/content-strings/footer.ts
  src/ui/server/content-strings/links.ts
Labels: fix

#494 feat(EMS-1531-1628): Application submitted - Send email to contact & Your business - Contact error message
  e2e-tests/content-strings/error-messages.js
  src/api/.keystone/config.js
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/emails/send-application-submitted-emails/index.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/is-owner-same-as-business-contact/index.test.ts
  src/api/helpers/is-owner-same-as-business-contact/index.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-mocks/mock-application.ts
  src/api/types.ts
  src/ui/server/content-strings/error-messages.ts
Labels: feature

#499 feat(EMS-1662): Account password reset - reset auth retries
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-password-reset.test.ts
  src/api/custom-resolvers/mutations/account-password-reset.ts
  src/api/custom-resolvers/mutations/account-sign-in.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code.ts
  src/api/helpers/get-authentication-retries-by-account-id/index.test.ts
  src/api/helpers/get-authentication-retries-by-account-id/index.ts
Labels: enhancement, tech

#500 chore/fix(EMS-1523-1544): Split up API email functions, fix time/hour issue in XLSX generation
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/submit-application.ts
  src/api/emails/application/index.test.ts
  src/api/emails/application/index.ts
  src/api/emails/call-notify/index.test.ts
  src/api/emails/call-notify/index.ts
  src/api/emails/confirm-email-address/index.test.ts
  src/api/emails/confirm-email-address/index.ts
  src/api/emails/documents/index.test.ts
  src/api/emails/documents/index.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/emails/insurance-feedback-email/index.test.ts
  src/api/emails/insurance-feedback-email/index.ts
  src/api/emails/password-reset-link/index.test.ts
  src/api/emails/password-reset-link/index.ts
  src/api/emails/security-code-email/index.test.ts
  src/api/emails/security-code-email/index.ts
  src/api/generate-xlsx/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/format-time-of-day/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/format-time-of-day/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
Labels: bug, tech, chore

#497 feat(eslint): de-structure rule
  e2e-tests/.eslintrc.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-single-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/cypress/fixtures/countries.js
  e2e-tests/cypress/support/get-reference-number.js
  generate-exip-pricing-grid/.eslintrc.js
  src/api/.eslintrc.js
  src/api/custom-resolvers/mutations/delete-application-by-refrence-number.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.test.ts
  src/api/helpers/get-country-by-field/index.test.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/ui/.eslintrc.js
  src/ui/server/controllers/insurance/declarations/confidentiality/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/generate-quote/index.test.ts
  src/ui/server/generate-quote/index.ts
  src/ui/server/helpers/get-country-by-iso-code/index.test.ts
  src/ui/server/helpers/get-country-by-name/index.test.ts
  src/ui/server/helpers/mappings/map-percentage-of-cover.test.ts
  src/ui/server/helpers/mappings/map-select-option.test.ts
  src/ui/server/helpers/mappings/map-submitted-eligibility-country/index.test.ts
  src/ui/server/helpers/mappings/map-total-months-of-insurance/index.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.test.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/submit-application.test.ts
  src/ui/server/helpers/task-list/index.test.ts
  src/ui/server/helpers/task-list/task-helpers.test.ts
Labels: feature, tech

#501 fix(EMS-1552-1594-1593): Application submission - various XLSX fixes
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/content-strings/XLSX.ts
  src/api/generate-xlsx/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-key-information/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-key-information/index.ts
  src/api/generate-xlsx/styled-columns/index.test.ts
  src/api/generate-xlsx/styled-columns/index.ts
Labels: bug, enhancement

#502 feat(EMS-1639): Account sign in - reject if already blocked
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/sign-in-already-blocked/account-sign-in-already-blocked.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-sign-in.test.ts
  src/api/custom-resolvers/mutations/account-sign-in.ts
Labels: enhancement

#503 fix(EMS-1623): Wipe insurance eligibility session data when creating a new application
  e2e-tests/cypress/e2e/journeys/insurance/complete-eligibility-ansewrs-for-a-second-time.spec.js
  e2e-tests/cypress/support/assert-unchecked-yes-no-radios.js
  e2e-tests/cypress/support/commands.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
Labels: bug, enhancement, dependencies

#505 chore(EMS-1616): Application versioning
  README.md
  database/exip.sql
  e2e-tests/constants/eligibility.js
  e2e-tests/constants/index.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  src/api/.keystone/config.js
  src/api/constants/application/get-application-definition/index.test.ts
  src/api/constants/application/get-application-definition/index.ts
  src/api/constants/application/index.ts
  src/api/constants/application/versions/index.ts
  src/api/constants/application/versions/latest.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/mock-application.ts
  src/api/types.ts
  src/ui/server/constants/application.ts
  src/ui/server/constants/application/index.ts
  src/ui/server/constants/application/versions/index.ts
  src/ui/server/constants/application/versions/latest.ts
  src/ui/server/constants/eligibility.ts
  src/ui/server/constants/index.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
Labels: tech

#508 feat(EMS-1687): Quote - Update 'full application' link, refactor some page content
  e2e-tests/content-strings/pages/quote.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/link-sent/account-password-reset-link-sent.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/cypress/e2e/pages/quote/yourQuote.js
  src/ui/server/content-strings/pages/quote.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/templates/quote/your-quote.njk
Labels: enhancement, tech

#507 feat(EMS-1686): Application submission - XLSX style updates
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/generate-xlsx/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row-seperator/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row-seperator/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.ts
  src/api/generate-xlsx/styled-columns/index.test.ts
  src/api/generate-xlsx/styled-columns/index.ts
Labels: enhancement

#509 fix(EMS-1546): Application submission - XLSX generation - special characters
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.ts
  src/api/helpers/replace-character-codes-with-characters/index.test.ts
  src/api/helpers/replace-character-codes-with-characters/index.ts
Labels: bug

#510 chore(tech): Fix typo, E2E test coverage improvement
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email-go-back.spec.js
  e2e-tests/cypress/support/insurance/account/assert-confirm-email-page-content.js
  src/ui/server/controllers/insurance/business/nature-of-business/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-business-nature-of-business.ts
Labels: tech
