Repository UK-Export-Finance/exip, pull requests merged in 2023-08, with the labels that each got.

#693 chore(EMS-1803): Policy and exports - construct payload
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.POST-save-and-back.test.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.ts
  src/ui/server/helpers/required-fields/policy-and-exports/index.test.ts
  src/ui/server/helpers/required-fields/policy-and-exports/index.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/server/shared-validation/requested-start-date/index.ts
Labels: tech, security, chore

#697 chore(EMS-1810-1812): Eligibility and feedback - construct payload
  e2e-tests/constants/field-ids/feedback/index.js
  e2e-tests/constants/field-ids/index.js
  src/ui/server/constants/field-ids/feedback/index.ts
  src/ui/server/constants/field-ids/index.ts
  src/ui/server/controllers/insurance/eligibility/account-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/account-to-apply-online/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-number/index.test.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-number/index.ts
  src/ui/server/controllers/insurance/eligibility/exporter-location/index.test.ts
  src/ui/server/controllers/insurance/eligibility/exporter-location/index.ts
  src/ui/server/controllers/insurance/eligibility/insured-amount/index.test.ts
  src/ui/server/controllers/insurance/eligibility/insured-amount/index.ts
  src/ui/server/controllers/insurance/eligibility/insured-period/index.test.ts
  src/ui/server/controllers/insurance/eligibility/insured-period/index.ts
  src/ui/server/controllers/insurance/eligibility/letter-of-credit/index.test.ts
  src/ui/server/controllers/insurance/eligibility/letter-of-credit/index.ts
  src/ui/server/controllers/insurance/eligibility/other-parties/index.test.ts
  src/ui/server/controllers/insurance/eligibility/other-parties/index.ts
  src/ui/server/controllers/insurance/eligibility/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/eligibility/pre-credit-period/index.ts
  src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/index.test.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/index.ts
  src/ui/server/controllers/quote/buyer-body/index.test.ts
  src/ui/server/controllers/quote/buyer-body/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/controllers/quote/exporter-location/index.test.ts
  src/ui/server/controllers/quote/exporter-location/index.ts
  src/ui/server/controllers/quote/policy-type/index.test.ts
  src/ui/server/controllers/quote/policy-type/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/controllers/quote/uk-goods-or-services/index.test.ts
  src/ui/server/controllers/quote/uk-goods-or-services/index.ts
Labels: tech, security, chore

#724 chore(EMS-1785): Check for existing account in keystone account creation resolver
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-password-reset/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in-new-code/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.test.ts
  src/api/custom-resolvers/mutations/add-and-get-OTP/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/custom-resolvers/mutations/delete-an-account/index.test.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.test.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.test.ts
  src/api/custom-resolvers/queries/get-account-password-reset-token/index.test.ts
  src/api/custom-resolvers/queries/verify-account-password-reset-token/index.test.ts
  src/api/helpers/account-has-used-password-before/index.test.ts
  src/api/helpers/block-account/index.test.ts
  src/api/helpers/create-authentication-entry/index.test.ts
  src/api/helpers/create-authentication-retry-entry/index.test.ts
  src/api/helpers/delete-authentication-retries/index.test.ts
  src/api/helpers/generate-otp-and-update-account/index.test.ts
  src/api/helpers/get-account-by-field/index.test.ts
  src/api/helpers/get-account-by-id/index.test.ts
  src/api/helpers/get-authentication-retries-by-account-id/index.test.ts
  src/api/helpers/send-email-confirm-email-address/index.test.ts
  src/api/helpers/should-block-account/index.test.ts
  src/api/keystone.test.ts
  src/api/keystone.ts
  src/api/schema.ts
  src/api/test-helpers/accounts.ts
  src/api/test-helpers/create-full-application.ts
  src/api/types.ts
Labels: tech, security, chore

#725 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/helpers/block-account/index.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: security, dependencies

#726 chore(EMS-1809): Your buyer - construct payload
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.ts
Labels: chore

#581 security(EMS-1757): Sanitise referer header
  e2e-tests/package-lock.json
  src/ui/server/middleware/headers/security/get-url-origin/index.test.ts
  src/ui/server/middleware/headers/security/get-url-origin/index.ts
  src/ui/server/middleware/headers/security/index.test.ts
  src/ui/server/middleware/headers/security/index.ts
  src/ui/server/middleware/headers/security/is-request-header-origin-valid/index.test.ts
  src/ui/server/middleware/headers/security/is-request-header-origin-valid/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/types/express/index.d.ts
Labels: tech, security

#706 chore(EMS-1811): Declarations - construct payload
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.ts
  src/ui/server/controllers/insurance/declarations/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/declarations/save-and-back/index.ts
  src/ui/server/controllers/insurance/declarations/save-data/index.test.ts
  src/ui/server/controllers/insurance/declarations/save-data/index.ts
Labels: security, chore

#707 chore(EMS-1804): Account - construct payload, sanitise req query
  src/ui/server/controllers/insurance/account/create/confirm-email-resent/index.test.ts
  src/ui/server/controllers/insurance/account/create/confirm-email-resent/index.ts
  src/ui/server/controllers/insurance/account/create/confirm-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/confirm-email/index.ts
  src/ui/server/controllers/insurance/account/create/resend-confirm-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/resend-confirm-email/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email-link-expired/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email-link-expired/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/password-reset/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/index.ts
  src/ui/server/controllers/insurance/account/password-reset/link-expired/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/link-expired/index.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/controllers/insurance/account/suspended/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/index.ts
  src/ui/server/controllers/insurance/account/suspended/link-expired/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/link-expired/index.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/types/index.d.ts
  src/ui/types/sanitise-value.ts
Labels: security, chore

#718 chore(EMS-1805): Your business - construct payload improvements
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/contact/index.test.ts
  src/ui/server/controllers/insurance/business/contact/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
Labels: tech, security, chore

#738 fix(EMS-1846): Duplicate h1 headings, radio/checkbox legend issues
  e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/declarations/anti-bribery.njk
  src/ui/templates/insurance/declarations/anti-bribery/code-of-conduct.njk
  src/ui/templates/insurance/declarations/anti-bribery/exporting-with-code-of-conduct.njk
  src/ui/templates/insurance/declarations/confidentiality.njk
  src/ui/templates/insurance/eligibility/account-to-apply-online.njk
  src/ui/templates/insurance/eligibility/companies-house-number.njk
  src/ui/templates/insurance/eligibility/insured-amount.njk
  src/ui/templates/insurance/eligibility/insured-period.njk
  src/ui/templates/insurance/eligibility/letter-of-credit.njk
  src/ui/templates/insurance/eligibility/other-parties.njk
  src/ui/templates/insurance/eligibility/pre-credit-period.njk
  src/ui/templates/insurance/eligibility/uk-goods-or-services.njk
  src/ui/templates/insurance/policy-and-exports/type-of-policy.njk
  src/ui/templates/insurance/your-business/broker.njk
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/insurance/your-buyer/working-with-buyer.njk
  src/ui/templates/quote/buyer-body.njk
  src/ui/templates/quote/uk-goods-or-services.njk
  src/ui/templates/shared-pages/declaration.njk
  src/ui/templates/shared-pages/exporter-location.njk
Labels: bug, tech, chore

#740 feat(EMS-1796-1797): Insurance Eligibility - Insured amount
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  package-lock.json
  src/api/.keystone/config.js
  src/api/package-lock.json
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
Labels: feature

#719 chore(EMS-1863): Insurance - Check your answers - construct payload
  src/ui/server/controllers/insurance/check-your-answers/eligibility/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/eligibility/index.ts
  src/ui/server/controllers/insurance/check-your-answers/policy-and-exports/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/check-your-answers/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/save-and-back/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.ts
Labels: tech, security, chore

#703 chore(EMS-1788-1859): Disable apollo/graphQL introspection, playground, keystone admin UI/CMS and telemetry
  src/api/.keystone/config.js
  src/api/auth.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/custom-resolvers/mutations/delete-an-account/index.ts
  src/api/custom-resolvers/mutations/delete-application-by-refrence-number/index.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.ts
  src/api/custom-schema/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/keystone.ts
Labels: documentation, tech, security, chore

#741 feat(EMS-1817-1819): Policy and exports - Change from 499,999 to 500,000
  .prettierignore
  e2e-tests/constants/application.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-multiple-policy-type-maximum-cover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-single-policy-type-maximum-cover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-populated-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers-summary-list/summary-list-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers-summary-list/summary-list-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/complete-policy-and-exports-as-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/complete-policy-and-exports-as-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-maximum-buyer-will-owe.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-sales-to-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-total-contract-value.spec.js
  e2e-tests/cypress/support/insurance/complete-and-submit-multiple-contract-policy-form.js
  e2e-tests/cypress/support/insurance/complete-and-submit-single-contract-policy-form.js
  e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-multiple.js
  e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-single.js
  e2e-tests/cypress/support/insurance/complete-sign-in-and-submit-an-application.js
  src/api/.keystone/config.js
  src/api/constants/application/versions/index.ts
  src/ui/server/constants/application/index.ts
  src/ui/server/constants/application/versions/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/total-contract-value.test.ts
Labels: feature

#751 chore(deps): dependencies updates
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  e2e-tests/package-lock.json
  package-lock.json
  package.json
  src/api/.dockerignore
  src/api/package-lock.json
  src/api/package.json
  src/ui/.dockerignore
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/cookies.js
  src/ui/public/js/formSubmission.js
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/main.js
  src/ui/public/js/mojFrontend.js
  src/ui/server/helpers/task-list/index.ts
Labels: security

#753 chore(EMS-1864): Update various UI controllers to use and test payload construction
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/turnover/save-and-back/index.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/save-and-back/index.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.ts
  src/ui/server/controllers/root/cookies/index.test.ts
  src/ui/server/controllers/root/cookies/index.ts
Labels: tech, chore

#750 chore(EMS-1893): Reject any GraphQL calls/resolvers that are not in an allowed list
  e2e-tests/cypress/support/api/index.js
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/apollo-plugins/index.test.ts
  src/api/apollo-plugins/index.ts
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/constants/index.ts
  src/api/keystone.ts
  src/ui/server/graphql/mutations/account/create.ts
  src/ui/server/graphql/mutations/account/password-reset.ts
  src/ui/server/graphql/mutations/account/reactivate-account-link.ts
  src/ui/server/graphql/mutations/account/send-email-confirm-email-address.ts
  src/ui/server/graphql/mutations/account/send-email-password-reset-link.ts
  src/ui/server/graphql/mutations/account/sign-in-send-new-code.ts
  src/ui/server/graphql/mutations/account/sign-in.ts
  src/ui/server/graphql/mutations/account/verify-account-reactivation-token.ts
  src/ui/server/graphql/mutations/account/verify-email-address.ts
  src/ui/server/graphql/mutations/account/verify-session.ts
  src/ui/server/graphql/mutations/account/verify-sign-in-code.ts
  src/ui/server/graphql/mutations/create-insurance-feedback.ts
  src/ui/server/graphql/queries/account/get.ts
  src/ui/server/graphql/queries/account/verify-account-password-reset-token.ts
Labels: tech, security, chore

#755 chore(EMS-1770): Align all 'expired' and 'invalid' link routes, namings, variables
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-verification-expired-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-verification-invalid-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-invalid-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/expired-link/account-password-reset-expired-link-send-new-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/expired-link/account-password-reset-expired-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/account-suspended-reactivate-after-expired-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/expired-link/account-suspended-expired-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/link-invalid/account-suspended-invalid-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/verify-email/account-suspended-verify-email-invalid-token.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/invalid-link/index.js
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email-expired-link/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email-expired-link/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.ts
  src/ui/server/controllers/insurance/account/invalid-link/index.test.ts
  src/ui/server/controllers/insurance/account/invalid-link/index.ts
  src/ui/server/controllers/insurance/account/password-reset/expired-link/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/expired-link/index.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.ts
  src/ui/server/controllers/insurance/account/suspended/expired-link/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/expired-link/index.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/templates/insurance/account/create/verify-email-expired-link.njk
  src/ui/templates/insurance/account/password-reset/expired-link.njk
  src/ui/templates/insurance/account/suspended/expired-link.njk
Labels: enhancement, tech, chore

#752 chore(EMS-1891): Merge main into main-application
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  generate-exip-pricing-grid/README.md
  generate-exip-pricing-grid/index.js
  src/ui/server/generate-quote/pricing-grid.json
Labels: tech, chore

#757 fix(EMS-1890): add temporary logs to debug in dev environment
  src/ui/server/middleware/headers/security/index.ts
Labels: security, chore

#768 fix(EMS-1890-1896): Fix issue where req.headers.referer is undefined in dev environment
  src/ui/server/middleware/headers/security/get-url-origin/index.test.ts
  src/ui/server/middleware/headers/security/get-url-origin/index.ts
  src/ui/server/middleware/headers/security/index.test.ts
  src/ui/server/middleware/headers/security/index.ts
  src/ui/server/middleware/headers/security/is-request-header-origin-valid/index.test.ts
  src/ui/server/test-mocks/index.ts
Labels: bug, chore

#769 chore(EMS-1893): Add a condition to allowed GraphQL resolvers
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
Labels: tech, chore

#785 chore(EMS-1300): "There is a problem" content string
  e2e-tests/content-strings/error-messages.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/templates/cookies.njk
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/password-reset/new-password.njk
  src/ui/templates/insurance/account/password-reset/password-reset.njk
  src/ui/templates/insurance/account/sign-in/enter-code.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
  src/ui/templates/insurance/declarations/anti-bribery.njk
  src/ui/templates/insurance/declarations/anti-bribery/code-of-conduct.njk
  src/ui/templates/insurance/declarations/anti-bribery/exporting-with-code-of-conduct.njk
  src/ui/templates/insurance/declarations/confidentiality.njk
  src/ui/templates/insurance/eligibility/account-to-apply-online.njk
  src/ui/templates/insurance/eligibility/companies-house-number.njk
  src/ui/templates/insurance/eligibility/insured-amount.njk
  src/ui/templates/insurance/eligibility/insured-period.njk
  src/ui/templates/insurance/eligibility/letter-of-credit.njk
  src/ui/templates/insurance/eligibility/other-parties.njk
  src/ui/templates/insurance/eligibility/pre-credit-period.njk
  src/ui/templates/insurance/eligibility/uk-goods-or-services.njk
  src/ui/templates/insurance/feedback.njk
  src/ui/templates/insurance/policy-and-exports/about-goods-or-services.njk
  src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk
  src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
  src/ui/templates/insurance/policy-and-exports/type-of-policy.njk
  src/ui/templates/insurance/your-business/broker.njk
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/templates/insurance/your-business/contact.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/insurance/your-buyer/working-with-buyer.njk
  src/ui/templates/quote/buyer-body.njk
  src/ui/templates/quote/policy-type.njk
  src/ui/templates/quote/tell-us-about-your-policy.njk
  src/ui/templates/quote/uk-goods-or-services.njk
  src/ui/templates/shared-pages/buyer-country.njk
  src/ui/templates/shared-pages/declaration.njk
  src/ui/templates/shared-pages/exporter-location.njk
  src/ui/types/page-variables.d.ts
Labels: tech, chore

#767 fix(EMS-1848): Change fieldset HEADING to LEGEND
  e2e-tests/constants/field-ids/insurance/business/index.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/contact/your-contact-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/broker/broker.js
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/templates/insurance/your-business/broker.njk
  src/ui/templates/insurance/your-business/contact.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
Labels: bug, feature

#798 chore(EMS-977-1317): Improve UI controller conditions, simplify some unit tests
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/save-and-back/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/helpers/get-valid-fields/index.ts
Labels: tech, chore

#799 fix(EMS-1898): Cookies banner typos, invalid/misleading E2E tests
  e2e-tests/content-strings/cookies-consent.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/cannot-apply-page.spec.js
  e2e-tests/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  src/ui/server/content-strings/cookies-consent.ts
Labels: bug, tech, chore

#800 chore(EMS-1298): Improve E2E summary list selectors
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-single-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-contact.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-contact.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-fields-multi-policy-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/eligibility.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/index.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/need-to-start-new-application.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/policy-and-exports.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/your-business.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/your-buyer.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/checkYourAnswers.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/index.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/checkYourAnswers.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/index.js
  e2e-tests/cypress/e2e/pages/quote/checkYourAnswers.js
  e2e-tests/cypress/e2e/pages/quote/yourQuote.js
  e2e-tests/cypress/e2e/pages/shared/index.js
  e2e-tests/cypress/e2e/pages/shared/summaryList.js
  e2e-tests/cypress/e2e/pages/your-business/check-your-answers/checkYourAnswers.js
  e2e-tests/cypress/e2e/pages/your-business/index.js
  e2e-tests/cypress/support/assert-summary-list-row-value.js
  e2e-tests/cypress/support/insurance/check-policy-and-exports-summary-list.js
  e2e-tests/cypress/support/insurance/check-your-answers-eligibility-summary-list.js
  e2e-tests/cypress/support/insurance/check-your-business-summary-list.js
  e2e-tests/cypress/support/insurance/check-your-buyer-summary-list.js
  src/ui/server/routes/insurance/check-your-answers/index.test.ts
Labels: tech, chore

#811 fix(EMS-1901): Quote - policy type - missing error message
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.test.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.ts
Labels: bug

#812 chore(EMS-971-798): Simplify UI validation functions, DRY "contract policy" cypress selectors
  e2e-tests/pages/insurance/policy-and-export/contractPolicy.js
  e2e-tests/pages/insurance/policy-and-export/multipleContractPolicy.js
  e2e-tests/pages/insurance/policy-and-export/singleContractPolicy.js
  src/ui/server/controllers/insurance/account/sign-in/enter-code/validation/rules/security-code.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/validation/rules/security-code.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-address-line-one.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/final-destination.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/final-destination.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-months-of-cover.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-months-of-cover.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.test.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/currency.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/currency.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/percentage-of-cover.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/percentage-of-cover.ts
  src/ui/server/shared-validation/policy-currency-code/index.test.ts
  src/ui/server/shared-validation/policy-currency-code/index.ts
Labels: documentation, tech, chore

#824 feat(EMS-1918): Quote - Kind of policy - copy updates
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/pages/quote/policyType.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/templates/quote/policy-type.njk
Labels: enhancement, tech

#829 fix(EMS-1300): Quote - tell us about your policy heading, improve test coverage
  e2e-tests/commands/check-buyer-country-form.js
  e2e-tests/commands/check-error-summary-list-heading.js
  e2e-tests/commands/shared-commands.js
  e2e-tests/commands/submit-and-assert-field-errors.js
  e2e-tests/commands/submit-and-assert-radio-errors.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/how-your-data-will-be-used.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/account-to-apply-online/account-to-apply-online.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house-number/companies-house-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/insured-amount/insured-amount.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/letter-of-credit/letter-of-credit.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/other-parties/other-parties.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/type-of-policy/type-of-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-company-website-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-invalid-phone-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-name-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-years-exporting-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-can-contact-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation.spec.js
  e2e-tests/partials/index.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cookies.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  src/api/.keystone/config.js
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/types/pages/tell-us-about-your-policy.d.ts
Labels: bug, tech, chore

#830 feat(EMS-1919-1933): Quote - Policy length updates, simplify policy type/length IDs usage
  e2e-tests/commands/quote/forms.js
  e2e-tests/constants/field-ids/shared/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/pages/insurance/policy-and-export/typeOfPolicy.js
  e2e-tests/pages/quote/policyType.js
  e2e-tests/pages/quote/tellUsAboutYourPolicy.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-policy-type-multiple-times-via-back-button.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  src/api/constants/field-ids/shared/index.ts
  src/ui/server/constants/field-ids/shared/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/controllers/quote/policy-type/index.test.ts
  src/ui/server/controllers/quote/policy-type/index.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/index.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-length.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/policy-length.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/policy-length.ts
  src/ui/server/helpers/data-content-mappings/map-answers-to-content.test.ts
  src/ui/server/helpers/data-content-mappings/map-answers-to-content.ts
  src/ui/server/helpers/data-content-mappings/map-policy-length.test.ts
  src/ui/server/helpers/data-content-mappings/map-policy-length.ts
  src/ui/server/helpers/data-content-mappings/map-quote-to-content.test.ts
  src/ui/server/helpers/data-content-mappings/map-quote-to-content.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.test.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.ts
  src/ui/server/helpers/update-submitted-data/quote/index.test.ts
  src/ui/server/helpers/update-submitted-data/quote/index.ts
  src/ui/server/middleware/required-data-provided/quote/index.test.ts
  src/ui/server/middleware/required-data-provided/quote/index.ts
  src/ui/templates/quote/policy-type.njk
  src/ui/templates/quote/tell-us-about-your-policy.njk
  src/ui/types/pages/tell-us-about-your-policy.d.ts
Labels: enhancement, feature, tech, chore

#832 chore(EMS-1938): Rename "hasTrading" fields
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/business/index.js
  src/api/constants/field-ids/insurance/business/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/mock-application.ts
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: tech, chore

#835 feat(EMS-1902): Policy and Exports - Final destination autocomplete
  e2e-tests/commands/check-autocomplete-input.js
  e2e-tests/commands/check-buyer-country-form.js
  e2e-tests/commands/forms.js
  e2e-tests/commands/insurance/complete-and-submit-about-goods-or-services-form.js
  e2e-tests/fixtures/application.js
  e2e-tests/fixtures/countries.js
  e2e-tests/insurance/cypress/e2e/journeys/apply-offline-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/complete-eligibility-answers-for-a-second-time.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-country-only-apply-offline.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/pages/insurance/policy-and-export/aboutGoodsOrServices.js
  e2e-tests/pages/shared/buyerCountry.js
  e2e-tests/pages/shared/countryInput.js
  e2e-tests/pages/shared/index.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-country-only-get-a-quote-by-email.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/public/js/cookies.js
  src/ui/public/js/cookies.js.map
  src/ui/public/js/formSubmission.js
  src/ui/public/js/formSubmission.js.map
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/jsEnabled.js.map
  src/ui/public/js/main.js
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/scripts/accessible-autocomplete.js
  src/ui/templates/insurance/policy-and-exports/about-goods-or-services.njk
Labels: feature

#849 fix(EMS-1946): Your business - Incorrect companies house error message
  e2e-tests/content-strings/error-messages.js
  src/ui/server/content-strings/error-messages.ts
Labels: fix

#850 feat(EMS-1899): Your buyer - Working with buyer hint
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/working-with-buyer.spec.js
  e2e-tests/pages/insurance/your-buyer/workingWithBuyer.js
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/templates/insurance/your-buyer/working-with-buyer.njk
Labels: feature

#865 fix(EMS-974): Turnover - Remove financialYearEndDate if does not exist
  e2e-tests/constants/examples/companies-house-number-examples.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-financial-year-end.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/update-company-and-company-address/index.test.ts
  src/api/custom-resolvers/mutations/update-company-and-company-address/index.ts
  src/api/test-helpers/company.ts
  src/api/test-mocks/mock-company.ts
  src/api/types.ts
Labels: fix

#878 fix(EMS-1938): Submission - Trading name and address incorrect XLSX format
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.ts
Labels: fix
