Repository UK-Export-Finance/exip, pull requests merged in 2023-03, with the labels that each got.

#348 feat(EMS-1013): Account creation - only create an account if the email is unique
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-validation-account-already-exists.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/account-sign-in.test.ts
  src/api/custom-resolvers/create-account.test.ts
  src/api/custom-resolvers/create-account.ts
  src/api/custom-schema.ts
  src/api/schema.graphql
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/index.ts
  src/ui/server/graphql/mutations/account/create.ts
Labels: feature

#351 fix(EMS-1086-1088): Your business - Check your answers - Turnover
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/cypress/support/insurance/check-your-business-summary-list.js
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
Labels: bug

#352 feat(EMS-739-742): Your buyer - Working with your buyer
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/validation/working-with-buyer-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/working-with-buyer.spec.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/index.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/workingWithBuyer.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/your-buyer/complete-and-submit-working-with-buyer-form.js
  e2e-tests/cypress/support/submit-and-assert-radio-errors.js
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/insurance/your-buyer/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.api-error.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/index.api-error.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/validation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/validation/index.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/validation/rules/connected-to-buyer.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/validation/rules/connected-to-buyer.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/validation/rules/index.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/validation/rules/traded-with-buyer.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/validation/rules/traded-with-buyer.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/your-buyer/working-with-buyer.njk
Labels: feature

#355 chore(EMS-976): E2E tests - move backLink selector into pages/shared, clickBackLink cypress command
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email-go-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/validation/account-sign-in-validation-unverified-account.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country-country-only-apply-offline.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/exporter-location/exporter-location-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/letter-of-credit/letter-of-credit-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/letter-of-credit/letter-of-credit.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-maximum-buyer-will-owe.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-sales-to-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-total-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-continue-no-errors.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-no-companies-house-link.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country-country-only-get-a-quote-by-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-policy-type-multiple-times-via-back-button.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-fields-multi-policy-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/cypress/e2e/journeys/quote/exporter-location/exporter-location-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/pages/shared/index.js
  e2e-tests/cypress/e2e/partials/index.js
  e2e-tests/cypress/support/click-back-link.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/core-page-checks.js
Labels: tech

#350 feat(EMS-849): Account creation - verification link expired page
  .env.sample
  .github/workflows/test.yml
  docker-compose.yml
  e2e-tests/.env.sample
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress.config.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-verification-link-expired.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/create-account-and-verify-email/create-account-and-verify-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email-go-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/sign-in-with-second-requested-sign-in-code/sign-in-with-second-requested-sign-in-code.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/verifyEmailLinkExpired.js
  e2e-tests/cypress/fixtures/account.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/api/index.js
  e2e-tests/cypress/support/insurance/account/delete-account.js
  e2e-tests/cypress/support/insurance/account/verify-account-email.js
  src/api/.env.sample
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/custom-resolvers/account-sign-in.ts
  src/api/custom-resolvers/add-and-get-OTP.ts
  src/api/custom-resolvers/verify-account-email-address.ts
  src/api/custom-schema.ts
  src/api/helpers/is-valid-otp.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/test-mocks/index.ts
  src/api/types.ts
  src/ui/.env.sample
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email-link-expired/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email-link-expired/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-email.test.ts
  src/ui/server/graphql/mutations/account/verify-email-address.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-account.ts
  src/ui/server/test-mocks/mock-broker.ts
  src/ui/server/test-mocks/mock-buyer.ts
  src/ui/templates/insurance/account/create/verify-email-link-expired.njk
Labels: feature, tech

#356 feat(EMS-758-719-761-760): Your Buyer - Check your answers
  database/exip.sql
  e2e-tests/constants/examples/website-address-examples.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/checkYourAnswers.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/index.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/insurance/check-your-buyer-summary-list.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/insurance/your-buyer/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/save-and-back/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/generate-multiple-field-html/index.test.ts
  src/ui/server/helpers/generate-multiple-field-html/index.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
  src/ui/server/helpers/summary-lists/your-business/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/broker-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/working-with-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/working-with-buyer/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/server/test-mocks/mock-buyer.ts
  src/ui/templates/insurance/your-buyer/check-your-answers.njk
  src/ui/types/application.ts
  src/ui/types/index.d.ts
  src/ui/types/submitted-data.d.ts
Labels: feature

#360 feat(EMS-1081-1082): Account sign in - session expiry checks, signed out page
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/account-signed-out.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/signed-out/index.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/verify-account-sign-in-code.test.ts
  src/api/custom-resolvers/verify-account-sign-in-code.ts
  src/api/custom-schema.ts
  src/api/schema.graphql
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/signed-out/index.test.ts
  src/ui/server/controllers/insurance/account/signed-out/index.ts
  src/ui/server/graphql/mutations/account/verify-sign-in-code.ts
  src/ui/server/index.ts
  src/ui/server/middleware/insurance/user-session/index.test.ts
  src/ui/server/middleware/insurance/user-session/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/signed-out.njk
Labels: feature, security

#359 feat(EMS-1137): Account sign in/creation - redirect if already logged in
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-already-signed-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in-already-signed-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/sign-in-with-second-requested-sign-in-code.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/no-access-to-application.spec.js
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
Labels: enhancement, feature

#363 feat(EMS-1113-1117-743): Check your answers - Eligibility
  e2e-tests/constants/routes/insurance/check-your-answers.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/fields/insurance/eligibility/index.js
  e2e-tests/content-strings/fields/insurance/index.js
  e2e-tests/content-strings/pages/insurance/check-your-answers/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/all-sections.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/check-your-answers-eligibility-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/eligibility/summary-list/check-your-answers-eligibility-summary-list.spec.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/eligibility.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/index.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/shared.js
  e2e-tests/cypress/e2e/pages/insurance/index.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/check-your-answers-eligibility-summary-list.js
  e2e-tests/cypress/support/insurance/complete-and-submit-prepare-your-application-section-single.js
  src/ui/server/constants/routes/insurance/check-your-answers.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/fields/insurance/eligibility/index.ts
  src/ui/server/content-strings/fields/insurance/index.ts
  src/ui/server/content-strings/pages/insurance/check-your-answers/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/check-your-answers/eligibility/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/eligibility/index.ts
  src/ui/server/helpers/mappings/map-yes-no-field.test.ts
  src/ui/server/helpers/mappings/map-yes-no-field.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.test.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.ts
  src/ui/server/helpers/summary-lists/eligibility/index.test.ts
  src/ui/server/helpers/summary-lists/eligibility/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/submit-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/submit-application.ts
  src/ui/server/middleware/insurance/get-application/index.test.ts
  src/ui/server/middleware/insurance/get-application/index.ts
  src/ui/server/routes/insurance/check-your-answers/index.test.ts
  src/ui/server/routes/insurance/check-your-answers/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/check-your-answers.njk
Labels: feature

#367 fix(EMS-1263): application access - add a check for exporter ID
  src/ui/server/middleware/insurance/application-access/index.test.ts
  src/ui/server/middleware/insurance/application-access/index.ts
Labels: bug

#368 feat(EMS-912-922-929): Dashboard, default application status
  database/exip.sql
  e2e-tests/constants/application.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-populated-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard.spec.js
  e2e-tests/cypress/e2e/pages/insurance/dashboard/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-application.js
  e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-dashboard.js
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/dashboard/index.test.ts
  src/ui/server/controllers/insurance/dashboard/index.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/save-and-back/index.test.ts
  src/ui/server/graphql/queries/applications.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/mappings/map-applications/index.test.ts
  src/ui/server/helpers/mappings/map-applications/index.ts
  src/ui/server/helpers/mappings/map-applications/map-insured-for.test.ts
  src/ui/server/helpers/mappings/map-applications/map-insured-for.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-applications.ts
  src/ui/templates/components/dashboard-table.njk
  src/ui/templates/components/status-tag.njk
  src/ui/templates/insurance/dashboard.njk
  src/ui/types/application.ts
Labels: feature

#379 chore(npm-update): dependencies updates, fix/update E2E tests
  .github/workflows/test.yml
  e2e-tests/cypress.config.js
  e2e-tests/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js
  e2e-tests/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js
  e2e-tests/cypress/e2e/journeys/cookies-consent/change-cookies-consent-via-banner-and-cookies-page.spec.js
  e2e-tests/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/create-account-and-verify-email/create-account-and-verify-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-all-required-fields.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-no-required-fields.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/broker-email-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-financial-year-end.spec.js
  e2e-tests/cypress/support/core-page-checks.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-sign-in-account-form.js
  package-lock.json
  package.json
  src/api/package-lock.json
  src/ui/package-lock.json
  src/ui/templates/components/keystone/document/README.md
Labels: bug, dependencies, chore

#373 feat(EMS-1180): Declarations - Anti-bribery
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/declarations/index.js
  e2e-tests/constants/routes/insurance/declarations.js
  e2e-tests/content-strings/fields/insurance/declarations/index.js
  e2e-tests/content-strings/pages/insurance/declarations/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email-go-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/anti-bribery.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/index.js
  e2e-tests/cypress/support/api/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/flatten-keystone-document.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-confidentiality-form.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/public/css/styles.css
  src/ui/server/api/keystone/application/declarations.ts
  src/ui/server/constants/field-ids/insurance/declarations/index.ts
  src/ui/server/constants/routes/insurance/declarations.ts
  src/ui/server/constants/templates/insurance/declarations/index.ts
  src/ui/server/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.ts
  src/ui/server/graphql/queries/declarations/anti-bribery.ts
  src/ui/server/helpers/keystone-document-renderer-config/index.test.ts
  src/ui/server/helpers/keystone-document-renderer-config/index.ts
  src/ui/server/routes/insurance/declarations/index.test.ts
  src/ui/server/routes/insurance/declarations/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-declarations.ts
  src/ui/styles/declaration-list.scss
  src/ui/templates/shared-pages/declaration.njk
Labels: feature, tech

#385 feat(EMS-937): Dashboard - order applications by most recently updated
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-multiple-applications.spec.js
  e2e-tests/cypress/e2e/pages/insurance/dashboard/index.js
  src/ui/server/api/keystone/applications/index.ts
  src/ui/server/graphql/queries/applications.ts
Labels: enhancement

#375 fix(EMS-1276): Declarations - Confidentiality - render from content strings
  e2e-tests/content-strings/pages/insurance/declarations/index.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/confidentiality.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/public/css/styles.css
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.LICENSE.txt
  src/ui/public/js/mojFrontend.js.map
  src/ui/server/api/keystone/application/declarations.ts
  src/ui/server/constants/templates/insurance/declarations/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.ts
  src/ui/server/graphql/queries/declarations/confidentiality.ts
  src/ui/styles/declaration-list.scss
  src/ui/templates/insurance/declarations/confidentiality.njk
Labels: bug

#376 feat(EMS-937-912): Dashboard - order applications by most recently updated, additional E2E test coverage
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-multiple-applications.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-no-applications.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard.spec.js
  e2e-tests/cypress/e2e/pages/insurance/dashboard/index.js
  e2e-tests/cypress/support/api/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/get-reference-number.js
  e2e-tests/cypress/support/insurance/account/complete-insurance-eligibility-sign-in-and-go-to-dashboard.js
  e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-application.js
  e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-dashboard.js
  e2e-tests/cypress/support/insurance/delete-account-and-application.js
  e2e-tests/cypress/support/insurance/eligibility/submit-answers-from-buyer-country-happy-path.js
  e2e-tests/cypress/support/insurance/eligibility/submit-answers-happy-path.js
  src/ui/server/api/keystone/applications/index.ts
  src/ui/server/graphql/queries/applications.ts
Labels: enhancement, tech

#377 feat(EMS-1139-1140): Check and change your answers - Your business
  e2e-tests/constants/examples/company-details-examples.js
  e2e-tests/constants/examples/index.js
  e2e-tests/constants/routes/insurance/check-your-answers.js
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/pages/insurance/check-your-answers/index.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/check-your-answers-your-business-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/index.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/your-business.js
  src/ui/server/constants/routes/insurance/check-your-answers.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/content-strings/pages/insurance/check-your-answers/index.ts
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/save-and-back/index.ts
  src/ui/server/helpers/summary-lists/your-business/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/broker-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/check-your-answers/index.test.ts
  src/ui/server/routes/insurance/check-your-answers/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: feature

#381 feat(EMS-1194-1188): Declarations - Confirmation and acknowledgements
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/declarations/index.js
  e2e-tests/constants/routes/insurance/declarations.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/declarations/index.js
  e2e-tests/content-strings/pages/insurance/declarations/index.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/confirmation-and-acknowledgements.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/index.js
  e2e-tests/cypress/support/api/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-anti-bribery-exporting-with-code-of-conduct-form.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-confirmation-and-acknowledgements-form.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/api/keystone/application/declarations.ts
  src/ui/server/constants/field-ids/insurance/declarations/index.ts
  src/ui/server/constants/routes/insurance/declarations.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/index.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/graphql/queries/declarations/confirmation-and-acknowledgement.ts
  src/ui/server/routes/insurance/declarations/index.test.ts
  src/ui/server/routes/insurance/declarations/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-declarations.ts
Labels: feature

#384 fix(EMS-1277): Your business - Company Details Down - "continue" link
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-house-unavailable/company-house-unavailable-page.spec.js
  src/ui/server/controllers/insurance/business/company-details/companies-house-unavailable/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/companies-house-unavailable/index.ts
  src/ui/templates/insurance/your-business/companies-house-error.njk
Labels: bug

#383 feat(EMS-1142): Check and change your answers - Your buyer
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/pages/insurance/check-your-answers/index.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-single.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/check-your-answers-your-buyer-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list.spec.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/index.js
  e2e-tests/cypress/e2e/pages/insurance/check-your-answers/your-buyer.js
  src/ui/server/constants/routes/insurance/check-your-answers.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/content-strings/pages/insurance/check-your-answers/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/save-and-back/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/working-with-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/working-with-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/working-with-buyer/index.ts
  src/ui/server/routes/insurance/check-your-answers/index.test.ts
  src/ui/server/routes/insurance/check-your-answers/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
Labels: feature

#389 fix(CVE-2023-28154): Webpack updated to 5.76.3
  package-lock.json
  src/api/package-lock.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: security

#392 feat(EMS-1183): Declarations - Code of conduct - yes/no redirections
  e2e-tests/constants/field-values.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-multiple-applications.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/assert-all-sections-url.js
  e2e-tests/cypress/support/insurance/your-buyer/complete-and-submit-company-or-organisation-form.js
  src/ui/server/constants/field-values.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.ts
Labels: enhancement, feature, tech

#393 feat(EMS-1327): Declarations - Anti-bribery - copy update
  e2e-tests/content-strings/pages/insurance/declarations/index.js
  src/ui/server/content-strings/pages/insurance/declarations/index.ts
Labels: enhancement

#394 chore(tech): Declarations - various improvements
  database/exip.sql
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confidentiality/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/how-your-data-will-be-used/how-your-data-will-be-used.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/how-your-data-will-be-used/save-and-back.spec.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/anti-bribery.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/confidentiality.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/confirmation-and-acknowledgements.js
  e2e-tests/cypress/e2e/pages/insurance/declarations/how-your-data-will-be-used.js
  e2e-tests/cypress/e2e/pages/shared/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/assert-submit-and-save-buttons.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-anti-bribery-form.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-confidentiality-form.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-confirmation-and-acknowledgements-form.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-how-your-data-will-be-used-form.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.ts
Labels: tech

#398 chore(npm-update): added --save flag
  generate-exip-pricing-grid/package-lock.json
  generate-exip-pricing-grid/package.json
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: chore

#399 feat(EMS-921-1217): Application submission
  database/exip.sql
  e2e-tests/constants/application.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/pages/insurance/application-submitted/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/application-submitted-visit-page-without-completed-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/application-submitted.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application.spec.js
  e2e-tests/cypress/e2e/pages/insurance/applicationSubmitted.js
  e2e-tests/cypress/e2e/pages/insurance/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/complete-sign-in-and-submit-an-application.js
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/custom-resolvers/add-and-get-OTP.test.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/submit-application.test.ts
  src/api/custom-resolvers/submit-application.ts
  src/api/custom-schema.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/public/css/styles.css
  src/ui/public/js/main.js.map
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/constants/application.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/pages/insurance/application-submitted/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/application-submitted/index.test.ts
  src/ui/server/controllers/insurance/application-submitted/index.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.ts
  src/ui/server/graphql/mutations/submit-application.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/styles/styles.scss
  src/ui/templates/components/status-tag.njk
  src/ui/templates/insurance/application-submitted.njk
  src/ui/types/application.ts
Labels: feature

#401 fix(remove-ssh): Removed SSHD from the container
  src/api/Dockerfile
  src/api/init.sh
  src/api/sshd_config
  src/ui/Dockerfile
  src/ui/init.sh
  src/ui/sshd_config
Labels: good first issue, tech, security

#402 feat(dependabot): added dependabot.yml GHA
  .github/workflows/dependabot.yml
Labels: enhancement, security, dependencies

#400 feat(EMS-1243): Application submission - exporter email confirmation
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/custom-resolvers/account-sign-in-new-code.test.ts
  src/api/custom-resolvers/account-sign-in.test.ts
  src/api/custom-resolvers/send-email-confirm-email-address.test.ts
  src/api/custom-resolvers/send-email-confirm-email-address.ts
  src/api/custom-resolvers/submit-application.test.ts
  src/api/custom-resolvers/submit-application.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/emails/send-email-application-submitted.test.ts
  src/api/emails/send-email-application-submitted.ts
  src/api/keystone.test.ts
  src/api/keystone.ts
  src/api/test-mocks/index.ts
  src/api/types.ts
Labels: feature

#403 fix(dependabot): moved to correct location
  .github/dependabot.yml
Labels: dependencies

#404 feat(EMS-1254-1260): Application submission - exporter document emails
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/custom-resolvers/submit-application.test.ts
  src/api/custom-resolvers/submit-application.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/emails/send-application-submitted-emails/index.ts
  src/api/emails/send-email-application-submitted.test.ts
  src/api/emails/send-email-application-submitted.ts
  src/api/test-mocks/index.ts
  src/api/types.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: feature, tech
