Repository UK-Export-Finance/exip, pull requests merged in 2023-04, with the labels that each got.

#407 fix(EMS-1089-1257-1331-1343-1354-1361): Various fixes for declarations, your buyer and check answers
  database/exip.sql
  e2e-tests/constants/routes/insurance/declarations.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/pages/insurance/declarations/index.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-single-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-single.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/how-your-data-will-be-used/how-your-data-will-be-used.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/working-with-buyer.spec.js
  e2e-tests/cypress/support/insurance/assert-submit-and-save-buttons.js
  e2e-tests/cypress/support/insurance/check-policy-and-exports-summary-list.js
  src/ui/server/constants/routes/insurance/declarations.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/pages/insurance/declarations/index.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/temp-create-account/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/temp-create-account/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/declarations/confidentiality.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/insurance/your-buyer/working-with-buyer.njk
  src/ui/templates/shared-pages/declaration.njk
Labels: bug, tech

#414 feat(EMS-534): Insurance - Eligibility - Exporter location error message wording change
  e2e-tests/content-strings/error-messages.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/ui/server/content-strings/error-messages.ts
Labels: feature

#415 feat(EMS-1334): Account - sign out
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/header.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-out/account-sign-out.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/header-authenticated.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/sign-in/signIn.js
  e2e-tests/cypress/support/check-authenticated-header.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/content-strings/header.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/controllers/insurance/account/sign-out/index.test.ts
  src/ui/server/controllers/insurance/account/sign-out/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/sign-in/sign-in.njk
Labels: feature

#417 feat(EMS-1294): Footer - Contact link and remove contact details
  e2e-tests/content-strings/footer.js
  e2e-tests/cypress.config.js
  e2e-tests/cypress/e2e/journeys/contact-us.spec.js
  e2e-tests/cypress/e2e/journeys/footer.spec.js
  e2e-tests/cypress/e2e/partials/footer.js
  src/ui/server/content-strings/footer.ts
  src/ui/templates/partials/footer.njk
Labels: feature

#422 fix(docker): downgraded docker image to Node 18.15
  src/api/Dockerfile
  src/ui/Dockerfile
Labels: fix

#425 chore(EMS-1357): Merge main into main-application
  CHANGELOG.md
  e2e-tests/constants/routes/index.js
  e2e-tests/content-strings/footer.js
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/cypress/e2e/journeys/accessibility-statement.spec.js
  e2e-tests/cypress/e2e/journeys/footer.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/e2e/pages/accessibility-statement.js
  e2e-tests/cypress/e2e/pages/index.js
  e2e-tests/cypress/e2e/partials/footer.js
  package-lock.json
  package.json
  src/api/package-lock.json
  src/ui/server/constants/routes/index.ts
  src/ui/server/constants/templates/index.ts
  src/ui/server/content-strings/footer.ts
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/server/controllers/root/accessibility-statement/index.test.ts
  src/ui/server/controllers/root/accessibility-statement/index.ts
  src/ui/server/middleware/headers/security.ts
  src/ui/server/routes/root/index.test.ts
  src/ui/server/routes/root/index.ts
  src/ui/templates/accessibility-statement.njk
  src/ui/templates/partials/footer.njk
Labels: tech, chore

#427 feat(EMS-1281): Feedback - Phase banner link
  e2e-tests/content-strings/index.js
  e2e-tests/content-strings/phase-banner.js
  e2e-tests/cypress/e2e/journeys/accessibility-statement.spec.js
  e2e-tests/cypress/e2e/journeys/contact-us.spec.js
  e2e-tests/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/cypress/e2e/journeys/page-not-found.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/need-to-start-again.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/cypress/support/check-phase-banner.js
  e2e-tests/cypress/support/core-page-checks.js
  src/ui/server/content-strings/index.ts
  src/ui/server/content-strings/phase-banner.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/controllers/root/accessibility-statement/index.test.ts
  src/ui/server/controllers/root/accessibility-statement/index.ts
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/server/helpers/page-variables/core/insurance/index.test.ts
  src/ui/server/helpers/page-variables/core/insurance/index.ts
  src/ui/server/helpers/page-variables/core/quote/index.test.ts
  src/ui/server/helpers/page-variables/single-input/index.test.ts
  src/ui/server/helpers/page-variables/single-input/index.ts
  src/ui/server/helpers/page-variables/single-input/insurance/index.test.ts
  src/ui/server/helpers/page-variables/single-input/insurance/index.ts
  src/ui/server/helpers/page-variables/single-input/quote/index.test.ts
  src/ui/server/helpers/page-variables/single-input/quote/index.ts
  src/ui/server/index.ts
  src/ui/templates/insurance/start.njk
  src/ui/templates/partials/phase-banner.njk
  src/ui/types/page-variables.d.ts
  src/ui/types/pages/tell-us-about-your-policy.d.ts
Labels: feature

#421 chore(EMS-1318): Re-enable temporarily disabled E2E tests, replace cypress-audit package
  e2e-tests/cypress.config.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/plugins/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/core-page-checks.js
  package-lock.json
  package.json
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/types/pages/tell-us-about-your-policy.d.ts
Labels: tech, dependencies, chore

#437 fix(directory): removed accidental directory creation
  src/generate-exip-pricing-grid/package-lock.json
Labels: fix

#419 fix(EMS-1352): Application relationships - update application's updatedAt timestamp
  src/api/.keystone/config.js
  src/api/helpers/update-application/index.test.ts
  src/api/helpers/update-application/index.ts
  src/api/keystone.test.ts
  src/api/schema.ts
Labels: bug

#431 feat(EMS-863-963-951): Account - Password reset - form and email
  database/exip.sql
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-account-not-found.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/validation/account-password-reset-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
  e2e-tests/cypress/e2e/partials/insurance/accountFormFields.js
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.ts
  src/api/custom-schema/type-defs.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/integrations/notify/index.ts
  src/api/package-lock.json
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/api/keystone/account/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/password-reset/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/index.ts
  src/ui/server/controllers/insurance/account/password-reset/validation/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/validation/index.ts
  src/ui/server/controllers/insurance/account/password-reset/validation/rules/email.test.ts
  src/ui/server/controllers/insurance/account/password-reset/validation/rules/email.ts
  src/ui/server/controllers/insurance/account/password-reset/validation/rules/index.ts
  src/ui/server/graphql/mutations/account/send-email-password-reset-link.ts
  src/ui/server/middleware/insurance/application-access/index.test.ts
  src/ui/server/middleware/insurance/application-access/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/password-reset/password-reset.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
Labels: feature

#443 fix(EMS-534): Eligibility - Change wording of exporting location error message
  e2e-tests/content-strings/error-messages.js
  src/ui/server/content-strings/error-messages.ts
Labels: fix

#436 feat(EMS-968): Account - Password reset - link sent page
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/link-sent/account-password-reset-link-sent.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/password-reset/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/password-reset/linkSent.js
  src/api/package-lock.json
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/password-reset/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/index.ts
  src/ui/server/controllers/insurance/account/password-reset/link-sent/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/link-sent/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/password-reset/link-sent.njk
  src/ui/types/express/index.d.ts
Labels: feature

#446 feat(EMS-1320): Completed application - Lock application
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/how-your-data-will-be-used/how-your-data-will-be-used.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/no-access-application-submitted.spec.js
  e2e-tests/cypress/e2e/pages/insurance/noAccessApplicationSubmitted.js
  src/api/.gitignore
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/no-access-application-submitted/index.test.ts
  src/ui/server/controllers/insurance/no-access-application-submitted/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/insurance/application-access/index.test.ts
  src/ui/server/middleware/insurance/application-access/index.ts
  src/ui/server/middleware/insurance/application-status/index.test.ts
  src/ui/server/middleware/insurance/application-status/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/cannot-access-application-submitted.njk
Labels: feature

#449 feat(EMS-1085): Account - Password reset - E2E test coverage for password form validation
  e2e-tests/constants/examples/index.js
  e2e-tests/constants/examples/password-examples.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details-validation-password.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/validation/account-password-reset-new-password-valdation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-only-my-applications.spec.js
Labels: tech

#450 fix(EMS-1506-1528-1536): Fix application submission and page specific header/back link issues
  e2e-tests/cypress/e2e/journeys/accessibility-statement.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-out/account-sign-out.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/application-submitted.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-without-exporting-with-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/no-access-application-submitted.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/complete-declarations.js
  e2e-tests/cypress/support/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/cypress/support/insurance/declarations/complete-and-submit-anti-bribery-exporting-with-code-of-conduct-form.js
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/controllers/root/accessibility-statement/index.test.ts
  src/ui/server/controllers/root/accessibility-statement/index.ts
  src/ui/server/helpers/get-true-properties/index.test.ts
  src/ui/server/helpers/get-true-properties/index.ts
  src/ui/templates/insurance/account/sign-in/sign-in.njk
Labels: bug, tech
