Repository UK-Export-Finance/exip, pull requests merged in 2023-12, with the labels that each got.

#1437 feat(EMS-2345): No PDF - Alternative Trading Address - Registered office address
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/partials/index.js
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.ts
  src/ui/templates/insurance/your-business/alternative-trading-address.njk
Labels: feature

#1439 feat(EMS-2287 2347 2363): No PDF - Single/multiple policy - currency enhancements
  e2e-tests/commands/insurance/check-policy-currency-code-input.js
  e2e-tests/commands/insurance/complete-and-submit-multiple-contract-policy-form.js
  e2e-tests/commands/insurance/complete-and-submit-single-contract-policy-form.js
  e2e-tests/commands/shared-commands/form/change-answer-radio-field.js
  e2e-tests/commands/shared-commands/form/index.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/constants/index.js
  e2e-tests/constants/supported-currencies.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/fixtures/currencies.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-multiple-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-single-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/pages/shared/index.js
  e2e-tests/pages/shared/radios.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  src/api/test-mocks/mock-currencies.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/supported-currencies.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/helpers/mappings/map-currencies.test.ts
  src/ui/server/helpers/mappings/map-currencies.ts
  src/ui/server/helpers/mappings/map-currencies/as-radio-options/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-radio-options/index.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.ts
  src/ui/server/helpers/mappings/map-currencies/map-supported-currencies/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/map-supported-currencies/index.ts
  src/ui/server/helpers/mappings/map-select-option.test.ts
  src/ui/server/helpers/mappings/map-select-option.ts
  src/ui/server/helpers/name-and-iso-code-text/index.test.ts
  src/ui/server/helpers/name-and-iso-code-text/index.ts
  src/ui/server/test-mocks/mock-currencies.ts
  src/ui/templates/components/currency-radio-inputs.njk
  src/ui/templates/components/policy-currency-code-hint.njk
  src/ui/templates/insurance/eligibility/cover-period.njk
  src/ui/templates/insurance/policy/different-name-on-policy.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/types/currency.d.ts
  src/ui/types/index.d.ts
  src/ui/types/radio-option.ts
Labels: enhancement, feature, tech

#1461 chore(deps): Bump dependencies
  .github/workflows/publish.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1470 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1472 feat(EMS-2211): No PDF - Alternative trading address - Save and back
  e2e-tests/commands/insurance/complete-and-submit-alternative-trading-address-form.js
  e2e-tests/constants/field-ids/insurance/business/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/save-and-back.spec.js
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/constants/routes/insurance/business.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/index.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-different-trading-address/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-different-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-different-trading-address/index.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/company-different-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/company-different-trading-address/index.ts
  src/ui/server/controllers/insurance/business/save-data/company-different-trading-address/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/save-data/company-different-trading-address/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: feature

#1478 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1481 chore(EMS-2409): Rename/align assertSummaryListRowValue cypress commands
  e2e-tests/commands/shared-commands/assertions/assert-summary-list-row-value-new.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-change-different-name-to-same-name-on-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-change-same-name-to-different-name-on-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-different-name-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-different-name-to-same-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-same-name-position.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-same-name-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/insurance/cypress/support/assertions/index.js
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
Labels: tech, chore, fix

#1486 feat(EMS-2386): Add Google tag manager script
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  README.md
  docker-compose.yml
  e2e-tests/commands/analytics/check-analytics-scripts-are-rendered.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/change-cookies-consent-via-banner-and-cookies-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cookies.spec.js
  src/ui/.env.sample
  src/ui/public/css/styles.css
  src/ui/public/js/googleAnalytics.js
  src/ui/public/js/googleAnalytics.js.map
  src/ui/public/js/googleTagManager.js
  src/ui/public/js/googleTagManager.js.map
  src/ui/scripts/google-analytics.js
  src/ui/scripts/google-tag-manager.js
  src/ui/server/constants/integrity.ts
  src/ui/server/middleware/cookies-consent/index.test.ts
  src/ui/server/middleware/cookies-consent/index.ts
  src/ui/server/middleware/integrity/index.test.ts
  src/ui/server/middleware/integrity/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/styles/styles.scss
  src/ui/templates/index.njk
  src/ui/types/express/index.d.ts
  src/ui/webpack.common.config.js
Labels: documentation, enhancement

#1463 chore(EMS-2394): Replace mock date constructions to use native JS instead of date-fns
  e2e-tests/commands/insurance/requested-start-date-field.js
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/need-to-start-new-application/need-to-start-new-application-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  src/api/keystone.test.ts
  src/api/test-mocks/mock-application.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
Labels: tech, chore

#1503 chore(deps): dependencies updates
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1507 chore(merge): Merge `main` into `main-application-no-pdf`
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  docker-compose.yml
  e2e-tests/commands/analytics/check-analytics-scripts-are-rendered.js
  e2e-tests/commands/insurance/requested-start-date-field.js
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/change-cookies-consent-via-banner-and-cookies-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cookies.spec.js
  package-lock.json
  package.json
  src/api/keystone.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/test-mocks/mock-application.ts
  src/ui/.env.sample
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/googleAnalytics.js
  src/ui/public/js/googleAnalytics.js.map
  src/ui/public/js/googleTagManager.js
  src/ui/public/js/googleTagManager.js.map
  src/ui/scripts/google-analytics.js
  src/ui/scripts/google-tag-manager.js
  src/ui/server/constants/integrity.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/middleware/cookies-consent/index.test.ts
  src/ui/server/middleware/cookies-consent/index.ts
  src/ui/server/middleware/integrity/index.test.ts
  src/ui/server/middleware/integrity/index.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/styles/styles.scss
  src/ui/templates/index.njk
  src/ui/types/express/index.d.ts
  src/ui/webpack.common.config.js
Labels: chore

#1511 chore(EMS-1964): Move external UI currency API calls into the EXIP API
  docker-compose.yml
  e2e-tests/constants/field-ids/shared/index.js
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/constants/field-ids/shared/index.ts
  src/api/constants/index.ts
  src/api/constants/supported-currencies/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/queries/get-APIM-CIS-countries/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.ts
  src/api/custom-resolvers/queries/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-currencies/index.test.ts
  src/api/helpers/map-currencies/index.ts
  src/api/integrations/APIM/index.ts
  src/api/schema.graphql
  src/api/test-mocks/mock-APIM-CIS-countries-response.ts
  src/api/test-mocks/mock-APIM-currencies-response.ts
  src/api/types/country/index.ts
  src/ui/.env.sample
  src/ui/server/api/external/index.ts
  src/ui/server/api/index.ts
  src/ui/server/api/keystone/APIM/index.ts
  src/ui/server/constants/field-ids/shared/index.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/graphql/queries/APIM/currencies.ts
  src/ui/server/helpers/mappings/map-currencies.test.ts
  src/ui/server/helpers/mappings/map-currencies.ts
Labels: tech, chore

#1515 chore(EMS-1964): Merge `main` into `main-application-no-pdf`, update/simplify UI currency mappings
  CHANGELOG.md
  docker-compose.yml
  e2e-tests/constants/field-ids/shared/index.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/constants/field-ids/shared/index.ts
  src/api/constants/index.ts
  src/api/constants/supported-currencies/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/queries/get-APIM-CIS-countries/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.ts
  src/api/custom-resolvers/queries/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-currencies/index.test.ts
  src/api/helpers/map-currencies/index.ts
  src/api/integrations/APIM/index.ts
  src/api/schema.graphql
  src/api/test-mocks/mock-APIM-CIS-countries-response.ts
  src/api/test-mocks/mock-APIM-currencies-response.ts
  src/api/types/country/index.ts
  src/ui/.env.sample
  src/ui/package-lock.json
  src/ui/server/api/external/index.ts
  src/ui/server/api/index.ts
  src/ui/server/api/keystone/APIM/index.ts
  src/ui/server/constants/field-ids/shared/index.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/graphql/queries/APIM/currencies.ts
  src/ui/server/helpers/mappings/map-currencies/as-radio-options/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-radio-options/index.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.ts
  src/ui/server/helpers/mappings/map-currencies/map-supported-currencies/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/map-supported-currencies/index.ts
Labels: tech, chore

#1513 feat(EMS-2300): No PDF - Your buyer - start page
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/start-your-buyer-section.js
  e2e-tests/commands/shared-commands/assertions/assert-section-start-content.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-populated-application.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/export-contract-root.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/root/insurance-policy-root.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-dashboard.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-header-and-page-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/root/your-business-root.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-can-contact-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-email.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-first-last-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-position.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/root/your-buyer-root.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/validation/working-with-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/working-with-buyer.spec.js
  e2e-tests/insurance/cypress/support/application/index.js
  e2e-tests/pages/shared/index.js
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.ts
  src/ui/server/controllers/insurance/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/shared-pages/section-start.njk
Labels: enhancement, feature

#1516 chore(EMS-2300): No PDF - Section start pages - tech improvements
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/root/export-contract-root.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/root/insurance-policy-root.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/root/your-business-root.spec.js
  src/ui/server/controllers/insurance/business/index.test.ts
  src/ui/server/controllers/insurance/business/index.ts
  src/ui/server/controllers/insurance/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/index.ts
  src/ui/server/controllers/insurance/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/index.ts
  src/ui/server/helpers/page-variables/core/insurance/section-start/index.test.ts
  src/ui/server/helpers/page-variables/core/insurance/section-start/index.ts
  src/ui/templates/shared-pages/section-start.njk
  src/ui/types/index.d.ts
  src/ui/types/page-variables.d.ts
Labels: bug, tech, chore

#1533 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1534 chore(EMS-722): Split up Companies house summary list assertions
  src/ui/server/helpers/summary-lists/companies-house/index.test.ts
Labels: tech, chore

#1535 chore(deps): dependencies updates
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/scripts/google-tag-manager.js
Labels: dependencies

#1536 feat(EMS-2399): No PDF - About goods or services - content updates
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/pages/insurance/export-contract/aboutGoodsOrServices.js
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/templates/insurance/export-contract/about-goods-or-services.njk
Labels: enhancement

#1537 fix(EMS-2453): Buyer country field - styling issue, DRY autocomplete component
  src/ui/templates/components/accessible-autocomplete-select.njk
  src/ui/templates/insurance/export-contract/about-goods-or-services.njk
  src/ui/templates/shared-pages/buyer-country.njk
Labels: bug, tech

#1540 fix(EMS-2453): Buyer country - fix styling issue
  src/ui/templates/components/accessible-autocomplete-select.njk
  src/ui/templates/insurance/policy/about-goods-or-services.njk
  src/ui/templates/shared-pages/buyer-country.njk
Labels: bug, tech

#1538 feat(EMS-2366): No PDF - Your Buyer - Connection to the buyer page
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-connection-to-the-buyer-form.js
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/connection-to-the-buyer-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/validation/connection-to-the-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/validation/working-with-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/working-with-buyer.spec.js
  e2e-tests/insurance/cypress/support/application/buyer/index.js
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/insurance/your-buyer/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/validation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/validation/index.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/validation/rules/connected-to-buyer.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/validation/rules/connected-to-buyer.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/validation/rules/connection-with-buyer-description.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/validation/rules/connection-with-buyer-description.ts
  src/ui/server/controllers/insurance/your-buyer/connection-to-the-buyer/validation/rules/index.ts
  src/ui/server/helpers/required-fields/your-buyer/index.test.ts
  src/ui/server/helpers/required-fields/your-buyer/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/server/test-mocks/mock-buyer.ts
  src/ui/templates/insurance/your-buyer/connection-to-the-buyer.njk
  src/ui/templates/shared-pages/single-radio-page.njk
  src/ui/types/application.ts
Labels: feature

#1545 style(EMS-2447 2451): Start page, cookies banner, cookies page content improvements
  e2e-tests/commands/analytics/check-cookies-consent-banner-does-not-exist.js
  e2e-tests/commands/analytics/check-cookies-consent-banner-is-not-visible.js
  e2e-tests/commands/analytics/check-cookies-consent-banner-is-visible.js
  e2e-tests/content-strings/cookies-consent.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/insurance/cypress/e2e/journeys/start.spec.js
  e2e-tests/pages/insurance/start.js
  e2e-tests/partials/cookieBanner.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/change-cookies-consent-via-banner-and-cookies-page.spec.js
  src/ui/server/content-strings/cookies-consent.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/templates/cookies.njk
  src/ui/templates/insurance/start.njk
  src/ui/templates/partials/cookies-banner.njk
Labels: enhancement, tech

#1549 style(EMS-2449): Get a quote - type of policy content updates
  .github/workflows/publish.yml
  e2e-tests/constants/eligibility.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  src/ui/server/constants/eligibility.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
Labels: enhancement, tech, chore

#1551 fix(EMS-2463): `ci:all` execution
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/ui/package-lock.json
Labels: dependencies, fix

#1561 chore(merge): Merge `main` into `main-application-no-pdf`
  .github/workflows/publish.yml
  .github/workflows/test.yml
  CHANGELOG.md
  e2e-tests/commands/analytics/check-cookies-consent-banner-does-not-exist.js
  e2e-tests/commands/analytics/check-cookies-consent-banner-is-not-visible.js
  e2e-tests/commands/analytics/check-cookies-consent-banner-is-visible.js
  e2e-tests/constants/eligibility.js
  e2e-tests/content-strings/cookies-consent.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/insurance/cypress/e2e/journeys/start.spec.js
  e2e-tests/pages/insurance/start.js
  e2e-tests/partials/cookieBanner.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/change-cookies-consent-via-banner-and-cookies-page.spec.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/package-lock.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/scripts/google-tag-manager.js
  src/ui/server/constants/eligibility.ts
  src/ui/server/content-strings/cookies-consent.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/templates/cookies.njk
  src/ui/templates/insurance/export-contract/about-goods-or-services.njk
  src/ui/templates/insurance/start.njk
  src/ui/templates/partials/cookies-banner.njk
  src/ui/templates/shared-pages/single-radio-page.njk
Labels: chore

#1562 style(EMS-2249): No PDF - Your business - Check your answers copy updates
  e2e-tests/content-strings/fields/insurance/business/index.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
Labels: enhancement

#1563 chore(EMS-2418): No PDF - Disable MOJ design library
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/new-password/account-password-reset-new-password.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in.spec.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/scripts/moj-frontend.js
  src/ui/server/nunjucks-configuration/index.ts
  src/ui/styles/styles.scss
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/password-reset/new-password.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
  src/ui/templates/insurance/your-business/company-details.njk
Labels: chore

#1564 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1569 chore(EMS-2418): No PDF - Upgrade GOV design package
  e2e-tests/commands/shared-commands/assertions/check-phase-banner.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/formSubmission.js
  src/ui/public/js/formSubmission.js.map
  src/ui/public/js/googleTagManager.js.map
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/jsEnabled.js.map
  src/ui/scripts/form-submission.js
  src/ui/scripts/js-enabled.js
  src/ui/server/constants/integrity.ts
  src/ui/server/index.ts
  src/ui/server/nunjucks-configuration/index.ts
  src/ui/styles/styles.scss
  src/ui/templates/components/accessible-autocomplete-select.njk
  src/ui/templates/components/status-tag.njk
  src/ui/templates/index.njk
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/password-reset/new-password.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
  src/ui/templates/partials/phase-banner.njk
Labels: tech, dependencies, chore

#1580 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1583 feat(EMS-2485): Introduce code coverage
  .cspell.json
  .github/workflows/test.yml
  CHANGELOG.md
Labels: feature

#1578 fix(EMS-2399-2418): No PDF - About goods or services - yes/no radio ordering
  README.md
  e2e-tests/commands/shared-commands/assertions/assert-first-and-last-radios.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/pages/shared/index.js
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/export-contract/about-goods-or-services.njk
Labels: documentation, tech, chore, fix

#1596 fix(test): Invalid month causing unit test to fail
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
Labels: chore, fix

#1579 fix(EMS-2484): release please GHA `v4` upgrade
  .github/workflows/publish.yml
  .release-please-manifest.json
  README.md
  package-lock.json
  package.json
  release-please-config.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: documentation, dependencies, chore, fix

#1595 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1599 chore(merge): Merge `main` into `main-application-no-pdf`
  .cspell.json
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  e2e-tests/pages/shared/index.js
  package-lock.json
  package.json
  release-please-config.json
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/schema.graphql
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/js/govukFrontend.js.LICENSE.txt
Labels: chore

#1560 feat(EMS-2249): No PDF - Your business - Check your answers - Multiple lists
  e2e-tests/commands/insurance/get-summary-list-field.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/content-strings/form-titles.js
  e2e-tests/content-strings/index.js
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/form-titles.ts
  src/ui/server/content-strings/index.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.ts
  src/ui/server/helpers/summary-lists/generate-groups-of-summary-lists/index.test.ts
  src/ui/server/helpers/summary-lists/generate-groups-of-summary-lists/index.ts
  src/ui/server/helpers/summary-lists/generate-summary-list-rows/index.ts
  src/ui/server/helpers/summary-lists/your-business/credit-control-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/credit-control-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.ts
  src/ui/templates/components/group-of-summary-lists.njk
  src/ui/templates/insurance/check-your-answers/check-your-answers.njk
  src/ui/templates/insurance/your-business/check-your-answers.njk
  src/ui/types/index.d.ts
  src/ui/types/summary-list.d.ts
Labels: documentation, enhancement, feature

#1602 fix(EMS-2492): Quote - Policy type form validation
  e2e-tests/pages/quote/policyType.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.test.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.ts
  src/ui/templates/cookies.njk
  src/ui/templates/quote/policy-type.njk
Labels: bug, tech

#1605 chore(main-application-no-pdf): release 2.5.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1601 chore(EMS-2454): No PDF - Check your answers - remove unnecessary save and back routes
  e2e-tests/constants/routes/insurance/business.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/check-your-answers-your-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-page.spec.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/ui/server/constants/routes/insurance/business.ts
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.ts
  src/ui/server/controllers/insurance/business/check-your-answers/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/save-and-back/index.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/save-and-back/index.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/templates/insurance/export-contract/check-your-answers.njk
  src/ui/templates/insurance/policy/check-your-answers.njk
  src/ui/templates/insurance/your-business/check-your-answers.njk
  src/ui/templates/insurance/your-buyer/check-your-answers.njk
Labels: tech, chore

#1603 feat(EMS-2296): No PDF - Multiple contract policy - update total months of cover field
  e2e-tests/commands/insurance/complete-and-submit-multiple-contract-policy-form.js
  e2e-tests/commands/insurance/complete-and-submit-single-contract-policy-form.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-multiple-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/validation/rules/total-months-of-cover.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/validation/rules/total-months-of-cover.ts
  src/ui/server/helpers/mappings/map-total-months-of-insurance/index.test.ts
  src/ui/server/helpers/mappings/map-total-months-of-insurance/index.ts
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
Labels: enhancement, feature

#1608 chore(merge): Merge `main` into `main-application-no-pdf`
  .cspell.json
  .github/workflows/publish.yml
  .github/workflows/test.yml
  .release-please-manifest.json
  CHANGELOG.md
  e2e-tests/pages/quote/policyType.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/integrations/ordnance-survey/index.ts
  src/ui/public/css/styles.css
  src/ui/public/js/googleTagManager.js.map
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.test.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.ts
  src/ui/templates/cookies.njk
  src/ui/templates/quote/policy-type.njk
Labels: chore

#1607 feat(EMS-2452-2462): No PDF - Policy type - Requested start date validation rules
  e2e-tests/commands/insurance/requested-start-date-field.js
  e2e-tests/commands/shared-commands/form/assert-field-errors.js
  e2e-tests/commands/shared-commands/form/index.js
  e2e-tests/commands/shared-commands/form/submit-and-assert-field-errors.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/check-your-answers/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/XLSX.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/check-your-answers/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/policy-length.ts
  src/ui/server/helpers/number/index.test.ts
  src/ui/server/helpers/number/index.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/server/shared-validation/requested-start-date/index.ts
Labels: documentation, enhancement, feature, tech

#1609 feat(EMS-2499): No PDF - Working with buyer/Trading with buyer - Check and Change your answers
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/working-with-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/working-with-buyer/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
Labels: feature
