Repository UK-Export-Finance/exip, pull requests merged in 2023-02, with the labels that each got.

#282 fix(EMS-880-938): Company Details - Handle company with no SIC code, delete previous SIC code, remove __typename from mapping
  e2e-tests/constants/examples/companies-house-number-examples.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-house-search.spec.js
  src/api/.keystone/config.js
  src/api/custom-schema.ts
  src/ui/server/controllers/insurance/business/company-details/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
Labels: bug, tech

#284 feat(EMS-945): ReferenceNumber set auto increment
  database/exip.sql
Labels: enhancement

#286 feat(EMS-782): account creation - password reveal
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/yourDetails.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.LICENSE.txt
  src/ui/public/js/mojFrontend.js.map
  src/ui/scripts/moj-frontend.js
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/webpack.common.config.js
Labels: enhancement

#287 fix(EMS-911-919): Policy and exports - fix field hint link and error message
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/cypress/support/insurance/check-policy-currency-code-input.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
Labels: bug

#288 feat(EMS-644): Company Details - Turnover - Financial year end date section
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/content-strings/pages/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-financial-year-end.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-page.spec.js
  e2e-tests/cypress/e2e/pages/your-business/index.js
  e2e-tests/cypress/e2e/pages/your-business/turnover/turnover.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/insurance/requested-start-date-field.js
  src/api/.keystone/config.js
  src/api/custom-schema.ts
  src/api/helpers/create-full-timestamp-from-day-month.test.ts
  src/api/helpers/create-full-timestamp-from-day-month.ts
  src/api/helpers/mapCompaniesHouseFields.test.ts
  src/api/helpers/mapCompaniesHouseFields.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/constants/templates/insurance/business/index.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/graphql/queries/companies-house.ts
  src/ui/server/helpers/date/format-date/index.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/server/helpers/mappings/map-financial-year-end-date.test.ts
  src/ui/server/helpers/mappings/map-financial-year-end-date.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover.njk
Labels: feature

#289 feat(EMS-794-800): account creation - confirm email page
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/confirmEmail.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-create-account-form.js
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/create/confirm-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/confirm-email/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/create/confirm-email.njk
Labels: feature

#290 feat(EMS-645): Company Details - Turnover - Estimated Annual Turnover field
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/turnover/turnover.js
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/controllers/insurance/business/turnover/validation/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/validation/index.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.test.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/your-business/turnover.njk
Labels: feature

#295 chore(npm): Package update
  package-lock.json
Labels: security

#297 chore(npm-audit): Package updates
  CHANGELOG.md
  package-lock.json
  package.json
  src/api/package-lock.json
  src/ui/package-lock.json
Labels: tech, security

#292 feat(EMS-794): Account creation - save in the database
  .env.sample
  .github/workflows/test.yml
  database/exip.sql
  e2e-tests/.env.sample
  e2e-tests/cypress.config.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-renders-submitted-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email.spec.js
  e2e-tests/cypress/fixtures/account.js
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/custom-schema.ts
  src/api/integrations/notify/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/api/keystone/account/index.ts
  src/ui/server/api/keystone/index.ts
  src/ui/server/controllers/insurance/account/create/confirm-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/confirm-email/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/save-data/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/save-data/index.ts
  src/ui/server/graphql/mutations/account/create.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-account.ts
  src/ui/templates/insurance/account/create/confirm-email.njk
  src/ui/types/account.d.ts
  src/ui/types/express/index.d.ts
  src/ui/types/index.d.ts
Labels: feature

#298 fix(EMS-946-947): Nature of Business - Mapping fields which are 0
  e2e-tests/cypress/fixtures/application.js
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/helpers/display-number-field-value/index.test.ts
  src/ui/server/helpers/display-number-field-value/index.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
Labels: bug

#302 fix(EMS-958): Account creation - conditionally render 'we sent a link to...' text
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-refresh-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-renders-submitted-email.spec.js
  src/ui/templates/insurance/account/create/confirm-email.njk
Labels: bug

#303 fix(EMS-948): change 'already have account' namings
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/account-to-apply-online/account-to-apply-online-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/account-to-apply-online/account-to-apply-online.spec.js
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/eligibility/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/controllers/insurance/eligibility/account-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/account-to-apply-online/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/temp-create-account/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/temp-create-account/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/templates/insurance/eligibility/account-to-apply-online.njk
Labels: bug, tech

#299 chore(EMS-859): is populated array helper function
  src/ui/server/controllers/insurance/business/company-details/helpers/companies-house-search.helper.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/helpers/combine-validation-rules/index.ts
  src/ui/server/helpers/has-form-data/index.ts
  src/ui/server/helpers/is-populated-array/index.test.ts
  src/ui/server/helpers/is-populated-array/index.ts
  src/ui/server/helpers/task-list/task-helpers.test.ts
  src/ui/server/helpers/task-list/task-helpers.ts
Labels: tech

#307 feat/fix(EMS-953-947): Company Details - Nature of your business - Employees Validation
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/nature-of-business/natureOfBusiness.js
  e2e-tests/cypress/fixtures/application.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.ts
  src/ui/server/helpers/whole-number-validation/index.ts
Labels: bug, feature

#308 feat(EMS-660): Company Details - Broker - Using a broker contact details
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/broker/broker.js
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/server/controllers/insurance/business/broker/validation/index.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-address-line-one.test.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-address-line-one.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-name.test.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-name.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-town.test.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-town.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/index.ts
  src/ui/templates/components/address-field-input.njk
  src/ui/templates/components/address-fields.njk
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/your-business/broker.njk
Labels: feature

#311 feat(EMS-871): Account sign in - password reveal
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/assert-password-reveal-button.js
  src/ui/server/content-strings/fields/insurance/account/index.ts
Labels: tech

#314 feat(EMS-670): Company Details - Broker - Email field
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/broker-email-validation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/broker/broker.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-email.test.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-email.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/index.ts
  src/ui/templates/components/address-field-input.njk
  src/ui/templates/insurance/your-business/broker.njk
Labels: feature

#313 chore(EMS-970): cypress command for checking core page elements and features
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/all-sections.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/apply-offline-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/account-to-apply-online/account-to-apply-online.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/cannot-apply-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/check-if-eligible.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/eligible-to-apply-online.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/letter-of-credit/letter-of-credit.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/need-to-start-again.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/page-not-found.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/speak-to-ukef-efm.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/start.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/turnover-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/page-not-found.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/need-to-start-again.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/cypress/e2e/pages/quote/yourQuote.js
  e2e-tests/cypress/e2e/pages/your-business/broker/broker.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/core-page-checks.js
  src/ui/templates/insurance/your-business/broker.njk
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/quote/your-quote.njk
Labels: tech

#310 feat(EMS-801): Account creation - verification
  database/exip.sql
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/cypress.config.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/create-account-and-verify-email/create-account-and-verify-email.spec.js
  e2e-tests/cypress/support/api/index.js
  src/api/.keystone/config.js
  src/api/README.md
  src/api/constants.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/verify-account-email-address.ts
  src/api/custom-schema.ts
  src/api/keystone.test.ts
  src/api/keystone.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/api/keystone/account/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.ts
  src/ui/server/graphql/mutations/account/verify-email-address.ts
  src/ui/server/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/templates/components/keystone/document/README.md
  src/ui/types/account.d.ts
  src/ui/types/express/index.d.ts
Labels: feature, tech

#315 fix(EMS-990): Company Details - Turnover - Allow negative turnover
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.test.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
  src/ui/server/helpers/whole-number-validation/index.test.ts
  src/ui/server/helpers/whole-number-validation/index.ts
Labels: bug

#318 feat(EMS-669): Company Details - Broker - Postcode Validation
  e2e-tests/constants/examples/index.js
  e2e-tests/constants/examples/postcode-examples.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/broker-email-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/broker-postcode-validation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/broker/broker.js
  src/api/.keystone/config.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-email.test.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-postcode.test.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-postcode.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/index.ts
  src/ui/server/shared-validation/postcode/index.test.ts
  src/ui/server/shared-validation/postcode/index.ts
Labels: feature

#319 feat(EMS-802): account verification - sign in page success banner
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/create-account-and-verify-email/create-account-and-verify-email.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/sign-in/signIn.js
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/templates/insurance/account/sign-in/sign-in.njk
Labels: enhancement, feature

#321 feat(EMS-870): account sign in - security code page setup
  e2e-tests/constants/field-ids/insurance/account/index.js
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/sign-in/enterCode.js
  e2e-tests/cypress/e2e/pages/insurance/account/sign-in/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/sign-in/signIn.js
  e2e-tests/cypress/e2e/partials/insurance/accountFormFields.js
  src/ui/server/constants/field-ids/insurance/account/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/sign-in/enter-code.njk
Labels: feature

#320 feat(EMS-815): Company Details - Broker - Save and go back and continue
  database/exip.sql
  e2e-tests/constants/examples/postcode-examples.js
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes.spec.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/check-value.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/complete-and-submit-broker-form.js
  src/api/.keystone/config.js
  src/api/helpers/mapCompaniesHouseFields.test.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/broker/validation/rules/broker-email.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/graphql/mutations/update-application/exporter-broker.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/shared-validation/postcode/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-broker.ts
  src/ui/server/test-mocks/mock-company.ts
  src/ui/templates/components/address-fields.njk
  src/ui/templates/insurance/your-business/broker.njk
  src/ui/types/application.ts
Labels: feature

#323 fix(EMS-1015): Account sign in - email/password validation
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/validation/account-sign-in-validation.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-sign-in-account-form.js
  src/ui/package-lock.json
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/email.test.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/email.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/password.test.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/password.ts
  src/ui/server/shared-validation/email-and-password/index.test.ts
  src/ui/server/shared-validation/email-and-password/index.ts
Labels: bug

#322 chore(tech): Address various todo comments
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-fields-multi-policy-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/switch-between-services/via-buyer-country-routes/complete-insurance-eligibility-then-get-a-quote.spec.js
  e2e-tests/cypress/e2e/journeys/switch-between-services/via-buyer-country-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  e2e-tests/cypress/e2e/journeys/switch-between-services/via-start-now-routes/complete-insurance-eligibility-then-get-a-quote.spec.js
  e2e-tests/cypress/e2e/journeys/switch-between-services/via-start-now-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/quote/submit-answers-happy-path-multiple-policy.js
  src/api/custom-schema.ts
  src/api/schema.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/company-details/helpers/companies-house-search.helper.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.ts
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/your-business/company-details.njk
Labels: tech

#325 fix(cookie): Docker image update + Cookie security
  e2e-tests/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/cypress/e2e/journeys/footer.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body-answer-yes.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-policy-type-multiple-times-via-back-button.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-fields-multi-policy-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  src/ui/Dockerfile
  src/ui/server/index.ts
  src/ui/server/middleware/headers/security.ts
Labels: tech, security

#328 feat(gha): Enhanced SCA GHA
  .github/workflows/publish.yml
  .github/workflows/sca.yml
  .github/workflows/scan_codacy_analysis.yml
Labels: enhancement, feature

#324 feat(EMS-870): Account sign in - API validation, OTP/security code generation
  database/exip.sql
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/create-account-and-verify-email/create-account-and-verify-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/resend-confirm-email/resend-confirm-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/account-sign-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code.spec.js
  e2e-tests/cypress/support/api/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/get-exporter-by-email.js
  e2e-tests/cypress/support/insurance/account/verify-account-email.js
  src/api/.env.sample
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/custom-resolvers/account-sign-in.test.ts
  src/api/custom-resolvers/account-sign-in.ts
  src/api/custom-resolvers/create-account.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/send-email-confirm-email-address.ts
  src/api/custom-resolvers/verify-account-email-address.ts
  src/api/custom-schema.ts
  src/api/emails/index.test.ts
  src/api/emails/index.ts
  src/api/helpers/generate-otp.test.ts
  src/api/helpers/generate-otp.ts
  src/api/helpers/get-account-by-field.ts
  src/api/helpers/is-valid-account-password.test.ts
  src/api/helpers/is-valid-account-password.ts
  src/api/integrations/notify/index.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/index.ts
  src/api/types.ts
  src/ui/server/api/keystone/account/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/graphql/mutations/account/create.ts
  src/ui/server/graphql/mutations/account/sign-in.ts
Labels: feature, tech, security

#329 fix(deployment-script): Code improvement
  .github/workflows/deploy.sh
Labels: enhancement

#330 feat(EMS-1046): Accessibility statement
  e2e-tests/constants/routes/index.js
  e2e-tests/content-strings/footer.js
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages.js
  e2e-tests/cypress/e2e/journeys/accessibility-statement.spec.js
  e2e-tests/cypress/e2e/pages/accessibility-statement.js
  e2e-tests/cypress/e2e/pages/index.js
  e2e-tests/cypress/e2e/partials/footer.js
  src/ui/server/constants/routes/index.ts
  src/ui/server/constants/templates/index.ts
  src/ui/server/content-strings/footer.ts
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages.ts
  src/ui/server/controllers/root/accessibility-statement/index.test.ts
  src/ui/server/controllers/root/accessibility-statement/index.ts
  src/ui/server/routes/root/index.test.ts
  src/ui/server/routes/root/index.ts
  src/ui/templates/accessibility-statement.njk
  src/ui/templates/partials/footer.njk
Labels: feature

#332 fix(EMS-1046): accessibility statement - add missing E2E test for footer link
  e2e-tests/cypress/e2e/journeys/footer.spec.js
Labels: tech

#335 chore(npm): NPM update
  generate-exip-pricing-grid/package-lock.json
  generate-exip-pricing-grid/package.json
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/generate-exip-pricing-grid/package-lock.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: tech

#334 feat(EMS-677): Company Details - Check your answers
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/content-strings/pages/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/cypress/e2e/pages/your-business/check-your-answers/checkYourAnswers.js
  e2e-tests/cypress/e2e/pages/your-business/index.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/insurance/assert-change-answers-page-url.js
  e2e-tests/cypress/support/insurance/check-your-business-summary-list.js
  e2e-tests/cypress/support/insurance/get-summary-list-field.js
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/constants/templates/insurance/business/index.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/helpers/summary-lists/your-business/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/map-sic-codes/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/map-sic-codes/index.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/insurance/your-business/check-your-answers.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/types/application.ts
  src/ui/types/index.d.ts
Labels: feature

#336 feat(EMS-678): Company Details - Check your answers - Nature of your business
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/cypress/e2e/pages/your-business/check-your-answers/checkYourAnswers.js
  e2e-tests/cypress/support/insurance/check-your-business-summary-list.js
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.test.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.ts
  src/ui/server/helpers/transform-number-to-string/index.test.ts
  src/ui/server/helpers/transform-number-to-string/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
Labels: feature

#337 feat(EMS-679): Company Details - Check your answers - Turnover
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/cypress/e2e/pages/your-business/check-your-answers/checkYourAnswers.js
  e2e-tests/cypress/support/insurance/check-your-business-summary-list.js
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/helpers/data-content-mappings/map-quote-to-content.test.ts
  src/ui/server/helpers/data-content-mappings/map-quote-to-content.ts
  src/ui/server/helpers/map-percentage/index.test.ts
  src/ui/server/helpers/map-percentage/index.ts
  src/ui/server/helpers/mappings/map-percentage-of-cover.test.ts
  src/ui/server/helpers/mappings/map-percentage-of-cover.ts
  src/ui/server/helpers/summary-lists/your-business/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/your-business/turnover.njk
Labels: feature

#339 feat(EMS-680): Company Details - Check your answers - Broker
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/cypress/e2e/pages/your-business/check-your-answers/checkYourAnswers.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/insurance/check-your-business-summary-list.js
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.ts
  src/ui/server/controllers/insurance/business/check-your-answers/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/save-and-back/index.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/is-field-false-or-zero/index.test.ts
  src/ui/server/helpers/is-field-false-or-zero/index.ts
  src/ui/server/helpers/summary-lists/your-business/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/broker-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/server/helpers/task-list/task-helpers.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/components/address-field-input.njk
  src/ui/templates/insurance/your-business/broker.njk
  src/ui/types/application.ts
Labels: feature

#342 fix(EMS-991): Your business - Turnover - Percentage Turnover allowed commas
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.test.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.ts
  src/ui/server/helpers/percentage-number-validation/index.test.ts
  src/ui/server/helpers/percentage-number-validation/index.ts
  src/ui/types/errors.ts
  src/ui/types/index.d.ts
Labels: bug

#344 feat(EMS-707): Your buyer - Company or organisation - Website
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/companyOrOrganisation.js
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/index.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/website.test.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/website.ts
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
Labels: feature

#343 feat(EMS-857): Account sign in - validation improvements
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/validation/account-sign-in-validation-unverified-account.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/validation/account-sign-in-validation.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/account-sign-in.test.ts
  src/api/custom-resolvers/account-sign-in.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/test-mocks/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
Labels: enhancement, feature

#345 feat(EMS-711-712): Your buyer - Company or organisation - First and Last Name
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/validation/company-or-organisation-validation-first-last-name.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/validation/company-or-organisation-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/companyOrOrganisation.js
  e2e-tests/cypress/fixtures/application.js
  src/api/custom-resolvers/add-and-get-OTP.test.ts
  src/api/custom-resolvers/send-email-confirm-email-address.test.ts
  src/api/helpers/generate-otp-and-update-account.test.ts
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/first-name.test.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/first-name.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/index.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/last-name.test.ts
  src/ui/server/controllers/insurance/your-buyer/validation/rules/last-name.ts
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
Labels: feature
