Repository UK-Export-Finance/exip, pull requests merged in 2023-09, with the labels that each got.

#919 chore(EMS-1814): Improve API test coverage, fix lint warnings & flaky tests
  src/api/.eslintignore
  src/api/custom-resolvers/mutations/account-password-reset/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.test.ts
  src/api/custom-resolvers/mutations/delete-an-account/index.test.ts
  src/api/custom-resolvers/mutations/delete-application-by-reference-number/index.test.ts
  src/api/custom-resolvers/mutations/delete-application-by-reference-number/index.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.test.ts
  src/api/custom-resolvers/mutations/submit-application/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.test.ts
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/helpers/create-authentication-entry/index.test.ts
  src/api/helpers/create-authentication-retry-entry/index.test.ts
  src/api/helpers/delete-authentication-retries/index.test.ts
  src/api/helpers/get-authentication-retries-by-account-id/index.test.ts
  src/api/helpers/should-block-account/index.test.ts
  src/api/helpers/update-application/index.test.ts
  src/api/integrations/companies-house/index.test.ts
  src/api/integrations/companies-house/index.ts
  src/api/integrations/industry-sector/index.test.ts
  src/api/integrations/industry-sector/index.ts
  src/api/integrations/notify/index.test.ts
  src/api/integrations/notify/index.ts
  src/api/jest.config.js
  src/api/package-lock.json
  src/api/package.json
  src/api/test-helpers/accounts.ts
  src/api/test-helpers/applications.ts
  src/api/test-helpers/auth-retries.ts
  src/api/tsconfig.json
  src/api/types.ts
Labels: tech, chore

#902 feat(EMS-1945): Dashboard - Redirect to application or dashboard
  e2e-tests/commands/insurance/account/complete-insurance-eligibility-sign-in-and-go-to-dashboard.js
  e2e-tests/commands/insurance/account/complete-sign-in-and-go-to-application.js
  e2e-tests/commands/insurance/account/complete-sign-in-and-otp.js
  e2e-tests/commands/shared-commands.js
  e2e-tests/insurance/cypress/e2e/journeys/account/account-creation-and-sign-in-with-eligibility-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/account-sign-in-create-code-dashboard-or-application-redirect.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-with-second-requested-sign-in-code.spec.js
  src/api/.keystone/config.js
  src/ui/server/api/keystone/applications/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
Labels: feature

#924 chore(EMS-1299): E2E tests - Common assertSummaryListRow command
  e2e-tests/commands/assert-summary-list-row-change-text.js
  e2e-tests/commands/assert-summary-list-row-key.js
  e2e-tests/commands/assert-summary-list-row.js
  e2e-tests/commands/insurance/check-policy-and-exports-summary-list.js
  e2e-tests/commands/insurance/check-your-answers-eligibility-summary-list.js
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/commands/shared-commands.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/account-sign-in-create-code-dashboard-or-application-redirect.spec.js
Labels: chore

#935 chore(deps): Update dependencies
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#914 fix(EMS-1952-53-56): Working with buyer, XLSX and declaration bug fixes
  database/exip.sql
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/working-with-buyer/working-with-buyer.spec.js
  e2e-tests/pages/insurance/your-buyer/workingWithBuyer.js
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/templates/insurance/your-buyer/working-with-buyer.njk
Labels: fix

#922 fix(EMS-1957): Type of policy - Specifically check the submitted type
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy-and-export/index.ts
  src/api/helpers/policy-type/index.test.ts
  src/api/helpers/policy-type/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.ts
  src/ui/server/controllers/quote/policy-type/index.test.ts
  src/ui/server/controllers/quote/policy-type/index.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.test.ts
  src/ui/server/controllers/quote/policy-type/validation/rules/policy-type.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/cost.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/credit-period.ts
  src/ui/server/generate-quote/index.ts
  src/ui/server/helpers/data-content-mappings/map-cost.ts
  src/ui/server/helpers/mappings/map-applications/map-insured-for.ts
  src/ui/server/helpers/policy-type/index.test.ts
  src/ui/server/helpers/policy-type/index.ts
  src/ui/server/helpers/required-fields/policy-and-exports/index.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.ts
  src/ui/server/helpers/summary-lists/policy-and-export/change-link/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/index.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.ts
  src/ui/server/helpers/update-submitted-data/quote/index.test.ts
  src/ui/server/helpers/update-submitted-data/quote/index.ts
  src/ui/server/middleware/required-data-provided/quote/index.ts
  src/ui/templates/quote/tell-us-about-your-policy.njk
Labels: bug, tech

#913 feat(EMS-1914-1915-1916): Dashboard table, application status updates
  e2e-tests/constants/application.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/account-creation-and-sign-in-with-eligibility-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/submit-an-application-single-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-application-submitted.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-multiple-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-only-my-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-populated-application.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard.spec.js
  e2e-tests/pages/insurance/dashboard/index.js
  src/api/.keystone/config.js
  src/api/constants/application/index.ts
  src/api/custom-resolvers/mutations/submit-application/index.test.ts
  src/api/custom-resolvers/mutations/submit-application/index.ts
  src/api/keystone.test.ts
  src/api/schema.ts
  src/ui/server/constants/application/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/application-submitted/index.test.ts
  src/ui/server/graphql/queries/applications.ts
  src/ui/server/helpers/application-is-complete/index.ts
  src/ui/server/helpers/can-submit-application/index.test.ts
  src/ui/server/helpers/can-submit-application/index.ts
  src/ui/server/helpers/mappings/map-applications/index.test.ts
  src/ui/server/helpers/mappings/map-applications/index.ts
  src/ui/server/helpers/mappings/map-applications/map-value.test.ts
  src/ui/server/helpers/mappings/map-applications/map-value.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/components/dashboard-table.njk
  src/ui/templates/components/status-tag.njk
Labels: enhancement, feature

#904 chore(deps): Update dependencies, simplify cypress config
  .github/workflows/test.yml
  README.md
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: tech, dependencies, chore

#946 chore(EMS-1969): Additional application fields, prevent submission if submissionCount is not 0
  database/exip.sql
  src/api/.keystone/config.js
  src/api/constants/application/index.ts
  src/api/custom-resolvers/mutations/submit-application/index.test.ts
  src/api/custom-resolvers/mutations/submit-application/index.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-mocks/mock-application.ts
  src/api/types.ts
  src/ui/server/constants/application/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/can-submit-application/index.test.ts
  src/ui/server/helpers/can-submit-application/index.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: tech, chore

#903 fix(keystone): Add --no-ui flags
  src/api/.keystone/config.js
  src/api/keystone.ts
  src/api/package.json
Labels: bug, tech, chore

#949 feat(EMS-1968): Policy and exports - About goods or services - copy update
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
Labels: enhancement

#950 chore(EMS-1965): Optimise "create application" API call
  e2e-tests/commands/api/index.js
  e2e-tests/commands/insurance/create-applications.js
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/constants/field-ids/shared-eligibility/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/create-an-application/index.test.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/create-a-buyer/index.test.ts
  src/api/helpers/create-a-buyer/index.ts
  src/api/helpers/create-an-eligibility/index.test.ts
  src/api/helpers/create-an-eligibility/index.ts
  src/api/jest.config.js
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.ts
  src/api/test-helpers/applications.ts
  src/api/test-helpers/buyers.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-mocks/index.ts
  src/api/types.ts
  src/ui/server/api/keystone/application/buyer.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/constants/field-ids/shared-eligibility/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
  src/ui/server/graphql/mutations/create-an-application.ts
  src/ui/server/graphql/mutations/create-application.ts
  src/ui/server/helpers/map-eligibility-answers/index.test.ts
  src/ui/server/helpers/map-eligibility-answers/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-eligibility.ts
Labels: enhancement, tech, chore

#961 chore(EMS-1966): Split up UI API calls
  src/ui/server/api/keystone/application/create.ts
  src/ui/server/api/keystone/application/declarations.ts
  src/ui/server/api/keystone/application/declarations/get-latest-anti-bribery.ts
  src/ui/server/api/keystone/application/declarations/get-latest-confirmation-and-acknowledgement.ts
  src/ui/server/api/keystone/application/declarations/get-latest-how-data-will-be-used.ts
  src/ui/server/api/keystone/application/declarations/index.ts
  src/ui/server/api/keystone/application/declarations/update.ts
  src/ui/server/api/keystone/application/get.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/api/keystone/application/submit.ts
  src/ui/server/api/keystone/application/update/broker.ts
  src/ui/server/api/keystone/application/update/business.ts
  src/ui/server/api/keystone/application/update/businessContact.ts
  src/ui/server/api/keystone/application/update/buyer.ts
  src/ui/server/api/keystone/application/update/company.ts
  src/ui/server/api/keystone/application/update/index.ts
  src/ui/server/api/keystone/application/update/policyAndExport.ts
  src/ui/server/api/keystone/application/update/sectionReview.ts
Labels: documentation, tech, chore

#964 feat(EMS-1979): Cypress optimisation
  .github/workflows/test.yml
  e2e-tests/insurance/cypress.config.js
  e2e-tests/quote/cypress.config.js
  e2e-tests/switch-between-services/cypress.config.js
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: tech

#984 fix(EMS-1159): Dashboard pagination - Fix issue where "total pages" count would not round up
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-16-applications.spec.js
  src/ui/server/helpers/pagination/get-total-pages/index.test.ts
  src/ui/server/helpers/pagination/get-total-pages/index.ts
Labels: bug

#1005 fix(cypress): GHA matrix test execution
  .github/workflows/test.yml
  e2e-tests/insurance/cypress.config.js
  e2e-tests/quote/cypress.config.js
  e2e-tests/switch-between-services/cypress.config.js
Labels: tech

#1019 fix(EMS-2001): Redirect to first dashboard page if the page number exceeds available pages
  e2e-tests/constants/index.js
  e2e-tests/constants/pagination.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-page-number-does-not-exist.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-page-number-not-a-number.spec.js
  src/ui/server/constants/index.ts
  src/ui/server/constants/pagination.ts
  src/ui/server/controllers/insurance/dashboard/index.test.ts
  src/ui/server/controllers/insurance/dashboard/index.ts
  src/ui/server/helpers/pagination/generate-pagination-items/index.test.ts
  src/ui/server/helpers/pagination/generate-pagination-items/index.ts
Labels: bug, documentation, tech

#1020 feat(EMS-1993): Policy and exports - Name on policy page
  e2e-tests/commands/insurance/complete-and-submit-name-on-policy-form.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/constants/routes/insurance/policy-and-export.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/pages/insurance/policy-and-exports/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/check-your-answers/check-your-answers-summary-list/summary-list-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/check-your-answers/check-your-answers-summary-list/summary-list-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/check-your-answers/check-your-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/complete-policy-and-exports-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/complete-policy-and-exports-as-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/name-on-policy/name-on-policy-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/support/commands.js
  e2e-tests/pages/shared/index.js
  e2e-tests/pages/shared/input.js
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/constants/routes/insurance/policy-and-export.ts
  src/ui/server/constants/templates/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/pages/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/validation/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/validation/index.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/validation/rules/name-on-policy.test.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/validation/rules/name-on-policy.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/validation/rules/position.test.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/validation/rules/position.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy-and-exports/index.test.ts
  src/ui/server/routes/insurance/policy-and-exports/index.ts
  src/ui/templates/insurance/policy-and-exports/name-on-policy.njk
Labels: feature

#1029 feat(docs): general documentation update
  .github/workflows/README.md
  CHANGELOG.md
  README.md
  generate-exip-pricing-grid/README.md
  src/api/README.md
  src/api/XLSX/README.md
  src/ui/README.md
  src/ui/server/helpers/task-list/README.md
  src/ui/templates/components/keystone/document/README.md
Labels: documentation

#1033 feat(git-attributes): added .gitattribute for EOL file handling
  .gitattributes
Labels: tech

#1034 fix(cypress): added CSP headers to cypress configuration
  e2e-tests/insurance/cypress.config.js
  e2e-tests/quote/cypress.config.js
  e2e-tests/switch-between-services/cypress.config.js
Labels: tech

#1038 fix(mulesoft): replaced all mulesoft references with APIM
  .github/workflows/README.md
  src/api/.keystone/config.js
  src/api/constants/external-apis.ts
  src/api/integrations/APIM/index.test.ts
  src/api/integrations/APIM/index.ts
  src/api/integrations/industry-sector/index.test.ts
  src/api/integrations/industry-sector/index.ts
Labels: tech

#1026 chore(EMS-2018): Enforce GQL operation name requirement
  e2e-tests/commands/api/index.js
  e2e-tests/commands/insurance/account/get-account-by-email.js
  e2e-tests/commands/insurance/account/verify-account-email.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email-go-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/account-password-reset-retry/account-password-reset-retry-maximum-retries.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/expired-link/account-password-reset-expired-link-send-new-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/expired-link/account-password-reset-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/reactivated/account-reactivated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-already-blocked/account-sign-in-already-blocked.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-retry/account-sign-in-retry-maximum-retries-with-invalid-credentials-suspends-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-with-a-reactivated-account/account-sign-in-with-a-reactivated-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/validation/account-sign-in-validation-unverified-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/account-suspended-reactivate-after-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/account-suspended.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/email-sent/account-suspended-email-sent.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/verify-email/account-suspended-verify-email.spec.js
  src/api/.keystone/config.js
  src/api/apollo-plugins/index.test.ts
  src/api/apollo-plugins/index.ts
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/ui/server/graphql/mutations/create-an-application.ts
  src/ui/server/graphql/mutations/submit-application.ts
  src/ui/server/graphql/mutations/update-application/broker.ts
  src/ui/server/graphql/mutations/update-application/business-contact.ts
  src/ui/server/graphql/mutations/update-application/business.ts
  src/ui/server/graphql/mutations/update-application/buyer.ts
  src/ui/server/graphql/mutations/update-application/company.ts
  src/ui/server/graphql/mutations/update-application/declaration.ts
  src/ui/server/graphql/mutations/update-application/export-contract.ts
  src/ui/server/graphql/mutations/update-application/policy.ts
  src/ui/server/graphql/mutations/update-application/section-review.ts
  src/ui/server/graphql/mutations/update-eligibility.ts
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/graphql/queries/applications.ts
  src/ui/server/graphql/queries/companies-house.ts
  src/ui/server/graphql/queries/countries-by-iso-code.ts
  src/ui/server/graphql/queries/countries.ts
  src/ui/server/graphql/queries/declarations/anti-bribery.ts
  src/ui/server/graphql/queries/declarations/confirmation-and-acknowledgement.ts
  src/ui/server/graphql/queries/declarations/how-data-will-be-used.ts
  src/ui/server/graphql/queries/page.ts
Labels: tech, security, chore

#1042 fix(EMS-806): Task list - remove link from eligibility task
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  e2e-tests/partials/insurance/taskList.js
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.ts
  src/ui/server/helpers/task-list/index.test.ts
  src/ui/server/helpers/task-list/index.ts
  src/ui/server/helpers/task-list/task-helpers.test.ts
  src/ui/server/helpers/task-list/task-helpers.ts
  src/ui/types/task-list.ts
Labels: bug, chore

#1051 fix(country-code): updated country code to SRB
  database/exip.sql
Labels: fix

#1056 bug(services): ports naming inconsistency
  .github/workflows/test.yml
  docker-compose.yml
  e2e-tests/commands/api/index.js
  e2e-tests/commands/insurance/account/verify-account-email.js
  e2e-tests/insurance/cypress.config.js
  e2e-tests/insurance/cypress/e2e/journeys/accessibility-statement-signed-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/expired-link/account-password-reset-expired-link-send-new-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/expired-link/account-password-reset-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-already-blocked/account-sign-in-already-blocked.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/account-suspended-reactivate-after-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/expired-link/account-suspended-expired-link.spec.js
  e2e-tests/quote/cypress.config.js
  e2e-tests/switch-between-services/cypress.config.js
  package-lock.json
  package.json
  src/api/Dockerfile
  src/api/README.md
  src/api/helpers/create-authentication-retry-entry/index.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/index.ts
Labels: bug, tech, chore

#1039 fix(EMS-2022-2024): Broker and declarations page - conditionally revealed content
  .cspell.json
  e2e-tests/commands/check-uk-goods-and-services-calculate-description.js
  e2e-tests/commands/check-uk-goods-and-services-description.js
  e2e-tests/commands/insurance/complete-and-submit-broker-form.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/request-new-code/account-sign-in-request-new-code.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/how-your-data-will-be-used.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/other-parties/other-parties.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-no-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/broker-email-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/broker-postcode-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/pages/insurance/account/sign-in/requestNewCode.js
  e2e-tests/pages/insurance/declarations/anti-bribery.js
  e2e-tests/pages/insurance/declarations/code-of-conduct.js
  e2e-tests/pages/insurance/eligibility/otherParties.js
  e2e-tests/pages/insurance/eligibility/preCreditPeriod.js
  e2e-tests/pages/quote/buyerBody.js
  e2e-tests/pages/shared/index.js
  e2e-tests/pages/your-business/broker/broker.js
  e2e-tests/pages/your-business/index.js
  e2e-tests/partials/ukGoodsAndServicesDescription.js
  e2e-tests/partials/ukGoodsOrServicesCalculateDescription.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/jsEnabled.js.map
  src/ui/scripts/cookies.js
  src/ui/scripts/js-enabled.js
  src/ui/server/constants/integrity.ts
  src/ui/server/middleware/integrity/index.test.ts
  src/ui/server/middleware/integrity/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/templates/index.njk
  src/ui/templates/insurance/declarations/anti-bribery/code-of-conduct.njk
  src/ui/templates/quote/buyer-body.njk
  src/ui/types/express/index.d.ts
  src/ui/webpack.common.config.js
Labels: bug, tech, chore

#1052 chore(EMS-2038): Split up API type definitions
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in-already-signed-in.spec.js
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/constants/application/index.ts
  src/api/constants/field-values/index.ts
  src/api/content-strings/XLSX.ts
  src/api/custom-resolvers/mutations/account-password-reset/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.ts
  src/api/custom-resolvers/mutations/add-and-get-OTP/index.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.test.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.ts
  src/api/custom-resolvers/mutations/update-company-and-company-address/index.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/custom-resolvers/queries/get-account-password-reset-token/index.ts
  src/api/custom-resolvers/queries/verify-account-password-reset-token/index.ts
  src/api/emails/application/index.test.ts
  src/api/emails/application/index.ts
  src/api/emails/index.ts
  src/api/package.json
  src/api/types.ts
  src/api/types/account/index.ts
  src/api/types/application-types/index.ts
  src/api/types/companies-house/index.ts
  src/api/types/company/index.ts
  src/api/types/country/index.ts
  src/api/types/currency/index.ts
  src/api/types/email/index.ts
  src/api/types/feedback/index.ts
  src/api/types/generic/index.ts
  src/api/types/index.ts
  src/api/types/relationship/index.ts
  src/api/types/test-helpers/index.ts
  src/api/types/xlsx-types/index.ts
Labels: tech, chore

#1077 chore(deps): bump deps
  e2e-tests/commands/insurance/create-an-application.js
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies

#1078 chore(EMS-2060-2061): Application submission - update XLSX and email mappings to use policyContact
  src/api/.keystone/config.js
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/emails/send-application-submitted-emails/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/is-owner-same-as-business-contact/index.test.ts
  src/api/helpers/is-owner-same-as-business-contact/index.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
Labels: documentation, tech, chore
