Repository UK-Export-Finance/exip, pull requests merged in 2023-10, with the labels that each got.

#1089 feat(EMS-2042): Name on policy, Different name on policy - Save and back
  e2e-tests/commands/insurance/complete-and-submit-different-name-on-policy-form.js
  e2e-tests/commands/insurance/complete-and-submit-name-on-policy-form.js
  e2e-tests/commands/insurance/complete-different-name-on-policy-form.js
  e2e-tests/commands/insurance/complete-name-on-policy-form.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/different-name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/support/commands.js
  src/ui/server/controllers/insurance/policy-and-export/different-name-on-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/different-name-on-policy/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/policy-contact/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/policy-contact/index.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/name-on-policy/save-and-back/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy-and-exports/index.test.ts
  src/ui/server/routes/insurance/policy-and-exports/index.ts
Labels: feature

#1090 fix(docker): downgraded dockerimage
  src/api/Dockerfile
  src/ui/Dockerfile
Labels: bug

#1091 fix(docker-file): added EXPOSE command
  src/api/Dockerfile
  src/ui/Dockerfile
Labels: fix

#1093 fix(ports): Added `PORT` and `WEBSITES_PORT` to IaC
  .github/workflows/infrastructure.yml
  docker-compose.yml
  src/api/Dockerfile
  src/ui/Dockerfile
Labels: fix

#1094 fix(tls-escape): added additional backslash escape
  .github/workflows/deployment.yml
  docker-compose.yml
  package-lock.json
  src/api/.env.sample
  src/api/Dockerfile
  src/api/keystone.ts
  src/api/package-lock.json
  src/ui/.env.sample
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/server/constants/tls.ts
  src/ui/server/helpers/sanitise-environment/index.test.ts
  src/ui/server/helpers/sanitise-environment/index.ts
  src/ui/server/middleware/https/index.test.ts
  src/ui/server/middleware/https/index.ts
Labels: fix

#1099 fix(EMS-2080): Account verification - token not sent via email
  e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email-once-and-sign-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email-twice-and-sign-in.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-password-reset/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.ts
  src/api/helpers/block-account/index.test.ts
  src/api/helpers/block-account/index.ts
  src/api/helpers/generate-otp-and-update-account/index.ts
  src/api/helpers/get-account-verification-hash/index.test.ts
  src/api/helpers/get-account-verification-hash/index.ts
  src/api/helpers/send-email-confirm-email-address/index.ts
  src/api/helpers/update-account/index.test.ts
  src/api/helpers/update-account/index.ts
  src/api/types/account/index.ts
Labels: bug, tech, chore

#1102 fix(cookies-security): local TLS server and trust proxy for Azure
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  package-lock.json
  src/api/keystone.ts
  src/api/package-lock.json
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/js/cookies.js.map
  src/ui/server/constants/environments.ts
  src/ui/server/constants/index.ts
  src/ui/server/helpers/http/index.test.ts
  src/ui/server/helpers/http/index.ts
  src/ui/server/helpers/https/index.test.ts
  src/ui/server/helpers/https/index.ts
  src/ui/server/helpers/is-production/index.test.ts
  src/ui/server/helpers/is-production/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/index.ts
Labels: documentation, enhancement, tech, security, dependencies

#1103 fix(release): release version manager
  .github/workflows/publish.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: fix

#1104 fix(EMS-2009): Application submission XLSX - fix missing final destination
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy-and-exports/index.ts
  src/api/generate-xlsx/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy-and-export/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy-and-export/index.ts
  src/api/generate-xlsx/styled-columns/index.test.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/generate-submitted-application.ts
  src/api/test-helpers/index.ts
  src/api/test-helpers/map-application-ids.ts
Labels: bug, fix

#1117 feat(EMS-2076): Policy and exports - Redirect to answer pages when changing policy type
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
Labels: enhancement, tech

#894 chore(docs): Spectaql config
  .cspell.json
  src/api/.gitignore
  src/api/Dockerfile
  src/api/README.md
  src/api/documentation/config.yml
  src/api/package-lock.json
  src/api/package.json
Labels: documentation, tech, chore

#1129 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1127 chore(EMS-2075-2078): Policy Contact: Fix mapping and all sections task status
  e2e-tests/commands/insurance/complete-and-submit-different-name-on-policy-form.js
  e2e-tests/commands/insurance/complete-different-name-on-policy-form.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-change-same-name-to-different-name-on-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/different-name-on-policy/changing-from-same-name-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/different-name-on-policy/entering-details-of-policy-owner.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/different-name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy-and-exports/name-on-policy/save-and-back.spec.js
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/policy-contact/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/policy-contact/index.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/has-policy-contact-changed/index.test.ts
  src/ui/server/helpers/is-policy-contact-data-same-as-owner/index.test.ts
  src/ui/server/helpers/is-policy-contact-data-same-as-owner/index.ts
  src/ui/server/helpers/required-fields/policy-and-exports/index.test.ts
  src/ui/server/helpers/required-fields/policy-and-exports/index.ts
  src/ui/server/helpers/string/index.test.ts
  src/ui/server/helpers/string/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/policy-contact-fields/index.ts
  src/ui/server/test-mocks/mock-contact.ts
Labels: chore, fix

#1139 chore(EMS-2080): Add temporary logs to debug account verification issue
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/helpers/get-account-by-field/index.ts
  src/api/helpers/update-account/index.ts
Labels: documentation, chore

#1140 fix(EMS-2083-2084-2089): Name on policy - Bug fixes
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  src/api/.keystone/config.js
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/name-on-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/name-on-policy/index.ts
Labels: fix

#1145 fix(EMS-2088): Application submission - XLSX mapping
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
Labels: bug

#1164 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/Dockerfile
  src/api/package-lock.json
  src/api/package.json
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1169 chore(EMS-2125-2126): API/GQL security improvements
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/apollo/format-graphql-error/index.test.ts
  src/api/apollo/format-graphql-error/index.ts
  src/api/apollo/index.ts
  src/api/apollo/plugins/index.test.ts
  src/api/apollo/plugins/index.ts
  src/api/keystone.ts
  src/api/middleware/headers/security/index.test.ts
  src/api/middleware/headers/security/index.ts
  src/api/package-lock.json
  src/api/package.json
Labels: tech, security, dependencies, chore

#1181 fix(headers): removed deprecated header block-all-mixed-content
  package-lock.json
  package.json
  src/api/middleware/headers/security/index.test.ts
  src/api/middleware/headers/security/index.ts
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/middleware/headers/security/index.test.ts
  src/ui/server/middleware/headers/security/index.ts
Labels: dependencies, fix

#1185 fix(EMS-2080): Account verification resolver returning success=false when already verified
  e2e-tests/commands/insurance/account/create-account.js
  e2e-tests/commands/insurance/account/verify-account-email.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-only-my-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/no-access-to-application/cannot-access-application-signed-in-check-your-answers.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/account/index.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/emails/confirm-email-address/index.test.ts
  src/api/emails/confirm-email-address/index.ts
  src/api/helpers/get-account-by-field/index.ts
  src/api/helpers/send-email-confirm-email-address/index.test.ts
  src/api/helpers/send-email-confirm-email-address/index.ts
  src/api/schema.graphql
  src/api/types/account/index.ts
  src/ui/server/api/keystone/account/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.ts
  src/ui/server/graphql/mutations/account/verify-email-address.ts
  src/ui/server/middleware/query-params/index.test.ts
  src/ui/server/middleware/query-params/index.ts
Labels: bug, tech, security

#1184 fix(dockerfile): Update base Dockerfile image
  package-lock.json
  src/api/Dockerfile
  src/api/package-lock.json
  src/api/package.json
  src/ui/Dockerfile
  src/ui/package-lock.json
Labels: dependencies

#1192 fix(dependencies): manually fixed dependencies versions
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies

#1214 chore(deps): Bump dependencies, update README
  README.md
  package-lock.json
  package.json
Labels: dependencies, chore
