Repository UK-Export-Finance/exip, pull requests merged in 2023-07, with the labels that each got.

#561 feat(apim): mulesoft to apim migration
  .env.sample
  .github/workflows/pr_tests.yml
  docker-compose.yml
  e2e-tests/cypress/e2e/journeys/accessibility-statement.spec.js
  e2e-tests/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/cypress/e2e/journeys/quote/cannot-obtain-cover-page.spec.js
  e2e-tests/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/company-based/company-based.spec.js
  e2e-tests/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/cypress/e2e/journeys/quote/need-to-start-again.spec.js
  e2e-tests/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  package-lock.json
  package.json
  src/ui/.env.sample
  src/ui/Dockerfile
  src/ui/init.sh
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/cookies.js
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/jsEnabled.js
  src/ui/public/js/main.js
  src/ui/server/api.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/helpers/mappings/map-countries.test.ts
  src/ui/server/helpers/mappings/map-countries.ts
  src/ui/sshd_config
  src/ui/types/cis-country.d.ts
Labels: enhancement, feature

#632 chore(deps): dependencies updates
  package-lock.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies

#598 feat(EMS-1789): Get a quote - update pricing grid
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  generate-exip-pricing-grid/README.md
  generate-exip-pricing-grid/index.js
  src/ui/server/generate-quote/pricing-grid.json
Labels: enhancement, tech

#631 chore(deps): dependencies updates
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/ui/README.md
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/submitButton.js
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/helpers/task-list/index.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/styles/accessible-autocomplete.min.scss
Labels: dependencies

#688 feat(EMS-1787-1802-1856): API security - Add x-api-key checks and rate limiter
  .env.sample
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  docker-compose.yml
  e2e-tests/cypress.config.js
  e2e-tests/cypress/support/api/index.js
  package-lock.json
  package.json
  src/api/.env.sample
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/keystone.ts
  src/api/middleware/headers/check-api-key/index.test.ts
  src/api/middleware/headers/check-api-key/index.ts
  src/api/middleware/rate-limiter/index.js
  src/api/middleware/rate-limiter/index.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/test-mocks/index.ts
  src/ui/.env.sample
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/graphql/apollo.ts
  src/ui/server/helpers/task-list/index.ts
  src/ui/server/middleware/insurance/get-application/index.ts
Labels: tech, security, dependencies
