Repository UK-Export-Finance/exip, pull requests merged in 2023-01, with the labels that each got.

#214 chore(EMS-786): update README
  README.md
  src/ui/server/controllers/insurance/policy-and-export/save-data/index.ts
Labels: documentation

#209 feat(EMS-505): All sections - render submission deadline and reference number
  e2e-tests/constants/application.js
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/field-values.js
  e2e-tests/constants/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/all-sections.spec.js
  e2e-tests/cypress/e2e/pages/insurance/allSections.js
  e2e-tests/cypress/e2e/pages/insurance/index.js
  src/ui/public/css/styles.css
  src/ui/server/constants/application.ts
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/field-values.ts
  src/ui/server/constants/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/helpers/date/format-date/index.test.ts
  src/ui/server/helpers/date/format-date/index.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/styles/styles.scss
  src/ui/templates/insurance/all-sections.njk
  src/ui/templates/insurance/your-business/company-details.njk
Labels: enhancement, tech

#210 feat(EMS-502): Policy and exports - Multiple contract policy page - initial setup
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/constants/routes/insurance/policy-and-export.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/pages/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/index.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/multipleContractPolicy.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/typeOfPolicy.js
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/constants/routes/insurance/policy-and-export.ts
  src/ui/server/constants/templates/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/pages/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/server/shared-validation/requested-start-date/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk
Labels: feature, tech

#215 chore(EMS-789): use FIELD_IDS for data-cy variables in the company details page
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/templates/insurance/your-business/company-details.njk
Labels: tech

#216 feat(EMS-572): Policy and exports - Multiple contract policy - months of cover field
  database/exip.sql
  e2e-tests/constants/application.js
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/multipleContractPolicy.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/complete-and-submit-multiple-contract-policy-form.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/application.ts
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/constants/field-values.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-months-of-cover.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-months-of-cover.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/data-content-mappings/map-answers-to-content.test.ts
  src/ui/server/helpers/data-content-mappings/map-answers-to-content.ts
  src/ui/server/helpers/data-content-mappings/map-month-string.test.ts
  src/ui/server/helpers/data-content-mappings/map-month-string.ts
  src/ui/server/helpers/data-content-mappings/map-policy-length.test.ts
  src/ui/server/helpers/data-content-mappings/map-policy-length.ts
  src/ui/server/helpers/mappings/map-total-months-of-insurance/index.test.ts
  src/ui/server/helpers/mappings/map-total-months-of-insurance/index.ts
  src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk
  src/ui/types/application.ts
Labels: enhancement, tech

#217 feat(EMS-573): Policy and exports - Multiple contract policy - total sales field
  database/exip.sql
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-sales-to-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/cypress/support/insurance/complete-and-submit-multiple-contract-policy-form.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/package-lock.json
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-sales-to-buyer.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/rules/total-sales-to-buyer.ts
  src/ui/server/graphql/queries/application.ts
Labels: enhancement

#223 feat(EMS-609): add countries graphql query
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/api/keystone/countries/index.ts
  src/ui/server/api/keystone/index.ts
  src/ui/server/graphql/queries/countries-by-iso-code.ts
  src/ui/server/graphql/queries/countries.ts
Labels: tech

#218 feat(EMS-682-634): Phone number validation
  e2e-tests/constants/examples/companies-house-number-examples.js
  e2e-tests/constants/examples/index.js
  e2e-tests/constants/examples/phone-number-examples.js
  e2e-tests/constants/examples/website-address-examples.js
  e2e-tests/constants/index.js
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-submit.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-company-website-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-invalid-phone-number-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-valid-phone-number-validation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/companies-house-search/companyDetails.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/constants/index.ts
  src/ui/server/constants/phone-number-countries.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/company-website.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/phone-number.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/phone-number.ts
  src/ui/server/shared-validation/phone-number/index.test.ts
  src/ui/server/shared-validation/phone-number/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-phone-numbers.ts
  src/ui/templates/insurance/your-business/company-details.njk
Labels: feature

#225 chore(types): Add ValidationErrors type to all functions that consume combineValidationRules
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house-response/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/companies-house/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/validation/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/index.ts
  src/ui/server/controllers/quote/policy-type/validation/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/index.ts
Labels: tech

#227 feat(EMS-608): Policy and exports - About goods or services - description field
  database/exip.sql
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation-description.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/aboutGoodsOrServices.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/complete-and-submit-about-goods-or-services-form.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/description.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/description.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/policy-and-exports/about-goods-or-services.njk
  src/ui/types/application.ts
Labels: enhancement

#230 feat(EMS-808): API/DB structure for exporter company
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  src/api/.keystone/config.js
  src/api/custom-schema.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/graphql/mutations/update-application/exporter-company.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/types/application.ts
Labels: feature

#233 chore(deps): bump json5
  package-lock.json
  src/ui/package-lock.json
Labels: security, dependencies

#231 feat(EMS-609): Improve country and currency mapping functions
  src/api/.keystone/config.js
  src/ui/server/api/keystone/countries/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/insurance/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/helpers/get-country-by-name/index.test.ts
  src/ui/server/helpers/mappings/map-cis-countries.test.ts
  src/ui/server/helpers/mappings/map-cis-countries.ts
  src/ui/server/helpers/mappings/map-countries-select.test.ts
  src/ui/server/helpers/mappings/map-countries-select.ts
  src/ui/server/helpers/mappings/map-countries.test.ts
  src/ui/server/helpers/mappings/map-countries.ts
  src/ui/server/helpers/mappings/map-currencies.test.ts
  src/ui/server/helpers/mappings/map-currencies.ts
  src/ui/server/helpers/mappings/map-select-option.test.ts
  src/ui/server/helpers/mappings/map-select-option.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/server/test-mocks/mock-currencies.ts
Labels: tech

#232 feat(EMS-609): Policy and export - About goods or services - final destination field
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation-description.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/aboutGoodsOrServices.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/fixtures/countries.js
  e2e-tests/cypress/support/insurance/complete-and-submit-about-goods-or-services-form.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/final-destination.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/final-destination.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/validation/rules/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/templates/insurance/policy-and-exports/about-goods-or-services.njk
  src/ui/types/application.ts
Labels: enhancement

#235 feat(EMS-607): Policy and export - update the task list to mark section completion
  e2e-tests/constants/field-ids/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/complete-policy-and-exports-as-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/complete-policy-and-exports-as-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-maximum-buyer-will-owe.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-policy-currency-code.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-total-sales-to-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-credit-period-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-policy-currency-code.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-total-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/complete-and-submit-policy-type-form.js
  src/ui/server/constants/field-ids/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
Labels: enhancement, feature

#236 feat(EMS-607): Policy and exports - callMapAndSave function
  src/ui/server/controllers/insurance/policy-and-export/call-map-and-save/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/call-map-and-save/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/validation/index.ts
Labels: tech

#237 feat(EMS-607): Policy and exports - about goods or services - save and go back
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/save-and-back/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
Labels: enhancement

#239 feat(EMS: 808): Company details - Save and go back
  database/exip.sql
  e2e-tests/constants/examples/phone-number-examples.js
  e2e-tests/cypress/e2e/journeys/insurance/all-sections.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-continue-no-errors.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-submit-errors.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-invalid-phone-number-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-valid-phone-number-validation.spec.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/navigate-to-url.js
  src/api/.keystone/config.js
  src/api/custom-schema.ts
  src/api/helpers/mapSicCodes.test.ts
  src/api/helpers/mapSicCodes.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.POST-save-and-back.test.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.API-ERROR.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/mocks/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/controllers/insurance/policy-and-export/save-data/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/save-data/index.ts
  src/ui/server/graphql/mutations/update-application/exporter-company.ts
  src/ui/server/helpers/get-data-to-save/index.test.ts
  src/ui/server/helpers/get-data-to-save/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/shared-validation/phone-number/index.test.ts
  src/ui/server/shared-validation/phone-number/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-company.ts
  src/ui/server/test-mocks/mock-phone-numbers.ts
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/types/application.ts
  src/ui/types/company-house-response.d.ts
Labels: feature, tech

#240 feat(EMS-612): Policy and exports - check your answers page
  e2e-tests/constants/routes/insurance/policy-and-export.js
  e2e-tests/content-strings/pages/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/complete-policy-and-exports-as-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/complete-policy-and-exports-as-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/type-of-policy/type-of-policy.spec.js
  src/ui/server/constants/routes/insurance/policy-and-export.ts
  src/ui/server/constants/templates/insurance/policy-and-exports/index.ts
  src/ui/server/content-strings/pages/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
  src/ui/server/helpers/summary-lists/get-key-text/index.test.ts
  src/ui/server/helpers/summary-lists/get-key-text/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/insurance/policy-and-exports/check-your-answers.njk
Labels: feature, tech

#241 feat(EMS-808): Your business - update API schema/DB to handle company SIC codes
  .github/workflows/scan_codeql_analysis.yml
  database/exip.sql
  src/api/.keystone/config.js
  src/api/custom-schema.ts
  src/api/helpers/mapSicCodes.test.ts
  src/api/helpers/mapSicCodes.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: enhancement, tech

#246 fix(EMS-795): Company Details - Companies house search heading and date
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  src/ui/server/content-strings/pages/insurance/your-business/exporter-business/index.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
Labels: bug

#242 chore(EMS-606): Improve summary list generation functions
  e2e-tests/content-strings/default.js
  e2e-tests/content-strings/index.js
  src/ui/server/content-strings/default.ts
  src/ui/server/content-strings/index.ts
  src/ui/server/helpers/data-content-mappings/map-answers-to-content.test.ts
  src/ui/server/helpers/data-content-mappings/map-answers-to-content.ts
  src/ui/server/helpers/data-content-mappings/map-cost.test.ts
  src/ui/server/helpers/data-content-mappings/map-cost.ts
  src/ui/server/helpers/data-content-mappings/map-policy-length.test.ts
  src/ui/server/helpers/data-content-mappings/map-policy-length.ts
  src/ui/server/helpers/data-content-mappings/map-quote-to-content.test.ts
  src/ui/server/helpers/data-content-mappings/map-quote-to-content.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.test.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.ts
  src/ui/server/helpers/summary-lists/generate-summary-list-rows/index.test.ts
  src/ui/server/helpers/summary-lists/generate-summary-list-rows/index.ts
  src/ui/server/helpers/summary-lists/get-key-text/index.test.ts
  src/ui/server/helpers/summary-lists/get-key-text/index.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.test.ts
  src/ui/server/helpers/summary-lists/quote-summary-list.ts
  src/ui/server/helpers/task-list/task-helpers.ts
  src/ui/types/answers.d.ts
  src/ui/types/company-details.d.ts
  src/ui/types/index.d.ts
  src/ui/types/quote.d.ts
  src/ui/types/summary-list.d.ts
Labels: tech

#247 chore(EMS-613): Your business - trading address & trading name as yes/no values
  database/exip.sql
  src/api/.keystone/config.js
  src/api/constants.ts
  src/api/custom-schema.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/your-business/company-details.njk
Labels: tech

#249 chore(deps): bump axios
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/api/external/index.ts
Labels: dependencies

#251 update README.md
  README.md
Labels: documentation

#243 feat(EMS-613-637): Company details - populate fields
  database/exip.sql
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-save-and-back.spec.js
  src/api/.keystone/config.js
  src/api/custom-schema.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/controllers/insurance/business/company-details/helpers/populate-companies-house-summary-list.test.ts
  src/ui/server/controllers/insurance/business/company-details/helpers/populate-companies-house-summary-list.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/mocks/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/mappings/map-sic-codes.test.ts
  src/ui/server/helpers/mappings/map-sic-codes.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-sic-codes.ts
  src/ui/types/application.ts
  src/ui/types/company-details.d.ts
  src/ui/types/index.d.ts
Labels: feature

#245 feat(EMS-637): Your business - Task list status change
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-continue-no-errors.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-save-and-back.spec.js
  e2e-tests/cypress/support/check-task-status.js
  e2e-tests/cypress/support/commands.js
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/server/helpers/task-list/task-helpers.test.ts
  src/ui/server/helpers/task-list/task-helpers.ts
  src/ui/types/application.ts
Labels: feature

#252 feat(EMS-605-606): Policy and exports - Check your answers - summary list
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/helpers/date.js
  e2e-tests/cypress/e2e/helpers/format-currency.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers-summary-list/summary-list-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers-summary-list/summary-list-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/checkYourAnswers.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/index.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/fixtures/currencies.js
  e2e-tests/cypress/support/insurance/check-policy-and-exports-summary-list.js
  src/api/schema.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/server/controllers/insurance/policy-and-export/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/helpers/format-currency/index.test.ts
  src/ui/server/helpers/format-currency/index.ts
  src/ui/server/helpers/get-country-by-iso-code/index.test.ts
  src/ui/server/helpers/get-country-by-iso-code/index.ts
  src/ui/server/helpers/get-field-by-id/index.test.ts
  src/ui/server/helpers/get-field-by-id/index.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.test.ts
  src/ui/server/helpers/summary-lists/answers-summary-list.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.test.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/about-goods-or-services-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/about-goods-or-services-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/policy-and-date-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/policy-and-date-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/templates/insurance/policy-and-exports/check-your-answers.njk
  src/ui/types/application.ts
  src/ui/types/index.d.ts
  src/ui/types/summary-list.d.ts
Labels: feature, tech

#253 feat(EMS-635): Nature of Business - Nature of Business page and goods and services field
  e2e-tests/constants/field-ids/insurance/exporter-business/index.js
  e2e-tests/constants/routes/insurance/exporter-business.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/exporter-business/index.js
  e2e-tests/content-strings/pages/insurance/exporter-business/index.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-continue-no-errors.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-company-website-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-valid-phone-number-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/cypress/e2e/pages/your-business/index.js
  e2e-tests/cypress/e2e/pages/your-business/nature-of-business/natureOfBusiness.js
  src/ui/server/constants/field-ids/insurance/exporter-business/index.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/constants/templates/insurance/business/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/goods-or-services.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/goods-or-services.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/about-goods-or-services-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/about-goods-or-services-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/policy-and-date-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/policy-and-date-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
Labels: feature

#254 fix(EMS-809): No companies house number - correct form link
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/apply-offline-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-no-companies-house-link.spec.js
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/apply-offline/index.test.ts
  src/ui/server/controllers/insurance/apply-offline/index.ts
  src/ui/templates/insurance/apply-offline.njk
Labels: bug

#256 fix(EMS-792-810): Policy end exports - pre-population issues
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-credit-period-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-credit-period-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk
  src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
Labels: bug

#257 chore(EMS-787): use constants instead of hard coded currency codes
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/helpers/format-currency.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/fixtures/currencies.js
  e2e-tests/cypress/support/quote/forms.js
  src/ui/server/constants/currencies.ts
  src/ui/server/constants/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/quote/check-your-answers/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/validation/rules/currency.test.ts
  src/ui/server/helpers/data-content-mappings/map-cost.test.ts
  src/ui/server/helpers/format-currency/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.ts
  src/ui/server/test-mocks/mock-answers.ts
  src/ui/server/test-mocks/mock-session.ts
Labels: tech

#259 feat(EMS-611-610): Policy and exports - Change answers via check your answers page
  e2e-tests/constants/routes/insurance/policy-and-export.js
  e2e-tests/content-strings/links.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/checkYourAnswers.js
  e2e-tests/cypress/support/assert-summary-list-row-value.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/assert-change-answers-page-url.js
  e2e-tests/cypress/support/insurance/check-policy-and-exports-summary-list.js
  src/ui/server/constants/routes/insurance/policy-and-export.ts
  src/ui/server/content-strings/links.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/type-of-policy/index.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.test.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.ts
  src/ui/server/helpers/summary-lists/generate-summary-list-rows/index.test.ts
  src/ui/server/helpers/summary-lists/generate-summary-list-rows/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/about-goods-or-services-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/about-goods-or-services-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/change-link/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/change-link/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/credit-period-and-currency-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/policy-and-date-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/policy-and-date-fields/index.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/templates/components/date-input.njk
  src/ui/templates/insurance/policy-and-exports/about-goods-or-services.njk
  src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk
  src/ui/types/summary-list.d.ts
Labels: enhancement, feature, tech

#262 fix(EMS-793): Policy and exports - fix string fields/inputs not saving as empty with save & back functionality
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/policy-and-export/map-submitted-data/index.ts
  src/ui/server/helpers/get-valid-fields/index.test.ts
  src/ui/server/helpers/get-valid-fields/index.ts
  src/ui/server/helpers/has-form-data/index.test.ts
  src/ui/server/helpers/has-form-data/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/string/index.test.ts
  src/ui/server/helpers/string/index.ts
Labels: bug, tech

#266 fix(EMS-837-875-855): Update submission deadline, fix policy and exports copy to match design
  e2e-tests/constants/application.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/check-your-answers/check-your-answers.spec.js
  src/api/.keystone/config.js
  src/api/constants.ts
  src/ui/server/constants/application.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/templates/insurance/policy-and-exports/check-your-answers.njk
Labels: bug

#264 fix(EMS-869): Policy and exports - add missing hint text to currency code fields
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-policy-currency-code.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-policy-currency-code.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/multipleContractPolicy.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/singleContractPolicy.js
  e2e-tests/cypress/e2e/partials/insurance/index.js
  e2e-tests/cypress/e2e/partials/insurance/policyCurrencyCodeFormField.js
  e2e-tests/cypress/support/insurance/check-policy-currency-code-input.js
  e2e-tests/cypress/support/insurance/complete-and-submit-multiple-contract-policy-form.js
  e2e-tests/cypress/support/insurance/complete-and-submit-single-contract-policy-form.js
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/templates/components/policy-currency-code-hint.njk
  src/ui/templates/insurance/policy-and-exports/multiple-contract-policy.njk
  src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
Labels: bug, tech

#268 fix(EMS-852): Order countries alphabetically
  src/ui/server/helpers/mappings/map-countries.test.ts
  src/ui/server/helpers/mappings/map-countries.ts
Labels: bug

#269 fix(EMS-884): Your business - Company Details - Fix website and phone number max lengths
  e2e-tests/constants/examples/phone-number-examples.js
  e2e-tests/constants/examples/website-address-examples.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-company-website-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/validation/company-details-invalid-phone-number-validation.spec.js
  src/ui/server/helpers/is-above-max-length/index.test.ts
  src/ui/server/helpers/is-above-max-length/index.ts
  src/ui/server/shared-validation/phone-number/index.test.ts
  src/ui/server/shared-validation/phone-number/index.ts
  src/ui/server/shared-validation/website-address/index.test.ts
  src/ui/server/shared-validation/website-address/index.ts
  src/ui/server/test-mocks/mock-phone-numbers.ts
Labels: bug

#270 fix(EMS-851): Explicit list of string number fields to allow submission/saving if submitted as a pure number
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
Labels: bug

#271 fix(EMS-867-EMS-877): Policy and exports - add invalid date format validation, fix typos in Your buyer address field
  e2e-tests/content-strings/error-messages.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/cypress/support/insurance/requested-start-date-field.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/controllers/insurance/policy-and-export/single-contract-policy/validation/rules/contract-completion-date.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/server/shared-validation/requested-start-date/index.ts
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
Labels: bug

#272 fix(EMS-898): Policy and exports - change from multiple to single policy type
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-single-contract-policy.spec.js
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.ts
Labels: bug

#274 fix(EMS-880-896): Company Details - Multiple sic codes fix & goods and services max count fix
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-continue-no-errors.spec.js
  e2e-tests/cypress/fixtures/application.js
  src/api/.keystone/config.js
  src/api/custom-schema.ts
  src/api/schema.graphql
  src/ui/server/controllers/insurance/business/map-and-save/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/helpers/get-sic-code-ids-from-application/index.test.ts
  src/ui/server/helpers/get-sic-code-ids-from-application/index.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
Labels: bug, enhancement

#275 fix(EMS-834-911): Policy and exports - update total contract value hint, update external links
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/cypress/e2e/pages/insurance/policy-and-export/singleContractPolicy.js
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
  src/ui/templates/insurance/policy-and-exports/single-contract-policy.njk
Labels: bug

#273 fix(EMS-874): Policy and exports - save fields that have had values removed/is empty
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/about-goods-or-services/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/multiple-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/single-contract-policy/save-and-back.spec.js
  e2e-tests/cypress/support/commands.js
  src/ui/server/controllers/insurance/business/map-and-save/index.test.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/helpers/get-valid-fields/index.test.ts
  src/ui/server/helpers/get-valid-fields/index.ts
  src/ui/server/helpers/strip-empty-form-fields/index.test.ts
  src/ui/server/helpers/strip-empty-form-fields/index.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.test.ts
  src/ui/server/helpers/summary-lists/company-house-summary-list.ts
Labels: bug, enhancement

#276 fix(EMS-913): Policy and exports - fix date issue when changing contract from multiple to single
  e2e-tests/cypress/e2e/journeys/insurance/policy-and-exports/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  src/ui/server/helpers/summary-lists/policy-and-export/multiple-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy-and-export/single-contract-policy-fields/index.ts
Labels: bug

#278 fix(EMS-911): policy and exports - update links to external proposal form
  e2e-tests/content-strings/fields/insurance/policy-and-exports/index.js
  src/ui/server/content-strings/fields/insurance/policy-and-exports/index.ts
Labels: bug

#277 feat(EMS-772-773-776): Eligibility - already have an account page/flow. Update required data middleware checks
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/already-have-account/already-have-account-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/already-have-account/already-have-account.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/eligible-to-apply-online.spec.js
  e2e-tests/cypress/e2e/pages/shared/index.js
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/routes/insurance/exporter-business.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/insurance/eligibility/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/controllers/insurance/eligibility/already-have-account/index.test.ts
  src/ui/server/controllers/insurance/eligibility/already-have-account/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/temp-create-account/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/temp-create-account/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.ts
  src/ui/server/middleware/insurance/get-application/index.test.ts
  src/ui/server/middleware/insurance/get-application/index.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/eligibility/already-have-account.njk
  src/ui/templates/insurance/eligibility/eligible-to-apply-online.njk
Labels: feature, tech

#280 feat(EMS-777-779): Accounts - creation - your details page setup, first/last name field validation
  e2e-tests/constants/field-ids/insurance/account/index.js
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/content-strings/fields/insurance/index.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/already-have-account/already-have-account-answer-no.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/already-have-account/already-have-account.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/create/yourDetails.js
  e2e-tests/cypress/e2e/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/pages/insurance/index.js
  e2e-tests/cypress/fixtures/account.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/submit-eligibility-and-start-account-creation.js
  src/ui/server/constants/field-ids/insurance/account/index.ts
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/constants/templates/insurance/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/first-name.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/first-name.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/last-name.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/last-name.ts
  src/ui/server/controllers/insurance/eligibility/already-have-account/index.test.ts
  src/ui/server/controllers/insurance/eligibility/already-have-account/index.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/shared-validation/empty-field/index.test.ts
  src/ui/server/shared-validation/empty-field/index.ts
  src/ui/templates/insurance/account/create/your-details.njk
Labels: feature

#281 chore(EMS-939): bump govuk-frontend, eslint-plugin import, notify packages
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies
