Repository UK-Export-Finance/exip, pull requests merged in 2023-06, with the labels that each got.

#511 feat/fix(EMS-1688): Account creation - create an application if eligibility answers are available
  e2e-tests/cypress/e2e/journeys/insurance/account/account-creation-and-sign-in-with-eligibility-answers.spec.js
  e2e-tests/cypress/support/insurance/account/complete-sign-in-and-go-to-application.js
  src/api/.keystone/config.js
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
  src/ui/server/helpers/can-create-an-application/index.test.ts
  src/ui/server/helpers/can-create-an-application/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-eligibility.ts
Labels: bug, enhancement, tech

#514 feat(deployment): refactored deployment script
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/development.yml
  .github/workflows/production.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: documentation, tech

#512 feat(EMS-1678): Your Buyer - Company or organisation - Change country to be text. Add buyer country during application creation
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/footer.js
  e2e-tests/cypress/e2e/journeys/footer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/save-and-back.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/validation/company-or-organisation-validation-can-contact-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/validation/company-or-organisation-validation-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/validation/company-or-organisation-validation-first-last-name.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/validation/company-or-organisation-validation-position.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/company-or-organisation/validation/company-or-organisation-validation.spec.js
  e2e-tests/cypress/e2e/pages/insurance/your-buyer/companyOrOrganisation.js
  e2e-tests/cypress/fixtures/application.js
  e2e-tests/cypress/support/check-footer-links.js
  e2e-tests/cypress/support/insurance/check-your-buyer-summary-list.js
  e2e-tests/cypress/support/insurance/your-buyer/complete-and-submit-company-or-organisation-form.js
  src/ui/server/api/keystone/application/buyer.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/country.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/country.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/index.ts
  src/ui/server/graphql/mutations/create-application.ts
  src/ui/server/helpers/mappings/map-applications/index.test.ts
  src/ui/server/helpers/required-fields/your-buyer/index.test.ts
  src/ui/server/helpers/required-fields/your-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.ts
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/types/application.ts
Labels: feature

#517 feat(infrastructure): Infrastructure refactorisation
  .github/workflows/infrastructure.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: tech

#515 fix(EMS-1693): Application submission - XLSX - dynamic section title row indexes
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/asubmit-an-application-multiple-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-single-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-all-required-fields.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-contact.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/cypress/support/insurance/complete-and-submit-broker-form.js
  e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-multiple.js
  e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-single.js
  e2e-tests/cypress/support/insurance/complete-sign-in-and-submit-an-application.js
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/constants/answers/index.ts
  src/api/constants/index.ts
  src/api/generate-xlsx/header-columns/index.test.ts
  src/api/generate-xlsx/header-columns/index.ts
  src/api/generate-xlsx/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy-and-export/index.ts
  src/api/generate-xlsx/styled-columns/index.test.ts
  src/api/generate-xlsx/styled-columns/index.ts
  src/api/helpers/policy-type/index.test.ts
  src/api/helpers/policy-type/index.ts
Labels: bug, tech

#522 feat(EMS-1710): Account sign in - update OTP expiry time
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code.test.ts
  src/api/helpers/generate-otp/index.test.ts
Labels: enhancement, tech, security

#524 fix(deploy): change base branch
  .github/workflows/deploy.sh
Labels: fix

#523 fix(EMS-1080): Your business - Company Details - Change your answers - SIC codes showing as blank
  e2e-tests/constants/examples/company-details-examples.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/update-company-and-company-address.ts
Labels: fix

#526 fix(EMS-1554): Page not found - Missing wording
  e2e-tests/content-strings/pages/index.js
  e2e-tests/cypress/e2e/journeys/insurance/page-not-found.spec.js
  e2e-tests/cypress/e2e/journeys/page-not-found.spec.js
  e2e-tests/cypress/support/check-page-not-found-page-text.js
  e2e-tests/cypress/support/commands.js
  src/ui/server/content-strings/pages/index.ts
  src/ui/templates/insurance/page-not-found.njk
  src/ui/templates/page-not-found.njk
Labels: fix

#527 feat(EMS-1696-1697): Reactivate an account
  e2e-tests/constants/field-ids/insurance/account/index.js
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/reactivated/account-reactivated.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/sign-in-retry/account-sign-in-retry-maximum-retries.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/sign-in-with-a-reactivated-account/account-sign-in-with-a-reactivated-account.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/account-suspended.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/email-sent/account-suspended-email-sent.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/link-expired/account-suspended-link-expired.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/verify-email/account-suspended-verify-email-invalid-token.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/verify-email/account-suspended-verify-email-no-token.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/verify-email/account-suspended-verify-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-has-not-traded-with-buyer-and-no-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/need-to-start-new-application/need-to-start-new-application-page.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/reactivated/index.js
  e2e-tests/cypress/support/api/index.js
  e2e-tests/cypress/support/commands.js
  e2e-tests/cypress/support/insurance/account/create-an-account-and-become-blocked.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/account/index.ts
  src/api/constants/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link.test.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/test-mocks/index.ts
  src/api/types.ts
  src/ui/README.md
  src/ui/server/api/keystone/account/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/reactivated/index.test.ts
  src/ui/server/controllers/insurance/account/reactivated/index.ts
  src/ui/server/controllers/insurance/account/suspended/link-expired/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/link-expired/index.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.ts
  src/ui/server/graphql/mutations/account/verify-account-reactivation-token.ts
  src/ui/server/middleware/insurance/application-access/index.test.ts
  src/ui/server/middleware/insurance/application-access/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/reactivated.njk
  src/ui/templates/insurance/account/suspended/link-expired.njk
Labels: feature, tech, dependencies

#529 fix(EMS-1723): Companies house search - APIM API error flag
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/update-company-and-company-address.ts
  src/api/custom-resolvers/queries/get-companies-house-information.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
Labels: fix

#530 fix(EMS-1714-1706): Missing back link, application submission XLSX time format
  e2e-tests/constants/date-format.js
  e2e-tests/cypress/e2e/helpers/date.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/email-sent/account-suspended-email-sent.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/all-sections.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-has-not-traded-with-buyer-and-no-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-multiple-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/need-to-start-new-application/need-to-start-new-application-page.spec.js
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/format-time-of-day/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/format-time-of-day/index.ts
  src/api/helpers/format-date/index.test.ts
  src/api/helpers/format-date/index.ts
  src/ui/server/constants/date-format.ts
  src/ui/server/helpers/date/format-date/index.test.ts
  src/ui/server/helpers/date/format-date/index.ts
  src/ui/templates/insurance/account/suspended/email-sent.njk
Labels: bug, tech

#531 feat(EMS-1700): Account - password reset - extend expiry date
  src/api/.keystone/config.js
  src/api/constants/index.test.ts
  src/api/constants/index.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.test.ts
  src/api/helpers/date/index.test.ts
  src/api/helpers/date/index.ts
  src/api/helpers/generate-otp/index.test.ts
Labels: enhancement, tech

#533 fix(EMS-512): Insurance - Start - Fix and add extra wording
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/cypress/e2e/journeys/insurance/start.spec.js
  e2e-tests/cypress/e2e/pages/insurance/start.js
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/templates/insurance/start.njk
Labels: feature, fix

#535 fix(EMS-1720): Quote - Tell us about your policy - Header
  e2e-tests/cypress/e2e/journeys/insurance/start.spec.js
  e2e-tests/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-signed-in.spec.js
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/types/pages/tell-us-about-your-policy.d.ts
Labels: fix

#534 feat(EMS-1689): Application submission - XLSX - add exporter contact details
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/application-submission/submit-an-application-single-policy-type-different-contact-details.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-and-exports-multiple-policy-type.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/change-your-answers/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/check-your-answers/policy-and-exports/summary-list/check-your-answers-policy-and-exports-multiple-summary-list.spec.js
  e2e-tests/cypress/support/insurance/complete-and-submit-your-contact-form.js
  e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-multiple.js
  e2e-tests/cypress/support/insurance/complete-prepare-your-application-section-single.js
  e2e-tests/cypress/support/insurance/complete-sign-in-and-submit-an-application.js
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/content-strings/XLSX.ts
  src/api/generate-xlsx/header-columns/index.test.ts
  src/api/generate-xlsx/header-columns/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.ts
  src/api/generate-xlsx/styled-columns/index.test.ts
  src/api/generate-xlsx/styled-columns/index.ts
  src/api/types.ts
Labels: documentation, enhancement, feature, tech

#536 fix(EMS-1729): Account - Sign in - Password as numbers only
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/password-as-number/sign-in-password-as-number.spec.js
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
Labels: fix

#537 fix(EMS-1701): Account suspension - fix issue where retries check would include irrelevant retries
  e2e-tests/constants/account.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-password-reset-form-maximum-retries.js
  e2e-tests/cypress/support/insurance/account/complete-and-submit-sign-in-account-form-maximum-retries.js
  src/api/.keystone/config.js
  src/api/constants/index.test.ts
  src/api/constants/index.ts
  src/api/custom-resolvers/mutations/account-sign-in.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link.ts
  src/api/helpers/date/index.test.ts
  src/api/helpers/date/index.ts
  src/api/helpers/should-block-account/index.test.ts
  src/api/helpers/should-block-account/index.ts
Labels: bug, tech

#541 chore(EMS-1721): API unit test helpers
  src/api/custom-resolvers/mutations/account-password-reset/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in-new-code/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.test.ts
  src/api/custom-resolvers/mutations/add-and-get-OTP/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/custom-resolvers/mutations/create-feedback/index.test.ts
  src/api/custom-resolvers/mutations/delete-an-account/index.test.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.test.ts
  src/api/custom-resolvers/mutations/send-email-insurance-feedback/index.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.test.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.test.ts
  src/api/custom-resolvers/mutations/submit-application/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.test.ts
  src/api/custom-resolvers/queries/get-account-password-reset-token/index.test.ts
  src/api/custom-resolvers/queries/verify-account-password-reset-token/index.test.ts
  src/api/helpers/account-has-used-password-before/index.test.ts
  src/api/helpers/block-account/index.test.ts
  src/api/helpers/create-authentication-entry/index.test.ts
  src/api/helpers/create-authentication-retry-entry/index.test.ts
  src/api/helpers/delete-authentication-retries/index.test.ts
  src/api/helpers/generate-otp-and-update-account/index.test.ts
  src/api/helpers/get-account-by-field/index.test.ts
  src/api/helpers/get-account-by-id/index.test.ts
  src/api/helpers/get-authentication-retries-by-account-id/index.test.ts
  src/api/helpers/get-country-by-field/index.test.ts
  src/api/helpers/send-email-confirm-email-address/index.test.ts
  src/api/helpers/should-block-account/index.test.ts
  src/api/keystone.test.ts
  src/api/test-helpers/accounts.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/get-keystone-context.ts
Labels: tech, chore

#545 feat(EMS-1742): Cookies saved page
  e2e-tests/constants/routes/index.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/cypress/e2e/journeys/insurance/cookies-saved-visit-directly-when-signed-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/cookies-saved.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/cookies.spec.js
  e2e-tests/cypress/e2e/journeys/quote/cookies-saved.spec.js
  e2e-tests/cypress/e2e/journeys/quote/cookies.spec.js
  e2e-tests/cypress/e2e/pages/cookies-saved.js
  e2e-tests/cypress/e2e/pages/cookies.js
  e2e-tests/cypress/e2e/pages/index.js
  src/ui/server/constants/routes/index.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/server/controllers/root/cookies/index.test.ts
  src/ui/server/controllers/root/cookies/index.ts
  src/ui/server/controllers/root/cookies/saved/index.test.ts
  src/ui/server/controllers/root/cookies/saved/index.ts
  src/ui/server/middleware/insurance/application-access/index.test.ts
  src/ui/server/middleware/insurance/application-access/index.ts
  src/ui/server/routes/root/index.test.ts
  src/ui/server/routes/root/index.ts
  src/ui/templates/cookies-saved.njk
  src/ui/templates/cookies.njk
  src/ui/types/express/index.d.ts
Labels: enhancement, feature

#546 feat(EMS-1739): Account suspended - invalid link page
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/invalid-link/account-suspended-invalid-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/link-expired/account-suspended-link-expired.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/verify-email/account-suspended-verify-email-invalid-token.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/cookies-saved-visit-directly-when-signed-in.spec.js
  e2e-tests/cypress/support/insurance/account/delete-account.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/types.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/templates/insurance/account/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/invalid-link/index.test.ts
  src/ui/server/controllers/insurance/account/invalid-link/index.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.ts
  src/ui/server/graphql/mutations/account/verify-account-reactivation-token.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/invalid-link.njk
Labels: enhancement, feature, tech

#547 feat(EMS-1738): Account suspension - Ability to reactivate account when token has expired
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/account-suspended-reactivate-after-link-expired.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/link-expired/account-suspended-link-expired.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/suspended/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/suspended/linkExpired.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/types.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/suspended/index.ts
  src/ui/server/controllers/insurance/account/suspended/link-expired/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/link-expired/index.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.ts
  src/ui/server/graphql/mutations/account/verify-account-reactivation-token.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/suspended/link-expired.njk
Labels: enhancement, feature

#548 fix(EMS-1345): Add requestedApplicationCreation to session when creating an application
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
  src/ui/server/helpers/can-create-an-application/index.test.ts
  src/ui/server/helpers/can-create-an-application/index.ts
  src/ui/types/express/index.d.ts
Labels: bug, documentation

#549 feat(EMS-1761): Account sign in - Enter code - Redirect if already signed in
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/new-password/validation/account-password-reset-new-password-valdation.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/enter-code/account-sign-in-enter-code-visit-directly-when-signed-in.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/sign-in/request-new-code/account-sign-in-request-new-code-visit-directly-when-signed-in.spec.js
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/controllers/insurance/account/sign-in/request-new-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/request-new-code/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/headers/security.ts
Labels: documentation, enhancement, feature

#551 fix(EMS-1771): Yes/no radio inputs aria labels
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/account-to-apply-online/account-to-apply-online.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/companies-house-number/companies-house-number.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/insured-amount/insured-amount.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/letter-of-credit/letter-of-credit.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/other-parties/other-parties.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/broker/broker-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-business/company-details/company-details-page.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/your-buyer/working-with-buyer/working-with-buyer.spec.js
  e2e-tests/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/cypress/support/check-aria-label.js
  e2e-tests/cypress/support/check-radio-input-no-aria-label.js
  e2e-tests/cypress/support/check-radio-input-yes-aria-label.js
  e2e-tests/cypress/support/commands.js
  src/ui/templates/components/yes-no-radio-buttons.njk
Labels: bug, tech

#552 feat(EMS-1746-1750): Account creation - verification - invalid link page
  e2e-tests/constants/field-ids/insurance/account/index.js
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-verification-link-expired.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/confirm-email/confirm-email-verification-link-invalid.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/create/create-account-and-verify-email/create-account-and-verify-email.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/invalid-link/account-suspended-invalid-link.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/link-expired/account-suspended-link-expired.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/suspended/verify-email/account-suspended-verify-email-invalid-token.spec.js
  e2e-tests/cypress/e2e/pages/insurance/account/index.js
  e2e-tests/cypress/e2e/pages/insurance/account/link-invalid/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/account/index.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/test-helpers/accounts.ts
  src/api/types.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.ts
  src/ui/server/controllers/insurance/account/suspended/verify-email/index.test.ts
  src/ui/server/graphql/mutations/account/verify-email-address.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature, tech

#553 fix(EMS-1345): UI application creation requests - immediately wipe eligibility answers from the session
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
  src/ui/server/helpers/can-create-an-application/index.test.ts
  src/ui/server/helpers/can-create-an-application/index.ts
  src/ui/types/express/index.d.ts
Labels: bug

#554 feat(EMS-1745): Account password reset - invalid link page/redirection
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/account-password-reset-link-invalid.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/account/password-reset/link-expired/account-password-reset-link-invalid.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/custom-resolvers/queries/verify-account-password-reset-token/index.test.ts
  src/api/custom-resolvers/queries/verify-account-password-reset-token/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/test-helpers/accounts.ts
  src/api/types.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.test.ts
  src/ui/server/controllers/insurance/account/password-reset/new-password/index.ts
  src/ui/server/graphql/queries/account/verify-account-password-reset-token.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature, tech

#543 chore(EMS-1030): Split map-and-save and save-data for business section
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.POST-save-and-back.test.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/contact/index.test.ts
  src/ui/server/controllers/insurance/business/contact/index.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/broker/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/broker/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/broker/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/contact/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/contact/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/contact/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/nature-of-business/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/turnover/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/turnover/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/save-data/broker/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/save-data/broker/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/broker/index.ts
  src/ui/server/controllers/insurance/business/save-data/business/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/save-data/business/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/business/index.ts
  src/ui/server/controllers/insurance/business/save-data/company-details/index.api-test.test.ts
  src/ui/server/controllers/insurance/business/save-data/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/company-details/index.ts
  src/ui/server/controllers/insurance/business/save-data/contact/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/save-data/contact/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/contact/index.ts
  src/ui/server/controllers/insurance/business/save-data/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/controllers/insurance/business/turnover/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/save-and-back/index.ts
Labels: chore

#558 chore(deps): bump deps
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#562 fix(EMS-1772): Insurance eligibility - update eligible to apply online logic
  e2e-tests/cypress/e2e/journeys/insurance/complete-eligibility-answers-for-a-second-time.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-create-a-new-application.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/dashboard/dashboard-get-a-quote.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/cannot-skip-flow/navigate-to-eligible-to-apply-online-page-directly.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/eligible-to-apply-online/eligible-to-apply-online-already-signed-in-with-eligibility-answers.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/eligible-to-apply-online/eligible-to-apply-online-already-signed-in-with-no-eligibility-answers.spec.js
  e2e-tests/cypress/e2e/journeys/insurance/eligibility/eligible-to-apply-online/eligible-to-apply-online-already-signed-in.spec.js
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
Labels: bug, documentation, enhancement, tech

#564 fix(EMS-1345): Add missing form IDs
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/insurance/your-buyer/working-with-buyer.njk
Labels: bug

#565 chore(EMS-1813): Fix various security and code smell issues reported by SonarCloud
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/public/js/cookies.js
  src/ui/public/js/cookies.js.map
  src/ui/scripts/accessible-autocomplete.js
  src/ui/scripts/cookies.js
  src/ui/server/controllers/quote/check-your-answers/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/helpers/string/index.ts
  src/ui/server/helpers/validation/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/middleware/required-data-provided/quote/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/styles/accessible-autocomplete.min.scss
Labels: tech, security, chore

#567 chore(EMS-1807-1808): Your Business - Construct payload
  src/ui/server/controllers/insurance/business/broker/index.test.ts
  src/ui/server/controllers/insurance/business/broker/index.ts
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/broker/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.POST-continue.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.POST-save-and-back.test.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/contact/index.test.ts
  src/ui/server/controllers/insurance/business/contact/index.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/contact/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/controllers/insurance/business/turnover/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/save-and-back/index.ts
  src/ui/server/helpers/construct-payload/index.test.ts
  src/ui/server/helpers/construct-payload/index.ts
  src/ui/server/test-mocks/mock-business-turnover.ts
Labels: chore
