Repository UK-Export-Finance/exip, pull requests merged in 2023-11, with the labels that each got.

#1242 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1223 feat(EMS-2082-2087): No PDF - 'Check if eligible' page updates
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-if-eligible.spec.js
  e2e-tests/pages/insurance/eligibility/checkIfEligible.js
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/templates/insurance/eligibility/check-if-eligible.njk
Labels: enhancement

#1229 feat(EMS-2111): No PDF - Eligibility - No Companies House Number exit page
  e2e-tests/commands/shared-commands/assertions/actions/index.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/actions.js
  e2e-tests/content-strings/index.js
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house-number/companies-house-number-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/no-companies-house-number/no-companies-house-number.spec.js
  e2e-tests/pages/insurance/eligibility/index.js
  e2e-tests/pages/insurance/eligibility/noCompaniesHouseNumber.js
  e2e-tests/pages/shared/actions.js
  e2e-tests/pages/shared/cannotApply.js
  e2e-tests/pages/shared/index.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/eligibility/index.ts
  src/ui/server/content-strings/actions.ts
  src/ui/server/content-strings/index.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-number/index.test.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-number/index.ts
  src/ui/server/controllers/insurance/eligibility/no-companies-house-number/index.test.ts
  src/ui/server/controllers/insurance/eligibility/no-companies-house-number/index.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/eligibility/no-companies-house-number.njk
Labels: enhancement, feature, tech

#1198 feat(EMS-1715-2194): IaC, update JWT expiry time
  .github/workflows/README.md
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.test.ts
  src/api/helpers/create-jwt/index.test.ts
  src/api/helpers/create-jwt/index.ts
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
Labels: documentation, enhancement, tech, dependencies

#1241 feat(EMS-2116): No PDF - Eligibility - Company details page
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/commands/insurance/create-an-application.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/fixtures/companies.js
  e2e-tests/fixtures/example.json
  e2e-tests/fixtures/sic-codes.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-invalid-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/account-suspended.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/suspended/expired-link/account-suspended-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies-saved.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-if-eligible.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house-search/companies-house-search-no-financial-year-end-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house-search/companies-house-search.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details-multiple-SIC-codes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details-no-SIC-code.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/eligible-to-apply-online/eligible-to-apply-online.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-financial-year-end.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/pages/cookies-saved.js
  e2e-tests/pages/insurance/account/create/verifyEmailLinkExpired.js
  e2e-tests/pages/insurance/account/invalid-link/index.js
  e2e-tests/pages/insurance/account/suspended/index.js
  e2e-tests/pages/insurance/account/suspended/linkExpired.js
  e2e-tests/pages/insurance/account/suspended/suspended.js
  e2e-tests/pages/insurance/eligibility/companyDetails.js
  e2e-tests/pages/insurance/eligibility/eligibleToApplyOnline.js
  e2e-tests/pages/insurance/eligibility/index.js
  e2e-tests/pages/shared/index.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cookies-saved.spec.js
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/company/index.ts
  src/ui/server/controllers/insurance/business/company-details/helpers/populate-companies-house-summary-list.test.ts
  src/ui/server/controllers/insurance/business/company-details/helpers/populate-companies-house-summary-list.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/eligibility/company-details/index.test.ts
  src/ui/server/controllers/insurance/eligibility/company-details/index.ts
  src/ui/server/helpers/mappings/map-sic-codes-and-industry-sectors/index.test.ts
  src/ui/server/helpers/mappings/map-sic-codes-and-industry-sectors/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-array-of-strings/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-array-of-strings/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-object/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-object/index.ts
  src/ui/server/helpers/summary-lists/companies-house/index.test.ts
  src/ui/server/helpers/summary-lists/companies-house/index.ts
  src/ui/server/helpers/summary-lists/your-business/map-sic-codes/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/map-sic-codes/index.ts
  src/ui/templates/insurance/eligibility/company-details.njk
  src/ui/templates/insurance/your-business/company-details.njk
Labels: documentation, enhancement, feature, tech

#1245 chore(EMS-2206): Replace wantCoverOverMaxAmount data saving with total contract value IDs
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/index.js
  e2e-tests/constants/total-contract-value.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/index.ts
  src/api/constants/index.ts
  src/api/constants/total-contract-value/index.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
  src/api/helpers/create-an-eligibility/index.test.ts
  src/api/helpers/create-an-eligibility/index.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/get-total-contract-value-by-field/index.test.ts
  src/api/helpers/get-total-contract-value-by-field/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/total-contract-value.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/index.ts
  src/ui/server/constants/total-contract-value.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/map-eligibility-answers/index.test.ts
  src/ui/server/helpers/map-eligibility-answers/index.ts
  src/ui/server/helpers/map-total-contract-value/index.test.ts
  src/ui/server/helpers/map-total-contract-value/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.test.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.ts
  src/ui/server/test-mocks/mock-eligibility.ts
Labels: tech, chore

#1247 feat(EMS-2197): Accessibility statement update
  e2e-tests/content-strings/pages/index.js
  e2e-tests/insurance/cypress/e2e/journeys/accessibility-statement.spec.js
  e2e-tests/pages/accessibility-statement.js
  e2e-tests/quote/cypress/e2e/journeys/quote/accessibility-statement.spec.js
  src/ui/server/content-strings/pages/index.ts
  src/ui/templates/accessibility-statement.njk
Labels: feature

#1246 fix(EMS-2207): GitHub Actions workflow cleanup
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  docker-compose.yml
  package-lock.json
  src/api/.env.sample
  src/api/package-lock.json
  src/ui/.env.sample
  src/ui/package-lock.json
Labels: bug, tech, dependencies

#1248 chore(EMS-2206): Replace wantCoverOverMaxPeriod data saving with cover period IDs
  database/exip.sql
  e2e-tests/constants/cover-period.js
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/index.js
  e2e-tests/constants/total-contract-value.js
  e2e-tests/fixtures/application.js
  src/api/.keystone/config.js
  src/api/constants/cover-period/index.ts
  src/api/constants/field-ids/insurance/index.ts
  src/api/constants/index.ts
  src/api/constants/total-contract-value/index.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
  src/api/helpers/create-an-eligibility/index.test.ts
  src/api/helpers/create-an-eligibility/index.ts
  src/api/helpers/get-cover-period-value-by-field/index.test.ts
  src/api/helpers/get-cover-period-value-by-field/index.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/get-total-contract-value-by-field/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/cover-period.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/cover-period.ts
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/index.ts
  src/ui/server/constants/total-contract-value.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/map-cover-period-id/index.test.ts
  src/ui/server/helpers/map-cover-period-id/index.ts
  src/ui/server/helpers/map-eligibility-answers/index.test.ts
  src/ui/server/helpers/map-eligibility-answers/index.ts
  src/ui/server/helpers/map-total-contract-value/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.test.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.ts
  src/ui/server/test-mocks/mock-eligibility.ts
Labels: tech, chore

#1249 fix(gha): target environment reference resolved
  .github/workflows/deployment.yml
Labels: fix

#1250 fix(gha): deployment script
  .github/workflows/deployment.yml
Labels: fix

#1251 fix(build): build fix
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: tech

#1253 fix(package): node version update
  generate-exip-pricing-grid/package-lock.json
  generate-exip-pricing-grid/package.json
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies

#1254 fix(alert-condition): condition updated to average 99 over 5 minutes
  .github/workflows/infrastructure.yml
Labels: fix

#1257 fix(EMS-2197): Accessibility statement copy
  e2e-tests/content-strings/pages/index.js
  src/ui/server/content-strings/pages/index.ts
Labels: bug

#1260 fix(EMS-2206): Application submission - XLSX eligibility yes/no answers
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/ui/server/helpers/map-cover-period-id/index.test.ts
  src/ui/server/helpers/map-cover-period-id/index.ts
  src/ui/server/helpers/map-total-contract-value/index.test.ts
  src/ui/server/helpers/map-total-contract-value/index.ts
Labels: bug

#1265 chore(deps): Bump express-rate-limit
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1267 chore(merge) `main` into `main-application-no-pdf`
  e2e-tests/insurance/cypress/fixtures/example.json
  package-lock.json
  src/ui/package-lock.json
Labels: chore

#1165 spike(EMS-1959): No PDF - Ordnance Survey API integration
  .cspell.json
  docker-compose.yml
  src/api/.env.sample
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.ts
  src/api/custom-resolvers/queries/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/is-valid-postcode/index.test.ts
  src/api/helpers/is-valid-postcode/index.ts
  src/api/helpers/map-address/index.test.ts
  src/api/helpers/map-address/index.ts
  src/api/helpers/map-and-filter-address/index.test.ts
  src/api/helpers/map-and-filter-address/index.ts
  src/api/helpers/remove-white-space/index.test.ts
  src/api/helpers/remove-white-space/index.ts
  src/api/integrations/ordnance-survey/index.test.ts
  src/api/integrations/ordnance-survey/index.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/schema.graphql
  src/api/test-mocks/mock-ordnance-survey-response.ts
  src/api/test-mocks/mock-os-address-input.ts
  src/api/test-mocks/mock-postcodes.ts
  src/api/types/address/index.ts
  src/api/types/companies-house/index.ts
  src/api/types/index.ts
  src/api/types/ordnance-survey/index.ts
  src/ui/server/api/keystone/get-ordnance-survey-address/index.ts
  src/ui/server/api/keystone/index.ts
  src/ui/server/graphql/queries/ordnance-survey-address.ts
Labels: feature, chore

#1307 feat(iac): database iac addition
  .cspell.json
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
Labels: enhancement

#1309 fix(deployment): deployment script
  .cspell.json
  .github/workflows/README.md
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
Labels: documentation, fix

#1306 feat(EMS-2217): Country autocomplete - visually hide list item text, update invalid CIS countries list
  src/api/.keystone/config.js
  src/api/constants/external-apis.ts
  src/api/helpers/map-CIS-countries/index.test.ts
  src/ui/public/css/styles.css
  src/ui/server/constants/invalid-CIS-countries.ts
  src/ui/styles/accessible-autocomplete.min.scss
Labels: enhancement, chore

#1312 chore(merge) `main` into `main-application-no-pdf`
  src/api/constants/external-apis.ts
  src/ui/server/constants/invalid-CIS-countries.ts
  src/ui/styles/accessible-autocomplete.min.scss
Labels: chore

#1313 fix(EMS-2236): Application - update credit period hint text
  e2e-tests/commands/insurance/check-credit-period-with-buyer-input.js
  e2e-tests/commands/insurance/check-policy-currency-code-input.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/partials/insurance/creditPeriodWithBuyerFormField.js
  e2e-tests/partials/insurance/index.js
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/templates/components/credit-period-with-buyer-hint.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
Labels: chore, fix

#1318 chore(merge) `main` into `main-application-no-pdf`
  CHANGELOG.md
  e2e-tests/commands/insurance/check-credit-period-with-buyer-input.js
  e2e-tests/commands/insurance/check-policy-currency-code-input.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/partials/insurance/creditPeriodWithBuyerFormField.js
  e2e-tests/partials/insurance/index.js
  package-lock.json
  package.json
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/templates/components/credit-period-with-buyer-hint.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
Labels: chore

#1304 feat(EMS-2141): No PDF - Your business - Credit control page/form/flow setup, alternative turnover currency link
  e2e-tests/commands/insurance/complete-and-submit-credit-control-form.js
  e2e-tests/commands/insurance/complete-and-submit-turnover-form.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/constants/field-ids/insurance/business/index.js
  e2e-tests/constants/routes/insurance/business.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/pages/insurance/business/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-all-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-no-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/broker-postcode-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/insurance/cypress/support/application/business/index.js
  e2e-tests/pages/your-business/turnover/index.js
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/constants/routes/insurance/business.ts
  src/ui/server/constants/templates/insurance/business/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/credit-control/index.test.ts
  src/ui/server/controllers/insurance/business/credit-control/index.ts
  src/ui/server/controllers/insurance/business/turnover/currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/currency/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/your-business/credit-control.njk
  src/ui/templates/insurance/your-business/turnover-currency.njk
  src/ui/templates/insurance/your-business/turnover.njk
Labels: feature

#1320 chore(release): Update commitlint version, API test mocks
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/test-mocks/mock-CIS-countries.ts
Labels: chore

#1330 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1329 feat(EMS-2100-2106-2261): No PDF - Eligibility - Exporter location and exit page content updates
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/content-strings/pages/quote.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  src/ui/server/content-strings/actions.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/controllers/insurance/eligibility/exporter-location/index.test.ts
  src/ui/server/controllers/insurance/eligibility/exporter-location/index.ts
  src/ui/templates/cannot-apply.njk
  src/ui/templates/shared-pages/exporter-location.njk
Labels: bug, enhancement

#1339 feat(EMS-2139): No PDF - Your business - Nature of business
  database/exip.sql
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-nature-of-your-business.js
  e2e-tests/constants/field-ids/insurance/business/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-years-exporting-validation.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/business/index.ts
  src/api/content-strings/XLSX.ts
  src/api/content-strings/fields/insurance/your-business/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/nature-of-business/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-international.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/index.ts
  src/ui/server/controllers/insurance/business/save-data/business/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/save-data/business/index.test.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/nature-of-your-business-fields/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-business-nature-of-business.ts
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/types/application.ts
  src/ui/types/business.d.ts
Labels: feature

#1344 fix(EMS-2270): No PDF - Do you have an account with us
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/eligible-to-apply-online/eligible-to-apply-online.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/have-an-account/have-an-account-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/have-an-account/have-an-account.spec.js
  src/api/constants/field-ids/insurance/index.ts
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/eligibility/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/controllers/insurance/eligibility/do-you-have-an-account/index.test.ts
  src/ui/server/controllers/insurance/eligibility/do-you-have-an-account/index.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.test.ts
  src/ui/server/controllers/insurance/eligibility/eligible-to-apply-online/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/templates/insurance/eligibility/have-an-account.njk
Labels: bug, chore

#1345 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1349 fix(EMS-2113): No PDF - Eligibility - inactive company exit page
  e2e-tests/content-strings/actions.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-not-active/company-not-active.spec.js
  src/ui/server/content-strings/actions.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/templates/insurance/eligibility/companies-house-exit.njk
Labels: bug

#1347 feat(EMS-2191): No PDF - Your business - Alternative trading address validation
  e2e-tests/commands/insurance/complete-and-submit-alternative-trading-address-form.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/index.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/index.ts
  src/ui/templates/insurance/your-business/alternative-trading-address.njk
Labels: feature

#1366 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1381 fix(EMS-2297-2298-2299): No PDF - Nature of your business - Bug fixes
  e2e-tests/commands/insurance/complete-and-submit-company-details.js
  e2e-tests/commands/insurance/complete-company-details-form.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-different-trading-name-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  src/api/.keystone/config.js
  src/api/schema.prisma
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.ts
Labels: bug, fix

#1383 fix(EMS-2309): No PDF - Nature of your business - Error messages
  e2e-tests/content-strings/error-messages.js
  src/ui/server/content-strings/error-messages.ts
Labels: fix

#1389 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1388 fix(EMS-2308): No PDF - Companies house summary list SIC codes
  e2e-tests/commands/insurance/assert-companies-house-summary-list.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  src/ui/server/constants/companies-house-number-examples.ts
  src/ui/server/constants/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-search/index.test.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-search/index.ts
  src/ui/server/helpers/companies-house-search/index.ts
  src/ui/server/helpers/mappings/map-companies-house-data/index.test.ts
  src/ui/server/helpers/mappings/map-companies-house-data/index.ts
  src/ui/server/helpers/mappings/map-sic-codes-and-industry-sectors/index.test.ts
  src/ui/server/helpers/mappings/map-sic-codes-and-industry-sectors/index.ts
  src/ui/server/helpers/summary-lists/companies-house/generate-sic-codes-value/application/index.test.ts
  src/ui/server/helpers/summary-lists/companies-house/generate-sic-codes-value/application/index.ts
  src/ui/server/helpers/summary-lists/companies-house/generate-sic-codes-value/eligibility/index.test.ts
  src/ui/server/helpers/summary-lists/companies-house/generate-sic-codes-value/eligibility/index.ts
  src/ui/server/helpers/summary-lists/companies-house/generate-sic-codes-value/index.test.ts
  src/ui/server/helpers/summary-lists/companies-house/generate-sic-codes-value/index.ts
  src/ui/server/helpers/summary-lists/companies-house/index.test.ts
  src/ui/server/helpers/summary-lists/companies-house/index.ts
  src/ui/server/helpers/summary-lists/your-business/map-sic-codes/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/map-sic-codes/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-companies-house-response.ts
  src/ui/server/test-mocks/mock-company.ts
  src/ui/server/test-mocks/mock-eligibility.ts
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/types/application.ts
  src/ui/types/company-details.d.ts
  src/ui/types/company-house-response.d.ts
  src/ui/types/company.d.ts
  src/ui/types/index.d.ts
  src/ui/types/sic-code.ts
  src/ui/types/submitted-data.d.ts
Labels: bug, documentation, tech, chore

#1367 chore(EMS-2119): No PDF - Country support - improve CIS mappings
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/schema.graphql
  src/api/test-mocks/mock-mapped-CIS-countries.ts
  src/api/types/country/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
  src/ui/server/helpers/mappings/map-submitted-eligibility-country/index.test.ts
  src/ui/server/helpers/mappings/map-submitted-eligibility-country/index.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/types/country.d.ts
Labels: documentation, tech, chore

#1393 feat(EMS-2119): No PDF - Extend country support for applications
  .cspell.json
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/commands/insurance/check-your-answers-eligibility-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-about-goods-or-services-form.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/fixtures/countries.js
  e2e-tests/insurance/cypress/e2e/journeys/apply-offline-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-multiple-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-single-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-country-only-apply-offline.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-country-only-get-a-quote-by-email.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  src/api/.keystone/config.js
  src/api/constants/external-apis.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-offline/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-offline/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/templates/shared-pages/buyer-country.njk
Labels: enhancement, feature, tech, chore

#1395 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1394 fix(EMS-2316-2318): No PDF - missing guidance text, PDF link
  e2e-tests/content-strings/pages/insurance/business/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/company/index.ts
  src/ui/templates/insurance/your-business/company-details.njk
Labels: bug

#1399 chore(prs): Create pull request template
  .github/pull_request_template.md
Labels: tech, chore

#1398 feat(EMS-2247-2248): No PDF - Business - Credit control data saving
  .github/workflows/test.yml
  database/exip.sql
  e2e-tests/commands/insurance/complete-and-submit-credit-control-form.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/constants/field-ids/insurance/business/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-all-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-no-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/broker-email-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/broker/validation/broker-postcode-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/mock-application.ts
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/credit-control/index.test.ts
  src/ui/server/controllers/insurance/business/credit-control/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/business/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/business/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/business/index.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/your-business/index.test.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/your-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/save-and-back/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/insurance/your-business/credit-control.njk
Labels: feature

#1401 fix(prs): Rename pull request template file
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, chore

#1403 chore(merge): Merge `main` into `main-application-no-pdf`
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  package-lock.json
  package.json
Labels: tech, chore

#1406 fix(prs): Pull request template emojis
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, chore

#1408 chore(merge): Merge `main` into `main-application-no-pdf`
  README.md
Labels: chore

#1418 feat(EMS-2248): No PDF - Your business - Credit control - Check & change answers
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/constants/routes/insurance/business.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/business/index.ts
  src/api/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/constants/routes/insurance/business.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/credit-control/index.test.ts
  src/ui/server/controllers/insurance/business/credit-control/index.ts
  src/ui/server/helpers/summary-lists/your-business/credit-control-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/credit-control-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: feature

#1420 fix(pull-request): updated pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#1426 chore(prTemplate): Simplify pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#1428 chore(merge): Merge `main` into `main-application-no-pdf`
  CHANGELOG.md
  package-lock.json
  package.json
Labels: chore

#1429 fix(EMS-2341): Quote page - update application link
  e2e-tests/content-strings/pages/quote.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  src/ui/server/content-strings/pages/quote.ts
Labels: fix

#1435 feat(EMS-2239-2240): No PDF - Eligibility - Added sectionReview population
  e2e-tests/commands/api/index.js
  e2e-tests/commands/insurance/create-an-application.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/create-an-application/index.test.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/create-a-section-review/index.test.ts
  src/api/helpers/create-a-section-review/index.ts
  src/api/keystone.test.ts
  src/api/nullable-checkbox/index.ts
  src/api/schema.graphql
  src/api/schema.ts
  src/api/test-helpers/applications.ts
  src/api/types/application-types/index.ts
  src/ui/server/api/keystone/application/create.ts
  src/ui/server/graphql/mutations/create-an-application.ts
  src/ui/server/helpers/map-eligibility-answers/index.test.ts
  src/ui/server/helpers/map-eligibility-answers/index.ts
  src/ui/types/submitted-data.d.ts
Labels: feature
