Repository UK-Export-Finance/exip, pull requests merged in 2024-12, with the labels that each got.

#3308 feat(EMS-3998): broker confirm address - enter manually link
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/pages/insurance/policy/brokerConfirmAddress.js
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts
  src/ui/templates/insurance/policy/broker-confirm-address.njk
Labels: enhancement

#3320 chore(EMS-4005): remove unnecessary expectedErrorsCount params
  e2e-tests/insurance/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-number/companies-house-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cover-period/cover-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/end-buyer/end-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/have-an-account/have-an-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/member-of-a-group/member-of-a-group.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/party-to-consortium/party-to-consortium.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/total-value-insured/total-value-insured.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/validation/pre-credit-period-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
Labels: tech, chore

#3298 chore(EMS-3983): dry heading caption cypress selectors
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/loss-payee-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/loss-payee-financial-details-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/partials/headingCaption.js
  e2e-tests/partials/index.js
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/templates/insurance/check-your-answers/check-your-answers.njk
  src/ui/templates/insurance/declarations/anti-bribery.njk
  src/ui/templates/insurance/declarations/confidentiality.njk
  src/ui/templates/insurance/eligibility/check-your-answers.njk
  src/ui/templates/insurance/export-contract/about-goods-or-services.njk
  src/ui/templates/insurance/export-contract/agent-charges.njk
  src/ui/templates/insurance/export-contract/agent-details.njk
  src/ui/templates/insurance/export-contract/agent-service.njk
  src/ui/templates/insurance/export-contract/check-your-answers.njk
  src/ui/templates/insurance/export-contract/declined-by-private-market.njk
  src/ui/templates/insurance/export-contract/how-much-the-agent-is-charging.njk
  src/ui/templates/insurance/export-contract/how-was-the-contract-awarded.njk
  src/ui/templates/insurance/export-contract/how-will-you-get-paid.njk
  src/ui/templates/insurance/policy/broker-confirm-address.njk
  src/ui/templates/insurance/policy/broker-details.njk
  src/ui/templates/insurance/policy/check-your-answers.njk
  src/ui/templates/insurance/policy/different-name-on-policy.njk
  src/ui/templates/insurance/policy/loss-payee-details.njk
  src/ui/templates/insurance/policy/loss-payee-financial-details-international.njk
  src/ui/templates/insurance/policy/loss-payee-financial-details-uk.njk
  src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/name-on-policy.njk
  src/ui/templates/insurance/policy/other-company-details.njk
  src/ui/templates/insurance/policy/single-contract-policy-total-contract-value.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
  src/ui/templates/insurance/policy/type-of-policy.njk
  src/ui/templates/insurance/your-business/alternative-trading-address.njk
  src/ui/templates/insurance/your-business/check-your-answers.njk
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/insurance/your-buyer/check-your-answers.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/insurance/your-buyer/outstanding-or-overdue-payments.njk
  src/ui/templates/insurance/your-buyer/trading-history.njk
  src/ui/templates/shared-pages/currency.njk
  src/ui/templates/shared-pages/declaration.njk
  src/ui/templates/shared-pages/single-radio.njk
  src/ui/types/page-variables.d.ts
Labels: tech, chore

#3307 feat(EMS-3975): broker manual address - initial page setup
  .github/workflows/test.yml
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-with-broker-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-with-broker-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/broker-manual-address-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-a-pure-number/submit-textarea-fields-with-a-pure-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-policy-textarea-fields-with-new-line-characters.spec.js
  e2e-tests/pages/insurance/policy/brokerManualAddress.js
  e2e-tests/pages/insurance/policy/index.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/fully-populated.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/minimal.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/api/content-strings/fields/insurance/policy/index.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/full-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/full-address/index.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.ts
  src/ui/server/controllers/insurance/policy/save-data/broker/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.test.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/server/shared-validation/date/index.test.ts
  src/ui/templates/insurance/policy/broker-manual-address.njk
Labels: feature, chore

#3309 feat(EMS-3978): broker manual address - form validation, redirect
  e2e-tests/commands/insurance/complete-and-submit-broker-manual-address-form.js
  e2e-tests/commands/insurance/complete-broker-manual-address-form.js
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/broker-manual-address-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/validation/broker-manual-address-validation.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  e2e-tests/pages/insurance/policy/index.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/validation/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/validation/index.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/validation/rules/full-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/validation/rules/full-address/index.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/validation/rules/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
Labels: enhancement, chore

#3321 feat(EMS-3973): broker details - redirects
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.ts
  src/ui/templates/insurance/policy/broker-manual-address.njk
Labels: enhancement, feature, chore

#3316 feat(EMS-3985-4004): broker addresses - dynamic intro, search again link
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses.spec.js
  e2e-tests/pages/insurance/policy/brokerAddresses.js
  e2e-tests/pages/insurance/policy/index.js
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/templates/insurance/policy/broker-addresses.njk
Labels: enhancement, feature

#3318 feat(EMS-3976): broker manual address - data saving
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/broker-manual-address-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-a-pure-number/submit-textarea-fields-with-a-pure-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-policy-textarea-fields-with-new-line-characters.spec.js
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.ts
Labels: enhancement, feature, chore

#3317 feat(EMS-3994): broker zero addresses - search again/manual entry links
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-page.spec.js
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.ts
  src/ui/templates/insurance/policy/broker-zero-addresses.njk
Labels: enhancement

#3345 chore(EMS-4019): account creation/sign in checks - dev environment
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/types/account/index.ts
  src/ui/server/shared-validation/date/index.test.ts
Labels: tech, chore, fix

#3348 chore(EMS-4020): merge main into main-broker-address-lookup
  .release-please-manifest.json
  CHANGELOG.md
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/pages/insurance/policy/typeOfPolicy.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/types/account/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
Labels: chore

#3251 chore(EMS-3539): improve xlsx styled column functions
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/INDEXES/APPLICATION_INFORMATION/index.test.ts
  src/api/constants/XLSX-CONFIG/INDEXES/APPLICATION_INFORMATION/index.ts
  src/api/constants/XLSX-CONFIG/INDEXES/index.ts
  src/api/generate-xlsx/styled-columns/index.test.ts
  src/api/generate-xlsx/styled-columns/index.ts
  src/api/generate-xlsx/styled-columns/is-title-row/index.test.ts
  src/api/generate-xlsx/styled-columns/is-title-row/index.ts
  src/api/generate-xlsx/styled-columns/modify-row-heights/index.test.ts
  src/api/generate-xlsx/styled-columns/modify-row-heights/index.ts
  src/api/generate-xlsx/styled-columns/modify-row-styles/index.test.ts
  src/api/generate-xlsx/styled-columns/modify-row-styles/index.ts
  src/api/test-mocks/create-mock-worksheet.ts
  src/api/test-mocks/mock-application.ts
  src/ui/server/shared-validation/date/index.test.ts
Labels: documentation, tech, chore

#3246 chore(EMS-3960): improve country mapping helper functions
  CHANGELOG.md
  generate-exip-pricing-grid/index.js
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-get-a-quote-by-email/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-get-a-quote-by-email/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-get-a-quote-online/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-get-a-quote-online/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/cannot-get-a-quote/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/cannot-get-a-quote/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-NBI-issue-available/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-esra-classification/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-esra-classification/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-short-term-cover-available/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-insurance-support/index.ts
  src/api/schema.graphql
  src/api/types/country/index.ts
  src/api/types/helpers/index.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-high-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-standard-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-multi-policy-very-high-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-single-policy-high-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-single-policy-standard-risk.test.ts
  src/ui/server/generate-quote/get-premium-rate/get-premium-rate-single-policy-very-high.test.ts
  src/ui/server/generate-quote/get-premium-rate/index.test.ts
  src/ui/server/generate-quote/get-premium-rate/index.ts
  src/ui/server/generate-quote/index.test.ts
  src/ui/server/generate-quote/index.ts
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
  src/ui/server/helpers/mappings/map-submitted-eligibility-country/index.test.ts
  src/ui/server/helpers/mappings/map-submitted-eligibility-country/index.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/types/country.d.ts
Labels: tech, chore

#3324 feat(EMS-4006): broker addresses - data saving
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  docker-compose.yml
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-page.spec.js
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-ordnance-survey-address/index.test.ts
  src/api/helpers/map-ordnance-survey-address/index.ts
  src/api/schema.graphql
  src/api/types/address/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
  src/ui/server/graphql/queries/ordnance-survey-address.ts
  src/ui/server/helpers/mappings/map-ordnance-survey-addresses/index.test.ts
  src/ui/server/helpers/mappings/map-ordnance-survey-addresses/index.ts
  src/ui/server/helpers/mappings/map-ordnance-survey-addresses/is-checked/index.test.ts
  src/ui/server/helpers/mappings/map-ordnance-survey-addresses/is-checked/index.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/types/application.ts
  src/ui/types/ordnance-survey.d.ts
Labels: enhancement, feature, chore

#3349 style(EMS-3986): broker addresses - enter address manually link
  e2e-tests/commands/shared-commands/assertions/assert-enter-address-manually-link.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/pages/insurance/policy/brokerConfirmAddress.js
  e2e-tests/partials/insurance/enterAddressManuallyLink.js
  e2e-tests/partials/insurance/index.js
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/templates/insurance/policy/broker-addresses.njk
  src/ui/templates/insurance/policy/broker-confirm-address.njk
  src/ui/templates/partials/insurance/enter-address-manually-link.njk
Labels: enhancement, tech

#3350 chore(EMS-4031): test dependabot changes
  .github/dependabot.yml
Labels: dependencies, chore

#3311 chore(EMS-4001): merge main into main-iterations-2
  .github/dependabot.yml
  .release-please-manifest.json
  CHANGELOG.md
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/pages/insurance/policy/typeOfPolicy.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/types/account/index.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
Labels: chore

#3370 chore(EMS-4031): revert package.json and add ignores to dependabot.yml
  .github/dependabot.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: chore

#3380 chore(EMS-4031): add ignores to dependabot.yml
  .github/dependabot.yml
Labels: chore

#3388 chore(EMS-4031): add ignores to dependabot.yml
  .github/dependabot.yml
Labels: chore

#3398 chore(EMS-4031): add ignores to dependabot.yml
  .github/dependabot.yml
Labels: chore

#3372 feat(EMS-3993): multiple contract policy - small export builder content
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/links.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js
  e2e-tests/pages/insurance/policy/multipleContractPolicyExportValue.js
  src/api/.keystone/config.js
  src/api/constants/application/versions/index.ts
  src/api/content-strings/fields/insurance/policy/index.ts
  src/api/content-strings/links.ts
  src/ui/server/constants/application/versions/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/links.ts
  src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk
  src/ui/types/application.ts
Labels: documentation, enhancement, tech, chore

#3291 chore(EMS-3969): align test descriptions
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-search/companies-house-search.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/agent.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/declined-by-private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-much-the-agent-is-charging/validation/how-much-the-agent-is-charging-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-was-the-contract-awarded/how-was-the-contract-awarded-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-was-the-contract-awarded/how-was-the-contract-awarded.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/different-name-on-policy-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/name-on-policy-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-company-website-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-different-trading-name-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-invalid-phone-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-name-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-years-exporting-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-financial-year-end.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/validation/connection-with-the-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/validation/credit-insurance-cover-validation.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/prefix.js
  e2e-tests/shared-test-assertions/percentage-field-validation/index.js
  src/api/custom-resolvers/mutations/create-feedback/index.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-international/index.test.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-uk/index.test.ts
  src/api/custom-resolvers/queries/get-companies-house-information/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.test.ts
  src/api/helpers/get-APIM-CIS-countries/index.test.ts
  src/api/helpers/get-APIM-currencies/index.test.ts
  src/api/helpers/update-inactive-applications/index.test.ts
  src/api/helpers/update-unverified-accounts/index.test.ts
  src/api/integrations/companies-house/index.ts
  src/api/integrations/ordnance-survey/index.ts
  src/ui/server/controllers/insurance/check-your-answers/export-contract/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/shared-validation/phone-number/index.test.ts
Labels: documentation, chore

#3405 chore(EMS-4031): reverts timing changes to dependabot.yml
  .github/dependabot.yml
Labels: chore

#3406 feat(EMS-4034): declarations - modern slavery - data model/creation
  database/exip.sql
  src/api/.keystone/config.js
  src/api/constants/declarations/index.test.ts
  src/api/constants/declarations/index.ts
  src/api/constants/declarations/modern-slavery-versions/index.test.ts
  src/api/constants/declarations/modern-slavery-versions/index.ts
  src/api/constants/declarations/versions/index.test.ts
  src/api/constants/declarations/versions/index.ts
  src/api/helpers/create-a-declaration-modern-slavery-version/index.test.ts
  src/api/helpers/create-a-declaration-modern-slavery-version/index.ts
  src/api/helpers/create-a-declaration-modern-slavery/index.test.ts
  src/api/helpers/create-a-declaration-modern-slavery/index.ts
  src/api/helpers/create-a-declaration-version/index.test.ts
  src/api/helpers/create-a-declaration/index.test.ts
  src/api/helpers/create-a-declaration/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/declarations-modern-slavery.ts
  src/api/test-helpers/declarations.ts
  src/api/types/application-types/index.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/submit-application.ts
Labels: feature, tech, chore

#3409 feat(EMS-4038): declarations - modern slavery - conditional reasons
  e2e-tests/constants/field-ids/insurance/declarations/index.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/fields/insurance/declarations/index.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/declarations/index.ts
  src/api/constants/validation.ts
  src/api/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/constants/field-ids/insurance/declarations/index.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.ts
  src/ui/templates/insurance/declarations/modern-slavery.njk
  src/ui/templates/partials/insurance/code-of-conduct-hint.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/conditional-reasons/aware-of-existing-slavery.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/conditional-reasons/cannot-adhere-to-all-requirements.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/conditional-reasons/offenses-or-investigations.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/has-no-offenses-or-investigations.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/is-not-aware-of-existing-slavery.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/will-adhere-to-all-requirements.njk
Labels: enhancement, feature

#3410 feat(EMS-4024): declarations - modern slavery - form validation
  e2e-tests/commands/insurance/declarations/complete-and-submit-anti-bribery-code-of-conduct-form.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-anti-bribery-exporting-with-code-of-conduct-form.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-anti-bribery-form.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-confidentiality-form.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-confirmation-and-acknowledgements-form.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-modern-slavery-form.js
  e2e-tests/commands/insurance/declarations/complete-modern-slavery-form-conditional-fields.js
  e2e-tests/commands/insurance/declarations/complete-modern-slavery-form.js
  e2e-tests/commands/shared-commands/form/submit-and-assert-radio-errors.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-all-radios-as-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-empty-form.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-has-no-offenses-or-investigations.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-is-not-aware-of-existing-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-will-adhere-to-all-requirements.spec.js
  e2e-tests/insurance/cypress/support/declarations/index.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/conditional-reasons/aware-of-existing-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/conditional-reasons/aware-of-existing-slavery/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/conditional-reasons/cannot-adhere-to-all-requirements/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/conditional-reasons/cannot-adhere-to-all-requirements/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/conditional-reasons/offenses-or-investigations/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/conditional-reasons/offenses-or-investigations/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/has-no-offenses-or-investigations/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/has-no-offenses-or-investigations/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/is-not-aware-of-existing-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/is-not-aware-of-existing-slavery/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/will-adhere-to-all-requirements/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/validation/rules/will-adhere-to-all-requirements/index.ts
  src/ui/server/routes/insurance/declarations/index.test.ts
  src/ui/server/routes/insurance/declarations/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/partials/insurance/declarations/modern-slavery/has-no-offenses-or-investigations.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/is-not-aware-of-existing-slavery.njk
  src/ui/templates/partials/insurance/declarations/modern-slavery/will-adhere-to-all-requirements.njk
Labels: documentation, enhancement, feature, tech, chore

#3411 feat(EMS-4034): declarations - modern slavery - update data model
  database/exip.sql
  src/api/.keystone/config.js
  src/api/helpers/create-a-declaration-modern-slavery/index.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
Labels: feature, chore

#3417 chore(EMS-4066): application eligibility - rename exit page
  .github/workflows/test.yml
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-no-short-term-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/talk-to-an-export-finance-manager/talk-to-an-export-finance-manager.spec.js
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/country-redirects.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/insurance/eligibility/talk-to-an-export-finance-manager/index.test.ts
  src/ui/server/controllers/insurance/eligibility/talk-to-an-export-finance-manager/index.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/templates/insurance/eligibility/talk-to-an-export-finance-manager.njk
Labels: tech, chore

#3419 feat(EMS-4065): country risk logic - application - no support
  e2e-tests/constants/api.js
  e2e-tests/constants/external-apis.js
  e2e-tests/fixtures/countries.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply/cannot-apply-page.spec.js
  src/api/.keystone/config.js
  src/api/constants/external-apis.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/has-valid-short-term-cover/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/has-valid-short-term-cover/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-quote-offline/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-quote-offline/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/esra-classification-is-standard-high-or-very-high/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/esra-classification-is-standard-high-or-very-high/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-short-term-cover-available/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-short-term-cover-available/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-insurance-support/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-insurance-support/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/a-and-b-rating-conditions/index-rating-a.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/a-and-b-rating-conditions/index-rating-b.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/a-and-b-rating-conditions/index-rating-c-and-d.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/a-and-b-rating-conditions/index-rating-none.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/a-and-b-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/c-and-d-rating-conditions/index-rating-a-and-b.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/c-and-d-rating-conditions/index-rating-c.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/c-and-d-rating-conditions/index-rating-d.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/c-and-d-rating-conditions/index-rating-none.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/c-and-d-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-insurance-support/index.ts
  src/api/types/country/index.ts
  src/api/types/helpers/index.ts
Labels: enhancement, feature, tech, chore

#3429 chore(EMS-4031): change dependabot npm schedule to monthly
  .github/dependabot.yml
Labels: chore

#3422 feat(EMS-4074): country risk logic - cannot get a quote
  e2e-tests/fixtures/countries.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  src/api/.keystone/config.js
  src/api/helpers/map-CIS-countries/map-CIS-country/cannot-get-a-quote/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/cannot-get-a-quote/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-support/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-support/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/country-redirects.test.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
Labels: enhancement, feature, tech, chore

#3423 chore(EMS-4075): country risk logic - remove canGetAQuoteOffline flag
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-quote-offline/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-quote-offline/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/schema.graphql
  src/api/test-mocks/mock-mapped-CIS-countries.ts
  src/api/types/country/index.ts
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/types/country.d.ts
Labels: tech, chore

#3342 chore(deps): bump dependencies
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/Dockerfile
  src/api/package-lock.json
  src/api/package.json
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#3424 feat(EMS-4073): country risk logic - remove canGetAQuoteByEmail flag
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-get-a-quote-by-email/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-get-a-quote-by-email/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/a-and-b-rating-conditions/index-rating-a.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/a-and-b-rating-conditions/index-rating-b.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/a-and-b-rating-conditions/index-rating-c-and-d.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/a-and-b-rating-conditions/index-rating-none.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/a-and-b-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/c-and-d-rating-conditions/index-rating-a-and-b.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/c-and-d-rating-conditions/index-rating-c.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/c-and-d-rating-conditions/index-rating-d.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/c-and-d-rating-conditions/index-rating-none.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/c-and-d-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-online-support/index.ts
  src/api/schema.graphql
  src/api/test-mocks/mock-mapped-CIS-countries.ts
  src/api/types/country/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/country-redirects.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/types/country.d.ts
Labels: enhancement, feature, tech, chore

#3433 chore(EMS-4076-4077): improve buyer country unit tests
  src/ui/server/controllers/insurance/eligibility/buyer-country/country-redirects.test.ts
  src/ui/server/controllers/quote/buyer-country/country-redirects.test.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/types/country.d.ts
Labels: tech, chore

#3436 chore(EMS-4079): country risk logic - simplify/improve mapping function
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index-rating-a.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index-rating-b.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index-rating-c-and-d.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index-rating-none.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index-rating-a-and-b.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index-rating-c.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index-rating-d.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index-rating-none.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-support/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-support/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-NBI-issue-available/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-NBI-issue-available/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-short-term-cover-available/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-short-term-cover-available/index.ts
  src/api/schema.graphql
  src/api/types/country/index.ts
  src/api/types/helpers/index.ts
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
  src/ui/types/country.d.ts
Labels: tech, chore

#3418 feat(EMS-4046): declarations - modern slavery - save and back
  e2e-tests/commands/insurance/declarations/complete-and-submit-modern-slavery-form-conditional-fields.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-modern-slavery-form.js
  e2e-tests/commands/insurance/declarations/complete-modern-slavery-form-conditional-fields.js
  e2e-tests/commands/insurance/declarations/complete-modern-slavery-form.js
  e2e-tests/constants/routes/insurance/declarations.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-has-no-offenses-or-investigations.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-is-not-aware-of-existing-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-will-adhere-to-all-requirements.spec.js
  e2e-tests/insurance/cypress/support/declarations/index.js
  src/ui/server/constants/routes/insurance/declarations.ts
  src/ui/server/controllers/insurance/business/save-data/business/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/save-data/company-different-trading-address/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/save-data/index.test.ts
  src/ui/server/controllers/insurance/declarations/map-and-save/modern-slavery/index.api-error.test.ts
  src/ui/server/controllers/insurance/declarations/map-and-save/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/map-and-save/modern-slavery/index.ts
  src/ui/server/controllers/insurance/declarations/map-submitted-data/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/map-submitted-data/modern-slavery/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/save-and-back/index.ts
  src/ui/server/controllers/insurance/declarations/save-data/modern-slavery/index.api-error.test.ts
  src/ui/server/controllers/insurance/declarations/save-data/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/save-data/modern-slavery/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/private-market/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/jointly-insured-party/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/loss-payee-financial-details-international/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/loss-payee-financial-details-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/policy-contact/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-relationship/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer/index.test.ts
  src/ui/server/routes/insurance/declarations/index.test.ts
  src/ui/server/routes/insurance/declarations/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature, tech

#3435 chore(EMS-4067-4070): country risk logic - e2e improvements
  e2e-tests/commands/insurance/complete-about-goods-or-services-form.js
  e2e-tests/commands/shared-commands/eligibility/complete-and-submit-buyer-country-form.js
  e2e-tests/fixtures/application.js
  e2e-tests/fixtures/countries.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-no-online-support.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-no-short-term-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-countries.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-country-only-get-a-quote-offline.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
Labels: tech, chore

#3420 feat(EMS-4041): declarations - modern slavery - user flow updates
  e2e-tests/commands/insurance/complete-declarations.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-declarations-forms.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-has-no-offenses-or-investigations.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-is-not-aware-of-existing-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-will-adhere-to-all-requirements.spec.js
  e2e-tests/insurance/cypress/support/application/declarations/index.js
  e2e-tests/insurance/cypress/support/application/index.js
  e2e-tests/insurance/cypress/support/commands.js
  e2e-tests/insurance/cypress/support/declarations/index.js
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/index.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/modern-slavery/index.ts
Labels: enhancement, feature, chore

#3437 feat(EMS-4059): task list - declarations - modern slavery
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/save-and-back.spec.js
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/helpers/application-is-complete/index.test.ts
  src/ui/server/helpers/application-is-complete/index.ts
  src/ui/server/helpers/can-submit-application/index.ts
  src/ui/server/helpers/required-fields/declarations/index.test.ts
  src/ui/server/helpers/required-fields/declarations/index.ts
  src/ui/server/helpers/required-fields/index.test.ts
  src/ui/server/helpers/required-fields/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/submit-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/submit-application.ts
  src/ui/server/helpers/task-list/index.test.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
Labels: enhancement, feature, tech, chore

#3438 feat(EMS-4060): declarations - modern slavery - change answers
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/save-and-back.spec.js
  src/ui/server/controllers/insurance/declarations/map-submitted-data/modern-slavery/index.test.ts
  src/ui/server/controllers/insurance/declarations/map-submitted-data/modern-slavery/index.ts
Labels: enhancement, feature, chore
