Repository UK-Export-Finance/exip, pull requests merged in 2024-05, with the labels that each got.

#2351 chore(EMS-3113): No PDF - Replace MOJ password reveal with GOV.UK component. Bump dependencies
  e2e-tests/commands/insurance/account/assert-password-reveal-button.js
  e2e-tests/partials/insurance/passwordField.js
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/scripts/moj-frontend.js
  src/ui/server/constants/integrity.ts
  src/ui/server/middleware/integrity/index.test.ts
  src/ui/server/middleware/integrity/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/styles/styles.scss
  src/ui/templates/components/password-input.njk
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/password-reset/new-password.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
  src/ui/types/express/index.d.ts
  src/ui/webpack.common.config.js
Labels: tech, dependencies, chore

#2371 fix(mysql): fixed mysql8.4 image start up
  .github/workflows/test.yml
  docker-compose.yml
  src/api/.env.sample
Labels: fix

#2340 style(EMS-3172): No PDF - Update/align various error messages
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/validation/pre-credit-period-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-registration-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/validation/connection-to-the-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/validation/credit-insurance-cover-validation.spec.js
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/goods-or-services.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/goods-or-services.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/improve-service.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/credit-period-with-buyer-description.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/credit-period-with-buyer-description.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/registration-number.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/registration-number.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/validation/rules/connection-with-buyer-description.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/validation/rules/connection-with-buyer-description.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/rules/credit-insurance-cover-description.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/rules/credit-insurance-cover-description.ts
Labels: enhancement, tech, chore

#2353 style(EMS-3262): No PDF - Eligibility - Total value insured - Content update
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
Labels: enhancement

#2362 fix(EMS-3191): No PDF - Export contract - Agent details - Validation - Submitted country
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
Labels: bug, fix

#2361 fix(EMS-2980): No PDF - Policy - Using broker - Change from "yes" to "no"
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy-contact/index.ts
  src/ui/server/controllers/insurance/policy/save-data/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/broker/index.ts
Labels: bug, fix

#2359 feat(EMS-2772): No PDF - Task list - "Insurance policy" - Loss payee - Financial details UK
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-form.js
  e2e-tests/commands/insurance/complete-loss-payee-financial-details-uk-form.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/loss-payee-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/validation/bic-swift-code-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/validation/financial-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/validation/iban-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/loss-payee-financial-details-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/validation/account-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/validation/financial-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/validation/sort-code-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-policy-loss-payee-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-policy-loss-payee-financial-textarea-fields-with-new-line-characters.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/required-fields/policy/index.test.ts
  src/ui/server/helpers/required-fields/policy/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/server/test-mocks/mock-nominated-loss-payee.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
  src/ui/types/task-list.ts
Labels: documentation, enhancement, tech, chore

#2372 chore(tests): DRY jest spys
  src/api/custom-resolvers/mutations/create-feedback/index.test.ts
  src/api/test-mocks/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/business/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/business/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-different-trading-address/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-different-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/turnover/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/turnover/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-business/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.test.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/jointly-insured-party/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee-financial-details-international/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee-financial-details-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy-contact/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy-contact/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer-relationship/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer/index.test.ts
  src/ui/server/helpers/get-application-by-reference-number/index.test.ts
  src/ui/server/helpers/get-application/index.test.ts
  src/ui/server/test-mocks/index.ts
Labels: tech, chore

#2350 feat(EMS-1175): No PDF - CRON jobs - Inactive application helper
  e2e-tests/constants/application.js
  src/api/.keystone/config.js
  src/api/constants/application/index.ts
  src/api/constants/index.ts
  src/api/helpers/date/index.test.ts
  src/api/helpers/date/index.ts
  src/api/helpers/get-inactive-applications/index.test.ts
  src/api/helpers/get-inactive-applications/index.ts
  src/api/helpers/map-and-update-inactive-applications/index.test.ts
  src/api/helpers/map-and-update-inactive-applications/index.ts
  src/api/helpers/map-inactive-applications/index.test.ts
  src/api/helpers/map-inactive-applications/index.ts
  src/api/helpers/update-inactive-applications/index.test.ts
  src/api/helpers/update-inactive-applications/index.ts
  src/api/test-helpers/applications.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/create-multiple-full-applications.ts
  src/api/test-helpers/index.ts
  src/api/types/cron/index.ts
  src/api/types/index.ts
  src/ui/server/constants/application/index.ts
Labels: feature

#2379 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2363 chore(EMS-3302): No PDF - Account - Split Account table into Account and AccountStatus
  .github/workflows/test.yml
  database/exip.sql
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/custom-resolvers/mutations/account-password-reset/index.test.ts
  src/api/custom-resolvers/mutations/account-password-reset/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/custom-resolvers/mutations/create-an-application/index.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.ts
  src/api/helpers/block-account/index.test.ts
  src/api/helpers/block-account/index.ts
  src/api/helpers/get-account-by-field/index.test.ts
  src/api/helpers/get-account-by-field/index.ts
  src/api/helpers/get-authentication-retries-by-account-id/index.test.ts
  src/api/helpers/update-account/index.test.ts
  src/api/helpers/update-account/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/account-status.ts
  src/api/test-helpers/accounts.ts
  src/api/test-mocks/index.ts
  src/api/types/account/index.ts
  src/api/types/test-helpers/index.ts
Labels: chore

#2384 feat(EMS-2880): Policy - Change your answers - Loss payee, financial details UK
  .github/workflows/test.yml
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-yes-to-no.spec.js
  src/ui/server/controllers/insurance/business/map-and-save/business/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-different-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/turnover/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.test.ts
  src/ui/server/controllers/insurance/policy/call-map-and-save/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/jointly-insured-party/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee-financial-details-international/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee-financial-details-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/nominated-loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy-contact/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer-relationship/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer/index.test.ts
  src/ui/server/helpers/nullify-loss-payee-financial-uk-data/index.test.ts
  src/ui/server/helpers/nullify-loss-payee-financial-uk-data/index.ts
  src/ui/server/helpers/should-nullify-agent-service-charge-data/index.ts
  src/ui/server/helpers/should-nullify-loss-payee-financial-uk-data/index.test.ts
  src/ui/server/helpers/should-nullify-loss-payee-financial-uk-data/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.test.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: documentation, enhancement, feature, tech, chore

#2389 fix(EMS-3312-3327): No PDF - Broker name validation, minor content updates/fixes
  database/exip.sql
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
Labels: bug, chore, fix

#2390 chore(merge): No PDF - Merge `main` into `main-application-no-pdf`
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
  .release-please-manifest.json
  CHANGELOG.md
  e2e-tests/commands/analytics/check-analytics-cookies-consent-and-accept.js
  e2e-tests/commands/analytics/check-cookies-consent-banner-is-visible.js
  e2e-tests/commands/core-page-checks.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies-consent/cookies-consent.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent.spec.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/content-strings/XLSX.ts
  src/api/content-strings/fields/insurance/declarations/index.ts
  src/api/content-strings/fields/insurance/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-agreed-field/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-agreed-field/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-yes-no-field/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.ts
  src/api/package-lock.json
  src/api/types/xlsx-types/index.ts
  src/ui/package-lock.json
  src/ui/public/css/styles.css
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.LICENSE.txt
  src/ui/public/js/mojFrontend.js.map
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/templates/partials/cookies-banner.njk
  src/ui/types/page-variables.d.ts
Labels: chore

#2391 feat(EMS-2935): No PDF - Policy - Change your answers - Loss payee, financial details - Location
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-international-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-uk-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-international-to-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-uk-to-international.spec.js
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index-with-financial-international-data.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index-with-financial-uk-data.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.ts
  src/ui/server/helpers/nullify-loss-payee-financial-international-data/index.test.ts
  src/ui/server/helpers/nullify-loss-payee-financial-international-data/index.ts
  src/ui/server/helpers/should-nullify-loss-payee-financial-international-data/index.test.ts
  src/ui/server/helpers/should-nullify-loss-payee-financial-international-data/index.ts
  src/ui/server/helpers/should-nullify-loss-payee-financial-uk-data/index.test.ts
  src/ui/server/helpers/should-nullify-loss-payee-financial-uk-data/index.ts
  src/ui/server/helpers/summary-lists/policy/loss-payee-fields/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: enhancement, feature, tech, chore

#2392 feat(EMS-2880-2935): No PDF - Policy - Change your answers - Loss Payee, financial details - UK, international fields, sort code formatting
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/helpers/format-sort-code.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-loss-payee-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-loss-payee-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-loss-payee-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-loss-payee-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-international-to-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-uk-to-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-uk.spec.js
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/sort-code.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/sort-code.ts
  src/ui/server/helpers/format-sort-code/index.test..ts
  src/ui/server/helpers/format-sort-code/index.ts
  src/ui/server/helpers/summary-lists/policy/loss-payee-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/loss-payee-fields/index.ts
Labels: tech, chore

#2393 fix(EMS-3125-3316): No PDF - Buyer - Organsation name error message, Application submitted page content
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages/insurance/application-submitted/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-name.spec.js
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/insurance/application-submitted/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.ts
Labels: bug, fix

#2396 fix(EMS-3299): No PDF - Export contract - Change your answers - Using agent - Yes to no
  e2e-tests/commands/shared-commands/assertions/assert-empty-agent-charges-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-agent-details-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-agent-service-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent/change-your-answers-agent-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-yes-to-no.spec.js
  package-lock.json
  package.json
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service-charge/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index-no-agent-and-agent-service-data.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/nullify-export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/nullify-export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.ts
  src/ui/server/helpers/nullify-agent-service-data/index.test.ts
  src/ui/server/helpers/nullify-agent-service-data/index.ts
  src/ui/server/helpers/should-nullify-agent-service-charge-data/index.ts
  src/ui/server/helpers/should-nullify-agent-service-data/index.test.ts
  src/ui/server/helpers/should-nullify-agent-service-data/index.ts
  src/ui/server/helpers/should-nullify-loss-payee-financial-uk-data/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: bug, dependencies, chore, fix

#2397 feat(EMS-3285-3286): No PDF - Change your answers - Policy - Loss payee
  e2e-tests/fixtures/account-numbers.js
  e2e-tests/fixtures/addresses.js
  e2e-tests/fixtures/application.js
  e2e-tests/fixtures/bic-swift-codes.js
  e2e-tests/fixtures/ibans.js
  e2e-tests/fixtures/sort-codes.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-international-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-uk-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-uk.spec.js
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.test.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.ts
Labels: enhancement, feature, tech, chore

#2394 feat(EMS-1175): No PDF - CRON jobs - Unverified account helper
  src/api/helpers/get-unverified-accounts/index.test.ts
  src/api/helpers/get-unverified-accounts/index.ts
  src/api/helpers/map-and-update-unverified-accounts/index.test.ts
  src/api/helpers/map-and-update-unverified-accounts/index.ts
  src/api/helpers/map-inactive-applications/index.test.ts
  src/api/helpers/map-unverified-accounts/index.test.ts
  src/api/helpers/map-unverified-accounts/index.ts
  src/api/helpers/update-unverified-accounts/index.test.ts
  src/api/helpers/update-unverified-accounts/index.ts
  src/api/test-helpers/accounts.ts
  src/api/test-helpers/create-multiple-accounts.ts
  src/api/test-helpers/create-multiple-full-applications.ts
  src/api/test-helpers/index.ts
  src/api/types/cron/index.ts
Labels: feature

#2402 style(EMS-3363): No PDF - Update phase banner from "alpha" to "beta"
  e2e-tests/commands/shared-commands/assertions/check-phase-banner.js
  src/ui/templates/partials/phase-banner.njk
Labels: enhancement, chore

#2414 feat(EMS-3256): No PDF - Export contract - Change your answers - Alternative currency
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-alternative-currency.spec.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/alternative-currency/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/helpers/required-fields/export-contract/index.test.ts
  src/ui/server/helpers/required-fields/export-contract/index.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: enhancement, feature, chore

#2404 feat(EMS-1172): No PDF - CRON jobs
  .cspell.json
  docker-compose.yml
  src/api/.env.sample
  src/api/.eslintrc.js
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/constants/cron/index.ts
  src/api/constants/index.ts
  src/api/cron/account/index.test.ts
  src/api/cron/account/index.ts
  src/api/cron/account/unverified-account-cron-job.test.ts
  src/api/cron/account/unverified-account-cron-job.ts
  src/api/cron/application/inactive-application-cron-job.test.ts
  src/api/cron/application/inactive-application-cron-job.ts
  src/api/cron/application/index.test.ts
  src/api/cron/application/index.ts
  src/api/cron/cron-job-scheduler.ts
  src/api/cron/index.ts
  src/api/helpers/cron/scheduler.ts
  src/api/helpers/get-unverified-accounts/index.ts
  src/api/keystone.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/types/cron/index.ts
Labels: feature

#2418 fix(EMS-3125 3316): No PDF - Feedback link, maximum characters constant
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages/insurance/application-submitted/index.js
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/insurance/application-submitted/index.ts
Labels: bug, fix

#2417 chore(EMS-3290): No PDF - Change your answers - Policy - Jointly insured party
  .github/workflows/test.yml
  e2e-tests/commands/shared-commands/assertions/assert-empty-other-company-details-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/another-company/change-your-answers-change-another-company-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/another-company/change-your-answers-change-another-company-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/other-company-details/change-your-answers-change-other-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/another-company/change-your-answers-change-another-company-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/another-company/change-your-answers-change-another-company-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/other-company-details/change-your-answers-change-other-company-details.spec.js
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.ts
Labels: enhancement, feature, tech, chore

#2421 style(EMS-3316): No PDF - Application submitted - Feedback link - Add missing full stop
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/application-submitted.spec.js
  e2e-tests/pages/insurance/applicationSubmitted.js
  src/ui/templates/insurance/application-submitted.njk
Labels: chore, fix

#2419 chore/fix(EMS-3291): No PDF - Change your answers - Business - Alternative trading address
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details-trading-address-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details-trading-address-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  src/api/types/application-types/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index-with-different-trading-address-data.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.api-error.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/nullify-company-different-address/index.test.ts
  src/ui/server/controllers/insurance/business/map-and-save/nullify-company-different-address/index.ts
  src/ui/server/controllers/insurance/business/save-data/company-different-trading-address/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/nullify-export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/nullify-export-contract-agent-service/index.ts
  src/ui/server/helpers/nullify-company-different-trading-address-data/index.test.ts
  src/ui/server/helpers/nullify-company-different-trading-address-data/index.ts
  src/ui/server/helpers/should-nullify-company-different-address/index.test.ts
  src/ui/server/helpers/should-nullify-company-different-address/index.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
Labels: bug, tech, chore, fix

#2420 chore(EMS-3292): No PDF - Change your answers - Business - Credit control - E2E tests
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/commands/insurance/complete-business-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-credit-control-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-credit-control-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
Labels: tech, chore

#2431 chore(deps): Bump dependencies
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2434 feat(EMS-3258): No PDF - Export Contract- Agent charges - Alternative currency URL
  e2e-tests/constants/routes/insurance/export-contract.js
  src/ui/server/constants/routes/insurance/export-contract.ts
Labels: feature

#2430 feat(EMS-3306-3308): No PDF - Change your answers - Your Buyer - Trading history
  .github/workflows/test.yml
  CHANGELOG.md
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-trading-history-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-buyer-financial-accounts.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-connection-with-buyer-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-connection-with-buyer-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-credit-insurance-history.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-trading-history-failed-payments.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-trading-history-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-trading-history-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-buyer-financial-accounts.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-connection-with-buyer-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-connection-with-buyer-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-credit-insurance-history.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-failed-payments.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-trading-history.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-registration-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/connection-with-the-buyer-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/validation/connection-with-the-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/credit-insurance-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/validation/credit-insurance-cover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-validation.spec.js
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.ts
Labels: enhancement, feature, tech, chore

#2435 chore(EMS-3306-3308): No PDF - Change your answers - Buyer - Trading history - E2E test improvements
  .github/workflows/test.yml
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
Labels: tech, chore

#2442 chore(main): release 2.7.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2450 style(EMS-3390): update phase banner from "alpha" to "beta"
  e2e-tests/commands/shared-commands/assertions/check-phase-banner.js
  src/ui/templates/partials/phase-banner.njk
Labels: enhancement, chore

#2458 chore(main): release 2.8.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2451 feat(EMS-3347): pricing grid updates
  CHANGELOG.md
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  src/ui/server/generate-quote/pricing-grid.json
Labels: feature

#2459 style(EMS-3392): get a quote content updates, "max cover period in months" from 24 to 22
  .husky/pre-commit
  e2e-tests/commands/quote/forms.js
  e2e-tests/commands/quote/submit-answers-happy-path-multiple-policy.js
  e2e-tests/commands/quote/submit-answers-happy-path-single-policy.js
  e2e-tests/constants/eligibility.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-get-a-quote.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy-maximum-cover-period.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-buyer-country-routes/complete-insurance-eligibility-then-get-a-quote.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-buyer-country-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-start-now-routes/complete-insurance-eligibility-then-get-a-quote.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-start-now-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  src/ui/server/constants/eligibility.ts
Labels: documentation, enhancement, tech, chore

#2462 fix(EMS-3384): no PDF - buyer - company or organisation - registration number validation
  .husky/pre-commit
  database/exip.sql
  src/api/.keystone/config.js
  src/api/schema.prisma
  src/api/schema.ts
Labels: bug, fix

#2463 fix(deployment): added missing dependency
  .github/workflows/publish.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: fix

#2464 fix(release-please): updated to GitHub plugin
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/publish.yml
  package-lock.json
  package.json
Labels: fix

#2461 feat(EMS-3346): no PDF - application submission - XLSX - key information, eligibility
  e2e-tests/fixtures/application.js
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/content-strings/XLSX.ts
  src/api/content-strings/fields/insurance/eligibility/index.ts
  src/api/content-strings/links.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-cover-period-field/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-cover-period-field/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-total-contract-field/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-total-contract-field/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-introduction/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-introduction/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-key-information/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-key-information/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-secondary-key-information/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-secondary-key-information/index.ts
Labels: documentation, enhancement, feature, tech, chore

#2465 chore(main): release 2.9.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2466 fix(EMS-3407): update SRI values
  CHANGELOG.md
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/main.js
  src/ui/public/js/main.js.map
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/server/constants/integrity.ts
Labels: bug, chore, fix

#2468 chore(main): release 2.9.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2467 feat(EMS-3063): no PDF - Your business - Turnover - Dynamic legend
  e2e-tests/commands/shared-commands/assertions/assert-copy-with-currency-name.js
  e2e-tests/commands/shared-commands/assertions/assert-heading-with-currency-name.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/templates/insurance/your-business/turnover.njk
Labels: feature

#2473 chore(gha-e2e-node-version): gha- Node version for e2e runners
  .github/workflows/test.yml
  e2e-tests/commands/shared-commands/assertions/assert-copy-with-currency-name.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
Labels: chore
