Repository UK-Export-Finance/exip, pull requests merged in 2024-04, with the labels that each got.

#2170 feat(EMS-2936): No PDF - Export contract - Private market - Save and back
  e2e-tests/commands/insurance/complete-and-submit-private-market-form.js
  e2e-tests/commands/insurance/complete-private-market-form.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/save-and-back.spec.js
  e2e-tests/insurance/cypress/support/application/export-contract/index.js
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/save-and-back/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature, chore

#2176 fix(EMS-3078): No PDF - Single/multiple contract policy - Alternative currency validation - Pre-selected radio
  e2e-tests/commands/insurance/assert-currency-form-fields.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-single-policy-type.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/form-submission.js
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.ts
  src/ui/server/shared-validation/date/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: bug, tech, chore, fix

#2185 fix(EMS-3081): No PDF - Policy - Loss payee details URL
  e2e-tests/constants/routes/insurance/policy/loss-payee.js
  src/ui/server/constants/routes/insurance/policy/loss-payee.ts
Labels: bug, fix

#2174 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2192 chore(tech): Upgrade docker syntax to V2
  .github/workflows/test.yml
  README.md
Labels: chore

#2194 fix(EMS-3086): Rebuild client side scripts, update integrity hashes
  src/ui/public/css/styles.css
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.LICENSE.txt
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/server/constants/integrity.ts
Labels: chore, fix

#2186 feat(EMS-2945): No PDF - Export contract - Agent - Form validation
  e2e-tests/commands/insurance/complete-agent-form.js
  e2e-tests/commands/insurance/complete-and-submit-agent-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/agent.spec.js
  e2e-tests/insurance/cypress/support/application/export-contract/index.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
Labels: enhancement, feature

#2191 feat(EMS-2946): No PDF - Export contract - Agent - Data model/schema
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/helpers/create-a-private-market/index.ts
  src/api/helpers/create-an-export-contract-agent-service/index.test.ts
  src/api/helpers/create-an-export-contract-agent-service/index.ts
  src/api/helpers/create-an-export-contract-agent/index.test.ts
  src/api/helpers/create-an-export-contract-agent/index.ts
  src/api/helpers/create-an-export-contract/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/graphql/queries/application.ts
Labels: documentation, chore

#2193 feat(EMS-2942): No PDF - Export contract - Declined by private market - Save data on form post
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/declined-by-private-market.spec.js
  src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
Labels: feature, chore

#2207 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2196 chore(sonarCloud): Simplify UI unit test error handling describe blocks
  src/ui/server/controllers/insurance/account/create/confirm-email-resent/index.test.ts
  src/ui/server/controllers/insurance/account/create/confirm-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/resend-confirm-email/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/request-new-code/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/save-data/index.test.ts
  src/ui/server/controllers/insurance/dashboard/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.test.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts
  src/ui/server/controllers/insurance/declarations/save-data/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/private-market/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/broker/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/save-data/jointly-insured-party/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/save-data/policy-contact/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-relationship/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer/index.test.ts
Labels: tech, chore

#2208 style(EMS-2467): No PDF - Export contract - Check your answers - Design updates
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/content-strings/form-titles.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/content-strings/form-titles.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.ts
  src/ui/server/helpers/summary-lists/export-contract/about-goods-or-services-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.ts
  src/ui/server/helpers/summary-lists/export-contract/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/index.ts
  src/ui/server/helpers/summary-lists/policy/index.test.ts
  src/ui/server/helpers/summary-lists/policy/index.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/templates/insurance/export-contract/check-your-answers.njk
Labels: documentation, enhancement, tech, chore

#2195 chore(EMS-2946): No PDF - Export contract - Agent, agent service - Setup UI GQL mutations
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/api/keystone/application/update/exportContractAgent.ts
  src/ui/server/api/keystone/application/update/exportContractAgentService.ts
  src/ui/server/api/keystone/application/update/index.ts
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent/index.ts
  src/ui/server/graphql/mutations/update-application/export-contract-agent-service.ts
  src/ui/server/graphql/mutations/update-application/export-contract-agent.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: documentation, chore

#2197 feat(EMS-2946): No PDF - Export contract - Agent - Save data on form post
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/agent.spec.js
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.ts
  src/ui/server/graphql/mutations/update-application/export-contract-agent-service.ts
  src/ui/server/graphql/mutations/update-application/export-contract-agent.ts
  src/ui/server/graphql/queries/application.ts
Labels: enhancement, feature

#2212 feat(EMS-3089-3112): No PDF - Export contract - Check/change answers - Payment terms description
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-how-will-you-get-paid-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/save-and-back.spec.js
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: enhancement, feature, tech, chore

#2198 feat(EMS-2946): No PDF - Export contract - Agent - Save and back
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/save-and-back.spec.js
  src/api/.keystone/config.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.ts
  src/ui/server/controllers/insurance/export-contract/agent/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/save-and-back/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature

#2216 feat(EMS-2948-3117): No PDF - Export contract - Agent service - Page setup
  .github/workflows/test.yml
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/agent-service.spec.js
  src/ui/server/constants/templates/insurance/export-contract/index.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/export-contract/agent-service.njk
Labels: feature

#2222 feat(EMS-2879): No PDF - Export contract - Agent details - Form post - Data saving
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/agent-details.spec.js
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
Labels: feature

#2236 chore(EMS-3171): Bump dependencies, update KeystoneJS
  .github/workflows/lint.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/keystone-account.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/schema.ts
  src/ui/package-lock.json
  src/ui/package.json
Labels: tech, chore

#2235 feat(EMS-3112-3120-3121): No PDF - Export contract - Check your answers - Private market, agent details
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-agent-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/declined-by-private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/index.ts
  src/ui/server/helpers/summary-lists/export-contract/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/index.ts
  src/ui/server/helpers/summary-lists/export-contract/private-market-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/private-market-fields/index.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
Labels: feature, chore

#2246 chore(EMS-3158): No PDF - Simplify previously submitted country mappings
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
Labels: tech, chore

#2245 feat(EMS-2952-2953): No PDF - Export contract - Agent service - Form validation
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/validation/agent-service-validation.spec.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/validation/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/validation/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/validation/rules/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/validation/rules/is-charging/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/validation/rules/is-charging/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/validation/rules/service-description/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/validation/rules/service-description/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/export-contract/agent-service.njk
Labels: enhancement, feature

#2247 feat(EMS-3117): No PDF - Export contract - Agent service - UI flow
  e2e-tests/commands/insurance/complete-and-submit-agent-service-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/agent-service.spec.js
  e2e-tests/insurance/cypress/support/application/export-contract/index.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.ts
Labels: feature, chore

#2248 feat(EMS-3120-3121): No PDF - Export contract - Check/change answers - Agent
  .github/workflows/test.yml
  e2e-tests/commands/insurance/assert-currency-form-fields.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/about-goods-or-services/change-your-answers-about-goods-or-services-final-destination-known-to-unknown.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/about-goods-or-services/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/private-market/change-your-answers-private-market-yes-to-no.spec.js
  e2e-tests/shared-test-assertions/autocomplete-assertions/index.js
  e2e-tests/shared-test-assertions/currency-form-fields/assertions.js
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature, tech, chore

#2249 feat(EMS-2860): No PDF - Policy - Check your answers - Other company to be insured
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/constants/routes/insurance/policy/another-company.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/form-titles.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-other-company-no-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-other-company-yes-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-other-company-no-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-other-company-yes-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-other-company-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-other-company-yes.spec.js
  src/ui/server/constants/routes/insurance/policy/another-company.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/form-titles.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
  src/ui/server/helpers/summary-lists/policy/index.test.ts
  src/ui/server/helpers/summary-lists/policy/index.ts
  src/ui/server/helpers/summary-lists/policy/other-company-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/other-company-fields/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/another-company/index.test.ts
  src/ui/server/routes/insurance/policy/another-company/index.ts
Labels: feature

#2253 chore(tech): Various tech improvements - Address TODO comments, documentation, E2E test alignments
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/agent.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/save-and-back.spec.js
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts
  src/ui/server/controllers/insurance/business/map-submitted-data/company-details/index.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/private-market/index.ts
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy-contact/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/company-name/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/company-number/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/country-code/index.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/type-of-policy/index.test.ts
  src/ui/server/helpers/combine-validation-rules/index.ts
  src/ui/server/helpers/mappings/map-currency-code-form-data/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/types/index.d.ts
  src/ui/types/task-list.ts
Labels: documentation, tech, dependencies, chore

#2254 feat(EMS-3118): No PDF - Export contract - Agent service - Form post - Data saving
  e2e-tests/commands/insurance/complete-and-submit-agent-service-form.js
  e2e-tests/commands/shared-commands/assertions/assert-agent-service-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/commands/shared-commands/form/submit-and-assert-field-errors.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/agent-service.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-special-characters/submit-export-contract-textarea-fields-with-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.test.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.test.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.ts
  src/ui/templates/insurance/export-contract/agent-service.njk
Labels: feature, tech, chore

#2256 feat(EMS-3119): No PDF - Export contract - Check your answers - Agent service description
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/index.ts
Labels: enhancement, feature

#2261 chore(deps): Bump dependencies
  generate-exip-pricing-grid/package-lock.json
  generate-exip-pricing-grid/package.json
  package-lock.json
  package.json
Labels: dependencies, chore

#2262 feat(EMS-3179): No PDF - Export contract - Agent charges - Page setup
  .github/workflows/test.yml
  e2e-tests/commands/shared-commands/assertions/assert-prefix.js
  e2e-tests/commands/shared-commands/assertions/assert-suffix.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  e2e-tests/constants/index.js
  e2e-tests/constants/supported-currencies.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/pages/insurance/export-contract/agentCharges.js
  e2e-tests/pages/insurance/export-contract/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/scripts/accessible-autocomplete.js
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/constants/integrity.ts
  src/ui/server/constants/templates/insurance/export-contract/index.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/export-contract/agent-charges.njk
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-fixed-sum-html.njk
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-percentage-html.njk
Labels: documentation, feature, tech, chore

#2269 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2268 feat(EMS-3180-3181): No PDF - Export contract - Agent charges - Form validation - Method - Fixed sum, Payable country code
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/validation/different-name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  src/api/.keystone/config.js
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/payable-country-code/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/payable-country-code/index.ts
  src/ui/server/helpers/percentage-number-validation/index.test.ts
  src/ui/server/helpers/percentage-number-validation/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/shared-validation/alpha-characters-and-max-length/index.test.ts
  src/ui/templates/insurance/export-contract/agent-charges.njk
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-fixed-sum-html.njk
Labels: enhancement, feature, tech, chore

#2273 feat(EMS-3183): No PDF - Export contract - Form validation - Chargable percentage
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  e2e-tests/shared-test-assertions/index.js
  e2e-tests/shared-test-assertions/percentage-field-validation/index.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/business/turnover/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.ts
  src/ui/server/helpers/percentage-number-validation/index.test.ts
  src/ui/server/helpers/percentage-number-validation/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
  src/ui/server/helpers/strip-empty-form-fields/index.test.ts
  src/ui/server/helpers/strip-empty-form-fields/index.ts
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-percentage-html.njk
Labels: documentation, enhancement, feature, tech, chore

#2275 style(EMS-3179): No PDF - Export contract - Agent charges - Design updates
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/templates/insurance/export-contract/agent-charges.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-fixed-sum-html.njk
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-percentage-html.njk
Labels: enhancement, chore

#2277 feat(EMS-3182): No PDF - Export contract - Agent charges - Data model/schema
  database/exip.sql
  e2e-tests/constants/application.js
  e2e-tests/fixtures/application.js
  src/api/.keystone/config.js
  src/api/constants/application/index.ts
  src/api/helpers/create-an-export-contract-agent-service-charge/index.test.ts
  src/api/helpers/create-an-export-contract-agent-service-charge/index.ts
  src/api/helpers/create-an-export-contract-agent-service/index.test.ts
  src/api/helpers/create-an-export-contract-agent-service/index.ts
  src/api/helpers/create-an-export-contract-agent/index.test.ts
  src/api/helpers/create-an-export-contract-agent/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/application/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: chore

#2279 feat(EMS-3182): No PDF - Task list - Update required "prepare application" fields
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-attempted-private-market-cover-and-using-an-agent-with-charges-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-attempted-private-market-cover-and-using-an-agent-with-charges-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-attempted-private-market-cover-and-using-an-agent-with-charges-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-attempted-private-market-cover-and-using-an-agent-with-charges-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/save-and-back.spec.js
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/required-fields/export-contract/index.test.ts
  src/ui/server/helpers/required-fields/export-contract/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/prepare-application.ts
  src/ui/types/task-list.ts
Labels: enhancement, tech, chore

#2281 style(EMS-3170): No PDF - Export contract - Start page - Content update
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
Labels: enhancement, dependencies, chore

#2280 feat(EMS-3182): No PDF - Export contract - Agent charges - Save and back
  e2e-tests/commands/insurance/complete-agent-charges-form.js
  e2e-tests/commands/insurance/complete-and-submit-agent-charges-form.js
  e2e-tests/commands/shared-commands/assertions/assert-agent-charges-field-values.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back.spec.js
  e2e-tests/insurance/cypress/support/application/export-contract/index.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/save-and-back/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: feature

#2288 feat(EMS-3186): No PDF - Export contract - Agent charges - Alternative currency - Page setup
  e2e-tests/commands/insurance/complete-and-submit-alternative-currency-form.js
  e2e-tests/commands/shared-commands/click-events/click-provide-alternative-currency-link.js
  e2e-tests/commands/shared-commands/click-events/index.js
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/alternative-currency/alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-alternative-currency.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/alternative-currency/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature, tech, chore

#2287 feat(EMS-3122): No PDF - Export contract - Check/change answers - Agent service
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-description.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/private-market/change-your-answers-private-market-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  src/api/.keystone/config.js
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service-charge/index.ts
  src/ui/server/helpers/nullify-agent-service-charge-data/index.test.ts
  src/ui/server/helpers/nullify-agent-service-charge-data/index.ts
  src/ui/server/helpers/section-status/index.test.ts
  src/ui/server/helpers/should-nullify-agent-service-charge-data/index.test.ts
  src/ui/server/helpers/should-nullify-agent-service-charge-data/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: enhancement, feature, tech, chore

#2289 feat(EMS-3186-3188): No PDF - Export contract - Agent charges - Alternative currency - Data model
  database/exip.sql
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/alternative-currency/alternative-currency.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/assertions.js
  e2e-tests/shared-test-assertions/currency-form-fields/index.js
  e2e-tests/shared-test-assertions/currency-form-fields/rendering.js
  src/api/.keystone/config.js
  src/api/helpers/create-an-export-contract-agent-service-charge/index.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types/application-types/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/alternative-currency/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/types/application.ts
Labels: documentation, feature, chore

#2291 chore(EMS-3239): No PDF - Export contract - Rename chargePercentage to percentageCharge
  database/exip.sql
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/commands/insurance/complete-agent-charges-form.js
  e2e-tests/commands/insurance/complete-and-submit-agent-charges-form.js
  e2e-tests/commands/shared-commands/assertions/assert-agent-charges-field-values.js
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/api/helpers/create-an-export-contract-agent-service-charge/index.test.ts
  src/api/helpers/create-an-export-contract-agent/index.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract-agent-service-charge/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/nullify-agent-service-charge-data/index.test.ts
  src/ui/server/helpers/nullify-agent-service-charge-data/index.ts
  src/ui/server/helpers/required-fields/export-contract/index.test.ts
  src/ui/server/helpers/required-fields/export-contract/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-percentage-html.njk
  src/ui/types/application.ts
Labels: tech, chore

#2295 feat(EMS-3186-3188): No PDF - Export contract - Agent charges - Alternative currency - Prefixes, dynamic label
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-change-currency.spec.js
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.ts
  src/ui/templates/partials/insurance/export-contract-agent-charges-conditional-fixed-sum-html.njk
Labels: documentation, enhancement, feature, chore, fix

#2293 feat(EMS-3159): No PDF - Export contract - Check/change answers - Agent charges
  .github/workflows/test.yml
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-to-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-payable-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-percentage-charge.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-percentage-to-fixed-sum.spec.js
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
Labels: documentation, enhancement, feature, chore

#2296 chore(deps): Bump dependencies
  e2e-tests/commands/shared-commands/assertions/check-buyer-country-form.js
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/server/constants/integrity.ts
  src/ui/styles/accessible-autocomplete.min.scss
Labels: dependencies, chore

#2299 fix(EMS-3129-3184-3187-3242): No PDF - Visual design issues - Email fields, content, unnecessary button, styling
  e2e-tests/commands/keyboard-input.js
  e2e-tests/commands/shared-commands/assertions/assert-section-start-content.js
  e2e-tests/commands/shared-commands/assertions/check-email-field-rendering.js
  e2e-tests/commands/shared-commands/assertions/check-type-attribute.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/commands/shared-commands/form/click-all-sections-link.js
  e2e-tests/commands/shared-commands/form/index.js
  e2e-tests/commands/shared-commands/form/submit-and-assert-field-errors.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/account-password-reset.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js
  e2e-tests/shared-test-assertions/email-field-validation/index.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/password-reset/password-reset.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
  src/ui/templates/insurance/export-contract/agent-details.njk
  src/ui/templates/insurance/policy/broker-details.njk
  src/ui/templates/insurance/policy/check-your-answers.njk
  src/ui/templates/insurance/policy/different-name-on-policy.njk
  src/ui/templates/insurance/your-business/check-your-answers.njk
  src/ui/templates/insurance/your-business/contact.njk
Labels: bug, enhancement, chore, fix

#2274 feat(EMS-3091): No PDF - Policy - Loss payee financial details UK - API decryption
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/constants/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/delete-application-by-reference-number/index.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-uk/index.test.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-uk/index.ts
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.test.ts
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.ts
  src/api/custom-resolvers/queries/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/decrypt-financial-uk/index.test.ts
  src/api/helpers/decrypt-financial-uk/index.ts
  src/api/helpers/decrypt-nominated-loss-payee/index.test.ts
  src/api/helpers/decrypt-nominated-loss-payee/index.ts
  src/api/helpers/decrypt/generate-buffer/index.test.ts
  src/api/helpers/decrypt/generate-buffer/index.ts
  src/api/helpers/decrypt/generate-decipher/index.test.ts
  src/api/helpers/decrypt/generate-decipher/index.ts
  src/api/helpers/decrypt/index.test.ts
  src/api/helpers/decrypt/index.ts
  src/api/helpers/encrypt/index.test.ts
  src/api/helpers/encrypt/index.ts
  src/api/helpers/get-application-by-reference-number/index.test.ts
  src/api/helpers/get-application-by-reference-number/index.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/map-loss-payee-financial-details-uk/index.test.ts
  src/api/helpers/map-loss-payee-financial-details-uk/index.ts
  src/api/schema.graphql
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/loss-payee-financial-uk.ts
  src/api/test-helpers/map-application-ids.ts
  src/api/test-mocks/index.ts
  src/api/test-mocks/mock-application.ts
  src/api/test-mocks/mock-nominated-loss-payee.ts
  src/api/types/application-types/index.ts
  src/api/types/encryption/index.ts
  src/ui/server/controllers/insurance/policy/save-data/loss-payee-financial-details-uk/index.ts
Labels: feature

#2312 feat(EMS-3229): No PDF - Check/change your answers - Export contract - About goods or services
  e2e-tests/commands/insurance/assert-change-answers-page-url.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-about-goods-or-services-final-destination-known-to-unknown.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/check-your-answers-export-contract-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-minimal.spec.js
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: documentation, enhancement, feature, chore

#2316 feat(EMS-3231): No PDF - Change your answers - Export contract - Private market
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-private-market-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-private-market-yes-to-no.spec.js
  src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
Labels: enhancement, feature

#2282 feat(EMS-3091): No PDF - Policy - Loss payee financial details UK - UI playback
  e2e-tests/commands/shared-commands/assertions/assert-loss-payee-financial-uk-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/loss-payee-financial-details-uk.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/schema.graphql
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/map-application-ids.ts
  src/api/test-helpers/sectionReview.ts
  src/api/types/application-types/index.ts
  src/ui/server/api/keystone/application/get-by-reference-number.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/index.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
  src/ui/server/helpers/get-application-by-reference-number-variables/index.test.ts
  src/ui/server/helpers/get-application-by-reference-number-variables/index.ts
  src/ui/server/helpers/get-application-by-reference-number/index.test.ts
  src/ui/server/helpers/get-application-by-reference-number/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/insurance/application-status/index.ts
  src/ui/server/middleware/insurance/get-application-by-reference-number/index.test.ts
  src/ui/server/middleware/insurance/get-application-by-reference-number/index.ts
  src/ui/server/middleware/insurance/get-application/index.test.ts
  src/ui/server/middleware/insurance/get-application/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/templates/insurance/policy/loss-payee-financial-details-uk.njk
  src/ui/types/application-by-reference-number-variables.ts
  src/ui/types/index.d.ts
Labels: feature

#2318 feat(EMS-3235): No PDF - Export contract - Change your answers - Agent details
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-details.spec.js
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
Labels: enhancement, feature

#2320 feat(EMS-3231): No PDF - Change your answers - Export contract - Agent
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-yes-to-no.spec.js
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: enhancement, feature

#2310 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2322 feat(EMS-3237): No PDF - Change your answers - Export contract - Agent charges
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-fixed-sum-amount.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-fixed-sum-to-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-payable-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-percentage-charge.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-charges-percentage-to-fixed-sum.spec.js
Labels: enhancement, feature, chore

#2297 feat(EMS-3088-3090): No PDF - Policy - Loss payee financial details International - UI playback
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-financial-details-international-form.js
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-financial-details-uk-form.js
  e2e-tests/commands/shared-commands/assertions/assert-loss-payee-financial-international-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-loss-payee-financial-uk-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-policy-loss-payee-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-policy-loss-payee-financial-textarea-fields-with-new-line-characters.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.test.ts
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/decrypt-financial-international/index.test.ts
  src/api/helpers/decrypt-financial-international/index.ts
  src/api/helpers/decrypt-financial-uk/index.test.ts
  src/api/helpers/decrypt-financial-uk/index.ts
  src/api/helpers/decrypt-nominated-loss-payee/index.test.ts
  src/api/helpers/decrypt-nominated-loss-payee/index.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/map-loss-payee-financial-details-uk/index.test.ts
  src/api/schema.graphql
  src/api/test-helpers/create-full-application.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-international/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-international/index.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
  src/ui/server/helpers/get-application-by-reference-number-variables/index.test.ts
  src/ui/server/helpers/get-application-by-reference-number-variables/index.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.test.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.ts
  src/ui/templates/insurance/policy/loss-payee-financial-details-international.njk
Labels: feature

#2323 fix(EMS-3241-3235): No PDF - Change your answers - Export contract - Agent details - Redirect logic
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/change-your-answers-agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent/change-your-answers-agent-no-to-yes.spec.js
  src/ui/server/controllers/insurance/export-contract/agent-details/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: bug, chore, fix

#2329 feat(EMS-3124): No PDF - Policy - Loss payee - Name - Increase maximum length
  database/exip.sql
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  src/api/.keystone/config.js
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.ts
Labels: enhancement, tech, chore

#2331 feat(EMS-3108): No PDF - Business - Company details - Different trading name - Maximum length
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-different-trading-name-validation.spec.js
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/different-trading-name.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/different-trading-name.ts
Labels: enhancement

#2328 style(EMS-3257): No PDF - Application submitted - Content updates
  e2e-tests/content-strings/pages/insurance/application-submitted/index.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/application-submitted.spec.js
  e2e-tests/pages/insurance/applicationSubmitted.js
  src/ui/server/content-strings/pages/insurance/application-submitted/index.ts
  src/ui/templates/insurance/application-submitted.njk
Labels: enhancement

#2332 feat(EMS-3125): No PDF - Buyer - Company or organisation name - Maximum length
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-name.spec.js
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/organisation-name.ts
Labels: enhancement

#2335 chore(EMS-3191): No PDF - Export contract - Agent details - Validation - Improve E2E test coverage
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
Labels: chore

#2334 chore(EMS-3185): No PDF - Financial details - Separate encryption vectors into their own tables
  database/exip.sql
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-international/index.test.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-international/index.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-uk/index.test.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-uk/index.ts
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/create-a-loss-payee-financial-international/index.test.ts
  src/api/helpers/create-a-loss-payee-financial-international/index.ts
  src/api/helpers/create-a-loss-payee-financial-uk/index.test.ts
  src/api/helpers/create-a-loss-payee-financial-uk/index.ts
  src/api/helpers/create-a-private-market/index.ts
  src/api/helpers/create-an-export-contract-agent-service-charge/index.ts
  src/api/helpers/create-an-export-contract-agent-service/index.ts
  src/api/helpers/create-an-export-contract-agent/index.ts
  src/api/helpers/decrypt-financial-international/index.test.ts
  src/api/helpers/decrypt-financial-international/index.ts
  src/api/helpers/decrypt-financial-uk/index.test.ts
  src/api/helpers/decrypt-financial-uk/index.ts
  src/api/helpers/decrypt-nominated-loss-payee/index.test.ts
  src/api/helpers/decrypt-nominated-loss-payee/index.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/map-loss-payee-financial-details-international/index.test.ts
  src/api/helpers/map-loss-payee-financial-details-international/index.ts
  src/api/helpers/map-loss-payee-financial-details-uk/index.test.ts
  src/api/helpers/map-loss-payee-financial-details-uk/index.ts
  src/api/helpers/update-loss-payee-financial-international-vector/index.test.ts
  src/api/helpers/update-loss-payee-financial-international-vector/index.ts
  src/api/helpers/update-loss-payee-financial-international/index.test.ts
  src/api/helpers/update-loss-payee-financial-international/index.ts
  src/api/helpers/update-loss-payee-financial-uk-vector/index.test.ts
  src/api/helpers/update-loss-payee-financial-uk-vector/index.ts
  src/api/helpers/update-loss-payee-financial-uk/index.test.ts
  src/api/helpers/update-loss-payee-financial-uk/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/loss-payee-financial-international-vector.ts
  src/api/test-helpers/loss-payee-financial-international.ts
  src/api/test-helpers/loss-payee-financial-uk-vector.ts
  src/api/test-helpers/loss-payee-financial-uk.ts
  src/api/test-mocks/index.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
  src/api/types/test-helpers/index.ts
Labels: tech, security, chore

#2337 fix(EMS-3195-3238): No PDF - Export contract - Agent charges - Country input - Layout issue
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js
  src/ui/templates/components/accessible-autocomplete-select.njk
  src/ui/templates/insurance/export-contract/agent-charges.njk
Labels: bug, chore, fix
