Repository UK-Export-Finance/exip, pull requests merged in 2024-08, with the labels that each got.

#2867 fix(iac): afd custom domains association
  .cspell.json
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
Labels: fix

#2854 chore(deps): bump dependencies
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2868 chore(main): release 2.28.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2870 chore(main): release 2.28.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2876 chore(main): release 2.29.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2883 feat(EMS-3665): export contract - how was contract awarded - data saving
  CHANGELOG.md
  e2e-tests/commands/insurance/complete-and-submit-how-was-the-contract-awarded-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/commands/shared-commands/assertions/assert-how-was-the-contract-awarded-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known-and-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-as-decimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-with-comma.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/alternative-currency/alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/agent-service.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/validation/agent-service-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/agent.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/declined-by-private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-was-the-contract-awarded/how-was-the-contract-awarded-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-was-the-contract-awarded/how-was-the-contract-awarded.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/save-and-back.spec.js
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/export-contract/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/templates/insurance/export-contract/how-was-the-contract-awarded.njk
Labels: enhancement, feature, chore

#2886 chore(main): release 2.30.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2896 chore(main): release 2.31.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2897 chore(main): release 2.32.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2882 chore(EMS-3708): code scanning - Server-side URL redirect
  src/ui/server/constants/regex.ts
  src/ui/server/controllers/redirects/index.test.ts
  src/ui/server/controllers/redirects/index.ts
  src/ui/server/helpers/is-valid-req-original-url/index.test.ts
  src/ui/server/helpers/is-valid-req-original-url/index.ts
Labels: chore

#2895 feat(EMS-3709-3710): export contract - how the contract was awarded - check your answers
  .github/workflows/test.yml
  CHANGELOG.md
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded-from-other-method.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answer-summary-list-contract-awarded-competitive-bidding.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answer-summary-list-contract-awarded-direct-award.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answer-summary-list-contract-awarded-negotiated-contract.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-contract-awarded-other-method.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum-decimals-multiple-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum-decimals.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded-from-other-method.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answer-summary-list-contract-awarded-competitive-bidding.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answer-summary-list-contract-awarded-direct-award.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answer-summary-list-contract-awarded-negotiated-contract.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-contract-awarded-other-method.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/fully-populated.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/generic.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/minimal.js
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/export-contract/index.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/about-the-export-fields/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: feature

#2901 feat(EMS-3722-3723): data migration - eligibility, export contract
  CHANGELOG.md
  database/exip.sql
  src/api/custom-schema/type-defs.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-field.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/index.ts
  src/api/data-migration/version-1-to-version-2/create-tables/create-export-contract-award-method-table.ts
  src/api/data-migration/version-1-to-version-2/create-tables/index.ts
  src/api/data-migration/version-1-to-version-2/get-all-declarations.ts
  src/api/data-migration/version-1-to-version-2/get-all-non-submitted-applications.ts
  src/api/data-migration/version-1-to-version-2/get-all-submitted-applications.ts
  src/api/data-migration/version-1-to-version-2/index.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-business-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-company-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-eligibility-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-eligibility-has-end-buyer-field.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-export-contract-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/index.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/declarations/get-latest-declarations/index.ts
  src/ui/server/controllers/insurance/all-sections/index.test.ts
  src/ui/server/controllers/insurance/all-sections/index.ts
  src/ui/server/controllers/quote/buyer-country/index.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/can-submit-application/index.ts
  src/ui/server/helpers/number-validation/index.ts
  src/ui/server/helpers/required-fields/check-your-answers/index.test.ts
  src/ui/server/helpers/required-fields/check-your-answers/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
  src/ui/server/helpers/required-fields/prepare-application/index.test.ts
  src/ui/server/helpers/required-fields/prepare-application/index.ts
  src/ui/server/helpers/required-fields/section-review/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/index.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.test.ts
  src/ui/server/helpers/task-list/generate-groups-and-tasks/initial-checks.ts
  src/ui/server/shared-validation/phone-number/index.ts
Labels: feature, tech, chore

#2909 chore(main): release 2.34.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2907 feat(EMS-3687): application submission - xlsx - how was contract awarded
  CHANGELOG.md
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded-from-other-method.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded-from-other-method.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/export-contract/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-how-was-the-contract-awarded/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-how-was-the-contract-awarded/index.ts
  src/api/test-mocks/index.ts
  src/api/types/application-types/index.ts
Labels: enhancement, chore

#2911 chore(main): release 2.35.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2913 fix(EMS-3711): updated husky script to v9
  .husky/commit-msg
  .husky/pre-commit
  CHANGELOG.md
  package.json
Labels: fix

#2910 fix(iac): explicit RBAC authorisation to false for Azure KV
  .github/workflows/infrastructure.yml
Labels: fix

#2915 chore(main): release 2.35.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2920 chore(EMS-3643): clean constants index
  src/ui/server/constants/index.ts
  src/ui/server/constants/quote.ts
  src/ui/server/constants/service-name.ts
Labels: tech, chore

#2921 fix(EMS-3633): data migration - declaration versioning
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-relationship/index.ts
Labels: bug, fix

#2922 chore(main): release 2.35.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2924 chore(merge): iterations - merge main into main-iterations
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-relationship/index.ts
  src/api/package-lock.json
  src/ui/server/constants/index.ts
  src/ui/server/constants/quote.ts
  src/ui/server/constants/service-name.ts
Labels: chore

#2926 chore(merge): iterations - merge main into main-iterations
  package-lock.json
  package.json
  src/api/keystone-create-application-timestamp-updates.test.ts
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2928 fix(EMS-3633): data migration - financial vector columns
  src/api/data-migration/version-1-to-version-2/README.md
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/index.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/create-loss-payee-financial-uk.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/update-loss-payee-financial-international-vector.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/update-loss-payee-financial-uk-vector.ts
Labels: bug, documentation, tech, chore, fix

#2929 chore(main): release 2.35.3
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2931 chore(EMS-3633): data migration - required fields for in progress applications
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.ts
  src/api/test-mocks/index.ts
  src/api/types/application-types/index.ts
  src/ui/server/controllers/insurance/check-your-answers/export-contract/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/export-contract/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/helpers/required-fields/export-contract/index.test.ts
  src/ui/server/helpers/required-fields/export-contract/index.ts
  src/ui/server/helpers/required-fields/prepare-application/index.test.ts
  src/ui/server/helpers/required-fields/prepare-application/index.ts
  src/ui/server/helpers/summary-lists/export-contract/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
  src/ui/types/application.ts
Labels: documentation, chore

#2932 fix(EMS-3633): data migration - xlsx - eligibility questions
  CHANGELOG.md
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
  src/api/schema.graphql
  src/api/types/helpers/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
Labels: bug, documentation, chore

#2933 chore(main): release 2.35.4
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2934 fix(EMS-3633): data migration - xlsx - total contract value
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
Labels: bug, fix

#2935 chore(main): release 2.35.5
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2949 fix(EMS-3755): fix failing e2e tests
  e2e-tests/commands/api/index.js
  e2e-tests/commands/insurance/create-applications.js
  e2e-tests/content-strings/links.js
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/constants/application/initial-application-data/index.ts
  src/api/content-strings/links.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/create-many-applications/index.test.ts
  src/api/custom-resolvers/mutations/create-many-applications/index.ts
  src/api/custom-resolvers/mutations/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/create-a-buyer/index.test.ts
  src/api/helpers/create-a-buyer/index.ts
  src/api/helpers/create-a-populated-buyer/index.test.ts
  src/api/helpers/create-a-populated-buyer/index.ts
  src/api/helpers/create-an-application/create-application-relationships/index.ts
  src/api/helpers/create-an-application/create-initial-application/index.ts
  src/api/helpers/create-many-applications-and-reference-numbers/index.test.ts
  src/api/helpers/create-many-applications-and-reference-numbers/index.ts
  src/api/helpers/update-applications-data/index.test.ts
  src/api/helpers/update-applications-data/index.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/schema.graphql
  src/api/test-helpers/applications.ts
  src/api/test-helpers/buyer.ts
  src/api/test-helpers/reference-number.ts
  src/api/types/application-types/index.ts
  src/api/types/index.ts
  src/api/types/object/index.ts
  src/ui/server/content-strings/links.ts
Labels: chore

#2957 chore(merge): merge main into main-iterations
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/data-migration/version-1-to-version-2/README.md
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/index.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/create-loss-payee-financial-uk.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/update-loss-payee-financial-international-vector.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/loss-payee/update-loss-payee-financial-uk-vector.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-eligibility/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.ts
  src/api/helpers/create-a-declaration/index.ts
  src/api/package-lock.json
  src/api/test-mocks/index.ts
  src/api/types/application-types/index.ts
  src/api/types/helpers/index.ts
  src/ui/server/controllers/insurance/check-your-answers/export-contract/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/export-contract/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/helpers/can-submit-application/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
  src/ui/server/helpers/required-fields/export-contract/index.test.ts
  src/ui/server/helpers/required-fields/export-contract/index.ts
  src/ui/server/helpers/required-fields/prepare-application/index.test.ts
  src/ui/server/helpers/required-fields/prepare-application/index.ts
  src/ui/server/helpers/summary-lists/export-contract/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
  src/ui/types/application.ts
Labels: chore

#2927 chore(EMS-3746): resolve legacy-peer-deps
  README.md
  generate-exip-pricing-grid/package-lock.json
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/Dockerfile
  src/api/package-lock.json
  src/api/package.json
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/public/js/googleTagManager.js
  src/ui/public/js/googleTagManager.js.map
  src/ui/server/constants/integrity.ts
  src/ui/webpack.common.config.js
Labels: chore

#2954 chore(EMS-3643-3757): address todo comments, fix buyer special characters issue
  e2e-tests/commands/shared-commands/assertions/assert-agent-charges-field-values.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-special-characters/submit-buyer-textarea-fields-with-special-characters.spec.js
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.test.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.ts
Labels: bug, tech, chore, fix

#2956 style(EMS-3556-3735): content iterations - eligibility, type of policy
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
Labels: enhancement

#2960 fix(EMS-3659): declarations - confirmation/acknowledgements - submit button copy
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.ts
Labels: bug, fix

#2962 chore(EMS-1156): e2e - cypress commands for eligibility forms
  e2e-tests/commands/insurance/complete-and-submit-all-insurance-eligibility-answers.js
  e2e-tests/commands/insurance/eligibility/submit-answers-from-exporter-location-happy-path.js
  e2e-tests/commands/quote/submit-answers-happy-path-multiple-policy.js
  e2e-tests/commands/quote/submit-answers-happy-path-single-policy.js
  e2e-tests/commands/shared-commands/eligibility/complete-and-submit-buyer-country-form.js
  e2e-tests/commands/shared-commands/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/complete-eligibility-answers-for-a-second-time.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-multiple-risks/cannot-apply-multiple-risks.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cover-period/cover-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/end-buyer/end-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/long-term-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/member-of-a-group-exit-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/member-of-a-group/member-of-a-group.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/party-to-consortium-exit-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/party-to-consortium/party-to-consortium.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/total-value-insured/total-value-insured.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body-answer-yes.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-policy-type-multiple-times-via-back-button.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location-answer-no.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/need-to-start-again.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-signed-in.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services-answer-no.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/quote/cypress/support/commands.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-exporter-location-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-start-now-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
Labels: tech

#2963 chore(EMS-3759): e2e - complete and submit eligibility forms command
  e2e-tests/commands/insurance/eligibility/complete-and-submit-eligibility-forms.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-no-short-term-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-countries.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-multiple-risks/cannot-apply-multiple-risks.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-number/companies-house-number-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-number/companies-house-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-search/companies-house-search-no-financial-year-end-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-search/companies-house-search.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details-company-name-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details-multiple-SIC-codes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-not-active/company-not-active.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cover-period/cover-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/end-buyer/end-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/long-term-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/member-of-a-group-exit-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/member-of-a-group/member-of-a-group.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/party-to-consortium-exit-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/party-to-consortium/party-to-consortium.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/total-value-insured/total-value-insured.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/insurance/cypress/support/eligibility/index.js
  src/ui/.eslintrc.js
  src/ui/tsconfig.json
Labels: tech

#2978 chore(test-split): e2e - split directories into jobs
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: tech

#2982 chore(test-retry): e2e - retry if dependencies or docker fail
  .github/modules/retry/action.yml
  .github/workflows/test.yml
  src/api/.keystone/config.js
Labels: tech

#2964 chore(EMS-3760): e2e - your buyer - complete and submit forms command
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-your-buyer-forms.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-buyer-financial-accounts.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-connection-with-buyer-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-connection-with-buyer-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-credit-insurance-history.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-failed-payments.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-outstanding-payments-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-trading-history-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/connection-with-the-buyer-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/save-and-back/no-connection-with-the-buyer-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/save-and-back/yes-connection-with-the-buyer-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/validation/connection-with-the-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/credit-insurance-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/save-and-back/credit-insurance-cover-answer-no-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/save-and-back/credit-insurance-cover-answer-yes-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/validation/credit-insurance-cover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/save-and-back/trading-history-no-outstanding-payments-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/save-and-back/trading-history-yes-outstanding-payments-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-validation.spec.js
  e2e-tests/insurance/cypress/support/application/buyer/index.js
Labels: tech

#2969 chore(EMS-3761): e2e - your business - complete and submit forms command
  .github/workflows/test.yml
  e2e-tests/commands/insurance/your-business/complete-and-submit-your-business-forms.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details-trading-address-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit-different-trading-address-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-years-exporting-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-financial-year-end.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  e2e-tests/insurance/cypress/support/application/business/index.js
  src/api/.keystone/config.js
Labels: tech

#2970 chore(EMS-3763): e2e - export contract - complete and submit forms command
  e2e-tests/commands/insurance/export-contract/complete-and-submit-export-contract-forms.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known-and-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-as-decimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-with-comma.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/alternative-currency/alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/agent-service.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/validation/agent-service-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/agent.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/declined-by-private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/save-and-back.spec.js
  e2e-tests/insurance/cypress/support/application/export-contract/index.js
Labels: tech

#2974 chore(EMS-3766): e2e - declarations - complete and submit forms command
  e2e-tests/commands/insurance/declarations/complete-and-submit-declarations-forms.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/insurance/cypress/support/declarations/index.js
  src/api/.keystone/config.js
Labels: tech

#2988 chore(EMS-3495): various documentation updates, alignments
  e2e-tests/commands/insurance/assert-change-answers-page-url.js
  e2e-tests/commands/shared-commands/assertions/assert-summary-list-row-change-text.js
  e2e-tests/commands/shared-commands/assertions/assert-summary-list-row-does-not-exist.js
  e2e-tests/commands/shared-commands/assertions/assert-summary-list-row-key.js
  e2e-tests/commands/shared-commands/assertions/assert-summary-list-row-value.js
  e2e-tests/commands/shared-commands/assertions/assert-summary-list-row.js
  e2e-tests/commands/shared-commands/assertions/check-summary-list-field-change.js
  e2e-tests/commands/shared-commands/assertions/submit-and-assert-change-answers-page-url.js
  e2e-tests/commands/shared-commands/assertions/submit-and-assert-summary-list-row-value.js
  src/api/XLSX/README.md
  src/api/constants/application/initial-application-data/index.ts
  src/api/helpers/create-a-buyer/index.ts
  src/api/helpers/get-application-by-reference-number/index.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-search/index.test.ts
  src/ui/server/controllers/insurance/eligibility/companies-house-unavailable/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/helpers/date/get-date-fields-from-timestamp/index.ts
  src/ui/server/helpers/generate-change-link/index.ts
  src/ui/server/helpers/get-application-by-reference-number-variables/index.ts
  src/ui/server/helpers/summary-lists/generate-field-group-item/index.ts
  src/ui/server/helpers/summary-lists/get-key-text/index.ts
  src/ui/server/helpers/validation/index.ts
  src/ui/server/shared-validation/empty-field/index.ts
  src/ui/server/shared-validation/password/index.ts
  src/ui/templates/insurance/your-business/companies_house_number.njk
Labels: documentation, chore

#2987 feat(EMS-3767-3768-3781): business - turnover currency page and check your answers
  .github/workflows/test.yml
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-alternative-currency-form.js
  e2e-tests/commands/insurance/complete-and-submit-turnover-form.js
  e2e-tests/commands/insurance/complete-business-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/commands/insurance/your-business/complete-and-submit-your-business-forms.js
  e2e-tests/constants/routes/insurance/business.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/content-strings/pages/insurance/business/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/business-conditions/submit-an-application-multiple-policy-type-business-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/business-conditions/submit-an-application-multiple-policy-type-with-alternative-turnover-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/business-conditions/submit-an-application-single-policy-type-business-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/business-conditions/submit-an-application-single-policy-type-with-alternative-turnover-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover-currency/turnover-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover-currency/turnover-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-financial-year-end.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/index.js
  e2e-tests/shared-test-assertions/currency-form-fields/prefix.js
  src/ui/server/constants/routes/insurance/business.ts
  src/ui/server/constants/templates/insurance/business/index.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/business/turnover-currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover-currency/index.ts
  src/ui/server/controllers/insurance/business/turnover-currency/validation/index.test.ts
  src/ui/server/controllers/insurance/business/turnover-currency/validation/index.ts
  src/ui/server/controllers/insurance/business/turnover-currency/validation/rules/alternative-currency.test.ts
  src/ui/server/controllers/insurance/business/turnover-currency/validation/rules/alternative-currency.ts
  src/ui/server/controllers/insurance/business/turnover-currency/validation/rules/currency.test.ts
  src/ui/server/controllers/insurance/business/turnover-currency/validation/rules/currency.ts
  src/ui/server/controllers/insurance/business/turnover-currency/validation/rules/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/templates/insurance/your-business/turnover.njk
Labels: feature

#2990 style(EMS-3785-3784): eligibility - content updates
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/contract-too-short/contract-too-short.spec.js
  e2e-tests/pages/insurance/eligibility/contractTooShort.js
  e2e-tests/pages/insurance/eligibility/index.js
  src/api/.keystone/config.js
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/templates/insurance/eligibility/contract-too-short.njk
Labels: enhancement

#2999 chore(EMS-3464): navigateToSignInAndSubmitForm command
  e2e-tests/commands/insurance/account/navigate-to-sign-in-and-submit-form.js
  e2e-tests/commands/login.js
  e2e-tests/commands/navigate-to-root-url.js
  e2e-tests/commands/shared-commands/account/index.js
  e2e-tests/commands/shared-commands/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in-with-an-expired-verification-inactive-state.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in-with-an-expired-verification.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in-with-an-unverified-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-retry/account-sign-in-retry-maximum-retries-with-invalid-credentials-suspends-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies-saved.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-accept.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/change-cookies-consent-via-banner-and-cookies-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/footer.spec.js
  e2e-tests/quote/cypress/e2e/journeys/give-feedback.spec.js
  e2e-tests/quote/cypress/e2e/journeys/privacy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/accessibility-statement.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body-answer-yes.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cannot-apply-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-policy-type-multiple-times-via-back-button.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-fields-multi-policy-credit-period.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/contact-us.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cookies-saved.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cookies.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location-answer-no.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/need-to-start-again.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-signed-in.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services-answer-no.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy-maximum-cover-period.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/skip-link.spec.js
Labels: tech, chore

#2950 chore(deps): bump dependencies
  e2e-tests/content-strings/links.js
  package-lock.json
  package.json
  src/api/.eslintrc.js
  src/api/.keystone/config.js
  src/api/content-strings/links.ts
  src/api/data-migration/version-1-to-version-2/README.md
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/content-strings/links.ts
Labels: dependencies, chore
