Repository UK-Export-Finance/exip, pull requests merged in 2024-02, with the labels that each got.

#1826 feat(EMS-2612-2371): No PDF - Your Buyer - Total outstanding additional fields
  e2e-tests/commands/insurance/complete-and-submit-alternative-currency-form.js
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-trading-history-with-buyer-form.js
  e2e-tests/commands/insurance/your-buyer/complete-trading-history-with-buyer-form.js
  e2e-tests/commands/shared-commands/assertions/assert-prefix.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-validation.spec.js
  e2e-tests/insurance/cypress/support/application/index.js
  e2e-tests/pages/your-business/turnover/index.js
  e2e-tests/partials/index.js
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/constants/templates/index.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/maximum-buyer-will-owe.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/total-sales-to-buyer.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/validation/rules/total-contract-value.ts
  src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.ts
  src/ui/server/shared-validation/date/index.test.ts
  src/ui/server/shared-validation/whole-number-above-minimum/index.test.ts
  src/ui/server/shared-validation/whole-number-above-minimum/index.ts
  src/ui/templates/components/monetary-value-input.njk
  src/ui/templates/insurance/your-buyer/trading-history.njk
  src/ui/templates/partials/insurance/buyer-outstanding-payment-conditional-yes-html.njk
Labels: feature

#1836 chore(EMS-2727): No PDF - Split up keystone API unit tests
  src/api/keystone-account.test.ts
  src/api/keystone-create-application-timestamp-updates.test.ts
  src/api/keystone-create-application.test.ts
  src/api/nullable-checkbox/index.ts
  src/api/test-helpers/buyer-trading-history.ts
  src/api/test-helpers/create-full-application.ts
  src/api/types/account/index.ts
  src/api/types/application-types/index.ts
Labels: tech, chore

#1827 chore(EMS-2726-2734): No PDF - Checked radio cypress commands
  e2e-tests/commands/insurance/assert-alternative-currency-form.js
  e2e-tests/commands/insurance/eligibility/assert-cover-period-radios.js
  e2e-tests/commands/insurance/eligibility/assert-total-value-insured-radios.js
  e2e-tests/commands/shared-commands/assertions/assert-no-radio-option-is-checked.js
  e2e-tests/commands/shared-commands/assertions/assert-radio-option-is-checked.js
  e2e-tests/commands/shared-commands/assertions/assert-yes-radio-option-is-checked.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-pre-credit-period-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house-number/companies-house-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/end-buyer/end-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-pre-credit-period-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/entering-details-of-policy-owner.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/name-on-policy-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit-different-trading-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/connection-to-the-buyer-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/save-and-back/no-connection-to-the-buyer-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/save-and-back/yes-connection-to-the-buyer-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body-answer-yes.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
Labels: tech, chore

#1843 chore(deps): Bump dependencies
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1833 fix(EMS-2709-2732): No PDF - Policy - Dynamic page titles with currency names
  database/exip.sql
  e2e-tests/commands/shared-commands/assertions/assert-heading-with-currency-name.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/content-strings/pages/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/map-submitted-data/index.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/graphql/queries/APIM/currencies.ts
  src/ui/server/helpers/mappings/map-currency-code-form-data/index.test.ts
  src/ui/server/helpers/mappings/map-currency-code-form-data/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-currencies.ts
  src/ui/templates/insurance/policy/single-contract-policy-total-contract-value.njk
Labels: bug, tech, chore, fix

#1842 chore(EMS-2722): No PDF - DRY E2E assertions for currency form fields
  e2e-tests/commands/insurance/assert-currency-form-fields.js
  e2e-tests/commands/insurance/check-policy-currency-code-input.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/form-submission.js
  e2e-tests/shared-test-assertions/currency-form-fields/index.js
  e2e-tests/shared-test-assertions/currency-form-fields/rendering.js
  e2e-tests/shared-test-assertions/index.js
Labels: documentation, tech, chore

#1848 feat(EMS-2474): No PDF - Your buyer - Buyer financial information page setup
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-buyer-financial-information-form.js
  e2e-tests/commands/insurance/your-buyer/complete-buyer-financial-information-form.js
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/support/application/buyer/index.js
  e2e-tests/pages/insurance/your-buyer/buyerFinancialAccounts.js
  e2e-tests/pages/insurance/your-buyer/index.js
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/index.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/validation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/validation/index.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/validation/rules/buyer-financial-information.test.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/validation/rules/buyer-financial-information.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/validation/rules/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/partials/insurance/buyer-financial-information-details.njk
Labels: feature

#1849 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1850 chore(EMS-2779): No PDF - Cypress command to click a "Save and back" button
  e2e-tests/commands/insurance/complete-business-section.js
  e2e-tests/commands/shared-commands/form/click-save-and-back-button.js
  e2e-tests/commands/shared-commands/form/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-about-goods-or-services-final-destination-known-to-unknown.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/save-and-back/no-connection-to-the-buyer-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/save-and-back/yes-connection-to-the-buyer-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/save-and-back.spec.js
Labels: tech, chore

#1841 feat(EMS-2372): No PDF - Your buyer - Trading history - Data saving and save and back
  database/exip.sql
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-trading-history-with-buyer-form.js
  e2e-tests/commands/insurance/your-buyer/complete-trading-history-with-buyer-form.js
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/save-and-back/trading-history-no-outstanding-payments-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/save-and-back/trading-history-yes-outstanding-payments-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js
  src/api/.keystone/config.js
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/save-and-back/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/strip-empty-form-fields/index.test.ts
  src/ui/server/helpers/strip-empty-form-fields/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/partials/insurance/buyer-outstanding-payment-conditional-yes-html.njk
Labels: feature

#1853 fix(EMS-2667-2778): No PDF - Policy - Different name on policy - validation
  database/exip.sql
  e2e-tests/content-strings/error-messages.js
  src/api/.keystone/config.js
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/content-strings/error-messages.ts
Labels: bug, chore, fix

#1858 chore(validation): No PDF - Clean UI validation rules
  e2e-tests/content-strings/error-messages.js
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/company-website.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/different-trading-name.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/phone-number.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/goods-or-services.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/years-exporting.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/improve-service.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/other-comments.ts
  src/ui/server/controllers/insurance/policy/broker/validation/rules/broker-address-line-one.ts
  src/ui/server/controllers/insurance/policy/broker/validation/rules/broker-email.ts
  src/ui/server/controllers/insurance/policy/broker/validation/rules/broker-name.ts
  src/ui/server/controllers/insurance/policy/broker/validation/rules/broker-postcode.ts
  src/ui/server/controllers/insurance/policy/broker/validation/rules/broker-town.ts
  src/ui/server/controllers/insurance/policy/broker/validation/rules/using-broker.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/email-address.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/first-name.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/last-name.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/position.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/maximum-buyer-will-owe.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/maximum-buyer-will-owe.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/total-sales-to-buyer.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/total-sales-to-buyer.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/validation/rules/total-contract-value.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/validation/rules/total-contract-value.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.ts
  src/ui/server/helpers/percentage-number-validation/index.ts
  src/ui/server/helpers/whole-number-validation/index.ts
  src/ui/server/shared-validation/whole-number-above-minimum/index.test.ts
  src/ui/server/shared-validation/whole-number-above-minimum/index.ts
Labels: tech, dependencies, chore

#1851 feat(EMS-2640-2586): No PDF - Policy - Other company details - Page setup
  .github/workflows/test.yml
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/another-company.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/other-company-details.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/templates/insurance/policy/other-company-details.njk
Labels: feature, chore

#1867 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1874 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1878 chore(tech): Various documentation, cypress command improvements
  e2e-tests/commands/shared-commands/assertions/assert-section-start-content.js
  e2e-tests/commands/shared-commands/assertions/check-completed-task-status.js
  e2e-tests/commands/shared-commands/assertions/check-intro-text.js
  e2e-tests/commands/shared-commands/assertions/check-link.js
  e2e-tests/commands/shared-commands/assertions/check-task-status.js
  e2e-tests/commands/shared-commands/assertions/check-text.js
  e2e-tests/commands/shared-commands/assertions/check-value.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/request-new-code/account-sign-in-request-new-code.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/application-submitted.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/complete-other-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-multiple-risks/cannot-apply-multiple-risks.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-if-eligible.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/long-term-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/start.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/company-website.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/different-trading-name.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/phone-number.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-name.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/goods-or-services.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/years-exporting.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/improve-service.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/other-comments.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/email.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/first-name.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/last-name.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/position.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/company-name/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/company-number/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/country/index.ts
  src/ui/server/helpers/combine-validation-rules/index.ts
  src/ui/server/helpers/companies-house-search/index.ts
  src/ui/server/helpers/get-data-to-save/index.ts
  src/ui/server/helpers/get-name-email-position-from-owner-and-policy/index.ts
  src/ui/server/helpers/percentage-number-validation/index.ts
  src/ui/server/helpers/whole-number-validation/index.ts
  src/ui/server/shared-validation/max-length/index.ts
  src/ui/server/shared-validation/phone-number/index.ts
Labels: documentation, tech, chore

#1880 feat(EMS-2514): No PDF - Your buyer - Buyer financial information - Data saving and save and back
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-buyer-financial-information-form.js
  e2e-tests/commands/insurance/your-buyer/complete-buyer-financial-information-form.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/save-and-back.spec.js
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/index.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/save-and-back/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
Labels: feature

#1886 feat(EMS-2473): No PDF - Buyer - Credit insurance cover - Data saving and save and back
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/credit-insurance-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/save-and-back/credit-insurance-cover-answer-no-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/save-and-back/credit-insurance-cover-answer-yes-save-and-back.spec.js
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/save-and-back/index.ts
  src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-relationship/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-relationship/index.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-relationship/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-relationship/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/partials/insurance/credit-insurance-cover-conditional-yes-html.njk
Labels: feature

#1885 fix(EMS-2786-2789): No PDF - Policy - Different name on policy - Form validation
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/validation/different-name-on-policy-validation.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/position.test.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/position.ts
  src/ui/templates/insurance/policy/different-name-on-policy.njk
Labels: bug, fix

#1882 fix(EMS-2809-2810-2811-2821): No PDF - Radio layout/alignment issues, missing "save and back" button
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/other-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-name-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/connection-to-the-buyer-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/validation/connection-to-the-buyer-validation.spec.js
  e2e-tests/pages/your-business/company-details/companyDetails.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/credit-control/index.test.ts
  src/ui/server/controllers/insurance/business/credit-control/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.ts
  src/ui/templates/insurance/your-business/company-details.njk
Labels: bug, chore, fix

#1887 fix(EMS-2808-2812): No PDF - Buyer - Radio order for trading history and prior trading history
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-validation.spec.js
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.ts
  src/ui/templates/insurance/your-buyer/trading-history.njk
Labels: fix

#1889 feat(EMS-2301): No PDF - Your buyer - Company or organisation - Remove MVP fields
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/pages/insurance/your-buyer/companyOrOrganisation.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/your-buyer/index.ts
  src/api/content-strings/fields/insurance/your-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
  src/ui/server/helpers/required-fields/your-buyer/index.test.ts
  src/ui/server/helpers/required-fields/your-buyer/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.ts
Labels: feature

#1895 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1898 feat(EMS-2628): No PDF - Your Buyer - Check your answers - Trading history summary list
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/form-titles.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/form-titles.ts
  src/ui/server/helpers/summary-lists/your-buyer/connection-with-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-buyer.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
Labels: feature

#1897 feat(EMS-2647): No PDF - Policy - Other company details - Data saving
  database/exip.sql
  e2e-tests/commands/insurance/complete-and-submit-other-company-details-form.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/other-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/validation/other-company-details-validation.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/scripts/accessible-autocomplete.js
  src/ui/server/api/keystone/application/update/jointlyInsuredParty.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/integrity.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/jointly-insured-party/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/jointly-insured-party/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/jointly-insured-party/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/country-code/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/country-code/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts
  src/ui/server/controllers/insurance/policy/type-of-policy/index.test.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/test-mocks/mock-jointly-insured-party.ts
  src/ui/templates/insurance/policy/other-company-details.njk
  src/ui/types/application.ts
Labels: documentation, enhancement, feature, tech

#1910 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1912 feat(EMS-2750): No PDF - Policy - Broker - Confirm address
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/pages/insurance/policy/brokerConfirmAddress.js
  e2e-tests/pages/insurance/policy/index.js
  e2e-tests/pages/shared/index.js
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.ts
  src/ui/server/controllers/insurance/policy/broker/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/templates/insurance/policy/broker-confirm-address.njk
Labels: feature, tech

#1920 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1924 fix(EMS-2864-2867): No PDF - Your buyer - Company or organisation - Page fixes
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-total-contract-value-above-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-address.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/address.ts
  src/ui/server/helpers/summary-lists/your-buyer/credit-insurance-history/index.test.ts
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
Labels: fix

#1925 feat(EMS-2826): No PDF - Nominated loss payee - Setup DB fields/schema
  database/exip.sql
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/create-an-application/index.test.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/helpers/create-a-loss-payee-financial-international/index.test.ts
  src/api/helpers/create-a-loss-payee-financial-international/index.ts
  src/api/helpers/create-a-loss-payee-financial-uk/index.test.ts
  src/api/helpers/create-a-loss-payee-financial-uk/index.ts
  src/api/helpers/create-a-nominated-loss-payee/index.test.ts
  src/api/helpers/create-a-nominated-loss-payee/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/applications.ts
  src/api/types/application-types/index.ts
  src/ui/server/graphql/queries/application.ts
Labels: documentation, tech, security, chore

#1927 feat(EMS-2852): No PDF - Your Buyer - Summary list currency
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/fixtures/application.js
  e2e-tests/helpers/format-currency.js
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/index.ts
Labels: feature

#1932 feat(EMS-2479): No PDF - Your buyer - Change your answers
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-buyer-financial-accounts.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-change-connection-to-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-credit-insurance-history.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-trading-history.spec.js
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
Labels: feature

#1931 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1934 feat(EMS-2854): No PDF - Policy - Confirm broker address - Multi line support
  e2e-tests/commands/insurance/complete-and-submit-broker-details-form.js
  e2e-tests/commands/insurance/complete-broker-details-form.js
  e2e-tests/constants/examples/full-address-examples.js
  e2e-tests/constants/examples/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address-multiple-lines.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/save-and-back.spec.js
  e2e-tests/pages/shared/index.js
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.test.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.ts
  src/ui/server/helpers/summary-lists/generate-address-object/index.ts
  src/ui/templates/insurance/policy/broker-confirm-address.njk
Labels: enhancement, tech

#1936 chore(EMS-2884): No PDF - DRY "Single/multiple" policy cypress commands
  e2e-tests/commands/insurance/complete-and-submit-policy-type-form.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-populated-application.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/another-company.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/validation/broker-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-different-name-to-same-name-then-back-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-same-name-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/different-name-on-policy-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/entering-details-of-policy-owner.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/validation/different-name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/validation/multiple-contract-policy-export-value-validation-maximum-buyer-will-owe.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/validation/multiple-contract-policy-export-value-validation-total-sales-to-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/name-on-policy-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/other-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/validation/other-company-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/validation/single-contract-policy-total-contract-value-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-special-characters/submit-policy-textarea-fields-with-special-characters.spec.js
Labels: documentation, tech, chore

#1938 fix(EMS-2881): No PDF - Your Buyer - Change your answers - Alternative currency
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-alternative-currency.spec.js
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
Labels: fix

#1939 feat(EMS-2755-2762): No PDF - Policy - Loss payee - Data saving
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-form.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-different-name-to-same-name-then-back-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-same-name-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/entering-details-of-policy-owner.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/ui/server/api/keystone/application/update/index.ts
  src/ui/server/api/keystone/application/update/nominatedLossPayee.ts
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/policy/broker/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/nominated-loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.api-error.test.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.ts
  src/ui/server/graphql/mutations/update-application/nominated-loss-payee.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-nominated-loss-payee.ts
  src/ui/types/application.ts
Labels: feature, tech

#1945 feat(EMS-2756): No PDF - Policy - Loss payee details - Page setup
  .github/workflows/test.yml
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address-multiple-lines.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/loss-payee-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/api/content-strings/fields/insurance/policy/index.ts
  src/api/helpers/create-a-nominated-loss-payee/index.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/templates/insurance/policy/loss-payee-details.njk
Labels: feature, tech, chore

#1946 chore(docs): Various documentation improvements/fixes; Update dependencies
  e2e-tests/commands/insurance/account/complete-sign-in-and-otp.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-change-broker.spec.js
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/controllers/insurance/policy/map-and-save/nominated-loss-payee/index.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.ts
  src/ui/server/helpers/summary-lists/policy/index.ts
  src/ui/server/helpers/summary-lists/policy/policy-contact-fields/index.ts
  src/ui/server/helpers/summary-lists/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/connection-with-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/credit-insurance-history/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/financial-accounts/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/index.ts
Labels: documentation, dependencies, chore

#1944 feat(EMS-2730): No PDF - Sign in - Change security code wording
  e2e-tests/commands/api/index.js
  e2e-tests/commands/insurance/account/complete-and-submit-enter-code-account-form.js
  e2e-tests/commands/insurance/account/complete-insurance-eligibility-sign-in-and-go-to-dashboard.js
  e2e-tests/commands/insurance/account/complete-sign-in-and-go-to-dashboard.js
  e2e-tests/commands/insurance/account/complete-sign-in-and-otp.js
  e2e-tests/commands/insurance/account/create-an-account-and-application-and-sign-in.js
  e2e-tests/commands/insurance/account/sign-in-and-assert-all-sections-url.js
  e2e-tests/commands/insurance/account/sign-in-and-go-to-url.js
  e2e-tests/constants/field-ids/insurance/account/index.js
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email-once-and-sign-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/resend-confirm-email/resend-confirm-email-twice-and-sign-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/manage/account-manage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/account-password-reset-and-sign-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-creation-and-sign-in-with-eligibility-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/account-sign-in-enter-code-without-completing-eligibility.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/account-sign-in-enter-code.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/request-new-code/account-sign-in-request-new-code.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-retry/account-sign-in-retry-multiple-times-with-valid-credentials.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-with-a-reactivated-account/account-sign-in-with-a-reactivated-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/sign-in-with-second-requested-sign-in-code.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-header-and-page-fields.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/account/index.ts
  src/api/constants/index.ts
  src/api/custom-resolvers/mutations/account-sign-in-new-code/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in-new-code/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.ts
  src/api/emails/access-code-email/index.test.ts
  src/api/emails/access-code-email/index.ts
  src/api/emails/index.ts
  src/api/emails/security-code-email/index.ts
  src/api/helpers/generate-otp-and-update-account/index.ts
  src/api/helpers/generate-otp/index.test.ts
  src/api/helpers/generate-otp/index.ts
  src/api/helpers/is-valid-otp/index.ts
  src/ui/server/constants/field-ids/insurance/account/index.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/index.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/validation/rules/access-code.test.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/validation/rules/access-code.ts
  src/ui/server/controllers/insurance/account/sign-in/enter-code/validation/rules/index.ts
  src/ui/server/controllers/insurance/account/sign-in/request-new-code/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
  src/ui/templates/insurance/account/sign-in/request-new-code.njk
Labels: feature

#1947 chore(test): Split up "Your buyer" E2E tests
  .github/workflows/test.yml
Labels: chore

#1948 feat(EMS-2898): Database tier
  .github/workflows/infrastructure.yml
Labels: documentation, enhancement

#1951 chore(main): release 2.5.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1967 feat(EMS-2914): Application submission - XLSX - Declarations fields
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/content-strings/XLSX.ts
  src/api/content-strings/fields/insurance/declarations/index.ts
  src/api/content-strings/fields/insurance/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-agreed-field/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-agreed-field/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/map-yes-no-field/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.ts
  src/api/types/xlsx-types/index.ts
Labels: documentation, enhancement, feature, chore

#1955 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1976 fix(EMS-2873): Cookies consent banner - "view cookies" link
  .github/workflows/test.yml
  e2e-tests/commands/analytics/check-analytics-cookies-consent-and-accept.js
  e2e-tests/commands/analytics/check-cookies-consent-banner-is-visible.js
  e2e-tests/commands/core-page-checks.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies-consent/cookies-consent.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent.spec.js
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/templates/partials/cookies-banner.njk
  src/ui/types/page-variables.d.ts
Labels: bug, documentation, tech, fix

#1977 chore(main): release 2.6.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
