Repository UK-Export-Finance/exip, pull requests merged in 2024-11, with the labels that each got.

#3270 chore(main): release 2.36.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3219 chore(EMS-3957): dry countries, currencies calls
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/custom-resolvers/index.ts
  src/api/custom-resolvers/mutations/account-password-reset/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/custom-resolvers/mutations/create-feedback/index.ts
  src/api/custom-resolvers/mutations/create-many-applications/index.ts
  src/api/custom-resolvers/mutations/delete-an-account/index.ts
  src/api/custom-resolvers/mutations/delete-application-by-reference-number/index.ts
  src/api/custom-resolvers/mutations/send-email-confirm-email-address/index.ts
  src/api/custom-resolvers/mutations/send-email-insurance-feedback/index.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.ts
  src/api/custom-resolvers/mutations/submit-application/index.ts
  src/api/custom-resolvers/queries/get-APIM-CIS-countries/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-CIS-countries/index.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.ts
  src/api/custom-resolvers/queries/get-companies-house-information/index.ts
  src/api/custom-resolvers/queries/get-countries-and-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-countries-and-currencies/index.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.ts
  src/api/custom-resolvers/queries/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/get-APIM-CIS-countries/index.test.ts
  src/api/helpers/get-APIM-CIS-countries/index.ts
  src/api/helpers/get-APIM-currencies/index.test.ts
  src/api/helpers/get-APIM-currencies/index.ts
  src/api/helpers/map-currencies/index.ts
  src/api/schema.graphql
  src/api/test-mocks/index.ts
  src/api/types/country/index.ts
  src/api/types/currency/index.ts
  src/api/types/generic/index.ts
  src/ui/server/api/keystone/get-countries-and-currencies/index.ts
  src/ui/server/api/keystone/index.ts
  src/ui/server/api/keystone/page/index.ts
  src/ui/server/controllers/insurance/check-your-answers/export-contract/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/export-contract/index.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
  src/ui/server/graphql/queries/countries-and-currencies.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-countries-and-currencies.ts
Labels: documentation, tech, chore

#3249 chore(EMS-3810): dry cypress commands for empty field values
  e2e-tests/commands/shared-commands/assertions/assert-empty-agent-charges-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-agent-details-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-autocomplete-field-value.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-field-value.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-loss-payee-details-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-loss-payee-financial-international-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-loss-payee-financial-uk-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-other-company-details-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-overdue-or-outstanding-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-textarea-field-value.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded-from-other-method.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details-trading-address-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/complete-eligibility-answers-for-a-second-time.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-service/change-your-answers-agent-service-charging-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/how-the-contract-was-awarded/change-your-answers-how-the-contract-was-awarded-from-other-method.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/multiple-policy/change-your-answers-change-policy-type-multiple-to-single-to-multiple.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/single-policy/change-your-answers-change-policy-type-single-to-multiple-to-single.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details-trading-address-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit-different-trading-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/save-and-back/yes-connection-with-the-buyer-save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/credit-insurance-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/save-and-back/credit-insurance-cover-answer-yes-save-and-back.spec.js
Labels: tech

#3278 chore(EMS-3966): update dependabot to run during non working hours
  .github/dependabot.yml
Labels: chore

#3276 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#3300 chore(main): release 2.36.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3301 fix(EMS-3988): regenerate api schema
  src/api/.keystone/config.js
Labels: chore

#3302 chore(main): release 2.36.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3305 fix(EMS-3988): apply - type of policy - hint text
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/pages/insurance/policy/typeOfPolicy.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
Labels: bug, tech, chore, fix

#3306 chore(main): release 2.36.3
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3295 feat(EMS-3972): broker details - based in the uk form fields
  .github/dependabot.yml
  .release-please-manifest.json
  CHANGELOG.md
  database/exip.sql
  e2e-tests/commands/insurance/complete-broker-details-form.js
  e2e-tests/commands/shared-commands/assertions/assert-broker-details-field-values.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-with-broker-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-with-broker-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/validation/broker-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-a-pure-number/submit-textarea-fields-with-a-pure-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-policy-textarea-fields-with-new-line-characters.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type.spec.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/fully-populated.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/minimal.js
  package-lock.json
  package.json
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.ts
  src/ui/server/helpers/required-fields/policy/index.test.ts
  src/ui/server/helpers/required-fields/policy/index.ts
  src/ui/server/test-mocks/mock-broker.ts
  src/ui/templates/insurance/policy/broker-details.njk
Labels: enhancement, feature, chore

#3293 chore(EMS-3970): add missing %o to console error logs
  e2e-tests/commands/api/index.js
  e2e-tests/commands/insurance/account/delete-account.js
  e2e-tests/commands/insurance/create-an-abandoned-application.js
  e2e-tests/commands/insurance/create-an-application.js
  e2e-tests/commands/insurance/create-applications.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.ts
  src/ui/server/controllers/insurance/business/turnover-currency/save-and-back/index.ts
Labels: chore

#3294 chore(EMS-3971): simplify some pageVariables, add documentation
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/controllers/insurance/business/company-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/index.ts
  src/ui/server/controllers/insurance/your-buyer/buyer-financial-information/index.ts
  src/ui/server/controllers/insurance/your-buyer/failed-to-pay-on-time/index.ts
  src/ui/server/controllers/insurance/your-buyer/outstanding-or-overdue-payments/index.ts
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
Labels: documentation, chore

#3296 chore(EMS-3980): remove unnecessary 'should exist' e2e assertions
  e2e-tests/commands/core-page-checks.js
  e2e-tests/commands/insurance/account/assert-password-reveal-button.js
  e2e-tests/commands/shared-commands/assertions/check-email-field-rendering.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/account-sign-in-enter-code.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/eligible-to-apply-online/eligible-to-apply-online.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/cookies-consent/banner/cookies-consent-reject.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/skip-link.spec.js
Labels: tech, chore

#3297 feat(EMS-3981): broker addresses - initial page setup
  .github/workflows/test.yml
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/nature-of-business/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/broker/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee/index.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/templates/insurance/policy/broker-addresses.njk
Labels: feature, chore

#3303 feat(EMS-3981-3984): broker addresses - ordnance survey integration
  .cspell.json
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/constants/field-ids/insurance/policy/index.ts
  src/api/content-strings/fields/insurance/policy/index.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.ts
  src/api/helpers/map-address/index.test.ts
  src/api/helpers/map-address/index.ts
  src/api/helpers/map-and-filter-address/index.test.ts
  src/api/helpers/map-and-filter-address/index.ts
  src/api/helpers/map-and-filter-ordnance-survey-addresses/index.test.ts
  src/api/helpers/map-and-filter-ordnance-survey-addresses/index.ts
  src/api/helpers/map-ordnance-survey-address/index.test.ts
  src/api/helpers/map-ordnance-survey-address/index.ts
  src/api/test-mocks/mock-ordnance-survey-response.ts
  src/api/test-mocks/mock-os-address-input.ts
  src/api/types/ordnance-survey/index.ts
  src/ui/server/api/keystone/get-companies-house-information/index.ts
  src/ui/server/api/keystone/get-ordnance-survey-address/index.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/graphql/queries/ordnance-survey-address.ts
  src/ui/server/helpers/mappings/map-ordnance-survey-addresses/index.test.ts
  src/ui/server/helpers/mappings/map-ordnance-survey-addresses/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-ordnance-survey-address-response.ts
  src/ui/templates/insurance/policy/broker-addresses.njk
  src/ui/types/address.d.ts
  src/ui/types/apollo/index.d.ts
  src/ui/types/index.d.ts
  src/ui/types/ordnance-survey.d.ts
Labels: enhancement, feature, tech

#3312 feat(EMS-3977): broker details - form validation updates
  database/exip.sql
  e2e-tests/commands/insurance/complete-broker-details-form.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/validation/broker-details-validation.spec.js
  src/api/.keystone/config.js
  src/api/constants/validation.ts
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/building-number-or-name/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/building-number-or-name/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/is-based-in-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/is-based-in-uk/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/postcode/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/postcode/index.ts
  src/ui/server/shared-validation/postcode/index.test.ts
  src/ui/server/shared-validation/postcode/index.ts
  src/ui/server/test-mocks/mock-broker.ts
  src/ui/templates/insurance/policy/broker-details.njk
Labels: enhancement, feature, chore

#3322 feat(EMS-3974): broker details - pre-population updates
  e2e-tests/commands/insurance/complete-and-submit-broker-details-form.js
  e2e-tests/commands/insurance/complete-broker-details-form.js
  e2e-tests/commands/shared-commands/assertions/assert-broker-details-field-values.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit-different-trading-address-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit-different-trading-name.spec.js
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.test.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
Labels: enhancement, feature, chore

#3319 feat(EMS-3996): broker addresses - form validation, redirect
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/templates/insurance/eligibility/cover-period.njk
  src/ui/templates/insurance/eligibility/total-value-insured.njk
  src/ui/templates/insurance/policy/broker-addresses.njk
Labels: enhancement, chore

#3304 feat(EMS-3994): broker zero addresses - initial page setup
  .github/workflows/test.yml
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-page.spec.js
  e2e-tests/pages/insurance/policy/brokerZeroAddresses.js
  e2e-tests/pages/insurance/policy/index.js
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/templates/insurance/policy/broker-zero-addresses.njk
Labels: feature
