Repository UK-Export-Finance/exip, pull requests merged in 2024-07, with the labels that each got.

#2649 fix(EMS-3518): no pdf - application submission - XLSX - final destination
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-fully-populated.spec.js
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-final-destination/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-final-destination/index.ts
  src/api/test-mocks/mock-application.ts
Labels: bug, chore, fix

#2621 feat(EMS-2433): no PDF - Eligibility - No short term cover redirect
  .github/workflows/test.yml
  e2e-tests/commands/insurance/eligibility/enter-country-and-assert-exit-page-url-buyer-country.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/fixtures/countries.js
  e2e-tests/insurance/cypress/e2e/journeys/apply-offline-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-country-only-apply-offline.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-no-short-term-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-countries.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/support/eligibility/index.js
  src/api/.keystone/config.js
  src/api/constants/external-apis.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-offline/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-offline/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/can-apply-for-insurance-online/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-insurance-support/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/no-insurance-support/index.ts
  src/api/schema.graphql
  src/api/test-mocks/mock-mapped-CIS-countries.ts
  src/api/types/country/index.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/controllers/insurance/apply-offline/index.test.ts
  src/ui/server/controllers/insurance/apply-offline/index.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/country-redirects.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.test.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/index.ts
  src/ui/server/controllers/quote/buyer-country/index.test.ts
  src/ui/server/graphql/queries/APIM/CIS-countries.ts
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/test-mocks/mock-countries.ts
  src/ui/types/country.d.ts
Labels: feature

#2653 fix(EMS-3234): no PDF - Export contract - Fixed sum amount - decimal number data saving
  database/exip.sql
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-agent-charges-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/helpers/format-currency.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum-decimals-multiple-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum-decimals.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-as-decimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated-with-agent-charges-fixed-sum-decimal.spec.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/fully-populated.js
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/helpers/format-currency/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/format-currency/index.ts
  src/api/helpers/format-currency/index.test.ts
  src/api/helpers/format-currency/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/regex.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts
  src/ui/server/helpers/format-currency/index.test.ts
  src/ui/server/helpers/format-currency/index.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.test.ts
  src/ui/server/helpers/mappings/map-application-to-form-fields/index.ts
  src/ui/server/helpers/number/index.test.ts
  src/ui/server/helpers/number/index.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.test.ts
  src/ui/server/helpers/summary-lists/export-contract/agent-fields/agent-charges/index.ts
Labels: fix

#2669 fix(EMS-3534): no pdf - account sign in - password input width
  e2e-tests/commands/insurance/check-export-contract-summary-list.js
  src/ui/templates/insurance/account/sign-in/sign-in.njk
Labels: bug, fix

#2670 fix(EMS-1269): no PDF - CRON - Submission deadline email
  src/api/.keystone/config.js
  src/api/helpers/send-email-application-submission-deadline/send-email/index.test.ts
  src/api/helpers/send-email-application-submission-deadline/send-email/index.ts
Labels: fix

#2674 chore(mysql-issue): downgraded mysql version
  docker-compose.yml
Labels: chore

#2677 fix(EMS-3524): no pdf - data migration - eligibility section review condition
  database/exip.sql
  e2e-tests/constants/field-ids/insurance/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/index.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-application-migrated-field.ts
  src/api/data-migration/version-1-to-version-2/update-applications/index.ts
  src/api/data-migration/version-1-to-version-2/update-applications/update-application-migrated.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/can-submit-application/index.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/required-fields/check-your-answers/index.test.ts
  src/ui/server/helpers/required-fields/check-your-answers/index.ts
  src/ui/server/helpers/required-fields/section-review/index.test.ts
  src/ui/server/helpers/required-fields/section-review/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: bug, tech, chore, fix

#2679 chore(mysql-downgrade): no PDF - MySQL version downgrade
  docker-compose.yml
Labels: chore

#2673 fix(EMS-3530): no PDF - Pure number in text field
  .github/workflows/test.yml
  e2e-tests/commands/insurance/complete-and-submit-other-company-details-form.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/other-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-a-pure-number/submit-textarea-fields-with-a-pure-number.spec.js
  src/api/helpers/send-email-application-submission-deadline/send-email/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
Labels: fix

#2678 fix(EMS-3546): no PDF - Export contract - Agent charges - Fixed sum commas
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-with-comma.spec.js
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts
Labels: fix

#2662 chore(deps): bump dependencies
  docker-compose.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/shared-validation/requested-start-date/index.test.ts
Labels: dependencies, chore

#2671 chore(merge): merge main into no-pdf
  .github/workflows/deployment.yml
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-a-pure-number/submit-textarea-fields-with-a-pure-number.spec.js
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2672 fix(EMS-3439): no pdf - business - company name with special characters
  e2e-tests/commands/insurance/account/complete-insurance-eligibility-sign-in-and-go-to-dashboard.js
  e2e-tests/commands/insurance/account/complete-sign-in-and-go-to-application.js
  e2e-tests/commands/insurance/assert-companies-house-summary-list.js
  e2e-tests/commands/insurance/check-your-answers-eligibility-summary-list.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/commands/insurance/create-an-application.js
  e2e-tests/commands/insurance/eligibility/submit-answers-from-exporter-location-happy-path.js
  e2e-tests/commands/insurance/eligibility/submit-answers-happy-path.js
  e2e-tests/fixtures/companies.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/business-conditions/submit-an-application-multiple-policy-type-business-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/business-conditions/submit-an-application-multiple-policy-type-company-name-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/business-conditions/submit-an-application-single-policy-type-business-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/business-conditions/submit-an-application-single-policy-type-company-name-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-multiple-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-your-answers/eligibility-check-your-answers-company-name-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details-company-name-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/eligible-to-apply-online/eligible-to-apply-online-already-signed-in-with-eligibility-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/header-authenticated-insurance-eligibility.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-header-and-page-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page-company-name-special-characters.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-exporter-location-routes/complete-insurance-eligibility-then-get-a-quote.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-exporter-location-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  src/api/.keystone/config.js
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/emails/send-application-submitted-emails/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-key-information/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-key-information/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/helpers/mappings/map-name-fields/index.test.ts
  src/ui/server/helpers/mappings/map-name-fields/index.ts
Labels: bug, documentation, tech, chore, fix

#2689 chore(mysql-authentication): docker-compose - MySQL authentication
  docker-compose.yml
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: chore

#2681 style(content): no pdf - various content updates
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/content-strings/uk-goods-and-services-description.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-with-the-buyer/connection-with-the-buyer-page.spec.js
  e2e-tests/pages/insurance/your-buyer/buyerFinancialAccounts.js
  e2e-tests/pages/insurance/your-buyer/connectionWithBuyer.js
  e2e-tests/pages/insurance/your-buyer/index.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/account/index.ts
  src/api/content-strings/fields/insurance/policy/index.ts
  src/api/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/content-strings/uk-goods-and-services-description.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.ts
  src/ui/templates/partials/insurance/buyer-financial-information-details.njk
  src/ui/templates/partials/insurance/connection-with-the-buyer-conditional-yes-html.njk
  src/ui/templates/partials/insurance/connection-with-the-buyer-hint.njk
Labels: enhancement

#2691 style(EMS-3504): no pdf - uk goods or services - content alignment
  e2e-tests/content-strings/pages/quote.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/partials/ukGoodsAndServicesDescription.js
  e2e-tests/quote/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/pages/quote.ts
  src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/eligibility/uk-goods-or-services/index.ts
  src/ui/server/controllers/quote/uk-goods-or-services/index.test.ts
  src/ui/server/controllers/quote/uk-goods-or-services/index.ts
  src/ui/templates/partials/quote/quote-uk-goods-and-services-details.njk
  src/ui/templates/partials/uk-goods-and-services-details.njk
Labels: enhancement, chore

#2699 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2692 chore(EMS-3550): no pdf - updateCompanyPostDataMigration unit test coverage
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/update-company-post-data-migration/index.test.ts
  src/api/custom-resolvers/mutations/update-company-post-data-migration/index.ts
  src/api/helpers/create-company-sic-codes/index.test.ts
  src/api/helpers/create-company-sic-codes/index.ts
Labels: tech, chore

#2703 chore(deps): no pdf - bump dependencies
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2698 feat(EMS-1289): add azure DNS zone
  .cspell.json
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
Labels: enhancement

#2705 feat(EMS-3547): Azure MySQL Flexible server version set
  .github/workflows/infrastructure.yml
Labels: feature

#2704 feat(validate-yml): added YAML validation
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  package-lock.json
  package.json
Labels: feature

#2707 chore(EMS-3558): no pdf - insurance/apply URL, redirects
  .github/workflows/test.yml
  e2e-tests/constants/routes/business.js
  e2e-tests/constants/routes/insurance/account.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/insurance/cypress/e2e/journeys/redirects/redirects-account-urls.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/redirects/redirects-application-urls.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/redirects/redirects.spec.js
  src/ui/server/constants/application/index.ts
  src/ui/server/constants/routes/insurance/account.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/index.test.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/index.ts
  src/ui/server/controllers/redirects/index.test.ts
  src/ui/server/controllers/redirects/index.ts
  src/ui/server/helpers/generate-redirect-url/index.test.ts
  src/ui/server/helpers/generate-redirect-url/index.ts
  src/ui/server/helpers/is-insurance-route/index.test.ts
  src/ui/server/helpers/is-insurance-route/index.ts
  src/ui/server/index.ts
  src/ui/server/routes/index.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.ts
  src/ui/server/routes/quote/index.ts
  src/ui/server/routes/redirects/index.test.ts
  src/ui/server/routes/redirects/index.ts
  src/ui/server/routes/root/index.ts
  src/ui/server/test-mocks/mock-feedback.ts
Labels: documentation, enhancement, tech, chore

#2715 chore(deployment-script): deployment - Change feature branch
  .github/workflows/deploy.sh
Labels: chore

#2708 chore(remove-script-prefix): package.json - Remove --prefix
  package.json
Labels: chore

#2722 chore(main): release 2.10.0
  .cspell.json
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2720 fix(EMS-3560): update az cli to v2
  .github/github.yml
  .github/workflows/deployment.yml
  .github/workflows/github.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/generate-quote/pricing-grid.json
Labels: fix

#2724 chore(main): release 2.10.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2725 chore(main): release 2.11.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2714 feat(EMS-3087): iterations - Loss payee financial international - IBAN and bicSwiftCode uppercase
  .cspell.json
  e2e-tests/fixtures/ibans.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/loss-payee-financial-details-international-lower-case.spec.js
  src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee-financial-details/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee-financial-details/index.ts
Labels: feature

#2728 fix(EMS-3439-3504): eligibility, application submission email copy fixes
  e2e-tests/commands/shared-commands/assertions/check-uk-goods-and-services-description.js
  e2e-tests/content-strings/uk-goods-and-services-description.js
  e2e-tests/partials/ukGoodsAndServicesDescription.js
  src/api/.keystone/config.js
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/emails/send-application-submitted-emails/index.ts
  src/ui/server/content-strings/uk-goods-and-services-description.ts
  src/ui/templates/partials/uk-goods-and-services-description.njk
Labels: bug, fix

#2732 chore(main): release 2.11.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2738 fix(EMS-3590-3591-3423): header link, integrity hashes
  CHANGELOG.md
  e2e-tests/commands/shared-commands/assertions/check-header-service-name-href.js
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/insurance/cypress/e2e/journeys/redirects/redirects.spec.js
  src/ui/public/css/styles.css
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/public/js/main.js
  src/ui/public/js/main.js.map
  src/ui/server/constants/integrity.ts
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
Labels: bug, chore, fix

#2740 chore(main): release 2.11.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2690 feat(EMS-3265-3201-3270-3271): iterations - Account - Name fields validation
  e2e-tests/constants/examples/index.js
  e2e-tests/constants/examples/name-examples.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-policy-loss-payee-details.spec.js
  e2e-tests/shared-test-assertions/name-field-validation/index.js
  src/ui/server/constants/regex.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/first-name.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/first-name.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/last-name.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/rules/last-name.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/validation/rules/name/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-details/validation/rules/name/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.ts
  src/ui/server/controllers/insurance/policy/name-on-policy/validation/rules/position.test.ts
  src/ui/server/controllers/insurance/policy/name-on-policy/validation/rules/position.ts
  src/ui/server/shared-validation/alpha-characters-hyphen-and-apostrophe-only/index.test.ts
  src/ui/server/shared-validation/alpha-characters-hyphen-and-apostrophe-only/index.ts
  src/ui/server/shared-validation/alpha-characters-only/index.test.ts
  src/ui/server/shared-validation/alpha-characters-only/index.ts
  src/ui/server/shared-validation/name/index.test.ts
  src/ui/server/shared-validation/name/index.ts
  src/ui/server/shared-validation/number-hyphen-and-spaces-only/index.test.ts
  src/ui/server/shared-validation/number-hyphen-and-spaces-only/index.ts
  src/ui/server/shared-validation/regex-validation/index.test.ts
  src/ui/server/shared-validation/regex-validation/index.ts
Labels: feature

#2742 feat(EMS-3587-3425): contact page - content iterations
  e2e-tests/content-strings/contact.js
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/content-strings/pages/index.js
  e2e-tests/insurance/cypress/e2e/journeys/contact-us.spec.js
  e2e-tests/pages/contact-us.js
  e2e-tests/quote/cypress/e2e/journeys/quote/contact-us.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/account/index.ts
  src/ui/server/content-strings/contact/index.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/content-strings/pages/index.ts
  src/ui/templates/contact-us.njk
Labels: bug, enhancement, feature, fix

#2743 chore(main): release 2.12.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2739 chore(EMS-3559): iterations - SonarCloud consistency errors
  e2e-tests/commands/shared-commands/assertions/assert-first-and-last-radios.js
  src/api/custom-resolvers/mutations/account-sign-in-new-code/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-sign-in-checks/index.test.ts
  src/api/custom-resolvers/mutations/account-sign-in/index.test.ts
  src/api/custom-resolvers/mutations/create-feedback/index.test.ts
  src/api/custom-resolvers/mutations/send-email-insurance-feedback/index.test.ts
  src/api/custom-resolvers/mutations/send-email-password-reset-link/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-CIS-countries/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.test.ts
  src/api/emails/access-code-email/index.test.ts
  src/api/emails/application/index.test.ts
  src/api/emails/confirm-email-address/index.test.ts
  src/api/emails/documents/index.test.ts
  src/api/emails/insurance-feedback-email/index.test.ts
  src/api/emails/password-reset-link/index.test.ts
  src/api/emails/reactivate-account-link/index.test.ts
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/helpers/send-email-confirm-email-address/index.test.ts
  src/api/test-mocks/index.ts
  src/ui/server/api/keystone/applications/index.ts
  src/ui/server/helpers/get-application/index.test.ts
  src/ui/server/helpers/mappings/map-applications/index.ts
Labels: chore

#2755 chore(deps): bump dependencies
  CHANGELOG.md
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2737 feat(EMS-2186): added key vault
  .cspell.json
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
Labels: feature

#2723 feat(EMS-3083): iterations - Loss Payee International - BIC Swift Code - updated validation
  e2e-tests/shared-test-assertions/bic-swift-code-field-validation/index.js
  src/ui/server/constants/regex.ts
  src/ui/server/shared-validation/alpha-numerical-characters-only/index.test.ts
  src/ui/server/shared-validation/alpha-numerical-characters-only/index.ts
Labels: feature

#2757 chore(main): release 2.12.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2744 chore(EMS-3559): iterations - SonarCloud intentionality errors
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-uk/index.test.ts
  src/api/helpers/map-sic-codes/index.ts
  src/api/helpers/sort-array-alphabetically/index.ts
  src/ui/public/js/submitButton.js
  src/ui/scripts/accessible-autocomplete.js
  src/ui/scripts/google-tag-manager.js
  src/ui/server/api/keystone/application/get.ts
  src/ui/server/controllers/insurance/eligibility/buyer-country/country-redirects.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/helpers/array/index.ts
  src/ui/server/helpers/object/index.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-object/index.ts
  src/ui/server/helpers/sort-array-alphabetically/index.ts
  src/ui/server/helpers/string/index.test.ts
  src/ui/server/helpers/strip-empty-form-fields/index.ts
  src/ui/server/helpers/task-list/task-helpers.ts
  src/ui/types/index.d.ts
  src/ui/types/object.d.ts
Labels: chore

#2756 chore(EMS-3467): iterations - move total contract value threshold flag into the API
  .cspell.json
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.ts
  src/api/helpers/create-an-application/index.api-error.test.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/map-sic-codes/index.test.ts
  src/api/helpers/map-total-contract-value-over-threshold/index.test.ts
  src/api/helpers/map-total-contract-value-over-threshold/index.ts
  src/api/schema.graphql
  src/api/test-helpers/create-full-application.ts
  src/api/test-mocks/index.ts
  src/api/types/application-types/index.ts
  src/ui/server/api/keystone/application/get.ts
  src/ui/server/api/keystone/application/index.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/get-application-by-reference-number/index.test.ts
  src/ui/server/helpers/get-application/index.test.ts
  src/ui/server/helpers/get-application/index.ts
  src/ui/server/index.ts
  src/ui/server/middleware/insurance/get-application-by-reference-number/index.test.ts
  src/ui/server/middleware/insurance/get-application-by-reference-number/index.ts
  src/ui/server/middleware/insurance/get-application/index.test.ts
  src/ui/server/middleware/insurance/get-application/index.ts
  src/ui/server/middleware/insurance/map-total-contract-value-over-threshold/index.test.ts
  src/ui/server/middleware/insurance/map-total-contract-value-over-threshold/index.ts
Labels: tech, chore

#2769 chore(main): release 2.12.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2770 feat(EMS-3566): iterations - Policy - Pre credit period - Content changes
  e2e-tests/content-strings/credit-period-with-buyer-description.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/partials/creditPeriodWithBuyer.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/credit-period-with-buyer-description.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.ts
  src/ui/templates/partials/insurance/credit-period-with-buyer-description.njk
Labels: feature

#2777 feat(EMS-3606): added missing environment variables
  .github/workflows/infrastructure.yml
  .github/workflows/test.yml
Labels: feature

#2779 chore(main): release 2.13.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2783 feat(EMS-3610): no PDF - Export contract - Agent - Content change
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
Labels: feature

#2784 chore(main): release 2.14.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2778 feat(EMS-3535): Declarations - Anti-bribery and Corruption - Content changes
  e2e-tests/content-strings/pages/insurance/declarations/index.js
  src/ui/server/content-strings/pages/insurance/declarations/index.ts
Labels: feature

#2786 chore(main): release 2.15.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2775 feat(EMS-3565): iterations - Eligibility - Eligible to apply online - Content
  e2e-tests/constants/application.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/eligible-to-apply-online/eligible-to-apply-online.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/no-access-to-application/no-access-to-application-abandoned.spec.js
  e2e-tests/pages/insurance/eligibility/eligibleToApplyOnline.js
  src/api/.keystone/config.js
  src/api/constants/application/index.ts
  src/api/constants/cron/index.ts
  src/api/helpers/get-inactive-applications/index.ts
  src/api/helpers/update-inactive-applications/index.ts
  src/ui/server/constants/application/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/templates/insurance/eligibility/eligible-to-apply-online.njk
Labels: feature

#2801 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2776 chore(EMS-3429): iterations - Verify email address - Invalid token
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-invalid-link.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/verify-account-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.ts
Labels: chore

#2789 feat(EMS-3536-3540): remove 'how your data will be used' declaration
  .github/workflows/test.yml
  e2e-tests/commands/insurance/complete-declarations.js
  e2e-tests/commands/insurance/declarations/complete-and-submit-how-your-data-will-be-used-form.js
  e2e-tests/constants/field-ids/insurance/declarations/index.js
  e2e-tests/constants/routes/insurance/declarations.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/declarations/index.js
  e2e-tests/content-strings/pages/insurance/declarations/how-your-data-will-be-used/index.js
  e2e-tests/content-strings/pages/insurance/declarations/index.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/application-submitted.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/cannot-skip-flow/declarations/navigate-to-declarations-pages-without-completing-previous-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/how-your-data-will-be-used.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/no-access-application-submitted/no-access-application-submitted-declarations.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/no-access-to-application/cannot-access-application-signed-in-declarations.spec.js
  e2e-tests/insurance/cypress/support/declarations/index.js
  e2e-tests/pages/insurance/declarations/how-your-data-will-be-used.js
  e2e-tests/pages/insurance/declarations/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/declarations/index.ts
  src/api/content-strings/XLSX.ts
  src/api/content-strings/fields/insurance/declarations/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.ts
  src/api/test-mocks/index.ts
  src/api/test-mocks/mock-declarations.ts
  src/ui/server/constants/field-ids/insurance/declarations/index.ts
  src/ui/server/constants/routes/insurance/declarations.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/how-your-data-will-be-used/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/index.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.test.ts
  src/ui/server/controllers/insurance/declarations/how-your-data-will-be-used/index.ts
  src/ui/server/graphql/mutations/update-application/declaration.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/required-fields/declarations/index.test.ts
  src/ui/server/helpers/required-fields/declarations/index.ts
  src/ui/server/middleware/insurance/application-status/is-submit-your-application-route/index.test.ts
  src/ui/server/middleware/insurance/application-status/is-submit-your-application-route/index.ts
  src/ui/server/routes/insurance/declarations/index.test.ts
  src/ui/server/routes/insurance/declarations/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/server/test-mocks/mock-declarations.ts
  src/ui/types/application.ts
Labels: enhancement, chore

#2803 chore(main): release 2.16.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2802 chore(EMS-3631): declarations - Declaration versioning in constants
  CHANGELOG.md
  e2e-tests/content-strings/pages/insurance/declarations/anti-bribery/index.js
  src/ui/server/constants/declarations/get-latest-declarations/index.test.ts
  src/ui/server/constants/declarations/get-latest-declarations/index.ts
  src/ui/server/constants/declarations/index.ts
  src/ui/server/constants/declarations/versions/index.test.ts
  src/ui/server/constants/declarations/versions/index.ts
  src/ui/server/constants/index.ts
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery-code-of-conduct/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery-exporting-with-code-of-conduct/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/confidentiality/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/confirmation-and-acknowledgements/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/how-your-data-will-be-used/index.ts
  src/ui/types/application.ts
  src/ui/types/index.d.ts
  src/ui/types/object.d.ts
Labels: feature

#2804 chore(EMS-3631): declaration - Use of declaration constant in controllers
  e2e-tests/content-strings/fields/insurance/declarations/index.js
  e2e-tests/content-strings/fields/insurance/index.js
  e2e-tests/content-strings/pages/insurance/declarations/anti-bribery-code-of-conduct/index.js
  e2e-tests/content-strings/pages/insurance/declarations/anti-bribery-exporting-with-code-of-conduct/index.js
  e2e-tests/content-strings/pages/insurance/declarations/anti-bribery/index.js
  e2e-tests/content-strings/pages/insurance/declarations/confidentiality/index.js
  e2e-tests/content-strings/pages/insurance/declarations/confirmation-and-acknowledgements/index.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  src/ui/server/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/content-strings/fields/insurance/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery-code-of-conduct/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery-exporting-with-code-of-conduct/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/confidentiality/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/confirmation-and-acknowledgements/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/how-your-data-will-be-used/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/code-of-conduct/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/exporting-with-code-of-conduct/index.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.test.ts
  src/ui/server/controllers/insurance/declarations/anti-bribery/index.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.test.ts
  src/ui/server/controllers/insurance/declarations/confidentiality/index.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.test.ts
  src/ui/server/controllers/insurance/declarations/confirmation-and-acknowledgements/index.ts
  src/ui/templates/insurance/declarations/anti-bribery.njk
Labels: chore

#2785 chore(EMS-2656): iterations - E2E - text and value cypress command
  e2e-tests/commands/shared-commands/assertions/assert-different-name-on-policy-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-name-email-and-position-fields.js
  e2e-tests/commands/shared-commands/assertions/check-currency-option.js
  e2e-tests/commands/shared-commands/assertions/check-text-and-value.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/save-and-back.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-country-only-get-a-quote-by-email.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/assertions.js
Labels: chore

#2814 chore(main): release 2.17.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2816 chore(main): release 2.18.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2811 feat(EMS-1921): custom domain names for Azure front door
  .github/workflows/infrastructure.yml
  src/api/.env.sample
Labels: feature

#2819 feat(EMS-3633): data migration - declarations
  CHANGELOG.md
  database/exip.sql
  src/api/.keystone/config.js
  src/api/constants/declarations/index.test.ts
  src/api/constants/declarations/index.ts
  src/api/data-migration/version-1-to-version-2/README.md
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-field.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-relationship/index.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-relationship/non-submitted-applications.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/declaration-version-relationship/submitted-applications.ts
  src/api/data-migration/version-1-to-version-2/create-new-application-relationships/index.ts
  src/api/data-migration/version-1-to-version-2/create-tables/create-declaration-version-table.ts
  src/api/data-migration/version-1-to-version-2/create-tables/index.ts
  src/api/data-migration/version-1-to-version-2/get-all-declaration-versions.ts
  src/api/data-migration/version-1-to-version-2/get-all-declarations.ts
  src/api/data-migration/version-1-to-version-2/get-all-non-submitted-applications.ts
  src/api/data-migration/version-1-to-version-2/get-all-submitted-applications.ts
  src/api/data-migration/version-1-to-version-2/index.ts
  src/api/data-migration/version-1-to-version-2/remove-declaration-content-tables/anti-bribery.ts
  src/api/data-migration/version-1-to-version-2/remove-declaration-content-tables/confidentiality.ts
  src/api/data-migration/version-1-to-version-2/remove-declaration-content-tables/confirmation-and-acknowledgement.ts
  src/api/data-migration/version-1-to-version-2/remove-declaration-content-tables/how-data-will-be-used.ts
  src/api/data-migration/version-1-to-version-2/remove-declaration-content-tables/index.ts
  src/api/data-migration/version-1-to-version-2/remove-declaration-fields.ts
  src/api/data-migration/version-1-to-version-2/update-accounts/remove-account-status-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-declaration-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/add-declarations-export-contract-field.ts
  src/api/data-migration/version-1-to-version-2/update-applications/index.ts
  src/api/data-migration/version-1-to-version-2/update-applications/update-declaration-fields.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
Labels: documentation, feature, tech, chore

#2821 chore(main): release 2.19.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2822 chore(main): release 2.20.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2825 chore(main): release 2.21.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2823 feat(EMS-3613): declaration - Format of proposal
  CHANGELOG.md
  e2e-tests/content-strings/pages/insurance/declarations/anti-bribery-code-of-conduct/index.js
  e2e-tests/content-strings/pages/insurance/declarations/anti-bribery/index.js
  e2e-tests/content-strings/pages/insurance/declarations/confidentiality/index.js
  e2e-tests/content-strings/pages/insurance/declarations/confirmation-and-acknowledgements/index.js
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery-code-of-conduct/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/confidentiality/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/confirmation-and-acknowledgements/index.ts
Labels: feature

#2850 chore(main): release 2.22.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2837 feat(EMS-3660): export contract - how was contract awarded - UI setup
  CHANGELOG.md
  e2e-tests/commands/insurance/complete-and-submit-how-was-the-contract-awarded-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known-and-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-as-decimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges-fixed-sum-amount-with-comma.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/agent-charges.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/alternative-currency/alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back-method-percentage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-fixed-sum.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/agent-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-details/validation/agent-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/agent-service.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-service/validation/agent-service-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/agent.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/declined-by-private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-was-the-contract-awarded/how-was-the-contract-awarded.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/root/export-contract-root.spec.js
  e2e-tests/insurance/cypress/support/application/export-contract/index.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/constants/templates/insurance/export-contract/index.ts
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.ts
  src/ui/server/controllers/insurance/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/export-contract/how-was-the-contract-awarded.njk
Labels: enhancement, feature

#2852 feat(EMS-3676): eligibility - Check your answers - Member of group and party to consortium
  CHANGELOG.md
  e2e-tests/commands/insurance/check-your-answers-eligibility-summary-list.js
  e2e-tests/content-strings/fields/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-member-of-a-group.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-party-to-consortium.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-your-answers/eligibility-check-your-answers-page.spec.js
  src/ui/server/content-strings/fields/insurance/eligibility/index.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.test.ts
  src/ui/server/helpers/summary-lists/eligibility/eligibility-fields/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: enhancement, feature

#2857 chore(main): release 2.24.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2858 chore(main): release 2.25.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2856 feat(EMS-3665): export contract - how was contract awarded - data model
  .cspell.json
  CHANGELOG.md
  database/exip.sql
  e2e-tests/constants/export-contract-award-method.js
  e2e-tests/constants/index.js
  src/api/.keystone/config.js
  src/api/constants/export-contract-award-method/index.ts
  src/api/constants/index.ts
  src/api/helpers/create-an-application/index.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/export-contract-award-method.ts
  src/ui/server/constants/index.ts
Labels: feature, chore

#2860 chore(main): release 2.26.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2853 feat(EMS-3680-3682): eligibility - Data saving
  database/exip.sql
  e2e-tests/fixtures/application.js
  src/api/.keystone/config.js
  src/api/custom-schema/type-defs.ts
  src/api/helpers/create-an-eligibility/index.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/mock-application.ts
  src/ui/server/graphql/queries/application-by-reference-number.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/application-is-complete/index.test.ts
  src/ui/server/helpers/map-eligibility-answers/index.test.ts
  src/ui/server/helpers/map-eligibility-answers/index.ts
  src/ui/server/helpers/required-fields/eligibility/index.test.ts
  src/ui/server/helpers/required-fields/eligibility/index.ts
  src/ui/server/test-mocks/mock-eligibility.ts
Labels: feature

#2863 chore(main): release 2.27.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#2859 chore(EMS-3660): export contract - how was contract awarded - form fields
  CHANGELOG.md
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-was-the-contract-awarded/how-was-the-contract-awarded.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/api/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/constants/export-contract-award-method.ts
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-was-the-contract-awarded/index.ts
  src/ui/templates/insurance/export-contract/how-was-the-contract-awarded.njk
  src/ui/templates/insurance/policy/name-on-policy.njk
  src/ui/templates/partials/insurance/how-was-the-contract-awarded-other-html.njk
Labels: chore

#2861 feat(EMS-3667): eligibility - Check if eligible - Content change
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-if-eligible.spec.js
  src/api/types/application-types/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
Labels: feature

#2866 chore(main): release 2.28.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending
