Repository UK-Export-Finance/exip, pull requests merged in 2024-03, with the labels that each got.

#2016 chore(EMS-3025): E2E - Split eligiblity e2e tests
  .github/workflows/test.yml
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-number/companies-house-number-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-number/companies-house-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-search/companies-house-search-no-financial-year-end-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-search/companies-house-search.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-unavailable/companies-house-unavailable.spec.js
Labels: chore

#2025 feat(EMS-2874): No PDF - Policy - Update root URL
  e2e-tests/constants/routes/insurance/policy.js
  src/ui/server/constants/routes/insurance/policy.ts
Labels: feature

#2029 chore(EMS-2927): Your Buyer - Update DB for registrationNumber
  database/exip.sql
  src/api/.keystone/config.js
  src/api/schema.prisma
  src/api/schema.ts
Labels: chore

#2026 feat(EMS-2753): Policy - Loss payee - Save and back
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/save-and-back.spec.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/controllers/insurance/policy/loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/nominated-loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
Labels: feature

#1950 chore(EMS-2908): No PDF - Rename countryInput cypress selector
  e2e-tests/commands/autocomplete-keyboard-input.js
  e2e-tests/commands/forms.js
  e2e-tests/commands/insurance/assert-currency-form-fields.js
  e2e-tests/commands/insurance/complete-about-goods-or-services-form.js
  e2e-tests/commands/insurance/complete-and-submit-other-company-details-form.js
  e2e-tests/commands/shared-commands/assertions/assert-other-company-details-field-values.js
  e2e-tests/commands/shared-commands/assertions/check-buyer-country-form.js
  e2e-tests/insurance/cypress/e2e/journeys/apply-offline-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/complete-eligibility-answers-for-a-second-time.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-country-only-apply-offline.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-apply-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/changing-another-company-from-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/validation/other-company-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/nature-of-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/pages/shared/autoCompleteField.js
  e2e-tests/pages/shared/countryInput.js
  e2e-tests/pages/shared/index.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-country-only-get-a-quote-by-email.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country-unsupported-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/get-a-quote-via-email.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/shared-test-assertions/autocomplete-assertions/index.js
  e2e-tests/shared-test-assertions/country-autocomplete-input/index.js
  e2e-tests/shared-test-assertions/currency-form-fields/assertions.js
Labels: tech, chore

#2037 fix(EMS-3045-3046): No PDF - Policy/Your Buyer - Content and route bugs
  e2e-tests/commands/shared-commands/assertions/assert-section-start-content.js
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/root/your-buyer-root.spec.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
Labels: fix

#2034 feat(EMS-2830): No PDF - Policy - Check your answers - Contact Email
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/commands/shared-commands/assertions/assert-summary-list-row-value.js
  e2e-tests/commands/shared-commands/assertions/check-summary-list-field-change.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-multiple-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-single-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-pre-credit-period-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/check-your-answers-policy-multiple-same-name-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/check-your-answers-policy-single-different-name-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/check-your-answers-policy-single-same-name-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-broker.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-different-name-on-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-same-name-on-policy.spec.js
  src/ui/server/controllers/insurance/policy/map-submitted-data/loss-payee/index.ts
  src/ui/server/helpers/summary-lists/policy/policy-contact-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/policy-contact-fields/index.ts
Labels: feature

#2036 fix(EMS-2763-2788-3047): No PDF - Policy/Turnover - Alternative currency bugs
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-change-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-change-currency.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/index.js
  e2e-tests/shared-test-assertions/currency-form-fields/prefix.js
  src/ui/server/constants/routes/insurance/business.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
  src/ui/templates/insurance/your-business/turnover.njk
Labels: fix

#2038 feat(EMS-2765): No PDF - Policy - Loss Payee Details - Validation
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-details-form.js
  e2e-tests/commands/insurance/complete-loss-payee-details-form.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/loss-payee-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/location.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/location.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-loss-payee-details.ts
  src/ui/templates/insurance/policy/loss-payee-details.njk
Labels: feature

#2046 chore(EMS-3067): No PDF - E2E - Missing tests in test.yml
  .github/workflows/test.yml
  e2e-tests/commands/shared-commands/assertions/assert-section-start-content.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-about-goods-or-services-final-destination-known-to-unknown.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/export-contract/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-relationship/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-relationship/index.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.ts
  src/ui/templates/insurance/export-contract/check-your-answers.njk
Labels: chore

#1998 chore(deps): Bump dependencies
  .github/workflows/deployment.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/test-mocks/index.ts
Labels: dependencies, chore

#1971 fix(EMS-2905): No PDF - Task list - Policy section marked as "complete" when incomplete
  e2e-tests/commands/insurance/complete-broker-details-form.js
  e2e-tests/constants/field-ids/insurance/account/index.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/constants/field-ids/shared/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/save-and-back.spec.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/api/constants/field-ids/shared/index.ts
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/field-ids/shared/index.ts
  src/ui/server/helpers/flatten-application-data/index.test.ts
  src/ui/server/helpers/flatten-application-data/index.ts
  src/ui/server/helpers/required-fields/policy/index.test.ts
  src/ui/server/helpers/required-fields/policy/index.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.ts
Labels: bug, tech, chore, fix

#2051 fix(EMS-3046): No PDF - Policy - Incorrect routes
  e2e-tests/constants/routes/insurance/policy.js
  src/ui/server/constants/routes/insurance/policy.ts
Labels: fix

#2050 fix(EMS-2919): Your Buyer - Check your answers - Conditional "Trading history" rows
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/commands/insurance/complete-buyer-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-credit-insurance-cover-form.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-total-contract-value-above-threshold.spec.js
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/optional-fields/outstanding-payments/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/optional-fields/outstanding-payments/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/optional-fields/traded-with-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/trading-history/optional-fields/traded-with-buyer/index.ts
  src/ui/server/test-mocks/index.ts
Labels: bug, documentation, tech, fix

#2045 feat(EMS-2768): No PDF - Policy - Loss Payee Bank Details - Page setup
  .github/workflows/test.yml
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-financial-uk-form.js
  e2e-tests/commands/insurance/complete-loss-payee-financial-uk-form.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-uk/loss-payee-financial-uk.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-loss-payee-financial-uk.ts
  src/ui/templates/insurance/policy/loss-payee-financial-uk.njk
Labels: feature

#2062 chore(EMS-3072): DRY text input nunjucks component
  e2e-tests/commands/insurance/your-buyer/complete-credit-insurance-cover-form.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  src/ui/templates/components/address-field-input.njk
  src/ui/templates/components/monetary-value-input.njk
  src/ui/templates/components/password-input.njk
  src/ui/templates/components/personal-details-input.njk
  src/ui/templates/components/text-input.njk
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/password-reset/new-password.njk
  src/ui/templates/insurance/account/password-reset/password-reset.njk
  src/ui/templates/insurance/account/sign-in/enter-code.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
  src/ui/templates/insurance/eligibility/companies-house-search.njk
  src/ui/templates/insurance/policy/broker-details.njk
  src/ui/templates/insurance/policy/different-name-on-policy.njk
  src/ui/templates/insurance/policy/loss-payee-details.njk
  src/ui/templates/insurance/policy/loss-payee-financial-uk.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/name-on-policy.njk
  src/ui/templates/insurance/policy/other-company-details.njk
  src/ui/templates/insurance/your-business/companies_house_number.njk
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/templates/insurance/your-business/contact.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/quote/tell-us-about-your-policy.njk
Labels: documentation, tech, chore

#2069 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2068 fix(EMS-2912): No PDF - Regenerate integrity hashes
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/main.js
  src/ui/public/js/main.js.map
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/server/constants/integrity.ts
Labels: chore, fix

#2070 feat(EMS-2903): No PDF - Align all "full address" maximum characters validation rules
  database/exip.sql
  e2e-tests/constants/index.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/validation/broker-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-address.spec.js
  src/api/.keystone/config.js
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/constants/index.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.test.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/full-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/full-address/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/index.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/address.test.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/address.ts
  src/ui/server/shared-validation/full-address/index.test.ts
  src/ui/server/shared-validation/full-address/index.ts
  src/ui/server/shared-validation/name/index.test.ts
Labels: documentation, enhancement, tech, chore

#2077 feat(EMS-2766): No PDF - Policy - Loss payee details - Save and back
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/save-and-back.spec.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/nominated-loss-payee/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
Labels: feature

#2075 feat(EMS-2769-2770-2771): No PDF - Policy - Loss payee - UK financial details - Validation
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-financial-uk-form.js
  e2e-tests/commands/insurance/complete-loss-payee-financial-uk-form.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-uk/loss-payee-financial-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-uk/validation/account-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-uk/validation/financial-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-uk/validation/sort-code-validation.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/constants/index.ts
  src/ui/server/constants/regex.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-international/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/rules/account-number.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/rules/account-number.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/rules/financial-address.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/rules/financial-address.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/rules/sort-code.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-uk/validation/rules/sort-code.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/server/shared-validation/alpha-characters-only/index.ts
  src/ui/server/shared-validation/number-hyphen-and-spaces-only/index.test.ts
  src/ui/server/shared-validation/number-hyphen-and-spaces-only/index.ts
  src/ui/server/shared-validation/whole-number-minimum-maximum-length/index.test.ts
  src/ui/server/shared-validation/whole-number-minimum-maximum-length/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-loss-payee-financial-uk.ts
Labels: feature

#2076 chore(EMS-3077): No PDF - Policy - Modular UI routes
  .github/workflows/test.yml
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/constants/routes/insurance/policy/another-company.js
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/constants/routes/insurance/policy/check-your-answers.js
  e2e-tests/constants/routes/insurance/policy/index.js
  e2e-tests/constants/routes/insurance/policy/loss-payee.js
  e2e-tests/constants/routes/insurance/policy/multiple-contract-policy.js
  e2e-tests/constants/routes/insurance/policy/name-on-policy.js
  e2e-tests/constants/routes/insurance/policy/pre-credit-period.js
  e2e-tests/constants/routes/insurance/policy/root.js
  e2e-tests/constants/routes/insurance/policy/single-contract-policy.js
  e2e-tests/constants/routes/insurance/policy/type-of-policy.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/constants/routes/insurance/policy/another-company.ts
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/constants/routes/insurance/policy/check-your-answers.ts
  src/ui/server/constants/routes/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy/loss-payee.ts
  src/ui/server/constants/routes/insurance/policy/multiple-contract-policy.ts
  src/ui/server/constants/routes/insurance/policy/name-on-policy.ts
  src/ui/server/constants/routes/insurance/policy/pre-credit-period.ts
  src/ui/server/constants/routes/insurance/policy/root.ts
  src/ui/server/constants/routes/insurance/policy/single-contract-policy.ts
  src/ui/server/constants/routes/insurance/policy/type-of-policy.ts
  src/ui/server/routes/insurance/policy/another-company/index.test.ts
  src/ui/server/routes/insurance/policy/another-company/index.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/server/routes/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/routes/insurance/policy/check-your-answers/index.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.test.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.ts
  src/ui/server/routes/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/routes/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/routes/insurance/policy/name-on-policy/index.test.ts
  src/ui/server/routes/insurance/policy/name-on-policy/index.ts
  src/ui/server/routes/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/routes/insurance/policy/pre-credit-period/index.ts
  src/ui/server/routes/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/routes/insurance/policy/single-contract-policy/index.ts
  src/ui/server/routes/insurance/policy/type-of-policy/index.test.ts
  src/ui/server/routes/insurance/policy/type-of-policy/index.ts
Labels: tech, chore

#2078 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: chore

#2081 chore(EMS-3077): No PDF - Policy - Loss Payee - Financial details - Update naming conventions
  .github/workflows/test.yml
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-financial-details-international-form.js
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-financial-details-uk-form.js
  e2e-tests/commands/insurance/complete-loss-payee-financial-details-international-form.js
  e2e-tests/commands/insurance/complete-loss-payee-financial-details-uk-form.js
  e2e-tests/constants/routes/insurance/policy/loss-payee.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/loss-payee-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/loss-payee-financial-details-uk.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/constants/routes/insurance/policy/loss-payee.ts
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-international/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-international/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/index.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/account-number.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/account-number.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/financial-address.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/financial-address.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/sort-code.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/sort-code.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.test.ts
  src/ui/server/routes/insurance/policy/loss-payee/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-loss-payee-financial-details-international.ts
  src/ui/server/test-mocks/mock-loss-payee-financial-details-uk.ts
  src/ui/templates/insurance/policy/loss-payee-financial-details-international.njk
  src/ui/templates/insurance/policy/loss-payee-financial-details-uk.njk
Labels: tech, chore

#2090 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2091 fix(EMS-2962): No PDF - Your Buyer - Check your answers - Buyer country
  e2e-tests/commands/insurance/check-your-buyer-summary-list.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list-minimal.spec.js
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/check-your-answers/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/company-or-organisation/index.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.test.ts
  src/ui/server/helpers/summary-lists/your-buyer/index.ts
Labels: fix

#2092 fix(EMS-2969): No PDF - Your Buyer - Check your answers - Trading history fields
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/change-your-answers/change-your-answers-trading-history-yes-to-no.spec.js
  src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/map-submitted-data/buyer-trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/save-data/buyer-trading-history/index.ts
Labels: fix

#2098 fix(EMS-3079): No PDF - Policy - Loss Payee details - Wrong name validation
  e2e-tests/commands/insurance/complete-and-submit-loss-payee-details-form.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-policy-loss-payee-details.spec.js
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.ts
  src/ui/server/helpers/mappings/map-name-fields/index.test.ts
  src/ui/server/helpers/mappings/map-name-fields/index.ts
Labels: fix

#2117 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2124 chore(deps): Bump dependencies
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2129 chore(EMS-3095): No PDF - Various DB/keystone field additions, improvements
  database/exip.sql
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/account-password-reset/index.test.ts
  src/api/custom-resolvers/mutations/create-an-application/index.test.ts
  src/api/custom-resolvers/mutations/create-an-application/index.ts
  src/api/custom-resolvers/mutations/verify-account-email-address/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-reactivation-token/index.test.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.test.ts
  src/api/helpers/create-a-buyer-trading-history/index.test.ts
  src/api/helpers/create-a-jointly-insured-party/index.test.ts
  src/api/helpers/create-a-jointly-insured-party/index.ts
  src/api/helpers/create-a-loss-payee-financial-international/index.test.ts
  src/api/helpers/create-a-loss-payee-financial-uk/index.test.ts
  src/api/helpers/create-a-nominated-loss-payee/index.test.ts
  src/api/helpers/create-a-policy/index.test.ts
  src/api/helpers/create-a-private-market/index.test.ts
  src/api/helpers/create-a-private-market/index.ts
  src/api/helpers/create-an-export-contract/index.test.ts
  src/api/helpers/create-an-export-contract/index.ts
  src/api/helpers/create-full-timestamp-from-day-month/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/map-risk-category/index.test.ts
  src/api/keystone-create-application-timestamp-updates.test.ts
  src/api/keystone-create-application.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-helpers/applications.ts
  src/api/test-helpers/create-full-application.ts
  src/api/types/application-types/index.ts
Labels: tech, chore

#2138 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2137 fix(EMS-3081-3082-3084-3085-3086-3093): No PDF - Textarea character counters
  e2e-tests/commands/shared-commands/assertions/assert-dynamic-character-count.js
  e2e-tests/commands/shared-commands/assertions/assert-textarea-rendering.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/character-count.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/index.js
  e2e-tests/insurance/cypress/e2e/journeys/feedback/feedback-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/loss-payee-financial-details-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/connection-to-the-buyer-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/credit-insurance-cover.spec.js
  e2e-tests/pages/shared/field.js
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/index.ts
  src/ui/templates/insurance/feedback.njk
Labels: bug, tech, chore, fix

#2139 feat(EMS-2562): No PDF - Export contract - How you will get paid - Page setup
  e2e-tests/commands/shared-commands/assertions/assert-textarea-rendering.js
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/fields/insurance/export-contract/index.js
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/pages/insurance/export-contract/howWillYouGetPaid.js
  e2e-tests/pages/insurance/export-contract/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/api/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/constants/templates/insurance/export-contract/index.ts
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/export-contract/how-will-you-get-paid.njk
Labels: feature, chore

#2141 feat(EMS-2562): No PDF - Export contract - How will you get paid - UI/UX flow
  e2e-tests/commands/insurance/complete-about-goods-or-services-form.js
  e2e-tests/commands/insurance/complete-and-submit-how-you-will-get-paid-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services-final-destination-not-known.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/check-your-answers/check-your-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: feature

#2142 fix(EMS-2910): No PDF - Broker - Confirm address - multiple lines
  e2e-tests/commands/shared-commands/assertions/assert-length.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/constants/examples/multi-line-string-examples.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address-multiple-lines.spec.js
  e2e-tests/pages/shared/index.js
  src/api/test-mocks/mock-broker.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts
  src/ui/server/test-mocks/mock-broker.ts
  src/ui/templates/insurance/policy/broker-confirm-address.njk
  src/ui/types/application.ts
Labels: bug, tech, fix

#2130 feat(EMS-2824-2827): No PDF - Account forms - Align maximum allowed email characters
  e2e-tests/constants/examples/email-examples.js
  e2e-tests/constants/validation.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/validation/account-sign-in-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/validation/broker-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/validation/different-name-on-policy-validation.spec.js
  e2e-tests/shared-test-assertions/email-field-validation/index.js
  src/ui/server/constants/validation.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/account/sign-in/index.test.ts
  src/ui/server/controllers/insurance/account/sign-in/index.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/email.test.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/email.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/password.test.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/password.ts
  src/ui/server/helpers/is-valid-email/index.test.ts
  src/ui/server/helpers/is-valid-email/index.ts
  src/ui/server/shared-validation/email-and-password-incorrect/index.test.ts
  src/ui/server/shared-validation/email-and-password-incorrect/index.ts
  src/ui/server/shared-validation/email-and-password/index.test.ts
  src/ui/server/shared-validation/email-and-password/index.ts
  src/ui/server/shared-validation/email/index.test.ts
  src/ui/server/shared-validation/email/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-valid-email.ts
  src/ui/types/errors.ts
Labels: documentation, enhancement, tech, chore

#2144 feat(EMS-2563): No PDF - Export contract - How will you get paid - Form validation
  .github/workflows/test.yml
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/pages/insurance/export-contract/howWillYouGetPaid.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/account/sign-in/validation/rules/email.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.ts
  src/ui/server/controllers/insurance/business/company-details/validation/company-details/rules/trading-address.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/validation/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/validation/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/validation/rules/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/validation/rules/payment-terms-description.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/validation/rules/payment-terms-description.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/full-address/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/validation/rules/name/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-details/validation/rules/name.ts
  src/ui/server/controllers/insurance/your-buyer/company-or-organisation/validation/rules/address.ts
  src/ui/server/shared-validation/financial-address/index.ts
  src/ui/server/shared-validation/full-address/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: documentation, enhancement, feature, chore

#2147 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2146 feat(EMS-2937): No PDF - Export contract - Private market - Page setup
  .github/workflows/test.yml
  e2e-tests/constants/field-ids/insurance/export-contract/index.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/index.js
  e2e-tests/content-strings/pages/insurance/export-contract/index.js
  e2e-tests/content-strings/private-market-why-description.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/partials/index.js
  e2e-tests/partials/privateMarketWhyDescription.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/constants/field-ids/insurance/export-contract/index.ts
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/index.ts
  src/ui/server/content-strings/pages/insurance/export-contract/index.ts
  src/ui/server/content-strings/private-market-why-description.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/partials/insurance/private-market-why-description.njk
Labels: feature, tech, chore

#2148 chore(EMS-3110): No PDF - Update all E2E tests to use new DRY error summary list commands
  e2e-tests/commands/pagination/assert-pagination-does-not-exist.js
  e2e-tests/commands/shared-commands/assertions/assert-error-summary-list-does-not-exist.js
  e2e-tests/commands/shared-commands/assertions/assert-error-summary-list-length.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/commands/shared-commands/form/assert-field-errors.js
  e2e-tests/commands/shared-commands/form/submit-and-assert-radio-errors.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-creation-and-sign-in-with-eligibility-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-invalid-page-number-param.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-multiple-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-no-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-only-my-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-135-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-16-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-30-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-45-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-60-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-75-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-90-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/validation/account-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/validation/sort-code-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/validation/pre-credit-period-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-company-website-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-valid-phone-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-years-exporting-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/policy-type/policy-type-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy-validation.spec.js
  e2e-tests/shared-test-assertions/autocomplete-assertions/index.js
  e2e-tests/shared-test-assertions/email-field-validation/index.js
Labels: tech, chore

#2149 feat(EMS-2563-2937-2938): No PDF - Export contract - How will you get paid - Redirection logic
  e2e-tests/commands/insurance/complete-and-submit-private-market-form.js
  e2e-tests/commands/insurance/complete-buyer-section.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid-total-contract-value-over-threshold.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/routes/insurance/export-contract/index.test.ts
  src/ui/server/routes/insurance/export-contract/index.ts
  src/ui/server/routes/insurance/index.test.ts
Labels: documentation, enhancement, chore

#2160 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2162 fix(EMS-3080): No PDF - Policy - Check your answers - Broker address
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/commands/shared-commands/assertions/assert-broker-details-field-values.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address-multiple-lines.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/pages/shared/summaryList.js
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.ts
Labels: bug, chore, fix

#2161 feat(EMS-2938): No PDF - Export contract - Private market - Form validation
  e2e-tests/commands/insurance/complete-and-submit-private-market-form.js
  e2e-tests/commands/insurance/complete-export-contract-section.js
  e2e-tests/constants/routes/insurance/export-contract.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js
  src/ui/server/constants/routes/insurance/export-contract.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
  src/ui/server/test-mocks/mock-application.ts
Labels: enhancement, feature

#2164 chore(EMS-3109): No PDF - Object structured cypress commands - submitAndAssertRadioErrors
  e2e-tests/commands/shared-commands/form/submit-and-assert-radio-errors.js
  e2e-tests/insurance/cypress/e2e/journeys/cookies.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/how-your-data-will-be-used/how-your-data-will-be-used.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-number/companies-house-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cover-period/cover-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/end-buyer/end-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/exporter-location/exporter-location.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/have-an-account/have-an-account.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/total-value-insured/total-value-insured.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/uk-goods-or-services/uk-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/another-company.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee/loss-payee.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/validation/pre-credit-period-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-trading-name-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/buyer-financial-information/buyer-financial-information-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/validation/connection-to-the-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/validation/credit-insurance-cover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-validation.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-body/buyer-body.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/cookies.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/exporter-location/exporter-location.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/uk-goods-or-services/uk-goods-or-services.spec.js
Labels: tech, chore

#2167 chore(EMS-3109): No PDF - Object structured cypress commands - submitAndAssertFieldErrors
  e2e-tests/commands/shared-commands/assertions/check-buyer-country-form.js
  e2e-tests/commands/shared-commands/form/submit-and-assert-field-errors.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details-validation-account-already-exists.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details-validation-password.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/new-password/validation/account-password-reset-new-password-valdation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/validation/account-password-reset-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/enter-code/validation/account-sign-in-enter-code-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/companies-house/companies-house-search/companies-house-search.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/declined-by-private-market/declined-by-private-market.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/how-will-you-get-paid/how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/feedback/validation/feedback-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/validation/broker-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/validation/different-name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-details/validation/loss-payee-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-international/validation/financial-address-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/validation/account-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/loss-payee-financial-details-uk/validation/sort-code-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/validation/name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/validation/other-company-details-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/validation/pre-credit-period-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/alternative-trading-address/alternative-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-submit.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-company-website-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-different-trading-name-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/validation/company-details-invalid-phone-number-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-employees-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-years-exporting-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-estimated-annual-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/validation/turnover-percentage-turnover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-registration-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/company-or-organisation/validation/company-or-organisation-validation-website.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/connection-to-the-buyer/validation/connection-to-the-buyer-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/validation/credit-insurance-cover-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/validation/trading-history-outstanding-payments-yes-validation.spec.js
  e2e-tests/shared-test-assertions/bic-swift-code-field-validation/index.js
  e2e-tests/shared-test-assertions/email-field-validation/index.js
  e2e-tests/shared-test-assertions/financial-address-field-validation/index.js
  e2e-tests/shared-test-assertions/iban-field-validation/index.js
Labels: tech, chore

#2168 feat(EMS-2936): No PDF - Export contract - Private market - Data saving
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/private-market/private-market.spec.js
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/ui/server/api/keystone/application/update/index.ts
  src/ui/server/api/keystone/application/update/privateMarket.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/save-and-back/index.ts
  src/ui/server/controllers/insurance/export-contract/declined-by-private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/index.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/export-contract/how-will-you-get-paid/save-and-back/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.api-error.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/private-market/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/save-data/private-market/index.test.ts
  src/ui/server/controllers/insurance/export-contract/save-data/private-market/index.ts
  src/ui/server/graphql/mutations/update-application/private-market.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/summary-lists/export-contract/about-goods-or-services-fields/index.test.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: feature, chore
