Repository UK-Export-Finance/exip, pull requests merged in 2024-01, with the labels that each got.

#1623 fix(tests): Mock months generated as 0
  e2e-tests/commands/insurance/requested-start-date-field.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
Labels: chore, fix

#1625 fix(release-please): specify target branch
  .github/workflows/publish.yml
Labels: fix

#1630 chore(main): release 2.4.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1634 chore(merge): Merge `main` into `main-application-no-pdf`
  .github/workflows/publish.yml
  .release-please-manifest.json
  CHANGELOG.md
  e2e-tests/commands/insurance/requested-start-date-field.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  package-lock.json
  package.json
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
Labels: chore

#1621 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1636 fix(feature-deployment): Feature environment deployment
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, fix

#1637 chore(main): release 2.4.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1640 feat(EMS-2349-2536): No PDF - Policy type - Completion date validation enhancements
  e2e-tests/commands/insurance/complete-and-submit-export-value-form.js
  e2e-tests/commands/insurance/complete-export-value-form.js
  e2e-tests/commands/insurance/date-field.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/validation/rules/contract-completion-date.ts
  src/ui/server/shared-validation/date/index.test.ts
  src/ui/server/shared-validation/date/index.ts
  src/ui/server/shared-validation/requested-start-date/index.test.ts
  src/ui/server/shared-validation/requested-start-date/index.ts
  src/ui/types/errors.ts
  src/ui/types/index.d.ts
Labels: enhancement, feature, tech

#1641 chore(merge): Merge `main` into `main-application-no-pdf`
  .github/workflows/deploy.sh
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
  .github/workflows/lint.yml
  .github/workflows/sca.yml
  .github/workflows/test.yml
  package-lock.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: chore

#1652 chore(deps): Bump dependencies
  .github/workflows/infrastructure.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1651 style(EMS-2466): No PDF - Policy - Check your answers - Multiple lists
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/form-titles.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/form-titles.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.ts
  src/ui/server/helpers/summary-lists/policy/credit-period-and-currency-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/credit-period-and-currency-fields/index.ts
  src/ui/server/helpers/summary-lists/policy/index.test.ts
  src/ui/server/helpers/summary-lists/policy/index.ts
  src/ui/server/helpers/summary-lists/policy/policy-and-date-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/policy-and-date-fields/index.ts
  src/ui/server/helpers/summary-lists/policy/policy-and-date-fields/multiple-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/policy-and-date-fields/multiple-contract-policy-fields/index.ts
  src/ui/server/helpers/summary-lists/policy/policy-and-date-fields/single-contract-policy-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/policy-and-date-fields/single-contract-policy-fields/index.ts
  src/ui/server/helpers/summary-lists/policy/policy-contact-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/policy-contact-fields/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/templates/insurance/policy/check-your-answers.njk
Labels: documentation, enhancement, tech

#1654 chore(EMS-2475): No PDF - Re-enable MOJ scripts/styles
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/password-reset/new-password/account-password-reset-new-password.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/sign-in/account-sign-in.spec.js
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/googleTagManager.js.map
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/scripts/moj-frontend.js
  src/ui/server/constants/integrity.ts
  src/ui/server/nunjucks-configuration/index.ts
  src/ui/styles/styles.scss
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/password-reset/new-password.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
Labels: dependencies, chore

#1666 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1675 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1680 feat(EMS-2572): No PDF - Policy - Pre-credit period - Page setup
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/index.js
  e2e-tests/content-strings/pages/insurance/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/content-strings/pre-credit-period-description.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/partials/index.js
  e2e-tests/partials/preCreditPeriodDescription.js
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/index.ts
  src/ui/server/content-strings/pages/insurance/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/content-strings/pre-credit-period-description.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/templates/components/single-radio.njk
  src/ui/templates/insurance/policy/broker.njk
  src/ui/templates/insurance/policy/different-name-on-policy.njk
  src/ui/templates/insurance/your-business/companies_house_number.njk
  src/ui/templates/insurance/your-business/contact.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover-currency.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/partials/insurance/pre-credit-period-conditional-yes-html.njk
  src/ui/templates/partials/insurance/pre-credit-period-description.njk
  src/ui/templates/partials/insurance/uk-goods-and-services-details.njk
  src/ui/templates/shared-pages/single-radio.njk
Labels: feature, chore

#1685 feat(EMS-2524): No PDF - Single contract policy - Total contract value - save and back
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/total-contract-value/single-contract-policy-total-contract-value.spec.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/save-and-back/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
Labels: enhancement, feature

#1688 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1691 fix(deployment): removed frivolous deployment environment variables set
  .github/workflows/deployment.yml
Labels: fix

#1689 feat(EMS-2370): No PDF - Your buyer - Trading history page
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/insurance/your-buyer/index.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/failed-payments.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/failed-payments.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/index.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/outstanding-payments.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/outstanding-payments.ts
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/insurance/account/create/your-details.njk
  src/ui/templates/insurance/account/manage.njk
  src/ui/templates/insurance/account/sign-in/enter-code.njk
  src/ui/templates/insurance/account/sign-in/request-new-code.njk
  src/ui/templates/insurance/account/sign-in/sign-in.njk
  src/ui/templates/insurance/application-submitted.njk
  src/ui/templates/insurance/complete-other-sections.njk
  src/ui/templates/insurance/declarations/confidentiality.njk
  src/ui/templates/insurance/eligibility/cannot-apply-multiple-risks.njk
  src/ui/templates/insurance/eligibility/check-if-eligible.njk
  src/ui/templates/insurance/eligibility/long-term-cover.njk
  src/ui/templates/insurance/start.njk
  src/ui/templates/insurance/your-buyer/trading-history.njk
  src/ui/templates/shared-pages/section-start.njk
  src/ui/types/page-variables.d.ts
Labels: feature

#1694 fix(EMS-2543-2571-2607-2608-2611): No PDF - copy fixes, country pre-population issue
  e2e-tests/commands/insurance/complete-and-submit-about-goods-or-services-form.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/uk-goods-and-services-calculate-description.js
  e2e-tests/content-strings/uk-goods-and-services-description.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/uk-goods-and-services-calculate-description.ts
  src/ui/server/content-strings/uk-goods-and-services-description.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
Labels: bug, fix

#1696 fix(EMS-2556-2570): No PDF - Multiple contract policy - Total months of cover - decimal places
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-total-months-of-cover.spec.js
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/validation/rules/total-months-of-cover.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/validation/rules/total-months-of-cover.ts
Labels: bug, dependencies, chore, fix

#1698 feat(EMS-2558): No PDF - Policy - Pre-credit period - Save data
  e2e-tests/commands/insurance/complete-and-submit-pre-credit-period-form.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/content-strings/credit-period-with-buyer-description.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/validation/pre-credit-period-validation.spec.js
  e2e-tests/partials/creditPeriodWithBuyer.js
  e2e-tests/partials/index.js
  e2e-tests/partials/preCreditPeriodDescription.js
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/credit-period-with-buyer-description.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/index.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/credit-period-with-buyer-description.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/credit-period-with-buyer-description.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/index.ts
  src/ui/templates/partials/insurance/credit-period-with-buyer-description.njk
  src/ui/templates/partials/insurance/pre-credit-period-conditional-yes-html.njk
  src/ui/templates/partials/insurance/pre-credit-period-description.njk
Labels: feature, tech

#1699 feat(EMS-2558): No PDF - Policy - Pre-credit period - Save and back
  e2e-tests/commands/insurance/complete-and-submit-pre-credit-period-form.js
  e2e-tests/commands/insurance/complete-pre-credit-period-form.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/controllers/insurance/policy/pre-credit-period/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/save-and-back/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
Labels: enhancement, feature

#1702 fix(EMS-2557): No PDF - Your business - check/change business trading address
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  src/ui/server/controllers/insurance/business/company-details/index.test.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
Labels: bug, documentation, tech, fix

#1701 feat(EMS-2546): No PDF - Your buyer - Alternative currency form
  e2e-tests/commands/insurance/assert-alternative-currency-form.js
  e2e-tests/commands/insurance/check-policy-currency-code-input.js
  e2e-tests/commands/shared-commands/assertions/check-currency-option.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/constants/field-ids/insurance/index.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  src/ui/server/constants/field-ids/insurance/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/shared-pages.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/validation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/validation/index.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/validation/rules/alternative-currency.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/validation/rules/alternative-currency.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/validation/rules/index.ts
  src/ui/server/helpers/mappings/map-currencies/as-radio-options/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-radio-options/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/components/currency-radio-inputs.njk
  src/ui/templates/insurance/your-buyer/trading-history.njk
  src/ui/templates/shared-pages/alternative-currency.njk
Labels: feature

#1703 feat(EMS-2558): No PDF - Policy - Pre-credit period - wipe a field if answer is changed
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.ts
Labels: documentation, tech, chore

#1697 fix(deployment): removed frivolous variables
  .github/workflows/deployment.yml
  .github/workflows/infrastructure.yml
Labels: fix

#1712 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1704 chore(main): release 2.4.3
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#1713 fix(EMS-2538-2654-2658): No PDF - Get a quote currencies ordering, content updates
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/index.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/tell-us-about-your-policy/tell-us-about-your-single-policy.spec.js
  src/api/constants/supported-currencies/index.ts
  src/api/test-mocks/mock-currencies.ts
  src/ui/server/constants/supported-currencies.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/index.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-currencies.ts
Labels: bug, enhancement, tech, fix

#1714 style(EMS-2658): No PDF - Update error messages
  e2e-tests/content-strings/error-messages.js
  src/ui/server/content-strings/error-messages.ts
Labels: enhancement

#1725 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1724 fix(EMS-2566-2657): No PDF - Date validation - Return an error if days is over days in a month
  e2e-tests/commands/insurance/date-field.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/validation/multiple-contract-policy-validation-requested-start-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-contract-completion-date.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/single-contract-policy/validation/single-contract-policy-validation-requested-start-date.spec.js
  src/ui/server/helpers/date/get-date-fields-from-timestamp/index.test.ts
  src/ui/server/helpers/date/get-days-in-a-month/index.test.ts
  src/ui/server/helpers/date/get-days-in-a-month/index.ts
  src/ui/server/shared-validation/date/index.test.ts
  src/ui/server/shared-validation/date/index.ts
  src/ui/server/shared-validation/date/valid-format/index.test.ts
  src/ui/server/shared-validation/date/valid-format/index.ts
  src/ui/types/index.d.ts
  src/ui/types/validation-errors.d.ts
Labels: bug, tech, fix

#1727 feat(EMS-2471): No PDF - Your Buyer - Credit insurance cover - page setup
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-trading-history-with-buyer-form.js
  e2e-tests/commands/insurance/your-buyer/complete-trading-history-with-buyer-form.js
  e2e-tests/constants/field-ids/insurance/your-buyer/index.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/content-strings/pages/insurance/your-buyer/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/credit-insurance-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/trading-history/trading-history-page.spec.js
  e2e-tests/insurance/cypress/support/application/buyer/index.js
  src/ui/server/constants/field-ids/insurance/your-buyer/index.ts
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/content-strings/pages/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.ts
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/server/helpers/page-variables/core/insurance/index.test.ts
  src/ui/server/helpers/page-variables/single-input/index.test.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
  src/ui/templates/partials/insurance/credit-insurance-cover-conditional-yes-html.njk
Labels: feature, tech, chore

#1726 chore(EMS-2622-2546): No PDF - Alternative currency input and APIM all currencies
  e2e-tests/commands/forms.js
  e2e-tests/commands/insurance/assert-alternative-currency-form.js
  e2e-tests/commands/shared-commands/assertions/check-autocomplete-input.js
  e2e-tests/fixtures/countries.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/change-your-answers-about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/buyer-country/buyer-country.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-multi-policy.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-currencies/index.test.ts
  src/api/helpers/map-currencies/index.ts
  src/ui/public/js/accessibleAutocomplete.js
  src/ui/public/js/accessibleAutocomplete.js.map
  src/ui/scripts/accessible-autocomplete.js
  src/ui/server/constants/integrity.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.ts
  src/ui/server/graphql/queries/APIM/currencies.ts
  src/ui/server/helpers/mappings/map-countries.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/server/test-mocks/mock-currencies.ts
  src/ui/templates/components/currency-radio-inputs.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
  src/ui/templates/partials/insurance/alternative-currency-input.njk
  src/ui/templates/shared-pages/alternative-currency.njk
Labels: feature, chore

#1729 style(EMS-2464): No PDF - Your business - Summary list updates
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/turnover-fields/index.ts
Labels: enhancement, chore

#1728 chore(EMS-2455): DRY "form buttons" nunjucks component
  src/ui/templates/components/form-buttons.njk
  src/ui/templates/components/single-radio.njk
  src/ui/templates/insurance/declarations/anti-bribery.njk
  src/ui/templates/insurance/declarations/confidentiality.njk
  src/ui/templates/insurance/export-contract/about-goods-or-services.njk
  src/ui/templates/insurance/export-contract/check-your-answers.njk
  src/ui/templates/insurance/policy/broker.njk
  src/ui/templates/insurance/policy/check-your-answers.njk
  src/ui/templates/insurance/policy/different-name-on-policy.njk
  src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/name-on-policy.njk
  src/ui/templates/insurance/policy/single-contract-policy-total-contract-value.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
  src/ui/templates/insurance/policy/type-of-policy.njk
  src/ui/templates/insurance/your-business/alternative-trading-address.njk
  src/ui/templates/insurance/your-business/check-your-answers.njk
  src/ui/templates/insurance/your-business/companies_house_number.njk
  src/ui/templates/insurance/your-business/company-details.njk
  src/ui/templates/insurance/your-business/contact.njk
  src/ui/templates/insurance/your-business/nature-of-your-business.njk
  src/ui/templates/insurance/your-business/turnover.njk
  src/ui/templates/insurance/your-buyer/check-your-answers.njk
  src/ui/templates/insurance/your-buyer/company-or-organisation.njk
  src/ui/templates/insurance/your-buyer/trading-history.njk
  src/ui/templates/shared-pages/declaration.njk
Labels: tech

#1738 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1741 feat(EMS-2583): No PDF - Policy - Another company - Page setup
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/another-company.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/pages/insurance/policy/broker.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/policy/index.ts
  src/api/schema.graphql
  src/ui/server/constants/field-ids/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
Labels: feature, chore

#1743 fix(EMS-2532-2533): No PDF - Your business - Check your answers - Save and back and trading name/address rows
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-alternative-trading-address-form.js
  e2e-tests/commands/insurance/complete-buyer-section.js
  e2e-tests/commands/insurance/complete-company-details-form.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  src/ui/server/controllers/insurance/business/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/business/check-your-answers/index.ts
  src/ui/server/controllers/insurance/business/company-details/index.ts
  src/ui/server/helpers/mappings/map-yes-alternate-field.test.ts
  src/ui/server/helpers/mappings/map-yes-alternate-field.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.test.ts
  src/ui/server/helpers/summary-lists/your-business/your-company-fields/index.ts
  src/ui/templates/insurance/your-business/check-your-answers.njk
Labels: fix

#1744 feat(EMS-2583): No PDF - Policy - Another company - Form validation, redirections
  e2e-tests/commands/insurance/complete-and-submit-another-company-form.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/another-company.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-all-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-no-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/broker-postcode-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-same-name-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/entering-details-of-policy-owner.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/pre-credit-period/pre-credit-period.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/index.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/index.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/index.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
Labels: feature, chore

#1745 feat(EMS-2412): No PDF - Your buyer - Trading history redirect
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/traded-with-buyer/traded-with-buyer.spec.js
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/traded-with-buyer/index.ts
Labels: feature

#1746 chore(EMS-2674): No PDF - Return alternativeCurrencies from getCurrencies()
  e2e-tests/commands/insurance/assert-alternative-currency-form.js
  e2e-tests/fixtures/currencies.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/map-currencies/index.test.ts
  src/api/helpers/map-currencies/index.ts
  src/api/schema.graphql
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.ts
  src/ui/server/controllers/quote/tell-us-about-your-policy/index.test.ts
  src/ui/server/graphql/queries/APIM/currencies.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/index.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/as-select-options/map-and-sort-currencies/index.ts
  src/ui/server/test-mocks/mock-currencies.ts
Labels: chore

#1747 feat(EMS-2481): No PDF - Your business - Turnover currency - Page setup
  e2e-tests/commands/core-page-checks.js
  e2e-tests/commands/insurance/assert-alternative-currency-form.js
  e2e-tests/commands/insurance/check-your-business-summary-list.js
  e2e-tests/commands/shared-commands/assertions/assert-save-and-back-button-does-not-exist.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/content-strings/fields/insurance/business/index.js
  e2e-tests/content-strings/pages/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/nature-of-business/validation/nature-of-business-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  src/api/.keystone/config.js
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/currency/index.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/alternative-currency/index.ts
  src/ui/server/helpers/mappings/map-currencies/radio-and-select-options/index.test.ts
  src/ui/server/helpers/mappings/map-currencies/radio-and-select-options/index.ts
  src/ui/templates/components/currency-radio-inputs.njk
  src/ui/templates/insurance/your-business/turnover-currency.njk
  src/ui/templates/partials/insurance/alternative-currency-input.njk
  src/ui/templates/shared-pages/alternative-currency.njk
Labels: feature, tech, chore

#1760 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1759 feat(EMS-2482): No PDF - Your business - Turnover currency - form validation
  e2e-tests/commands/insurance/assert-alternative-currency-form.js
  e2e-tests/commands/insurance/complete-and-submit-turnover-currency-form.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/type-of-policy/type-of-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/support/application/business/index.js
  e2e-tests/pages/shared/radios.js
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/currency/index.ts
  src/ui/server/controllers/insurance/business/turnover/currency/validation/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/currency/validation/index.ts
  src/ui/server/controllers/insurance/business/turnover/currency/validation/rules/alternative-currency.test.ts
  src/ui/server/controllers/insurance/business/turnover/currency/validation/rules/alternative-currency.ts
  src/ui/server/controllers/insurance/business/turnover/currency/validation/rules/currency.test.ts
  src/ui/server/controllers/insurance/business/turnover/currency/validation/rules/currency.ts
  src/ui/server/controllers/insurance/business/turnover/currency/validation/rules/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/components/currency-radio-inputs.njk
  src/ui/templates/insurance/policy/multiple-contract-policy.njk
  src/ui/templates/insurance/policy/single-contract-policy.njk
  src/ui/templates/partials/insurance/alternative-currency-input.njk
  src/ui/templates/shared-pages/alternative-currency.njk
Labels: feature, tech

#1761 feat(EMS-2535): No PDF - Policy - Change from single to multiple - enhancements
  e2e-tests/commands/insurance/change-policy-type-to-multiple-and-submit-contract-policy-form.js
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/change-your-answers-change-policy-type-single-to-multiple.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/index.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/index.ts
  src/ui/server/helpers/sanitise-data/index.test.ts
  src/ui/server/helpers/sanitise-data/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
Labels: documentation, enhancement, feature, tech

#1770 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1769 fix(EMS-2543): No PDF - Policy - Export contract - About goods or services - validation conditions
  e2e-tests/commands/insurance/complete-about-goods-or-services-form.js
  e2e-tests/commands/insurance/complete-and-submit-about-goods-or-services-form.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/validation/about-goods-or-services-validation.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  src/ui/server/constants/templates/index.ts
  src/ui/server/constants/templates/partials/index.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.test.ts
  src/ui/server/controllers/insurance/export-contract/about-goods-or-services/index.ts
  src/ui/server/controllers/insurance/policy/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/broker/index.ts
  src/ui/templates/components/single-radio.njk
  src/ui/templates/components/yes-no-radio-buttons.njk
  src/ui/templates/insurance/export-contract/about-goods-or-services.njk
  src/ui/templates/partials/insurance/about-goods-or-services-conditional-yes-html.njk
Labels: bug, tech, fix

#1771 feat(EMS-2541): No PDF - Policy - Other company details - Page setup
  e2e-tests/commands/insurance/complete-and-submit-another-company-form.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/another-company/another-company.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/broker-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-all-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/are-you-using-a-broker-answer-yes/are-you-using-a-broker-answer-yes-no-required-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker/validation/broker-postcode-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/changing-from-same-name-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/entering-details-of-policy-owner.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/other-company-details/other-company-details.spec.js
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/constants/templates/insurance/policy/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/another-company/index.test.ts
  src/ui/server/controllers/insurance/policy/another-company/index.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.test.ts
  src/ui/server/controllers/insurance/policy/other-company-details/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/index.test.ts
  src/ui/server/routes/insurance/policy/index.ts
  src/ui/templates/insurance/policy/other-company-details.njk
Labels: feature, tech

#1780 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1792 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1791 fix(EMS-2698-2686-2705): No PDF - Different name on policy - validation, various copy updates
  database/exip.sql
  e2e-tests/content-strings/buttons.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/account/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/different-name-on-policy/validation/different-name-on-policy-validation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/different-name-on-policy-name-fields-with-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  src/api/.keystone/config.js
  src/api/schema.prisma
  src/api/schema.ts
  src/ui/server/content-strings/buttons.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/account/index.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.test.ts
  src/ui/server/controllers/insurance/business/alternative-trading-address/validation/rules/alternative-trading-address.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.test.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/percentage-of-turnover.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/improve-service.test.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/improve-service.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/other-comments.test.ts
  src/ui/server/controllers/insurance/feedback/feedback-form/validation/rules/other-comments.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/index.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/email-address.test.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/first-name.test.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/first-name.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/last-name.test.ts
  src/ui/server/controllers/insurance/policy/different-name-on-policy/validation/rules/last-name.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/credit-period-with-buyer-description.test.ts
  src/ui/server/controllers/insurance/policy/pre-credit-period/validation/rules/credit-period-with-buyer-description.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/validation/rules/connection-with-buyer-description.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/validation/rules/connection-with-buyer-description.ts
  src/ui/server/helpers/percentage-number-validation/index.test.ts
  src/ui/server/helpers/percentage-number-validation/index.ts
  src/ui/server/shared-validation/alpha-characters-only/index.test.ts
  src/ui/server/shared-validation/alpha-characters-only/index.ts
  src/ui/server/shared-validation/name/index.test.ts
  src/ui/server/shared-validation/name/index.ts
  src/ui/templates/shared-pages/alternative-currency.njk
  src/ui/types/errors.ts
  src/ui/types/index.d.ts
Labels: enhancement, tech, fix

#1793 feat(EMS-2472): No PDF - Credit insurance cover - validation
  e2e-tests/commands/insurance/your-buyer/complete-and-submit-credit-insurance-cover-form.js
  e2e-tests/commands/insurance/your-buyer/complete-credit-insurance-cover-form.js
  e2e-tests/constants/routes/insurance/your-buyer.js
  e2e-tests/content-strings/error-messages.js
  e2e-tests/content-strings/fields/insurance/your-buyer/index.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/credit-insurance-cover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/credit-insurance-cover/validation/credit-insurance-cover-validation.spec.js
  e2e-tests/insurance/cypress/support/application/buyer/index.js
  src/ui/server/constants/routes/insurance/your-buyer.ts
  src/ui/server/content-strings/error-messages.ts
  src/ui/server/content-strings/fields/insurance/your-buyer/index.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/index.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/index.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/rules/credit-insurance-cover-description.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/rules/credit-insurance-cover-description.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/rules/credit-insurance-cover.test.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/rules/credit-insurance-cover.ts
  src/ui/server/controllers/insurance/your-buyer/credit-insurance-cover/validation/rules/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.test.ts
  src/ui/server/routes/insurance/your-buyer/index.ts
Labels: feature

#1805 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1807 fix(EMS-2691): No PDF - Business - Turnover - alternative currency
  e2e-tests/constants/routes/insurance/business.js
  e2e-tests/content-strings/pages/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  src/ui/server/constants/routes/insurance/business.ts
  src/ui/server/constants/templates/insurance/business/index.ts
  src/ui/server/content-strings/pages/insurance/your-business/index.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/validation/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/validation/index.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/validation/rules/alternative-currency.test.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/validation/rules/alternative-currency.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/validation/rules/currency.test.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/validation/rules/currency.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/validation/rules/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/routes/insurance/business/index.test.js
  src/ui/server/routes/insurance/business/index.ts
Labels: bug, fix

#1815 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1814 feat(EMS-2483): No PDF - Business - Turnover - Alternative currency - Data saving
  database/exip.sql
  e2e-tests/commands/insurance/complete-and-submit-turnover-currency-form.js
  e2e-tests/constants/field-ids/insurance/business/index.js
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-buyer/alternative-currency/alternative-currency-page.spec.js
  e2e-tests/insurance/cypress/support/application/business/index.js
  src/api/.keystone/config.js
  src/api/constants/field-ids/insurance/business/index.ts
  src/api/keystone.test.ts
  src/api/schema.graphql
  src/api/schema.prisma
  src/api/schema.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
  src/ui/server/constants/field-ids/insurance/business/index.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/alternative-currency/index.ts
  src/ui/server/controllers/insurance/business/turnover/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/index.ts
  src/ui/server/controllers/insurance/business/turnover/map-submitted-data/index.test.ts
  src/ui/server/controllers/insurance/business/turnover/map-submitted-data/index.ts
  src/ui/server/graphql/queries/application.ts
  src/ui/server/helpers/required-fields/business/index.test.ts
  src/ui/server/helpers/required-fields/business/index.ts
  src/ui/server/test-mocks/mock-application.ts
  src/ui/types/application.ts
Labels: enhancement, feature, tech

#1816 fix(EMS-2384): No PDF - Policy - Route/url, error messages
  e2e-tests/constants/routes/insurance/policy.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/api/helpers/create-a-buyer/index.ts
  src/ui/server/constants/routes/insurance/policy.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
Labels: bug, documentation, fix

#1823 chore(deps): Bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#1825 chore(EMS-2719): No PDF - Currencies - Filter out "gold" currency from APIM
  src/api/.keystone/config.js
  src/api/constants/external-apis.ts
  src/api/custom-resolvers/queries/get-APIM-CIS-countries/index.test.ts
  src/api/custom-resolvers/queries/get-APIM-currencies/index.test.ts
  src/api/helpers/filter-cis-entries/index.test.ts
  src/api/helpers/filter-cis-entries/index.ts
  src/api/helpers/map-CIS-countries/index.test.ts
  src/api/helpers/map-CIS-countries/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/index.test.ts
  src/api/helpers/map-currencies/index.test.ts
  src/api/helpers/map-currencies/index.ts
  src/api/integrations/APIM/index.test.ts
  src/api/test-mocks/index.ts
Labels: enhancement, tech, chore
