Repository UK-Export-Finance/exip, pull requests merged in 2024-06, with the labels that each got.

#2492 feat(EMS-1027): no PDF - account - sign in - verify email after expiry
  e2e-tests/commands/api/index.js
  e2e-tests/constants/account.js
  e2e-tests/content-strings/pages/insurance/account/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired-in-inactive-state.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired-link.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-abandoned-applications.spec.js
  e2e-tests/pages/insurance/account/create/verifyEmailLinkExpired.js
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/custom-resolvers/mutations/account-password-reset/index.ts
  src/api/custom-resolvers/mutations/account-sign-in/account-checks/index.ts
  src/api/custom-resolvers/mutations/verify-account-sign-in-code/index.ts
  src/api/custom-resolvers/queries/verify-account-password-reset-token/index.ts
  src/api/helpers/date/index.test.ts
  src/api/helpers/date/index.ts
  src/api/helpers/map-unverified-accounts/index.test.ts
  src/api/helpers/map-unverified-accounts/index.ts
  src/api/helpers/send-email-confirm-email-address/index.test.ts
  src/api/helpers/send-email-confirm-email-address/index.ts
  src/api/helpers/update-account/index.ts
  src/api/types/cron/index.ts
  src/ui/server/content-strings/pages/insurance/account/index.ts
  src/ui/server/controllers/insurance/account/create/verify-email-expired-link/index.test.ts
  src/ui/server/controllers/insurance/account/create/verify-email-expired-link/index.ts
  src/ui/server/routes/insurance/account/index.test.ts
  src/ui/server/routes/insurance/account/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/account/create/verify-email-expired-link.njk
Labels: feature

#2500 fix(EMS-3385): no PDF - policy - nullify data when changing policy type
  e2e-tests/commands/insurance/assert-currency-form-fields.js
  e2e-tests/commands/insurance/change-policy-type-to-multiple-and-submit-contract-policy-form.js
  e2e-tests/commands/insurance/change-policy-type-to-single-and-submit-contract-policy-form.js
  e2e-tests/commands/shared-commands/assertions/assert-currency-form-fields-are-empty.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-contract-completion-date-field-values.js
  e2e-tests/commands/shared-commands/assertions/assert-empty-requested-start-date-field-values.js
  e2e-tests/commands/shared-commands/assertions/index.js
  e2e-tests/constants/field-ids/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/multiple-policy/change-your-answers-change-policy-type-multiple-to-single-to-multiple.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/multiple-policy/change-your-answers-change-policy-type-multiple-to-single.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/single-policy/change-your-answers-change-policy-type-single-to-multiple-to-single.spec.js
  e2e-tests/insurance/cypress/support/application/policy/index.js
  e2e-tests/shared-test-assertions/currency-form-fields/assertions.js
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-introduction/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-introduction/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/date-fields/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/date-fields/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/policy/index.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.test.ts
  src/ui/server/controllers/insurance/policy/save-data/policy/index.ts
  src/ui/server/helpers/has-policy-contact-changed/index.ts
  src/ui/server/helpers/has-policy-type-changed/index.test.ts
  src/ui/server/helpers/has-policy-type-changed/index.ts
  src/ui/server/helpers/nullify-generic-contract-policy-fields/index.test.ts
  src/ui/server/helpers/nullify-generic-contract-policy-fields/index.ts
  src/ui/server/helpers/nullify-multiple-contract-policy-fields/index.test.ts
  src/ui/server/helpers/nullify-multiple-contract-policy-fields/index.ts
  src/ui/server/helpers/nullify-single-contract-policy-fields/index.test.ts
  src/ui/server/helpers/nullify-single-contract-policy-fields/index.ts
Labels: bug, documentation, tech, chore, fix

#2504 style(EMS-3403): no PDF - eligibility - total value insured - content update
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
Labels: enhancement

#2505 fix(EMS-3268): no PDF - policy - check your answers - redirect
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-multiple-contract-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/complete-policy-as-single-contract-policy.spec.js
  src/ui/server/controllers/insurance/policy/check-your-answers/index.test.ts
  src/ui/server/controllers/insurance/policy/check-your-answers/index.ts
Labels: bug, fix

#2501 feat(EMS-3428): no PDF - CRON - Application - submissionDeadline
  e2e-tests/commands/insurance/assert-currency-form-fields.js
  e2e-tests/commands/shared-commands/assertions/assert-currency-form-fields-are-empty.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/confirm-email/confirm-email-verification-expired.spec.js
  e2e-tests/shared-test-assertions/currency-form-fields/assertions.js
  src/api/.keystone/config.js
  src/api/helpers/date/index.test.ts
  src/api/helpers/date/index.ts
  src/api/helpers/get-inactive-applications/index.test.ts
  src/api/helpers/get-inactive-applications/index.ts
  src/api/helpers/update-inactive-applications/index.test.ts
  src/api/test-helpers/applications.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/create-multiple-full-applications.ts
Labels: chore

#2485 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2547 fix(EMS-3436-3448): no pdf - application submission - XLSX - content mapping issues
  .github/workflows/test.yml
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/declarations-conditions/submit-an-application-multiple-policy-type-has-not-traded-with-buyer-and-no-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/declarations-conditions/submit-an-application-multiple-policy-type-without-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/declarations-conditions/submit-an-application-multiple-policy-type-without-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-different-name-on-policy.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/declarations-conditions/submit-an-application-single-policy-type-has-not-traded-with-buyer-and-no-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/declarations-conditions/submit-an-application-single-policy-type-without-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/declarations-conditions/submit-an-application-single-policy-type-without-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/policy-conditions/submit-an-application-single-policy-type-different-name-on-policy.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/XLSX.ts
  src/api/generate-xlsx/map-application-to-XLSX/helpers/xlsx-row/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-declarations/index.ts
Labels: bug, tech, fix

#2548 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2549 fix(EMS-3443): no pdf - application submission - XLSX - content updates
  src/api/.keystone/config.js
  src/api/content-strings/XLSX.ts
Labels: bug, fix

#2541 chore(merge): no pdf - merge main into main-application-no-pdf
  .github/workflows/deployment.yml
  .github/workflows/github.yml
  .release-please-manifest.json
  CHANGELOG.md
  e2e-tests/commands/quote/forms.js
  e2e-tests/commands/quote/submit-answers-happy-path-multiple-policy.js
  e2e-tests/commands/quote/submit-answers-happy-path-single-policy.js
  e2e-tests/constants/eligibility.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/single-policy/change-your-answers-policy-single-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-get-a-quote.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-export-fields.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/change-your-answers/change-your-answers-policy-type-and-length.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/check-your-answers/check-your-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-change-answers-single-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-kenya-single-policy-USD.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-large-contract-value.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-multi-policy.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-non-gbp-currency.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy-maximum-cover-period.spec.js
  e2e-tests/quote/cypress/e2e/journeys/quote/your-quote/your-quote-single-policy.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-exporter-location-routes/complete-insurance-eligibility-then-get-a-quote.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-exporter-location-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-start-now-routes/complete-insurance-eligibility-then-get-a-quote.spec.js
  e2e-tests/switch-between-services/cypress/e2e/journeys/via-start-now-routes/get-a-quote-then-complete-insurance-eligibility.spec.js
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/server/constants/eligibility.ts
  src/ui/server/generate-quote/pricing-grid.json
  src/ui/server/helpers/page-variables/core/index.test.ts
  src/ui/templates/partials/phase-banner.njk
Labels: chore

#2551 fix(EMS-3401): no pdf - remove MOJ dependency
  .cspell.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/js/mojFrontend.js
  src/ui/public/js/mojFrontend.js.map
  src/ui/server/nunjucks-configuration/index.ts
Labels: chore, fix

#2554 fix(EMS-3466): no pdf - application submission - XLSX - your buyer section
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-buyer-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-total-contract-value-over-threshold.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-using-a-broker.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-appointed-a-loss-payee.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-buyer-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-total-contract-value-over-threshold.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-using-a-broker.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.ts
  src/api/test-mocks/index.ts
  src/ui/server/middleware/insurance/get-application/index.ts
Labels: bug, fix

#2555 chore(EMS-3438): no pdf - application submission - XLSX - alphabetical content strings
  src/api/.keystone/config.js
  src/api/content-strings/XLSX.ts
Labels: tech, chore

#2550 feat(EMS-1269): no PDF - CRON - Application submission deadline reminder email
  .github/workflows/infrastructure.yml
  docker-compose.yml
  src/api/.env.sample
  src/api/.keystone/config.js
  src/api/constants/application/index.ts
  src/api/constants/cron/index.ts
  src/api/constants/index.ts
  src/api/cron/application/email-submission-deadline-cron-job.test.ts
  src/api/cron/application/email-submission-deadline-reminder-cron-job.ts
  src/api/cron/application/index.test.ts
  src/api/cron/application/index.ts
  src/api/emails/index.ts
  src/api/emails/submission-deadline/index.test.ts
  src/api/emails/submission-deadline/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-buyer/map-previous-cover-with-buyer/index.test.ts
  src/api/helpers/date/index.test.ts
  src/api/helpers/date/index.ts
  src/api/helpers/generate-application-url/index.test.ts
  src/api/helpers/generate-application-url/index.ts
  src/api/helpers/get-expiring-applications/date-checks.test.ts
  src/api/helpers/get-expiring-applications/index.test.ts
  src/api/helpers/get-expiring-applications/index.ts
  src/api/helpers/get-start-and-end-time-of-date/index.test.ts
  src/api/helpers/get-start-and-end-time-of-date/index.ts
  src/api/helpers/map-application-submission-deadline-variables/index.test.ts
  src/api/helpers/map-application-submission-deadline-variables/index.ts
  src/api/helpers/send-email-application-submission-deadline/index.test.ts
  src/api/helpers/send-email-application-submission-deadline/index.ts
  src/api/helpers/send-email-application-submission-deadline/send-email/index.test.ts
  src/api/helpers/send-email-application-submission-deadline/send-email/index.ts
  src/api/test-helpers/applications.ts
  src/api/test-mocks/index.ts
  src/api/types/email/index.ts
Labels: feature

#2563 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2567 fix(EMS-3462): no pdf - application submission - XLSX - buyer - typos
  src/api/.keystone/config.js
  src/api/content-strings/XLSX.ts
Labels: bug, fix

#2562 feat(EMS-3342): no pdf - application submission - XLSX - loss payee - financial information
  e2e-tests/constants/application.js
  src/api/.keystone/config.js
  src/api/constants/application/index.ts
  src/api/custom-resolvers/mutations/submit-application/index.test.ts
  src/api/custom-resolvers/mutations/submit-application/index.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-international/index.test.ts
  src/api/custom-resolvers/mutations/update-loss-payee-financial-details-uk/index.test.ts
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.test.ts
  src/api/custom-resolvers/queries/get-application-by-reference-number/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-intro/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-intro/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-intro/map-policy-type/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-intro/map-policy-type/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-multiple-contract-policy/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-single-contract-policy/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-single-contract-policy/index.ts
  src/api/helpers/create-a-broker/index.test.ts
  src/api/helpers/create-a-broker/index.ts
  src/api/helpers/create-a-loss-payee-financial-international/index.ts
  src/api/helpers/create-a-loss-payee-financial-uk/index.ts
  src/api/helpers/get-populated-application/index.api-error.test.ts
  src/api/helpers/get-populated-application/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/helpers/get-populated-application/nominated-loss-payee/index.test.ts
  src/api/helpers/get-populated-application/nominated-loss-payee/index.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/generate-submitted-application.ts
  src/api/test-helpers/loss-payee-financial-international.ts
  src/api/test-helpers/loss-payee-financial-uk.ts
  src/api/test-helpers/nominated-loss-payee.ts
  src/api/types/test-helpers/index.ts
  src/ui/server/constants/application/index.ts
Labels: documentation, enhancement, tech, chore

#2577 feat(EMS-3461): no PDF - Account creation with a blocked account
  e2e-tests/insurance/cypress/e2e/journeys/account/create/account-blocked/create-account-already-blocked-sign-in.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/account/create/account-blocked/create-account-already-exists-and-is-blocked.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/mutations/create-an-account/account-exists-blocked.test.ts
  src/api/custom-resolvers/mutations/create-an-account/account-exists-unverified.test.ts
  src/api/custom-resolvers/mutations/create-an-account/account-exists-wrong-password.test.ts
  src/api/custom-resolvers/mutations/create-an-account/account-exists.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.test.ts
  src/api/custom-resolvers/mutations/create-an-account/index.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.test.ts
  src/api/custom-resolvers/mutations/send-email-reactivate-account-link/index.ts
  src/api/custom-schema/type-defs.ts
  src/api/helpers/get-expiring-applications/index.test.ts
  src/api/helpers/send-email-reactivate-account-link/index.test.ts
  src/api/helpers/send-email-reactivate-account-link/index.ts
  src/api/schema.graphql
  src/ui/server/controllers/insurance/account/create/your-details/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/index.ts
  src/ui/server/graphql/mutations/account/create.ts
Labels: feature

#2582 fix(EMS-3234): no PDF - Validation - Number validation decimal places
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/agent-charges/validation/agent-charges-validation-method-fixed-sum.spec.js
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/employees-uk.ts
  src/ui/server/controllers/insurance/business/nature-of-business/validation/rules/years-exporting.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.test.ts
  src/ui/server/controllers/insurance/business/turnover/validation/rules/estimated-annual-turnover.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.test.ts
  src/ui/server/controllers/insurance/export-contract/agent-charges/validation/rules/method/index.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/account-number.test.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/account-number.ts
  src/ui/server/controllers/insurance/policy/loss-payee-financial-details-uk/validation/rules/sort-code.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/maximum-buyer-will-owe.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/maximum-buyer-will-owe.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/total-sales-to-buyer.test.ts
  src/ui/server/controllers/insurance/policy/multiple-contract-policy/export-value/validation/rules/total-sales-to-buyer.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/validation/rules/total-contract-value.test.ts
  src/ui/server/controllers/insurance/policy/single-contract-policy/total-contract-value/validation/rules/total-contract-value.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/amount-overdue.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.test.ts
  src/ui/server/controllers/insurance/your-buyer/trading-history/validation/rules/total-outstanding.ts
  src/ui/server/helpers/number-validation/index.test.ts
  src/ui/server/helpers/number-validation/index.ts
  src/ui/server/shared-validation/number-above-minimum/index.test.ts
  src/ui/server/shared-validation/number-above-minimum/index.ts
  src/ui/server/shared-validation/number-minimum-maximum-length/index.test.ts
  src/ui/server/shared-validation/number-minimum-maximum-length/index.ts
  src/ui/types/index.d.ts
  src/ui/types/validation-errors.d.ts
Labels: fix

#2584 feat(EMS-3490): no pdf - application submission - XLSX - protect from modification
  .env.sample
  .github/workflows/deployment.yml
  .github/workflows/test.yml
  src/api/.env.sample
  src/api/.keystone/config.js
  src/api/generate-xlsx/index.test.ts
  src/api/generate-xlsx/index.ts
Labels: documentation, feature, tech, security, chore

#2585 chore(EMS-3484): no pdf - application submission - improve E2E test coverage
  e2e-tests/commands/insurance/assert-dashboard-application-number-link-does-not-exist.js
  e2e-tests/commands/insurance/assert-dashboard-application-submitted-status.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/commands/shared-commands/url/index.js
  e2e-tests/commands/shared-commands/url/navigate-to-dashboard-url.js
  e2e-tests/insurance/cypress/e2e/journeys/account/manage/account-manage.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/submit-an-application-multiple-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/submit-an-application-single-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-abandoned-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-application-submitted.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-no-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-only-my-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-135-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-15-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-16-applications-and-1-abandoned.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-16-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-30-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-45-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-60-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-75-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-pagination/dashboard-pagination-90-applications.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-name-fields-with-special-characters/submit-name-fields-with-special-characters-header-and-page-fields.spec.js
  e2e-tests/insurance/cypress/support/assertions/index.js
Labels: documentation, tech, chore

#2586 style(EMS-3447): no pdf - application submission - XLSX - exporter role
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/INDEXES/index.test.ts
  src/api/constants/XLSX-CONFIG/INDEXES/index.ts
  src/api/content-strings/XLSX.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-contact-details/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-introduction/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-introduction/index.ts
Labels: enhancement, chore

#2588 fix(EMS-3459): no pdf - account creation - validation rules
  e2e-tests/insurance/cypress/e2e/journeys/account/create/your-details/account-create-your-details-validation-account-already-exists-verified-valid-password.spec.js
  src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/already-verified/index.test.ts
  src/ui/server/controllers/insurance/account/create/your-details/validation/account-already-exists/already-verified/index.ts
Labels: bug, fix

#2583 feat(EMS-3338): no pdf - application submission - XLSX - export contract
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/export-contract-conditions/submit-an-application-multiple-policy-type-export-contract-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/export-contract-conditions/submit-an-application-multiple-policy-type-export-contract-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/export-contract-conditions/submit-an-application-multiple-policy-type-using-an-agent.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/export-contract-conditions/submit-an-application-single-policy-type-export-contract-fully-populated.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/export-contract-conditions/submit-an-application-single-policy-type-export-contract-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/export-contract-conditions/submit-an-application-single-policy-type-using-an-agent.spec.js
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/INDEXES/index.test.ts
  src/api/constants/XLSX-CONFIG/INDEXES/index.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-appointed-a-loss-payee.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-buyer-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-different-name-on-policy.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-export-contract-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-minimal.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-other-company-involved.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-total-contract-value-over-threshold.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-using-a-broker.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-appointed-a-loss-payee.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-buyer-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-different-name-on-policy.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-export-contract-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-other-company-involved.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-total-contract-value-over-threshold.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-using-a-broker.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/content-strings/XLSX.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/map-agent-charge-amount/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-agent/map-agent-charge/map-agent-charge-amount/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-export-contract/map-private-market/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-jointly-insured-party/index.ts
  src/api/generate-xlsx/styled-columns/index.test.ts
  src/api/helpers/get-populated-application/index.ts
  src/api/jest.config.js
  src/api/test-mocks/index.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
  src/api/types/xlsx-types/index.ts
  src/ui/types/application.ts
Labels: documentation, enhancement, feature, tech, chore

#2580 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2592 chore(merge): merge main into no-pdf
  .github/workflows/deployment.yml
  e2e-tests/insurance/cypress/e2e/journeys/policy/name-on-policy/save-and-back.spec.js
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/public/css/styles.css
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.map
  src/ui/server/constants/integrity.ts
Labels: chore

#2606 fix(deployment-yml): deployment.yaml fix
  .github/workflows/deployment.yml
Labels: fix

#2607 fix(deployment-yml): deployment.yml fix
  .github/workflows/deployment.yml
Labels: fix

#2604 fix(EMS-3471): no PDF - console.info for debugging urlOrigin
  src/api/helpers/send-email-confirm-email-address/index.ts
  src/ui/server/api/keystone/account/index.ts
Labels: chore

#2593 fix(EMS-3399): no PDF - Export contract - Agent charges - Changing back to standard currency
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/change-your-answers/agent-charges/change-your-answers-agent-charges-fixed-sum-amount-alternative-currency.spec.js
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.test.ts
  src/ui/server/controllers/insurance/export-contract/map-submitted-data/agent-service-charge/index.ts
Labels: fix

#2610 feat(EMS-2433): no PDF - Eligibility - Contract too short exit page
  .github/workflows/test.yml
  e2e-tests/constants/routes/insurance/index.js
  e2e-tests/content-strings/pages/insurance/eligibility/index.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/contract-too-short/contract-too-short.spec.js
  e2e-tests/pages/insurance/eligibility/contractTooShort.js
  e2e-tests/pages/insurance/eligibility/index.js
  src/ui/server/constants/routes/insurance/index.ts
  src/ui/server/constants/templates/insurance/eligibility/index.ts
  src/ui/server/content-strings/pages/insurance/eligibility/index.ts
  src/ui/server/controllers/insurance/eligibility/contract-too-short/index.test.ts
  src/ui/server/controllers/insurance/eligibility/contract-too-short/index.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.test.ts
  src/ui/server/middleware/required-data-provided/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/eligibility/index.test.ts
  src/ui/server/routes/insurance/eligibility/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/templates/insurance/eligibility/contract-too-short.njk
Labels: feature

#2605 fix(EMS-3454): no PDF - XLSX - Currency symbols
  e2e-tests/commands/insurance/complete-and-submit-multiple-contract-policy-form.js
  e2e-tests/commands/insurance/complete-and-submit-single-contract-policy-form.js
  e2e-tests/commands/insurance/complete-and-submit-turnover-form.js
  e2e-tests/commands/insurance/complete-business-section.js
  e2e-tests/commands/insurance/complete-multiple-contract-policy-form.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/commands/insurance/complete-single-contract-policy-form.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/business-conditions/submit-an-application-multiple-policy-type-with-alternative-turnover-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/business-conditions/submit-an-application-single-policy-type-with-alternative-turnover-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/policy-conditions/submit-an-application-single-policy-type-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-multiple-contract-policy-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/check-your-answers/check-your-answers-summary-list/summary-list-single-contract-policy-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details-trading-address-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-credit-control-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/check-your-answers/check-your-answers-summary-list/check-your-answers-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/credit-control.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/credit-control/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/turnover/turnover-page.spec.js
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-business/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-business/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-multiple-contract-policy/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-multiple-contract-policy/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-single-contract-policy/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-single-contract-policy/index.ts
  src/api/test-helpers/create-full-application.ts
Labels: fix

#2613 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#2632 fix(EMS-3439): no PDF - Eligibility - Check your answers - Special characters
  e2e-tests/commands/insurance/assert-companies-house-summary-list.js
  e2e-tests/commands/insurance/check-your-answers-eligibility-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-all-insurance-eligibility-answers.js
  e2e-tests/constants/examples/companies-house-number-examples.js
  e2e-tests/fixtures/companies.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-buyer-country.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-companies-house-search.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-cover-period.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-end-buyer.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-exporter-location.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-has-companies-house-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-total-value-insured.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/change-your-answers/change-your-answers-uk-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-your-answers/eligibility-check-your-answers-company-name-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/check-your-answers/eligibility-check-your-answers-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details-company-name-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/company-details/company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  src/ui/server/helpers/update-submitted-data/insurance/index.test.ts
  src/ui/server/helpers/update-submitted-data/insurance/index.ts
Labels: fix

#2641 fix(EMS-3520): no pdf - dashboard - policy currency code
  e2e-tests/commands/insurance/assert-companies-house-summary-list.js
  e2e-tests/commands/insurance/complete-and-submit-multiple-contract-policy-form.js
  e2e-tests/commands/insurance/complete-and-submit-single-contract-policy-form.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-populated-application-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/dashboard/dashboard-populated-application-non-gbp-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/your-business/company-details/company-details-page.spec.js
  src/ui/server/graphql/queries/applications.ts
  src/ui/server/helpers/mappings/map-applications/map-value.test.ts
  src/ui/server/helpers/mappings/map-applications/map-value.ts
Labels: bug, chore, fix

#2636 fix(EMS-3515): no PDF - XLSX - Policy - Pre credit period
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-need-credit-period.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-need-credit-period.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/content-strings/XLSX.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-credit-period/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-credit-period/index.ts
  src/api/test-mocks/mock-application.ts
  src/api/types/application-types/index.ts
Labels: fix

#2644 fix(EMS-3494): no pdf - application submission - XLSX date format
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-business/map-financial-year-end-date/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-exporter-business/map-financial-year-end-date/index.ts
Labels: bug, fix

#2647 fix(EMS-3508): no pdf - application submission - XLSX - buyer conditions
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/buyer-conditions/submit-an-application-multiple-policy-type-buyer-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/buyer-conditions/submit-an-application-single-policy-type-buyer-minimal.spec.js
  src/api/.keystone/config.js
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-export-contract-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-multiple-contract-policy-total-contract-value-over-threshold.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-export-contract-conditions.test.ts
  src/api/constants/XLSX-CONFIG/index-single-contract-policy-total-contract-value-over-threshold.test.ts
  src/api/constants/XLSX-CONFIG/index.ts
  src/api/test-mocks/index.ts
Labels: bug, chore, fix

#2650 fix(EMS-3524): no pdf - data migration - account, buyer relationships
  src/api/data-migration/version-1-to-version-2/README.md
  src/api/data-migration/version-1-to-version-2/connect-to-database.ts
  src/api/data-migration/version-1-to-version-2/create-new-account-status-relationships/index.ts
  src/api/data-migration/version-1-to-version-2/get-all-buyer-contacts.ts
  src/api/data-migration/version-1-to-version-2/get-all-buyer-relationships.ts
  src/api/data-migration/version-1-to-version-2/get-all-buyer-trading-histories.ts
  src/api/data-migration/version-1-to-version-2/index.ts
  src/api/data-migration/version-1-to-version-2/update-applications/move-buyer-contact-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/move-buyer-relationship-fields.ts
  src/api/data-migration/version-1-to-version-2/update-applications/move-buyer-trading-history-fields.ts
  src/api/data-migration/version-1-to-version-2/update-buyers/index.ts
  src/api/data-migration/version-1-to-version-2/update-buyers/update-buyer-relationship-ids.ts
Labels: bug, tech, chore, fix

#2651 chore(deps): bump dependencies
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore
