Repository UK-Export-Finance/exip, pull requests merged in 2025-03, with the labels that each got.

#3523 fix(EMS-4214): fix failing getISO8601 test
  src/ui/server/helpers/date/iso-8601/index.test.ts
Labels: fix

#3524 fix(EMS-4204): fix incorrect file format sent to mdm for submission email
  src/api/.keystone/config.js
  src/api/emails/application/index.test.ts
  src/api/emails/application/index.ts
Labels: fix

#3528 fix(EMS-4216): remove buildingNameOrNumber from xlsx generation
  src/api/.keystone/config.js
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/based-in-the-uk/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/based-in-the-uk/index.ts
Labels: fix

#3526 chore(main): release 2.41.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3529 chore(EMS-4122): re-enable small export builder functionality
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-eligible-for-small-export-builder-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-not-eligible-for-small-export-builder-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js
  src/api/.keystone/config.js
  src/api/constants/index.ts
  src/api/emails/application/get-submitted-confirmation-template-id/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/index.ts
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.ts
  src/api/emails/application/index.test.ts
  src/api/emails/application/index.ts
  src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk
Labels: chore

#3531 chore(EMS-4217): dependabot - limit typescript to below 5.8
  .github/dependabot.yml
Labels: chore

#3533 chore(EMS-4217): dependabot - limit typescript to 5.4 only in ui directory
  .github/dependabot.yml
Labels: chore

#3535 chore(EMS-4217): dependabot - remove typescript version limit
  .github/dependabot.yml
Labels: chore

#3544 feat(EMS-4156): acr purge workflow
  .cspell.json
  .github/actions/azure-container-registry/action.yml
  .github/actions/notify/action.yml
  .github/workflows/deployment.yml
  .github/workflows/purge.yml
Labels: feature
