Repository UK-Export-Finance/exip, pull requests merged in 2025-02, with the labels that each got.

#3507 chore(EMS-4155): apim notify integration
  src/api/.keystone/config.js
  src/api/XLSX/README.md
  src/api/constants/external-apis.ts
  src/api/emails/access-code-email/index.test.ts
  src/api/emails/access-code-email/index.ts
  src/api/emails/application/index.test.ts
  src/api/emails/application/index.ts
  src/api/emails/call-notify/index.test.ts
  src/api/emails/call-notify/index.ts
  src/api/emails/confirm-email-address/index.test.ts
  src/api/emails/confirm-email-address/index.ts
  src/api/emails/documents/index.test.ts
  src/api/emails/documents/index.ts
  src/api/emails/insurance-feedback-email/index.test.ts
  src/api/emails/insurance-feedback-email/index.ts
  src/api/emails/password-reset-link/index.test.ts
  src/api/emails/password-reset-link/index.ts
  src/api/emails/reactivate-account-link/index.test.ts
  src/api/emails/reactivate-account-link/index.ts
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/emails/submission-deadline/index.test.ts
  src/api/emails/submission-deadline/index.ts
  src/api/integrations/APIM/index.test.ts
  src/api/integrations/APIM/index.ts
  src/api/integrations/notify/index.test.ts
  src/api/integrations/notify/index.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/types/email/index.ts
Labels: documentation, tech, chore

#3513 fix(EMS-4197): broker address lookup - line 1 data saving
  e2e-tests/constants/examples/address-lookup-input-examples.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
Labels: bug, fix

#3514 fix(EMS-4205): enter your brokers address button label
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/broker-manual-address-page.spec.js
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.ts
  src/ui/templates/insurance/policy/broker-manual-address.njk
Labels: fix

#3515 chore(deps): dependencies updates
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, chore

#3516 fix(keystone): updated keystone configuration
  src/api/.keystone/config.js
Labels: fix

#3517 fix(EMS-4206-4207): fix incorrect problem-with-service when no addresses found
  e2e-tests/content-strings/pages/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-ordnance-survey-invalid-postcode.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-page.spec.js
  e2e-tests/pages/insurance/policy/brokerZeroAddresses.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.ts
  src/api/integrations/ordnance-survey/index.test.ts
  src/api/integrations/ordnance-survey/index.ts
  src/api/types/ordnance-survey/index.ts
  src/ui/server/content-strings/pages/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.ts
  src/ui/templates/insurance/policy/broker-zero-addresses.njk
Labels: fix

#3518 fix(EMS-4209): fixed incorrect policy check-your-answers page status
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/another-company/change-your-answers-change-another-company-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/another-company/change-your-answers-change-another-company-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-based-in-uk-to-not-based-in-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-multiple-addresses-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-multiple-addresses-enter-address-manually.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-single-address-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-single-address-enter-address-manually.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-based-in-uk-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-manual-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-no-to-yes-based-in-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-no-to-yes-not-based-in-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-fields-name-and-email.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-international-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-details-uk-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-international-to-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-uk-to-international.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-financial-details-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/loss-payee/change-your-answers-change-loss-payee-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/multiple-policy/change-your-answers-policy-multiple-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/multiple-policy/change-your-answers-policy-type-change-multiple-to-single-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/name-on-policy/change-your-answers-different-name-fields.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/name-on-policy/change-your-answers-different-name-to-same-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/name-on-policy/change-your-answers-same-name-position.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/name-on-policy/change-your-answers-same-name-to-different-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/other-company-details/change-your-answers-change-other-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-broker-based-in-uk-summary-list-manual-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-broker-based-in-uk-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-broker-not-based-in-uk-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-different-name-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-other-company-no-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-other-company-yes-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-same-name-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-broker-based-in-uk-summary-list-manual-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-broker-based-in-uk-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-broker-not-based-in-uk-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-different-name-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-other-company-no-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-other-company-yes-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-same-name-summary-list.spec.js
  src/api/.keystone/config.js
  src/ui/server/controllers/insurance/check-your-answers/policy/index.test.ts
  src/ui/server/controllers/insurance/check-your-answers/policy/index.ts
Labels: fix

#3519 fix(EMS-4206): fix certain postcode searches going to problem with service page
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-ordnance-survey-invalid-postcode.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.ts
  src/api/integrations/ordnance-survey/index.ts
Labels: fix

#3520 chore(EMS-4212): merge main into main-broker-address-lookup
  .release-please-manifest.json
  CHANGELOG.md
  e2e-tests/insurance/cypress/e2e/journeys/all-sections.spec.js
  package-lock.json
  package.json
  src/api/data-migration/version-4-to-version-5/update-applications/index.ts
  src/api/data-migration/version-4-to-version-5/update-applications/update-application-migrated-to-field.ts
  src/api/package-lock.json
  src/api/package.json
  src/api/test-helpers/declaration.ts
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/types/application.ts
Labels: chore
