Repository UK-Export-Finance/exip, pull requests merged in 2025-01, with the labels that each got.

#3439 style(EMS-4040-44-47): declarations - modern slavery - content iterations
  e2e-tests/content-strings/fields/insurance/declarations/index.js
  e2e-tests/content-strings/links.js
  e2e-tests/content-strings/pages/insurance/declarations/modern-slavery/index.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/declarations/index.ts
  src/api/content-strings/links.ts
  src/ui/server/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/content-strings/links.ts
  src/ui/server/content-strings/pages/insurance/declarations/modern-slavery/index.ts
Labels: bug, enhancement, chore

#3442 feat(EMS-4087): application submission - small export builder - non gbp
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-eligible-for-small-export-builder-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-not-eligible-for-small-export-builder-alternative-currency.spec.js
  src/api/.keystone/config.js
  src/api/constants/external-apis.ts
  src/api/constants/index.ts
  src/api/custom-resolvers/queries/get-companies-house-information/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-address/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/index.ts
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.ts
  src/api/emails/application/index.test.ts
  src/api/emails/application/index.ts
  src/api/helpers/get-APIM-CIS-countries/index.test.ts
  src/api/helpers/get-APIM-currencies-exchange-rate/index.test.ts
  src/api/helpers/get-APIM-currencies-exchange-rate/index.ts
  src/api/helpers/get-APIM-currencies/index.test.ts
  src/api/helpers/round-number/index.test.ts
  src/api/helpers/round-number/index.ts
  src/api/integrations/APIM/index.test.ts
  src/api/integrations/APIM/index.ts
  src/api/test-mocks/mock-APIM-currencies-exchange-response.ts
  src/api/test-mocks/mock-application.ts
  src/api/test-mocks/mock-currencies.ts
  src/api/types/application-types/index.ts
  src/api/types/currency/index.ts
Labels: enhancement, chore

#3440 feat(EMS-4063): declarations - modern slavery - textarea edge cases
  e2e-tests/insurance/cypress/e2e/journeys/cannot-skip-flow/declarations/navigate-to-declarations-pages-without-completing-previous-sections.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-all-radios-as-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-empty-form.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-has-no-offenses-or-investigations.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-is-not-aware-of-existing-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-will-adhere-to-all-requirements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-a-pure-number/submit-declarations-textarea-fields-with-a-pure-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-declarations-textarea-fields-with-new-line-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-special-characters/submit-declarations-textarea-fields-with-special-characters.spec.js
  src/ui/server/helpers/mappings/map-textarea-fields/index.test.ts
  src/ui/server/helpers/mappings/map-textarea-fields/index.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
  src/ui/server/middleware/insurance/application-status/is-submit-your-application-route/index.test.ts
  src/ui/server/middleware/insurance/application-status/is-submit-your-application-route/index.ts
Labels: enhancement, feature, tech, chore

#3444 fix(EMS-4088): application submission - small export builder calculation
  src/api/.keystone/config.js
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.ts
  src/api/emails/send-application-submitted-emails/index.test.ts
  src/api/emails/send-application-submitted-emails/index.ts
Labels: bug, chore, fix

#3445 chore(EMS-4089): merge main into main-iterations-2
  .github/dependabot.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/Dockerfile
  src/api/package-lock.json
  src/api/package.json
  src/ui/Dockerfile
  src/ui/package-lock.json
  src/ui/package.json
Labels: chore

#3460 chore(main): release 2.38.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3357 feat(EMS-3991-3994): broker addresses data saving, e2e, redirect updates
  e2e-tests/commands/insurance/complete-and-submit-broker-details-form.js
  e2e-tests/commands/insurance/complete-broker-addresses-form.js
  e2e-tests/commands/insurance/complete-broker-details-form.js
  e2e-tests/commands/insurance/policy/complete-and-submit-policy-forms.js
  e2e-tests/fixtures/application.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page-skipping-broker-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-zero-addresses/broker-zero-addresses-page.spec.js
  src/api/.keystone/config.js
  src/api/helpers/map-and-filter-ordnance-survey-addresses/index.test.ts
  src/api/helpers/map-and-filter-ordnance-survey-addresses/index.ts
  src/ui/server/api/keystone/get-ordnance-survey-addresses/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-zero-addresses/index.ts
  src/ui/server/graphql/queries/ordnance-survey-addresses.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.test.ts
  src/ui/server/helpers/sanitise-data/sanitise-value/index.ts
  src/ui/types/application.ts
Labels: documentation, enhancement, tech, chore

#3464 chore(main): release 2.38.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3465 fix(EMS-4100): country risk logic - short term cover
  e2e-tests/fixtures/countries.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-no-online-support.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/buyer-country/buyer-country-unsupported-countries.spec.js
  src/api/.keystone/config.js
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index-rating-a.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index-rating-b.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/a-and-b-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index-rating-c.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index-rating-d.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-online-support/c-and-d-rating-conditions/index.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-support/index.test.ts
  src/api/helpers/map-CIS-countries/map-CIS-country/has-no-support/index.ts
Labels: bug, fix

#3466 chore(main): release 2.38.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3462 feat(EMS-4098): automate deployment pipeline
  .github/actions/mysql/action.yml
  .github/actions/rerun/action.yml
  .github/actions/webapp/action.yml
  .github/modules/retry/action.yml
  .github/workflows/deployment.yml
  .github/workflows/github.yml
  .github/workflows/pr.yml
  .github/workflows/publish.yml
  .github/workflows/test.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/api/package.json
  src/ui/package-lock.json
  src/ui/package.json
  src/ui/server/helpers/task-list/index.ts
Labels: feature

#3467 chore(main): release 2.39.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3461 feat(EMS-4008): broker addresses - save and back
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/save-and-back.spec.js
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/broker-details/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.ts
  src/ui/server/helpers/get-chosen-ordnance-survey-address/index.test.ts
  src/ui/server/helpers/get-chosen-ordnance-survey-address/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/server/test-mocks/mock-ordnance-survey-address-response.ts
  src/ui/types/ordnance-survey.d.ts
Labels: enhancement, feature

#3469 chore(EMS-3977-3991): broker address lookup - postcode test improvements
  e2e-tests/constants/examples/postcode-examples.js
  e2e-tests/insurance/cypress/e2e/journeys/export-contract/about-goods-or-services/about-goods-or-services.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/validation/broker-details-validation.spec.js
  e2e-tests/shared-test-assertions/email-field-validation/index.js
  e2e-tests/shared-test-assertions/index.js
  e2e-tests/shared-test-assertions/postcode-field-validation/index.js
  src/api/helpers/is-valid-postcode/index.test.ts
  src/api/test-mocks/mock-postcodes.ts
Labels: tech, chore

#3470 feat(EMS-4098): deployment pipeline automation
  .github/actions/mysql/action.yml
  .github/actions/webapp/action.yml
  .github/workflows/deployment.yml
  package-lock.json
  src/api/package-lock.json
  src/ui/package-lock.json
Labels: fix

#3472 fix(EMS-4101): update gov integrity hash
  src/ui/public/css/styles.css
  src/ui/public/js/govukFrontend.js
  src/ui/public/js/govukFrontend.js.LICENSE.txt
  src/ui/public/js/govukFrontend.js.map
  src/ui/server/constants/integrity.ts
Labels: bug, fix

#3471 chore(main): release 2.39.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3468 feat(EMS-4015): application submission - xlsx - uk broker address
  src/api/.keystone/config.js
  src/api/content-strings/XLSX.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/based-in-the-uk/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/based-in-the-uk/index.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/index.test.ts
  src/api/generate-xlsx/map-application-to-XLSX/map-policy/map-broker/map-broker-address/index.ts
  src/api/helpers/string/index.test.ts
  src/api/helpers/string/index.ts
  src/api/test-mocks/mock-broker.ts
  src/api/types/application-types/index.ts
Labels: enhancement, tech

#3474 feat(EMS-4011-4115): policy - check your answers - broker address
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/constants/routes/insurance/policy/broker.js
  e2e-tests/content-strings/fields/insurance/policy/index.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/multiple-policy/check-your-answers-policy-multiple-with-broker-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-with-broker-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/broker-manual-address-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/validation/broker-manual-address-validation.spec.js
  e2e-tests/shared-test-assertions/summary-lists/export-contract/fully-populated.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/policy/index.ts
  src/ui/server/constants/routes/insurance/policy/broker.ts
  src/ui/server/content-strings/fields/insurance/policy/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-manual-address/index.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/address-field/based-in-the-uk/index.test.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/address-field/based-in-the-uk/index.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/address-field/index.test.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/address-field/index.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.test.ts
  src/ui/server/helpers/summary-lists/policy/broker-fields/index.ts
  src/ui/server/helpers/summary-lists/policy/other-company-fields/index.ts
  src/ui/server/routes/insurance/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.test.ts
  src/ui/server/routes/insurance/policy/broker/index.ts
  src/ui/server/test-mocks/mock-broker.ts
  src/ui/types/application.ts
Labels: documentation, enhancement, feature, tech, chore

#3478 chore(EMS-4121): disable small export builder functionality
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-eligible-for-small-export-builder-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-not-eligible-for-small-export-builder-alternative-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/multiple-contract-policy/export-value/multiple-contract-policy-export-value.spec.js
  src/api/.keystone/config.js
  src/api/emails/application/get-submitted-confirmation-template-id/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/index.ts
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.test.ts
  src/api/emails/application/get-submitted-confirmation-template-id/multiple-policy-type/index.ts
  src/api/emails/application/index.test.ts
  src/api/emails/application/index.ts
  src/ui/templates/insurance/policy/multiple-contract-policy-export-value.njk
Labels: chore

#3479 chore(main): release 2.39.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3473 feat(EMS-3981-3991): broker address lookup - mapping updates
  e2e-tests/commands/insurance/complete-broker-addresses-form.js
  e2e-tests/commands/insurance/complete-broker-details-form.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/constants/examples/building-names.js
  e2e-tests/constants/examples/index.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-with-broker-based-in-uk-building-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/multiple-policy-type/policy-conditions/submit-an-application-multiple-policy-type-with-broker-based-in-uk-building-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/policy-conditions/submit-an-application-single-policy-type-with-broker-based-in-uk-building-name.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/application-submission/single-policy-type/policy-conditions/submit-an-application-single-policy-type-with-broker-based-in-uk-building-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/save-and-back.spec.js
  src/api/.keystone/config.js
  src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.test.ts
  src/api/custom-resolvers/queries/get-ordnance-survey-addresses/index.ts
  src/api/helpers/filter-ordnance-survey-addresses/index.test.ts
  src/api/helpers/filter-ordnance-survey-addresses/index.ts
  src/api/helpers/map-and-filter-ordnance-survey-addresses/index.test.ts
  src/api/helpers/map-and-filter-ordnance-survey-addresses/index.ts
  src/api/helpers/map-ordnance-survey-address/index.test.ts
  src/api/helpers/map-ordnance-survey-address/index.ts
  src/api/helpers/map-ordnance-survey-addresses/index.test.ts
  src/api/helpers/map-ordnance-survey-addresses/index.ts
  src/api/test-mocks/mock-ordnance-survey-response.ts
  src/api/types/address/index.ts
  src/api/types/ordnance-survey/index.ts
Labels: documentation, enhancement, feature, tech, chore

#3480 fix(EMS-4098): deployment pipeline update
  .github/workflows/deployment.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: dependencies, fix

#3481 chore(main): release 2.39.3
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3483 fix(EMS-4125): update keystone config
  src/api/.keystone/config.js
Labels: fix

#3484 chore(main): release 2.39.4
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3488 chore(deps): dependencies updates
  .github/workflows/deployment.yml
  package-lock.json
  package.json
  src/api/package-lock.json
  src/ui/package-lock.json
  src/ui/package.json
Labels: chore

#3475 feat(EMS-4054): broker addresses - single address redirection
  e2e-tests/commands/insurance/complete-broker-addresses-form.js
  e2e-tests/commands/insurance/complete-policy-section.js
  e2e-tests/commands/insurance/complete-prepare-application-section-multiple-policy-type.js
  e2e-tests/commands/insurance/complete-prepare-application-section-single-policy-type.js
  e2e-tests/commands/insurance/complete-sign-in-and-submit-an-application.js
  e2e-tests/commands/insurance/policy/complete-and-submit-policy-forms.js
  e2e-tests/commands/shared-commands/click-events/click-zero-addresses-enter-manually-link.js
  e2e-tests/commands/shared-commands/click-events/index.js
  e2e-tests/constants/examples/address-lookup-input-examples.js
  e2e-tests/constants/examples/index.js
  e2e-tests/constants/examples/multi-line-string-ordnance-survey-examples.js
  e2e-tests/constants/examples/ordnance-survey-examples.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-details/broker-details-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/broker-manual-address-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-manual-address/validation/broker-manual-address-validation.spec.js
  src/ui/server/controllers/insurance/policy/broker-addresses/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/index.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/save-and-back/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-addresses/save-and-back/index.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-confirm-address/index.ts
  src/ui/server/helpers/format-sort-code/index.test..ts
  src/ui/server/helpers/generate-broker-address-inset-text-html/index.test.ts
  src/ui/server/helpers/generate-broker-address-inset-text-html/index.ts
  src/ui/server/helpers/generate-multiple-field-html/index.test.ts
  src/ui/server/helpers/generate-multiple-field-html/index.ts
  src/ui/server/helpers/get-chosen-ordnance-survey-address/by-id/index.test.ts
  src/ui/server/helpers/get-chosen-ordnance-survey-address/by-id/index.ts
  src/ui/server/helpers/get-chosen-ordnance-survey-address/by-index/index.test.ts
  src/ui/server/helpers/get-chosen-ordnance-survey-address/by-index/index.ts
  src/ui/types/index.d.ts
  src/ui/types/ordnance-survey.d.ts
Labels: documentation, enhancement, feature, tech, chore

#3490 style(EMS-4136): declarations - content iterations
  e2e-tests/content-strings/fields/insurance/declarations/index.js
  e2e-tests/content-strings/pages/insurance/declarations/anti-bribery/index.js
  e2e-tests/content-strings/pages/insurance/declarations/modern-slavery/index.js
  src/api/.keystone/config.js
  src/api/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/content-strings/fields/insurance/declarations/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/anti-bribery/index.ts
  src/ui/server/content-strings/pages/insurance/declarations/modern-slavery/index.ts
Labels: enhancement

#3491 feat(EMS-4117-4118): policy - change your answers - broker data mapping
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-address-based-in-uk-to-not-based-in-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-multiple-addresses-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-single-address-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-based-in-uk-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-based-in-uk-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-no-to-yes-based-in-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-no-to-yes-not-based-in-uk.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-using-a-broker-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-fields-name-and-email.spec.js
  src/api/.keystone/config.js
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-submitted-data/broker/index.ts
Labels: enhancement, tech, chore

#3489 feat(EMS-4134): add additional security routes
  e2e-tests/constants/routes/index.js
  e2e-tests/constants/routes/well-known.js
  package-lock.json
  src/api/package-lock.json
  src/ui/package-lock.json
  src/ui/server/constants/routes/index.ts
  src/ui/server/constants/routes/well-known.ts
  src/ui/server/controllers/root/thank-you/index.test.ts
  src/ui/server/controllers/root/thank-you/index.ts
  src/ui/server/controllers/well-known/security/index.test.ts
  src/ui/server/controllers/well-known/security/index.ts
  src/ui/server/helpers/date/iso-8601/index.test.ts
  src/ui/server/helpers/date/iso-8601/index.ts
  src/ui/server/index.ts
  src/ui/server/routes/index.ts
  src/ui/server/routes/root/index.test.ts
  src/ui/server/routes/root/index.ts
  src/ui/server/routes/well-known/index.test.ts
  src/ui/server/routes/well-known/index.ts
  src/ui/server/test-mocks/index.ts
  src/ui/types/express/index.d.ts
Labels: feature

#3493 chore(main): release 2.40.0
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3496 fix(EMS-4138): declarations - modern slavery - error messages
  e2e-tests/content-strings/error-messages.js
  src/ui/server/content-strings/error-messages.ts
Labels: bug, fix

#3499 chore(EMS-4146): merge main into main-declarations-modern-slavery
  CHANGELOG.md
  e2e-tests/commands/insurance/declarations/complete-and-submit-declarations-forms.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/about-goods-or-services/change-your-answers-about-goods-or-services-final-destination-known-to-unknown.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/change-your-answers/how-will-you-get-paid/change-your-answers-how-will-you-get-paid.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/check-your-answers-export-contract-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/export-contract/summary-list/check-your-answers-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/single-policy/change-your-answers-policy-single-policy-type.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/single-policy/change-your-answers-policy-type-change-single-to-multiple-policy-type-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/check-your-answers-policy-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/summary-list/single-policy/check-your-answers-policy-single-other-company-no-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details-trading-address-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-company-details.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-nature-of-your-business.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-trading-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover-currency.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/change-your-answers/change-your-answers-change-turnover.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/check-your-answers-your-business-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-business/summary-list/check-your-answers-your-business-summary-list.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-buyer-financial-accounts.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-company-or-organisation.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/change-your-answers/change-your-answers-change-working-with-buyer-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/check-your-answers-your-buyer-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/your-buyer/summary-list/check-your-answers-your-buyer-summary-list-minimal.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/complete-prepare-application-tasks.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/anti-bribery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct-answer-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/anti-bribery-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/anti-bribery-exporting-with-code-of-conduct.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/exporting-with-code-of-conduct/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/anti-bribery/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/confidentiality.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confidentiality/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/confirmation-and-acknowledgements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/confirmation-and-acknowledgements/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-expandable-definition-content.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-no-to-yes.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery-radios.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/modern-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/save-and-back.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-all-radios-as-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-empty-form.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-has-no-offenses-or-investigations.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-is-not-aware-of-existing-slavery.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/declarations/modern-slavery/validation/modern-slavery-validation-will-adhere-to-all-requirements.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-a-pure-number/submit-declarations-textarea-fields-with-a-pure-number.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-declarations-textarea-fields-with-new-line-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-special-characters/submit-declarations-textarea-fields-with-special-characters.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/task-list/complete-prepare-application-group.spec.js
  src/api/package-lock.json
  src/api/types/application-types/index.ts
Labels: chore

#3501 chore(main): release 2.40.1
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3502 chore(keystone): updated keystone configuration
  src/api/.keystone/config.js
Labels: fix

#3504 chore(main): release 2.40.2
  .release-please-manifest.json
  CHANGELOG.md
  package-lock.json
  package.json
Labels: autorelease: pending

#3498 chore(EMS-4102-4114): broker address - e2e improvements
  e2e-tests/commands/insurance/check-policy-summary-list.js
  e2e-tests/commands/shared-commands/click-events/click-use-different-address-link.js
  e2e-tests/commands/shared-commands/click-events/index.js
  e2e-tests/constants/examples/ordnance-survey-examples.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-multiple-addresses-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-multiple-addresses-enter-address-manually.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-single-address-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-single-address-enter-address-manually.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-based-in-uk-yes-to-no.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-field-manual-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/check-your-answers/policy/change-your-answers/broker/change-your-answers-fields-name-and-email.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-addresses/broker-addresses-page.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/broker-confirm-address/broker-confirm-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-multiple-addresses-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-multiple-addresses-enter-address-manually.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-single-address-available.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-address-not-based-in-uk-to-based-in-uk-single-address-enter-address-manually.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-field-manual-address.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/policy/change-your-answers/broker/change-your-answers-fields-name-and-email.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/submit-textarea-fields-with-new-line-characters/submit-policy-textarea-fields-with-new-line-characters.spec.js
  e2e-tests/pages/insurance/policy/brokerConfirmAddress.js
  e2e-tests/pages/insurance/policy/index.js
  e2e-tests/partials/insurance/enterAddressManuallyLink.js
  src/ui/server/controllers/insurance/policy/broker-details/index.test.ts
  src/ui/server/controllers/insurance/policy/broker-details/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.test.ts
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.ts
  src/ui/server/graphql/mutations/update-application/broker.ts
  src/ui/server/helpers/broker-details-data-change-flags/index.test.ts
  src/ui/server/helpers/broker-details-data-change-flags/index.ts
  src/ui/server/helpers/get-broker-details-post-redirect-url/based-in-uk/index.test.ts
  src/ui/server/helpers/get-broker-details-post-redirect-url/based-in-uk/index.ts
  src/ui/server/helpers/get-broker-details-post-redirect-url/index.test.ts
  src/ui/server/helpers/get-broker-details-post-redirect-url/index.ts
  src/ui/types/broker-details.d.ts
  src/ui/types/index.d.ts
Labels: bug, tech, chore, fix

#3509 style(EMS-4157): declarations - modern slavery - content iterations
  e2e-tests/content-strings/error-messages.js
  src/ui/server/content-strings/error-messages.ts
Labels: enhancement

#3510 chore(EMS-4160): insurance eligibility - improve e2e coverage
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-skip-flow/navigate-to-companies-house-search-page-directly.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-skip-flow/navigate-to-company-details-page-directly.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-skip-flow/navigate-to-member-of-a-group-page-directly.spec.js
  e2e-tests/insurance/cypress/e2e/journeys/eligibility/cannot-skip-flow/navigate-to-party-to-consortium-page-directly.spec.js
  src/api/content-strings/fields/insurance/export-contract/index.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.test.ts
  src/ui/server/controllers/insurance/your-buyer/connection-with-buyer/index.ts
Labels: tech, chore

#3506 chore(EMS-4062-4099): logging, unit test improvements
  src/api/.keystone/config.js
  src/api/constants/allowed-graphql-resolvers/index.test.ts
  src/api/constants/allowed-graphql-resolvers/index.ts
  src/api/test-helpers/account-status.ts
  src/api/test-helpers/accounts.ts
  src/api/test-helpers/applications.ts
  src/api/test-helpers/auth-retries.ts
  src/api/test-helpers/broker.ts
  src/api/test-helpers/business.ts
  src/api/test-helpers/buyer-relationship.ts
  src/api/test-helpers/buyer-trading-history.ts
  src/api/test-helpers/buyer.ts
  src/api/test-helpers/company.ts
  src/api/test-helpers/country.ts
  src/api/test-helpers/cover-period.ts
  src/api/test-helpers/create-full-application.ts
  src/api/test-helpers/create-multiple-accounts.ts
  src/api/test-helpers/create-multiple-full-applications.ts
  src/api/test-helpers/declaration.ts
  src/api/test-helpers/declarations.ts
  src/api/test-helpers/eligibility.ts
  src/api/test-helpers/export-contract-agent-service-charge.ts
  src/api/test-helpers/export-contract-agent-service.ts
  src/api/test-helpers/export-contract-agent.ts
  src/api/test-helpers/export-contract.ts
  src/api/test-helpers/generate-submitted-application.ts
  src/api/test-helpers/policies.ts
  src/api/test-helpers/policy-contact.ts
  src/api/test-helpers/private-market.ts
  src/api/test-helpers/reference-number.ts
  src/api/test-helpers/sectionReview.ts
  src/api/test-helpers/total-contract-value.ts
  src/ui/server/controllers/insurance/business/map-and-save/business/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-details/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/company-different-trading-address/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/nullify-company-different-address/index.ts
  src/ui/server/controllers/insurance/business/map-and-save/turnover/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service-charge/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract-agent/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/export-contract/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/nullify-export-contract-agent-service/index.ts
  src/ui/server/controllers/insurance/export-contract/map-and-save/private-market/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/broker/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/jointly-insured-party/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee-financial-details-international/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee-financial-details-uk/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/loss-payee/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy-contact/index.ts
  src/ui/server/controllers/insurance/policy/map-and-save/policy/index.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer-relationship/index.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer-trading-history/index.ts
  src/ui/server/controllers/insurance/your-buyer/map-and-save/buyer/index.ts
  src/ui/server/helpers/is-production/index.ts
Labels: tech, chore
